### ISSUE TITLE
Floatrules - ksdev/ks-0018-on-0010-KD-5380

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#1]
### Siirrettävä ominaisuus

Floatrules-järjestelmäasetus, jolla määritetään kirjasto/kuntakohtaisia kellutussääntöjä.

![floatrules](https://user-images.githubusercontent.com/33121325/209780999-f6a686bd-a89a-4a4c-900f-72d2dc1511bc.png)

**Comment by emta001** [comment]
Tuotu testeille.

**Comment by pknuuti** [comment]
Nykyisen tuotannon asetusten mukainen kellutussääntö näyttäisi toimivan, tosin en pysty testaamaan ei-kelluvia lehtiä, kun en löydä Vaaran next-kannasta ollenkaan lehtiniteitä.

**Comment by AnneliO** [comment]
Lisaäsin vaara-nextille yhden kausijulkaisutietueen ja otin vastaan yhden niteen: https://vaara-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=11701465

**Comment by pknuuti** [comment]
Kiitos, tämän "lehden" myötä totesin, että kellutus toimii myös lehtien osalta eli eivät kellu, kuten on tarkoitus.

**Comment by ajrajala** [comment]
Testattu Vaskissa enkä huomannut mitään ongelmia. (Testauksessa eri tyyppisiä sääntöjä: yhdensuuntainen kellutus, kellutus molempiin suuntiin, aineistolajiin/nidetyyppiin/hyllypaikkaan/kokoelmakoodin kohdistuvat säännöt.)

**Comment by pirliis** [comment]
Testattu OUTIssa ja kellutukset toimivat asetusten mukaisesti.

**Comment by emta001** [comment]
Kellutus vaikuttaisi siis toimivan testien perusteella kuten pitää. Suljen tiketin tältä osin.
