### ISSUE TITLE
Web-Kake-integraatio - ksdev/ks-0036-KD-4601-ILL

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#10]
### Siirrettävä ominaisuus

Kaukolainaohjelma WebKakeen on tehty integraatio, jossa asiakastiedot haetaan Kohasta WebKakeen ja asiakkaan kaukolainat näytetään Kohassa lainojen alapuolella Lainat-sivulla.

**Comment by AnneliO** [comment]
Jukka Hakosalo hoitaa tämän. Laitan vastuuhenkilöksi kuitenkin Semenoffin Piian, koska Jukka ei ole meidän Githubissa.

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 24.4.2023: Kodo laittaa Jukalle viestiä ja selvittää, miten testaus onnistuu.

**Comment by CodoDerDritte** [comment]
Huonosti onnistuu kun ei koko hommaa saa nyt tässä kohtaa matkaan. Kohan circulation.tt on liian erilainen että Web-Kake -muutosten mergeäminen vanhasta versiosta onnistuisi. Järkevää olisi tietysti plugarisoida koko Web-Kake-kikkura tässä kohtaa.

**Comment by piiaseme** [comment]
Eli onko oletettava, että Webkaken ja Kohan uuden version yhteys ei ole toiminnassa heti versionvaihdon jälkeen? Kyselen tätä tiedottamisen vuoksi, että pitäiskö varoitella työkamuja, että kaukot ei näy Kohassa eikä asiakastiedot siirry Kohasta Webkakeen heti uudessa versiossa?

**Comment by CodoDerDritte** [comment]
> Eli onko oletettava, että Webkaken ja Kohan uuden version yhteys ei ole toiminnassa heti versionvaihdon jälkeen? Kyselen tätä tiedottamisen vuoksi, että pitäiskö varoitella työkamuja, että kaukot ei näy Kohassa eikä asiakastiedot siirry Kohasta Webkakeen heti uudessa versiossa?

Se on mahdollista. Katsomme tuota vielä Hakosalon Jukan kanssa tänään tai huomenna ja ilmoittelen sitten tarkemmin.

--Edit--

Ja tarkennus siis että Webkake-Koha yhteys toimii kyllä Webkaken suunnasta (eli asiakastietojen pitäisi kyllä siirtyä Kohasta Webkakeen). Ongelma tässä on siis ainoastaan asiakkaan kaukolainojen näyttäminen Kohan puolella, jonka kanssa on hieman haasteita.

**Comment by emta001** [comment]
Koha-Suomen palaveri 22.4.2024: Tehdään uusi tiketti Web-Kake-liitännäisestä.
