### ISSUE TITLE
koha-suomi-messaging (KSM)

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/Koha-22x#100]
### Siirrettävä ominaisuus

Suomi.fi -viestit ja e-kirjeet

**Comment by CodoDerDritte** [comment]
Tähän liittyy myös #20 GetSuomiFiMessages - ksdev/ks-0054-KD-4624.

**Comment by CodoDerDritte** [comment]
iPost EPL testattu Outissa, testaillaan vielä hieman lisää. Suomi.fi -viestit täytyy kokeilla Vaarassa ja iPost PDF Lumpeessa.

**Comment by CodoDerDritte** [comment]
Myös PDF ja suomi.fi nyt testattu.
