### ISSUE TITLE
Hyllytarkenne - ksdev/ks-0040-KD-5312-items_sublocation

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#102]
### Siirrettävä ominaisuus

ksdev/ks-0040-KD-5312-items_sublocation

**Comment by emta001** [comment]
Tuotu testeille, vaikuttaa tällä hetkellä vain Varaukset-sivuun (niteen viivakoodin pitäisi näkyä oikein eikä vain lataa loputtomasti). Toinen paikka johon tää vaikuttaa taisi olla hyllyvaraus-sivu?

**Comment by Kati-Helle** [comment]
Testaus Helle-nextillä niteellä itemnumber=1525050. Niteellä hyllytarkenne Uutuus (auktorisoitu arvo=UUSI)
- tein asiakkaalle varauksen ja tärppäytin varaukseen niteen itemnumber=1525050
- asiakkaan Varaukset-sivu latautui sukkelaan ja näkyvillä tietoja varauksesta viivakoodeineen
- niteen tietueen Varaukset-sivu latautui sukkelaan ja näkyvillä tietoja tärpänneestä varauksesta viivakoodeineen

**Comment by ajrajala** [comment]
Testasin myös, Varaukset-sivu latautui normaalisti vaikka joukossa olikin hyllytarkenteelliseen niteeseen kiinnittynyt varaus. Hyllyvaraukset-raportinkin kurkkasin, en ainakaan huomannut sen latautumisessa tai hyllytarkenteen näyttämisessä/sillä suodattamisessa ongelmia.

**Comment by pirliis** [comment]
Testasin myös OUTIssa. Näyttäisi toimivan ok. hyllytarkenteellisen niteen varaus kuin myös Varauset-sivu ja Hyllyvaraus-raportti.

**Comment by emta001** [comment]
Suljen tiketin.
