### ISSUE TITLE
Konfiguraatiotiedostot

### ISSUE THREAD

**Issue by CodoDerDritte** [KohaSuomi/Koha-22x#103]
### Siirrettävä ominaisuus

* koha-httpd.conf
* koha-conf.xml
* log4perl.conf

**Comment by CodoDerDritte** [comment]
koha-httpd.conf kopioitu kaikkiin next kontteihin vaski-nextiltä ja memcachedin namespace vaihdettu:

for i in *-next; do NAMESPACE="$(echo $i | tr [[:lower:]] [[:upper:]] | tr -d '-')"; sed -i "s/VASKITEST/$NAMESPACE/" $i/koha/koha-httpd.conf; done

**Comment by AnneliO** [comment]
Liittyy tiketteihin #163 ja  #164

**Comment by CodoDerDritte** [comment]
Varmistettu, että konfissa on asetus <bcrypt_setting> sekä <encryption_key> ja että <elasticsearch_index_mappings> osoittaa oikeaan tiedostoon.

**Comment by CodoDerDritte** [comment]
Althostnamet tarkistettu (ja Kirkekseen lisätty).

**Comment by CodoDerDritte** [comment]
Vanha log4perl konfiguraatio näyttää aiheuttavan ainakin maksujen 500 virheilmoituksen (mahdollisesti muutakin häröilyä). Kokeilin vaihtaa outille kopioin nextien konfiguraatiosta ja maksut näyttäisivät nyt siellä toimivan.

**Comment by CodoDerDritte** [comment]
No eipä ollutkaan tuo mikä sen maksujen virheilmoituksen aiheuttaa. Jokin muu siinä nyt kinnaa.

**Comment by CodoDerDritte** [comment]
log4perl.conf ja logrotate.d/koha on nyt päivitetty kaikkiin testikontteihin. koha-adm kotihakemistossa on fix-logfile-permissions.sh, joka täytyy ajaa kun uusi log4perl.conf otetaan käyttöön.

**Comment by AnneliO** [comment]
Jos tämä on valmis, niin suljetko Kodo tiketin. :)

**Comment by CodoDerDritte** [comment]
Joo, sori unohtunut.
