### ISSUE TITLE
Varauksen voimassaoloaika ei päivity

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha-22x#104]
### Mikä vikana?

Redminen tiketti: https://tiketti.koha-suomi.fi/issues/4182

Kun kiinni jäänyt varaus lainataan toiselle asiakkaalle, joka on eri kuin alkuperäinen varaaja, Koha pyytää lainan vahvistuksen: 
![image](https://user-images.githubusercontent.com/98814860/219382104-e8202183-9d6f-4e16-a6da-62809236e5b4.png)
Jos alkuperäistä varausta ei poisteta, vaan valitaan "Peruuta odottava-tila" ja nide lainataan toiselle asiakkaalle, muuttuu alkuperäisen varaajan varaus takaisin voimassa olevaksi, mutta varauksen voimassaoloajaksi jää noudettavana olleen varauksen viimeinen noutopäivä.

### Mitä pitäisi tapahtua

Varaukselle pitäisi päivittyä varauksen oletusvoimassaoloaika päivästä, jolloin varaus aktivoitiin takaisin voimassa olevaksi.

**Comment by AnneliO** [comment]
Tämä tuntuisi korjaantuneen versiossa 22.11. Testaatko Pirlii tätä outi-nextillä sitten kun se on käytettävissä?

**Comment by pirliis** [comment]
Jep, testaan. Laitoin muistiin. :)

**Comment by piiaseme** [comment]
Testasin teoksella "Käsi jota kerran pitelin". Vanhenee-kenttä muuttui varaajalla tyhjäksi. Päivittyyköhän ensi yönä varaukselle oikean mittainen vanhentumisaika?

**Comment by AnneliO** [comment]
Voipi olla, että tähän vaikuttaa nyt myös tiketin #42 ongelma. Varsinkin, jos DefaultHoldExpirationdate on pois päältä. Eli jos asetus olisi päällä, niin siihen tulisi todennäköisesti se oletusaika.

**Comment by pirliis** [comment]
Sama havainto kuin Piialla. Testataan uudestaan, kun saadaan tiketin #42 ongelmaan korjaus. Jospa korjaisi myös tämän.

**Comment by ajrajala** [comment]
Testasin tätä nyt kun #42 on korjattu. Meillä on siis DefaultHoldExpirationdate päällä. Vanhenee-kenttä näytti muuttuvan tyhjäksi kuten Piian ja Pirkko-Liisan aiemmissa testeissä.

**Comment by AnneliO** [comment]
Jep, sama huomio kuin Annilla minulla outin nextillä. Sellainen lisähuomio, että jos vanhenemispäivän yrittää asettaa, vilahtaa arvo kentässä ja kenttä tyhjenee samantien. Jos tämän jälkeen päivittää sivun, tulee virhe 500. Osoitekentässä on tällainen osoite silloin:

https://outi-next.koha-suomi.fi/cgi-bin/koha/reserve/request.pl?action=move&where=down&first_priority=1&last_priority=4&prev_priority=0&next_priority=1&borrowernumber=301772&biblionumber=2280729&itemnumber=3506963&reserve_id=4156301&date=2023-04-24

**Comment by velimarj** [comment]
Lisähuomiona vielä tällainen, että kun oli ensin perunut odottava-tilan ja sen jälkeen palautti teoksen uudelleen, tuli vanhenemispäiväksi varauksen viimeinen noutopäivä, jonka sitten pystyi muuttamaan haluamakseen.

**Comment by AnneliO** [comment]
Alkuperäinen tiketin ongelma on sinänsä "korjaantunut", eli viimeiseksi voimassaolopäiväksi ei jää enää varauksen kiinni jäädessä asetettu päivämäärä vaan päiväys tyhjennetään. Se on ehkä parempi vaihtoehto, mutta siinäkin on ongelmansa.

Teen tuosta viimeisen voimassaolopäivän muokkauksen virheestä erillisen tiketin.

**Comment by AnneliO** [comment]
Tiketti #181 nyt tuosta viimeisen voimassaolopäivän muokkauksen virheestä.

**Comment by AnneliO** [comment]
Voisiko tämän sulkea? :)

**Comment by pirliis** [comment]
Joo voi. :) Suljen.
