### ISSUE TITLE
Olemassa olevan asiakastietueen tallennus ei onnistu

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha-22x#106]
### Mikä vikana?

Kun yritän muokata ja tallentaa jotakin valmiiksi olemassa ollutta asiakastietuetta (esim. [borrowernumber 307898](https://vaski-next.koha-suomi.fi/cgi-bin/koha/members/moremember.pl?borrowernumber=307898)), tallenna-painikkeen painamisen jälkeen muokkaus-sivu jää näkyville eikä muutetut tiedot näytä päivittyneen asiakkaalle. Kokeilin poistaa käytöstä pakolliseksi asiakasmääreeksi asetetun Varaustunnus-määreen, mutta sillä ei ollut vaikutusta asiaan.

Loin kokonaan uuden asiakkaan ([borrowernumber 383731](https://vaski-next.koha-suomi.fi/cgi-bin/koha/members/moremember.pl?borrowernumber=383731)) ja tuon asiakastietueen muokkaaminen ja tallentaminen onnistuu normaalisti.

### Mitä pitäisi tapahtua

Tallenna-painikkeen painamisen jälkeen muutettujen tietojen pitäisi olla tallentunut ja näytölle latautua ko. asiakkaan lainaus-sivu.

### Kuinka toistaa ongelma/asia

1. Avaa asiakastietue https://vaski-next.koha-suomi.fi/cgi-bin/koha/members/moremember.pl?borrowernumber=307898
2. Valitse Muokkaa, lisää tietoihin esim. varaustunnus ja sen jälkeen Tallenna.
3. Havaitse, että muokkaus-sivu jää näkyville eikä käyttäjälle tule mitään virheilmoitusta.

**Comment by lmstrand** [comment]
Meidän vanha varaustunnus aiheuttaa ongelmia. Kun sen lisää myös tietoihin, tallennus onnistuu. Vanha varaustunnus on pakollinen tietokantatasolla, mutta tuosta virkailijaliittymästä pakollisuustieto puuttuu. Jätetään pakollisuus vielä hetkeksi tietokantaan, kunnes päätetään, edetäänkö uuden asiakasmääreen kanssa (Finna-yhteensopivuus pitäisi testata).

**Comment by AnneliO** [comment]
othernames pitää olla myös uniikki, joten jos tallennus ei siltikään onnistu, niin kokeile jotain muuta varaustunnusta. :)

**Comment by ajrajala** [comment]
Okei, no hyvä tietää että selittyi ihan vaan tuolla vanhalla varautunnuksella. Se ei kai aiemmin näkynyt muokkaussivulla (tai sitten olen sokea ja minut voi irtisanoa :D), mutta nyt tosiaan onnistuu tallentaa eli tämän tiketin voinee sulkea pois.
