### ISSUE TITLE
Yksittäisen niteen tiedot -linkistä aukeaa tietueen kaikki niteet

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha-22x#107]
### Mikä vikana?

Kun esimerkiksi palautusnäytön tai tietueen Perustiedot-näkymän kautta klikkaa niteen viivakoodi -linkkiä, näyttäisi aina aukeavan näkymä jossa on tietueen kaikki niteet vaikka näkyville pitäisi tulla ainoastaan yksittäisen niteen tiedot.

Itse linkit näyttäisivät sinänsä samalta kuin mitä 21.11-versiossa:
- Palautuksen kautta siirtyessä nextillä ja testillä .../cgi-bin/koha/catalogue/moredetail.pl?biblionumber=305509&itemnumber=242663#item242663
- Tietueen kautta siirtyessä nextillä ja testillä .../cgi-bin/koha/catalogue/moredetail.pl?itemnumber=242663&biblionumber=305509&bi=305509#item242663

### Mitä pitäisi tapahtua

Niteen viivakoodi -linkistä pitäisi avautua suoraan yksittäisen niteen tiedot kuten versiossa 21.11.

### Kuinka toistaa ongelma/asia

1. Hae jokin tietue
2. Klikkaa jokin nide auki niteen viivakoodi-linkistä
3. Huomaa, että päädyt sen sivun ylälaitaan, jolla esitetään tietueen kaikki niteet

**Comment by pknuuti** [comment]
Vaaran nextillä testattu ja toimii juuri kuten Vaski ilmoittanut eli ei avaudu oikean niteen kohdalle.

**Comment by AnneliO** [comment]
Tieteelliset huomasivat tämän saman ongelma ja siihen on joko heillä tai yhteisössä korjaus. En ota selvää muistiosta, kenen tuo ongelman kohdalla mainittu build on: https://www.kiwi.fi/pages/viewpage.action?pageId=318734527

**Comment by emta001** [comment]
> Tieteelliset huomasivat tämän saman ongelma ja siihen on joko heillä tai yhteisössä korjaus. En ota selvää muistiosta, kenen tuo ongelman kohdalla mainittu build on: https://www.kiwi.fi/pages/viewpage.action?pageId=318734527

Veikkaisin, että kyseessä on KK:n oma buildi. Pitänee etsiä sieltä korjausta tähän.

**Comment by emta001** [comment]
Kyseessä saattaa sittenkin olleen yhteisön korjaus, KK:han taitaa tehdä oman buildinsa yhteisön masterin päälle :D Korjattu siis yheisön tiketissä [32583](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=32583).

**Comment by emta001** [comment]
Korjaus tuotu testeille.

**Comment by ajrajala** [comment]
Testasin ja nyt palautuksesta sekä tietueen Perustiedot -näytöltä niteen viivakoodi -linkistä aukeaa ko. niteen tiedot.

Tuli kuitenkin mieleen testata vielä siirtyminen nidehaun tuloksista. Siellä niteen viivakoodia klikkaamalla päätyy edelleen tietueen kaikkiin niteisiin (sivun alkuun, ei tietyn niteen kohdalle). Tuotannossa kun testasin niin nidehaun tuloksissa niteen viivakoodi -linkki vie Niteet-sivulle suoraan oikean niteen kohdalle.

**Comment by emta001** [comment]
> Testasin ja nyt palautuksesta sekä tietueen Perustiedot -näytöltä niteen viivakoodi -linkistä aukeaa ko. niteen tiedot.
> 
> Tuli kuitenkin mieleen testata vielä siirtyminen nidehaun tuloksista. Siellä niteen viivakoodia klikkaamalla päätyy edelleen tietueen kaikkiin niteisiin (sivun alkuun, ei tietyn niteen kohdalle). Tuotannossa kun testasin niin nidehaun tuloksissa niteen viivakoodi -linkki vie Niteet-sivulle suoraan oikean niteen kohdalle.

Näemmä sama ongelma löytyy yhteisöstä korjaamattomana. Tehdään sinne tiketti ja korjaus.

EDIT Eipäs sittenkään, tämäkin näkyy toimivan kuten pitää yhteisössä. Etsitään siis korjaus ja tuodaan meille.

**Comment by emta001** [comment]
Tuli mieleen voisiko tuo nide haun ongelma johtua jostain js-rimpsusta. En ainakaan koodista meinaa hoksata millä tämä on korjattu.

**Comment by AnneliO** [comment]
Otin Vaara-nextillä kaikki IntranetUserJS:t pois ja nidehaun kautta niteeseen siirryttäessä sivu menee edelleen vain nidesivun alkuun. Osoitteessa on kyllä merkintä niteestä, mutta ei sen kohdalle kuitenkaan mennä.

https://vaara-next.koha-suomi.fi/cgi-bin/koha/catalogue/moredetail.pl?biblionumber=11675142#item101525248

**Comment by emta001** [comment]
> Otin Vaara-nextillä kaikki IntranetUserJS:t pois ja nidehaun kautta niteeseen siirryttäessä sivu menee edelleen vain nidesivun alkuun. Osoitteessa on kyllä merkintä niteestä, mutta ei sen kohdalle kuitenkaan mennä.
> 
> https://vaara-next.koha-suomi.fi/cgi-bin/koha/catalogue/moredetail.pl?biblionumber=11675142#item101525248

Jees, kiitti testauksesta! Eli siellä on nyt jotain koodissa mikä jäänyt huomaamatta. Ja linkkihän tosiaan on ihan oikein ja samanlainen yhteisön ja meidän version välillä. Hämmentävää :D

**Comment by AnneliO** [comment]
Tämä näyttäisi toimivan nyt ainakin Vaara-nextillä.

**Comment by Kati-Helle** [comment]
Hellessä nidetunnus/niteen viivakoodi -linkki vie oikein linkattuun niteeseen ainakin näistä testaamistani
- niteen palautuksesta
- tietueen perustiedoista
- asiakkaan varauksista
- asiakkaan lainoista

**Comment by emta001** [comment]
Miten ihmeessä, kun tälle ei ole tehty mitään? Ainakaan en muista tehneeni :D

**Comment by ajrajala** [comment]
Eikös nuo muut linkeistä siirtymiset korjaantuneet silloin aiemmin kun korjaus tuotiin nexteille, mutta ongelmaksi jäi nidehausta nidelinkillä siirtyminen? Kokeilin äsken nextillä sitä ja näyttäisi edelleen vievän Niteet-sivun alkuun eikä oikean niteen kohdalle. 🤔

**Comment by emta001** [comment]
> Eikös nuo muut linkeistä siirtymiset korjaantuneet silloin aiemmin kun korjaus tuotiin nexteille, mutta ongelmaksi jäi nidehausta nidelinkillä siirtyminen? Kokeilin äsken nextillä sitä ja näyttäisi edelleen vievän Niteet-sivun alkuun eikä oikean niteen kohdalle. thinking

Tämä ei tosiaan toimi vieläkään. Hämäännyin tuosta Annelin kommentista, että näyttäisi nyt toimivan vaara-nexteillä :D

**Comment by AnneliO** [comment]
Mien edes hoksannut tuota nidehakua testata. :D Mutta se ei tosiaan toimi edelleenkään. Nidehaussa linkki niteeseen on erilainen kuin muualla.

**Comment by emta001** [comment]
> Mien edes hoksannut tuota nidehakua testata. :D Mutta se ei tosiaan toimi edelleenkään. Nidehaussa linkki niteeseen on erilainen kuin muualla.

Siinä on semmonen hashtag, jonka pitäs osata mennä moredetail-sivulla oikean html id:n kohdalle (esim. id="item1234"). Mutta se ei nyt jostain syystä toimi nexteillä. Yhteisössä toimii, mutten löydä siihen mitään korjausta.

Pikakorjauksena mainittakoon, että jos tuolla moredetail-sivulla valitsee osotepalkista ton sivun linkin (maalaa sen tai jotain) ja painaa enter, niin sivu siirtyy oikeen niteen kohdalle :D

**Comment by emta001** [comment]
Teenpä nyt niin, että suljen tämän ja teen tiketin tuosta Annin huomaamasta nidehaku ongelmasta. Pysyy homma paremmin kasassa :D
