### ISSUE TITLE
OverdueNoticeFrom

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#108]
### Kysymys

[OverdueNoticeFrom](https://koha-community.org/manual/22.11/en/html/circulationpreferences.html#overduenoticefrom)

Onko tällä asetuksella vaikutusta meidän overdue_notices.pl-croniin?

Kuvaus:

Asks: Organize and send overdue notices using the ___.

Default: command-line option

Values:

    command-line option

    item home library

    checkout library

Description:

This system preference determines which library’s information will be used in the overdue notices (if there is information in the [notice template](https://koha-community.org/manual/22.11/en/html/tools.html#notices-and-slips-label) such as <<branches.branchname>> or <<branches.branchphone>>, or, in the new syntax, [% branch.branchname %] or [% branch.branchphone %]) and which email address will be used to send the notices.

This system preference overrides the –frombranch parameter in the [overdue_notices.pl cronjob](https://koha-community.org/manual/22.11/en/html/cron_jobs.html#cron-overdue-notice-label).

When set to “command-line option”, the library information will be that of the –frombranch parameter in the [overdue_notices.pl cronjob](https://koha-community.org/manual/22.11/en/html/cron_jobs.html#cron-overdue-notice-label) or the checkout library if the parameter is absent.

When set to “item home library”, the library information will be that of the overdue item’s home library.

When set to “checkout library”, the library information will be that of the library at which the overdue item was checked out.

### Asiasanat/tagit

overdue_notices palautuskehotukset myöhästymisilmoitukset overdue notices overduenotices

**Comment by emta001** [comment]
Ei ole vaikutusta, koska meillä on käytössä oma overdue_notices.pl (utilityn alla). Yhteisön vastaavassa cronissa tuo on käytössä, nähdäkseni sitä ei kuitenkaan ole käytetty missään muussa yhteydessä.

**Comment by AnneliO** [comment]
Tutkitaan versionvaihdon jälkeen, onko tarvetta.
