### ISSUE TITLE
Omatoimikirjastojen blokkaukset -ksdev/ks-0038-KD-4572

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#11]
### Siirrettävä ominaisuus

Omatoimikirjastojen blokkaukset välitetään SIP2-sanomassa omatoimikoneelle. Blokki lisätään borrower_ss_blocks-tauluun.

**Comment by lmstrand** [comment]
https://github.com/KohaSuomi/Koha-22x/issues/15
