### ISSUE TITLE
Uutista ei pysty tallentamaan TinyMCE-virheen vuoksi

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#110]
### Mikä vikana?

Jos järjestelmäasetukseen AdditionalContentsEditor on valittu vaihtoehto _WYSIWYG-editorin kautta (TinyMCE)_, ei saa tallennettua Työkaluissa uutisia. Tallennusnappia painaessa ei tapahdu mitään.

Jos tarkastelee sivun tietoja, Console-välilehdellä on kolme virheilmoitusta:

Uncaught ReferenceError: tinymce is not defined
    \<anonymous> https://vaara-next.koha-suomi.fi/cgi-bin/koha/tools/additional-contents.pl?op=add_form&id=28&editmode=wysiwyg:2015

Uncaught ReferenceError: tinyMCE is not defined
    initTinyMce https://vaara-next.koha-suomi.fi/cgi-bin/koha/tools/additional-contents.pl?op=add_form&id=28&editmode=wysiwyg:2500
    \<anonymous> https://vaara-next.koha-suomi.fi/cgi-bin/koha/tools/additional-contents.pl?op=add_form&id=28&editmode=wysiwyg:2487

GET https://vaara-next.koha-suomi.fi/intranet-tmpl/lib/tiny_mce/tinymce.min_22.1100001.js

404 Not Found

### Mitä pitäisi tapahtua

Uutisen pitäisi pystyä tallentamaan.

### Kuinka toistaa ongelma/asia

1. Laita AdditionalContentsEditor-järjestelmäasetukseen päälle vaihtoehto _WYSIWYG-editorin kautta (TinyMCE)_.
2. Mene Työkalut -> Uutiset -> Luo uusi
3. Kirjoita Sisältö-kenttään tekstiä.
4. Klikkaa Tallenna-nappia.

### Asiasanat/tagit

Uutiset TinyMCE

**Comment by lmstrand** [comment]
Nexteillä tiedostonimi oli muotoa /koha-tmpl/intranet-tmpl/lib/tiny_mce/tinymce.min.js.
Vaihdoin tiedostonimeksi  tinymce.min_22.1100001.js ja uutisten tallennus onnistui.

Pitäisi selvittää, miksi tietostonimi ei sisältänyt versionumeroa.

**Comment by lmstrand** [comment]
Eipäs toimikaan halutulla tavalla :) Uudelleennimeäminen ei ole ratkaisu, se tapahtuu jotenkin selainpäässä.

**Comment by lmstrand** [comment]
Syspref  intranet_includes sisälsi Vaskin ja Vaaran nexteillä arvon includes. Tyhjensin asetuksen, eikä selain enää näyttäisi herjaavan,että tinyMCE-kirjaston lataaminen ainakaan epäonnistuisi (GET https://vaara-next.koha-suomi.fi/intranet-tmpl/lib/tiny_mce/tinymce.min_22.1100001.js 404 Not Found).

Silti nuo tinyMCE is not defined -herjat jatkuvat. Voisiko jossain includes-systeemissä olla vikaa? Yhteisöstä ei löydy mainintaa ongelmasta.

**Comment by lmstrand** [comment]
Tuo includes-systeemi on niin monimutkainen että en ota siitä selvää.
Tilapäinen korjaus onnistui lisäämällä tinymce-kirjasto joka sivulle intranetuserJS:n kautta (oletettavasti ongelma nyt on että kirjasto ei vain lataudu, eikä siten alustu?).

```
///tinyMCE hack (WYSIWYG-editori ei lataudu Kohan editoria käyttävillä sivuilla///
var s = document.createElement("script");
s.type = "text/javascript";
s.src = "/intranet-tmpl/lib/tiny_mce/tinymce.min.js";
$("head").append(s);
```

**Comment by Kati-Helle** [comment]
Hellessä uutisen lisääminen onnistui Työkalut/Uutiset-toiminnolla.
![kuva](https://user-images.githubusercontent.com/99952449/223704207-695a037a-f832-4585-87c3-7a00f907d23b.png)

Etusivun uutisesta uutisen muokkaukseen: uutismuokkauksen jälkeen tallennus-painikkeella ei tapahtu mitään.
Sama, kun muokkaa olemassa olevaa uutista Työkalut/Uutiset-toiminnolla: tallennus-painikkeella ei tapahdu mitään.

Uutisen poistaminen etusivulla ei onnistunut.
Uutisen poistaminen Työkalut/Uutiset-toiminnolla onnistui.

**Comment by pknuuti** [comment]
Testasin Vaaran nextillä. Uutisen saa näkyviin vasta kun hoksaa laittaa Julkaisuvuosi-sarakkeeseen tallennuspäivän. Nykyisessä tuotantokannassa se tulee automaattisesti, onko tässä nyt joku virhe?

**Comment by AnneliO** [comment]
> Testasin Vaaran nextillä. Uutisen saa näkyviin vasta kun hoksaa laittaa Julkaisuvuosi-sarakkeeseen tallennuspäivän. Nykyisessä tuotantokannassa se tulee automaattisesti, onko tässä nyt joku virhe?

Tämä näyttäisi toimivan sandboxissa samalla tavalla, eli Publication date on oletuksena tyhjänä ja jos sen jättää tyhjäksi, kenttään ei tule automaattisesti päivämäärää tallennettaessa (kuten nyt) ja uutinen ei näy. En löydä bögzillasta tähän liityen mitään tikettiäkään.

**Comment by lmstrand** [comment]
Apache-konfiguraatiot on päivitetty nexteille. Tämä korjasi TinyMCE-herjat ja WYSIWYG-editoiri toimii taas nexteillä. Päivämäärän voisi generoida automaattisesti intranetuserjs:llä. Pitäisi korjata siis myös yhteisöön jos tehdään koodimuutos...

**Comment by AnneliO** [comment]
Pohdin tuota IntranetUserJS-rimpsua, että onko se tarpeellinen? Uutisen voi myös ajastaa tulevaisuuteen (ja menneisyyteen, mikä on hassua), joten olisivatko ajatelleet yhteisössä, että päivämäärä olisi hyvä aina valita?

**Comment by Kati-Helle** [comment]
> Pohdin tuota IntranetUserJS-rimpsua, että onko se tarpeellinen? Uutisen voi myös ajastaa tulevaisuuteen (ja menneisyyteen, mikä on hassua), joten olisivatko ajatelleet yhteisössä, että päivämäärä olisi hyvä aina valita?

Ainakaan mInä en kaipaa päiväysautomatiikkaa, sillä tapanani on ollut lisätä päiväys itse.

**Comment by lmstrand** [comment]
Ehkä tuo yhteisön tapa on ihan järkevä noiden Publication datejen kanssa. Uutista voi muokata rajattomasti ja vasta kun se oikeasti halutaan julkaista, sille voi valita päivämäärän. Avataan tuosta oma tiketti jos on tarpeen. Suljen tämän.

**Comment by Kati-Helle** [comment]
Helle-next-testailuissa kävi näin:

Uutiset-työkalun testauksesta
- uutisen lisääminen Työkalut/Uutiset-toiminnolla: OK
- uutisen muokkaus Työkalut/Uutiset-toiminnolla: OK
- uutisen poisto Työkalut/Uutiset-toiminnosta: OK

- uutisen lisääminen Kohan etusivun uutisen Uusi-linkistä: OK
- uutisen muokkaaminen Kohan etusivun uutisen Muokkaa-linkistä: OK
- uutisen poisto Kohan etusivun uutisen Poista-linkistä: EI OK
![kuva](https://user-images.githubusercontent.com/99952449/227520742-844d7ef3-c50f-494b-90fa-23093a9ed1b2.png)

**Comment by AnneliO** [comment]
Teetkö @Kati-Helle tuosta ongelmasta uuden tiketin? :)

**Comment by Kati-Helle** [comment]
> Teetkö @Kati-Helle tuosta ongelmasta uuden tiketin? :)

Uusi tiketti https://github.com/KohaSuomi/Koha-22x/issues/110#issuecomment-1482782333

**Comment by Kati-Helle** [comment]
> Teetkö @Kati-Helle tuosta ongelmasta uuden tiketin? :)

Uusi tiketti https://github.com/KohaSuomi/Koha/issues/485
