### ISSUE TITLE
Tietueen varaukset -näytöllä päivämääräarvot eivät näy

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-22x#111]
### Mikä vikana?

Tietueen varauksissa päivämääräarvot eivät näy (ainakaan läppärin näytöllä):
Pvm
Vanhenee

![kuva](https://user-images.githubusercontent.com/99952449/222652119-380dc203-a8d3-4008-93f3-51e285410abb.png)

**Comment by AnneliO** [comment]
Päivämäärien näkyminen riippuu useammasta asiasta: minkä kokoinen näyttö, kuinka paljon sivua on zoomattu selaimen ctrl+ -toiminnolla, mikä on näytön resoluutio yms.

![kuva](https://user-images.githubusercontent.com/33121325/222669943-f242b770-3ed2-46aa-8493-f2ac3b476339.png)

Tieteelliset Koha-kirjastot ovat huomanneet tuon saman ongelman ja se on kirjattu mm. heidän [Release 22.11 User Interface changes discussion and improvements](https://www.kiwi.fi/display/KK/Release+22.11+User+Interface+changes+discussion+and+improvements) -sivulle.

Oiskohan tähän yhteisössä jotain korjausta olemassa, koska Biblibren sandboxissa päivämääräkenttä on isompi ja suurenee sivua zoomatessa?

**Comment by AnneliO** [comment]
Biblibren sandboxissa kentissä ei kyllä ole tuota datepickerin kuvaketta, kuten meillä.

![kuva](https://user-images.githubusercontent.com/33121325/222672167-dcc3e672-7a5d-4a27-8b59-4557cf693363.png)

**Comment by emta001** [comment]
Tämän pitäisi korjaantua tällä samalla rimpsulla, joka korjaa tiketin #119 ongelman

`.flatpickr-input {width: auto}`

**Comment by AnneliO** [comment]
Minun testien mukaan rimpsu toimii. Lisäsin rimpsun [IntranetUserCSS-sivulle](https://github.com/KohaSuomi/Koha-22x/wiki/IntranetUserCSS#vahvasti-suositeltavat) vahvasti suositeltuihin Yleiset-osioon.

Kati, jos sinun testien mukaan myös ok, niin suljetko sitten tiketin? :)

**Comment by Kati-Helle** [comment]
Jep, Emmin tekemä toteutustapa tepsii myös tietueen varauksilla
![kuva](https://user-images.githubusercontent.com/99952449/224233861-b6a45b99-f663-481d-984b-88fd6a33a92f.png)
