### ISSUE TITLE
Asiakkaan maksujen Hyvitys-toiminnon piilotustarpeet

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-22x#115]
### Mikä vikana?

Asiakkaan maksujen Hyvitys-toiminnot pitäisi saada piiloon/ei-käyttökelpoisiksi.

Asiakkaan maksuja hyvittämään pääsee nyt ainakin näiden toimintojen Maksa-painikkeista:
Maksut/Tapahtumat
Maksut/Maksa maksuja

![kuva](https://user-images.githubusercontent.com/99952449/223072360-f93fc3f0-3852-460b-94ea-d3bc204ea094.png)

![kuva](https://user-images.githubusercontent.com/99952449/223071365-182b3d36-2c0a-4910-b3f9-b911fb18e91a.png)

**Comment by AnneliO** [comment]
Noita kautta mentäessä näytti olevan eri tunniste välilehdellä (miksipä ei olisi..). Tällä IntranetUserCSS-rimpsulla noiltakin sivuilta maksamaan mennessä saa credit/hyvitys-sivun piiloon:

body#pat_paycollect.pat a[href*="/cgi-bin/koha/members/mancredit.pl"] {
  display: none;
}

Rimpsu lisätty myös [IntranetUserCSS](https://github.com/KohaSuomi/Koha-22x/wiki/IntranetUserCSS)-sivulle.

**Comment by Kati-Helle** [comment]
Kiitos Anneli :)
