### ISSUE TITLE
Noudettavana olevan palautuksen pop-upin Peruuta varaus -piilotus ei toimi

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-22x#116]
### Mikä vikana?

Tämä IntranetUserCSS-piilotusrimpsu ei vaikuta toimivan mainitulla tavalla: 
'Piilota varauksen palauttamisen yhteydessä popparista Älä huomioi -nappi, noudettavana olevan varauksen palautuksen yhteydessä popparista Poista varaus -nappi ja Peru kuljetus -nappi'

Nide tärppää palauttaessa varaukseen
![kuva](https://user-images.githubusercontent.com/99952449/223093092-b6324cd4-6fbe-4e63-a74d-8bca87555ba0.png)

Jo varaukseen noudettavaksi tärpännyt nide palautettu uudestaan. Niteen kotikirjasto on Koha-sijaintikirjasto
![kuva](https://user-images.githubusercontent.com/99952449/223093404-940520de-abb4-4666-8be8-25668b51936c.png)

Helle-Koha-testissä noudettavana olevan varatun niteen palautuksesta tämä:
![kuva](https://user-images.githubusercontent.com/99952449/223094917-a7e980e5-eb6c-44f1-b01e-c8fd72b9ba13.png)

**Comment by Kati-Helle** [comment]
Älä huomioi -painike myös näkyvillä.

**Comment by AnneliO** [comment]
Hellessä oli kommentoitu tuo kyseinen rimpsu pois käytöstä. Poistin varsinaisen piilotuksen edestä /*-merkinnän pois. Se oli jäänyt tuonne IntraneUserCSS-sivulle "päälle" vahingossa.

**Comment by Kati-Helle** [comment]
Ok, entäpä Älä huomioi -painikkeen piilotus?
![kuva](https://user-images.githubusercontent.com/99952449/223103917-d747c8b9-9b6a-4c78-b3d4-d5c93f839c66.png)

**Comment by Kati-Helle** [comment]
Vai liittyykö rimpsun 'Älä huomioi' vain ei-vielä tärpänneen varatun niteen palautukseen?

**Comment by AnneliO** [comment]
> Vai liittyykö rimpsun 'Älä huomioi' vain ei-vielä tärpänneen varatun niteen palautukseen?

Liittyy ja vielä siinä tapauksessa, että käytössä ei ole  HoldsAutoFill-järjestelmäasetus.

**Comment by Kati-Helle** [comment]
Kiitos tiedosta ja avusta. 
Tämä oli tässä.
