### ISSUE TITLE
Uusi versio 22x: kaikkien asiakastietojen haun esto varauksenteossa

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-22x#117]
### Kehitysehdotukseni

Varausta tehdessä saa haettua kaikki asiakastiedot Haku-painikkeella. Saisiko tähän muutoksen.

![kuva](https://user-images.githubusercontent.com/99952449/223113200-c077af4b-d28a-4c66-ae89-9afffea5e71b.png)

**Comment by AnneliO** [comment]
Tein jo aiemmin css-rimpsun, jolla tuosta samasta kohdasta piilotettiin asiakastietojen selailu (samanlainen kuin asiakkaat-sivulla), koska se on uusi haitallinen (meidän toimintaympäristöön sopimaton) ominaisuus. Joten ajattelisin, että tuon hakutuloslistauksen piilotus menee samalla perusteella versionvaihdon työnä. Siirrän tiketin 22.xx-version repoon. :)

**Comment by AnneliO** [comment]
Tämä IntranetUserCSS-piilotus ei varsinaisesti estä asiakkaiden hakemista, mutta se piilottaa tulostaulukon, jolloin asiakkaiden tietoja ei näe. Asiakkaan haku kirjastokortin numerolla toimii edelleen testieni perusteella. Kannattaa kuitenkin testata vielä.

/* Piilota varauksen teko -sivulta asiakashaun tulostaulukko */
body#circ_request.catalog div#table_borrowers_wrapper.dataTables_wrapper.no-footer { display: none; }

**Comment by Kati-Helle** [comment]
Kiitos Anneli rimpsusta :)
Toimii, eli hakuehdottomalla haulla ei näy yhtäkään hakutulosta. 
Kirjastokorttinumero-haku toimii, samoin esim. sukunimihaku.

**Comment by AnneliO** [comment]
Hienoa. :)

Rimpsu lisätty myös [IntranetUserCSS](https://github.com/KohaSuomi/Koha-22x/wiki/IntranetUserCSS)-sivulle.

**Comment by MikkoLiimatainen** [comment]
Onkohan tällä haun toiminnalle mahdollista tehdä mitään? Piilotus toimii kyllä, mutta tuolla kyselyn vastausviestissä näyttäisi olevan täydet asiakastietueet. Ne ovat saatavilla myös käyttäjille, joilla ei ole muuten pääsyä asiakastietoihin. Koska tiedot ovat tuolla sivulla saatavilla, niin mielestäni nuo haut pitäisi vähintäänkin lokittaa asiakastietojen katseluiksi, jos tuota asiakastietojen selausta ei tuolta sivulta saa kokonaan pois.

**Comment by AnneliO** [comment]
Haku tehdään RESTin kautta ja ne lokittuu asiakkaan muutoslokille näin (ylin):
![kuva](https://user-images.githubusercontent.com/33121325/224644291-e4d3712b-fa09-4315-8eaf-a3e26e4457be.png)

**Comment by MikkoLiimatainen** [comment]
Ok. Hyvä tietää, että lokittuvat. Tänään näyttääkin nuo lokittuneen, mutta aiemmin ei tainnut lokitus olla päällä.

Tuosta varauksen teosta varmaan kannattaa myös piilottaa tuo selaa sukunimen mukaan osa, koska se ei tee mitään näkyvää, kun tuo tulostaulukko on piilotettu. Tällä rimpsulla saa tuon piiloon: body#circ_request.catalog div#holds_patronsearch_pane div.browse { display: none; }

**Comment by AnneliO** [comment]
> Ok. Hyvä tietää, että lokittuvat. Tänään näyttääkin nuo lokittuneen, mutta aiemmin ei tainnut lokitus olla päällä.
> 

Ok, en ole itse aiemmin testannut, joten voi olla, että jokin on muuttunut tässä välissä. :)

> Tuosta varauksen teosta varmaan kannattaa myös piilottaa tuo selaa sukunimen mukaan osa, koska se ei tee mitään näkyvää, kun tuo tulostaulukko on piilotettu. Tällä rimpsulla saa tuon piiloon: body#circ_request.catalog div#holds_patronsearch_pane div.browse { display: none; }

Se selaa sukunimen mukaan -toiminnolle on piilotus täällä: https://github.com/KohaSuomi/Koha-22x/wiki/IntranetUserCSS :)

**Comment by AnneliO** [comment]
Keksiikö tähän vielä jotain vai laitetaanko tiketti kiinni?

**Comment by AnneliO** [comment]
Koska uutta ei ole tullut kolmeen viikkoon, suljen tiketin. :)

**Comment by Kati-Helle** [comment]
> Kiitos Anneli rimpsusta :) Toimii, eli hakuehdottomalla haulla ei näy yhtäkään hakutulosta. Kirjastokorttinumero-haku toimii, samoin esim. sukunimihaku.

Mietin tätä haun onnistumista sukunimellä... liittynee siihen, että uuden version testauskannassa asiakastietoja ei ollut suurta määrää ja olen tehnyt haun sukunimellä, joka on rekisterissä vain yhdellä asiakastiedolla.
