### ISSUE TITLE
Lainaus-toimintoon piilotus painikkeelle Tulosta kuitti ja tyhjennä näyttö

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-22x#118]
### Mikä vikana?

Saisiko Lainaus-näytöltä piiloon kuittipainikkeen 'Tulosta kuitti ja tyhjennä näyttö'?

![kuva](https://user-images.githubusercontent.com/99952449/223427082-3f4af586-5e7f-4c51-bf81-f5d4672019fe.png)

Valinnan jälkeen päätyy todellakin tyhjennetylle näytölle (valitsipa painikkeen vaihtoehdoista kumman tahansa)
![kuva](https://user-images.githubusercontent.com/99952449/223427349-8274496d-37fb-43fc-9091-c600f83cebc6.png)

**Comment by AnneliO** [comment]
Noiden näkyvyyttä säädellään järjestelmäasetuksella  DisplayClearScreenButton. :)

**Comment by Kati-Helle** [comment]
Kiitos Anneli tiedosta. Tosiaan, onhan tuo jo nyt käytössä Hellessäkin. Erikoiselta vaikutti uudessa versiossa painikkeiden käytön jälkeinen Lainaus-näkymä, jossa näkyy otsikko Lainoja. (Vastaava näkymä myös Lainaus-toiminnon avaamalla.)
![kuva](https://user-images.githubusercontent.com/99952449/223661755-29832fa2-7c06-491f-9b52-c79fd0df2681.png)

Tänään Helle-Kohassa tämä näkymä
![kuva](https://user-images.githubusercontent.com/99952449/223661082-63c14fb4-2e78-41cb-9c1a-dcf57a5d1417.png)

Sekä nykyisessä että uudessa versiossa kursori menee hienosti automaattisesti lainaus-kenttään.
