### ISSUE TITLE
Kaikkien varausten keskeytyspäivämäärän valinta liian leveä

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#119]
### Mikä vikana?

Asiakkaan Lainaus-näytöllä ja Tiedot-näytöllä Varaukset-välilehdellä varausten alapuolella on mahdollisuus keskeyttää kaikki varaukset tiettyyn päivämäärään saakka. Päivämäärä-kenttä on kuitenkin jostain syystä hirmuisen leveä:
![kuva](https://user-images.githubusercontent.com/33121325/223447089-decdca34-7a9f-48d8-bf48-cf804956f303.png)

Testasin ja otin kaikki IntranetUserCSS- ja IntranetUserJS-määritykset pois, mutta niillä ei ollut merkitystä kentän kokoon.

### Mitä pitäisi tapahtua

Kentän kuuluisi olla suunnilleen tämän näköinen:
![kuva](https://user-images.githubusercontent.com/33121325/223447837-bf0ba2c0-1599-47a9-a70a-e25f8ef25785.png)

### Kuinka toistaa ongelma/asia

1. Mene sellaisen asiakkaan tietoihin, joissa on varaus, esim. https://vaara-next.koha-suomi.fi/cgi-bin/koha/members/moremember.pl?borrowernumber=11010257
2. Mene Varaukset-välilehdelle
3. Huomaa keskeytyspäivämäärä-kentän leveys.

### Asiasanat/tagit

varauksen keskeytys päivämäärä-kenttä

**Comment by Kati-Helle** [comment]
Vastaavaa Palautus-näytöllä
![kuva](https://user-images.githubusercontent.com/99952449/223699095-ec81345c-3ce8-4d25-9abe-a76676bbdf2f.png)

**Comment by AnneliO** [comment]
Koha-Suomen kokous 9.3.2023: Kokeillaan tuoda 22.11 uudet ominaisuudet erilliseen feature-branchiin, josko ne auttais.

**Comment by emta001** [comment]
22.11 ominaisuuksien tuominen omaan feateru-branchiin töppäsi muutamaan ongelmaan. Ensinnäkin tuotantobrachin rakennus olisi venynyt mahdottoman pitkäksi, kun kaikki yhteisön commitit pitäisi aina käydä läpi ennen kuin päästään edes meidän ominaisuuksiin. Yhteisöön on jo nyt tullut yli 500 uutta committia ja vuoden päästä niitä on jo ties kuinka monta. Toinen ongelma ovat merge conflictit, jos jokin meidän feature branch aiheuttaa sellaisen, olisi se tiputettava pois käytöstä (tai tehtävä siihen korjaus, mikä ei aina/lähes koskaan ole edes mahdollista). Testin kautta näistä pääsisi, mutta ei siitä että tuotantohaaran rakentaminen venyisi jo nyt mahdottoman pitkäksi.

**Comment by emta001** [comment]
Tällaisella CSS-rimpsulla nuo flatpickerit pitäis saada kuosiin:

`.flatpickr-input {width: auto}`

**Comment by AnneliO** [comment]
Minun testien mukaan rimpsu toimii. Lisäsin rimpsun [IntranetUserCSS-sivulle](https://github.com/KohaSuomi/Koha-22x/wiki/IntranetUserCSS#vahvasti-suositeltavat) vahvasti suositeltuihin Yleiset-osioon.

Suljen tiketin. Kiitos! :)

**Comment by AnneliO** [comment]
Muistiin tänne, että tämä ongelma on tullut bugin https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=31943 myötä ja "korjattu" bugissa https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=32606.
