### ISSUE TITLE
Järjestelmäsetus: BorrowerCategoryTimeout - ksdev/ks-0039-on-0024-KD-4564

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#12]
### Siirrettävä ominaisuus

Asiakastyyppikohtainen timeout, tehty Kohan itsepalvelulainausta (SCO:ta) varten.

**Comment by lmstrand** [comment]
Ominaisuus ei estä itsepalvelulainauksen asiakasnäkymästä uloskirjautumista. Ongelma on kierretty muilla tavoin. Ominaisuudesta luovutaan.

**Comment by lmstrand** [comment]
Ominaisuus on toiminut ok. Sessioiden siivoaminen öisin truncate_sessions.pl -cronilla on aiheuttanut sessioiden "vanhenemisen". Tuodaan ominaisuus takasin.
