### ISSUE TITLE
Toimiiko Finnassa salasanan palautus, jos OpacResetPassword-järjestelmäasetuksen ottaa pois päältä?

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#120]
### Mikä vikana?

Testattava, toimiiko Finnassa salasanan palautus, jos OpacResetPassword-järjestelmäasetuksen ottaa pois päältä. Jos tuon asetuksen saisi otettua pois päältä, piilottuisi asiakkaan tiedoista mahdollisuus lähettää salasanan resetointiviesti. Kyseinen toiminto vaatii kuitenkin Kohan oman opacin käytön, joten toiminto on meille turha.

Liittyy viestipohjaan [STAFF_PASSWORD_RESET](https://github.com/KohaSuomi/Koha-22x/wiki/Kuitit-ja-tulosteet#staff_password_reset).

**Comment by AnneliO** [comment]
Testasin Vaaran Finna-nextillä tätä ja salasanan palautus toimi, vaikka OpacResetPassword-järjestelmäasetuksessa oli "eivät saa". Eli asetuksen voi laittaa pois päältä ja salasanan resetointivaihtoehdon sitä myötä piiloon Muita toimintoja -valikosta asiakkaan tiedoista.

**Comment by AnneliO** [comment]
Varmistan vielä Finna-toimistosta tuon asetuksen käytön, koska tämän n. kolme vuotta vanhan [Finna-ohjeen](https://www.kiwi.fi/pages/viewpage.action?pageId=103197538) mukaan asetus pitää olla päällä, jotta salasanan palautus toimii. Laitoin viestiä Finna-toimistoon.

**Comment by AnneliO** [comment]
Ilmeisesti Finna ei ota huomioon OpacResetPassword-asetusta. Finna-toimistosta ei tosin saanut mitään varmaa tietoa tästä. [Finna-liitännäisen käyttämissä järjestelmäasetuksissa](https://github.com/KohaSuomi/koha-plugin-rest-di#sysprefs) sitä ei ole mainittu.

Eli lienee suht turvallista olettaa, että järjestelmäasetuksella ei ole vaikutusta ja sen voi laittaa "eivät saa" -asentoon.

Jos joku muu vielä testaa tämän, niin pistän sitten tiketin kiinni. :)

**Comment by ajrajala** [comment]
Testasin Vaskin Finna-nextillä, salasanan palautus tosiaan toimi vaikka OpacResetPassword olikin Kohassa 'not allowed'.

**Comment by velimarj** [comment]
Toimii myös OUTI-nextillä.

**Comment by AnneliO** [comment]
Tuntuisi toimivan, joten suljen tiketin.
