### ISSUE TITLE
Asiakastiedon Palautusmuistutukset-välilehdelle tarvitaan tapa piilottaa

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-22x#121]
### Mikä vikana?

Miten piilottaa Asiakastiedon Palautusmuistutukset-välilehti?

![kuva](https://user-images.githubusercontent.com/99952449/223717814-2e0f4ab3-7588-45ac-a130-8ddc2687b602.png)

**Comment by AnneliO** [comment]
Matrixissa käydyn keskustelun perusteella välilehden saa piiloon, kun tyhjentää  ClaimReturnedLostValue ja  BundleLostValue -järjestelmäasetukset. Jälkimmäisen tyhjennystarve on kyllä hieman outo, mutta jos tuota toimintoa ei aio ottaa käyttöön, voi sen tyhjentää halutessaan.

Jos kuitenkin aikoo ottaa nidepaketit (item bundle) käyttöön niin tällä Liimataisen Mikon tekemällä IntranetUserJS-piilotuksella välilehden saa piiloon:

```
// Palautusilmoitus-välilehden piilotus asiakkaan tiedoissa ja lainoissa
$(document).ready(function(){ 
  $("a#return-claims-tab").parent().hide();
});
```

**Comment by Kati-Helle** [comment]
Kiitos :)

**Comment by AnneliO** [comment]
Tähän vielä muistiin lisätieto, että Nidepaketti-toiminnallisuus tekee automaattisesti "ilmoittaa palauttaneensa" -merkinnän lainaan, kun palautetaan nidepaketti ja kaikkia niteitä ei vahvisteta palautetuksi. Eli paketista puuttuvat niteet laitetaan kadonnut-tilaan (Puuttuu nidepaketista) ja niistä tehdään palautusilmoitus/claim.
