### ISSUE TITLE
Varaa asiakkaalle -toiminnossa asiakastieto väärällä rivillä

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#122]
### Mikä vikana?

Jos lähtee asiakkaan tiedoista käsin varaamaan teosta Hae ja varaa -toiminnolla ja tietueessa klikkaa työkalurivillä _Varaa_ avautuu tällainen valikko:
![kuva](https://user-images.githubusercontent.com/33121325/224051220-afc1460b-6503-4b21-b6ba-f5caa1e46d3f.png)

Valikossa pitäisi olla vain kaksi riviä Varaa ja Varaa asiakkaalle xxx eli näin:
![kuva](https://user-images.githubusercontent.com/33121325/224051806-ba2541a1-6073-4577-990b-51a9889444a8.png)

Jos meidän näkymässä klikkaa Varaa asiakkaalle, tehdään varaus halutulle asiakkaalle. Jos taas klikkaa asiakkaan nimeä, päätyy asiakkaan tietoihin.

Kokeilin poistaa kaikki meidän IntranetUserCSS:t ja IntranetUserJS:t ja niiden poistolla ei ollut vaikutusta.

### Kuinka toistaa ongelma/asia

1. Hae jokin asiakas, esim. https://vaara-next.koha-suomi.fi/cgi-bin/koha/members/moremember.pl?borrowernumber=11010257
2. Klikkaa _Hae ja varaa_ -nappia.
3. Hae jokin teos, esim. Kaikki tiet vievät Roomaan
4. Klikkaa _Varaa_-nappia.
5. Klikkaa _Varaa asiakkaalle_ -nappia, niin pääset tekemään varauksen halutulle asiakkaalle.
6. Klikkaa asiakkaan nimeä valikossa ja päädyt asiakkaan tietoihin.

### Asiasanat/tagit

Varaa asiakkaalle Hae ja varaa varauksen teko varaaminen

**Comment by emta001** [comment]
Johtuu 0021 branchin muutoksista (tiketti #58). Korjaan tämän suoraan siihen päälle.

**Comment by emta001** [comment]
Eli tämä on nyt korjattu branchiin 0021. Johtui siis siitä, että kyseisen <a> tägin sisällä käytettävään patron-title.inciin ei välitetty no_html parametriä.

**Comment by Kati-Helle** [comment]
Englanninkielisessä Helle-nextissä toimii nyt oikein. Asiakkaan nimestä pääsee tekemää varauksen ko. asiakkaalle (Place hold for...)
![kuva](https://user-images.githubusercontent.com/99952449/225890724-4dd92f71-d160-45ae-bbb5-95caa2af4faf.png)

**Comment by AnneliO** [comment]
Minunkin testien mukaan tämä toimii. Suljen tiketin. :)

**Comment by Kati-Helle** [comment]
Hae ja varaa -painikkeesta ei tällä hetkellä avaudu vaihtoehtoja
![kuva](https://user-images.githubusercontent.com/99952449/230015799-8d7d2b57-1920-4688-93c9-ab98f1861c20.png)

Sama tilanne englanninkielisessä Kohassa.

**Comment by AnneliO** [comment]
Tuosta napista pitäisi siirtyä vain tiedonhakuun, eikö niin tapahdu? Mitään vaihtoehtoja ei siis pitäisi tullakaan tarjolle. :)

**Comment by Kati-Helle** [comment]
Hyvä! Kunnossa siis.

**Comment by MikkoLiimatainen** [comment]
Tämä on taas nextillä riesana.

**Comment by emta001** [comment]
> Tämä on taas nextillä riesana.

Oon näköjään unohtanut ottaa korjauksen matkaan tuohon branchiin. Korjataan.

**Comment by emta001** [comment]
> > Tämä on taas nextillä riesana.
> 
> Oon näköjään unohtanut ottaa korjauksen matkaan tuohon branchiin. Korjataan.

Eikun hetkinen, on se siellä. Nyt on jokin muu pielessä.

**Comment by emta001** [comment]
En saa kyllä tätä nextillä toistettua. @MikkoLiimatainen onko kyseessä varmasti sama bugi vai miten saitte tämän toistettua?

**Comment by AnneliO** [comment]
Sain toistettua outi-nextillä näin:

1. Hae asiakas ja mene asiakkaan tietoihin
2. Valitse Search to hold yläreunan valikosta
3. Hae jokin teos, esim. marja
4. Avaa joltain teokselta auki perustiedot-näyttö
5. Klikkaa Place hold -näppäintä ja saa seuraava näkymä:
![kuva](https://github.com/KohaSuomi/Koha-22x/assets/33121325/9d0b46a5-d0b2-4083-b313-1fd2eb9e8674)

**Comment by emta001** [comment]
> Sain toistettua outi-nextillä näin:
> 
>     1. Hae asiakas ja mene asiakkaan tietoihin
> 
>     2. Valitse Search to hold yläreunan valikosta
> 
>     3. Hae jokin teos, esim. marja
> 
>     4. Avaa joltain teokselta auki perustiedot-näyttö
> 
>     5. Klikkaa Place hold -näppäintä ja saa seuraava näkymä:
>        ![kuva](https://private-user-images.githubusercontent.com/33121325/323541983-9d0b46a5-d0b2-4083-b313-1fd2eb9e8674.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MzIyMjYsIm5iZiI6MTcxMzQzMTkyNiwicGF0aCI6Ii8zMzEyMTMyNS8zMjM1NDE5ODMtOWQwYjQ2YTUtZDBiMi00MDgzLWIzMTMtMWZkMmViOWU4Njc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA5MTg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5OGRjODU5YzE3NWYwZGQ4YTZjN2M4YmY4NzJjZGU2ZTkyNzMyM2RkODhmMTZjZjJmODcyZDhjMDU1NTRiYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2YQjtZ7pYbCpjh2WBf-P_XNESJtELU2gqPxUNe8AGOM)

Jeps, rikkihän tuo on vaikka korjaus on paikallaan branchissa. Onpa kumma. Avaan tämän tiketin uudestaan 23-repossa ja suljen tämän tiketin. Jatketaan selvittelyä siellä.
