### ISSUE TITLE
Tarkan haun fasetille Räätälöidyt hakutulokset nimimuutos

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-22x#123]
### Mikä vikana?

Saisiko Tarkan haun Räätälöidyt hakutulokset -otsikolle niminuutoksen. 
Räätälöinnissä mukana Emokohda JA Osakohde:

![kuva](https://user-images.githubusercontent.com/99952449/224234741-45862934-eebf-4ef1-b443-e01fe03c4d1f.png)

**Comment by AnneliO** [comment]
Minkälainen nimimuutos sulla oli mielessä?

**Comment by Kati-Helle** [comment]
Voisiko olla sama kuin Tarkka haku -toiminnossa?
Emokohde/Osakohde

![kuva](https://user-images.githubusercontent.com/99952449/224248527-1bb3bc9c-7022-447a-b60d-d349f0bd7ea3.png)

**Comment by AnneliO** [comment]
Siihen räätälöityihin hakutuloksiin voi tehdä halutessaan muitakin rajauksia kuin emokohde/osakohde-rajaukset, joten en lähtisi muuttamaan toiminnon nimeä ainakaan ihan noin paljon. :)

**Comment by Kati-Helle** [comment]
Entäpä 
Hakurajauksia
tai
Rajaa hakua
tai 
Rajaa hakutulosta

**Comment by pirliis** [comment]
"Rajaa hakutulosta" olisi hyvä.

**Comment by AnneliO** [comment]
![kuva](https://user-images.githubusercontent.com/33121325/225308240-14dc073d-46b4-470f-91e9-33d45bf226e7.png)

Osion pääotsikossa on _Tarkenna hakuasi_ ja tuo Räätälöidyt haun rajaukset on ikäänkuin otsikkotasolla 2, joten ehdotetuista olisi minusta paras tällä hetkellä tuo _Hakurajauksia_ tai jos noudattaa muiden vastaavien otsikkotasojen sanamuotoa, niin _Hakurajaukset_.

**Comment by pirliis** [comment]
_Hakurajaukset_ ok.

**Comment by AnneliO** [comment]
Räätälöidyt haun rajaukset muutettu käännöstiedostoissa muotoon Hakurajaukset ja tiedosto viety GitHubiin. Tulee näkyviin, kun käännökset ajetaan seuraavan kerran.

**Comment by Kati-Helle** [comment]
Kiitos Anneli. Muutos näkyy
![kuva](https://user-images.githubusercontent.com/99952449/227466830-f9f7ab9a-c263-4d1f-b621-ffedd90b674d.png)
