### ISSUE TITLE
Hellen Tarkka haku: hakuvaihtoehdoksi Hyllytarkenne

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-22x#124]
### Mikä vikana?

Hellen Tarkka haku -hakuvaihtoehdoissa ei näy Hyllytarkenne. 
Hellessä on neljä Hyllytarkenne-arvoa käytössä.

![kuva](https://user-images.githubusercontent.com/99952449/224239225-cec3ed32-16fa-472c-8456-f4327bf7970b.png)

Hyllytarkenne hakuvaihtoehdoksi -määrittely sisältyy IntranetUserJS-rimpsuuun:

/// ALKU ///

/* Näillä rimpsuilla tehdään tiedonhakuun Indeksointi-työryhmän päättämät muutokset. Asetetaan otsikot eri kielillä aineistotyyppi-, hyllytarkenne- ja ikärajavälilehdille tiedonhaussa. Lisätään alasvetovalikoihin YKL, UDK, Päivittyvä julkaisu ja Kausijulkaisu */
$(document).ready(function() {

    if ( $('html').attr('lang') == 'fi-FI') {
      $("#advsearch-tab-mtype a").text("Aineistotyyppi"); /* MTYPE auktorisoituarvo tarkassa haussa */
      $("#advsearch-tab-subloc a").text("Hyllytarkenne"); /* SUBLOC auktorisoituarvo tarkassa haussa */
      $("#advsearch-tab-agelevel a").text("Ikärajat"); /* AGELEVEL auktorisoituarvo tarkassa haussa */
      $("#searchterms select").append(new Option('YKL-luokitus', 'other-classification')); /* Lisää uuden valinnan YKL-luokitus */
      $("#searchterms select").append(new Option('UDK-luokitus', 'udc-classification')); /* Lisää uuden valinnan UDK-luokitus */
      $("#subtype select option[value='mus:i'").parent().append(new Option('Päivittyvä julkaisu', 'bib-level:i')); /*Lisää lisärajoitukset valikkoon uuden arvon */
      $("#subtype select option[value='mus:i'").parent().append(new Option('Kausijulkaisu', 'bib-level:s')); /*Lisää lisärajoitukset valikkoon uuden arvon */
    }
    else if ( $('html').attr('lang') == 'sv-SE') {
      $("#advsearch-tab-mtype a").text("Materialtyp");
      $("#advsearch-tab-subloc a").text("Underplats");
      $("#advsearch-tab-agelevel a").text("Åldersgränser");
      $("#searchterms select").append(new Option('YKL-klassification', 'other-classification'));
      $("#searchterms select").append(new Option('UDC-klassification', 'udc-classification'));
      $("#subtype select option[value='mus:i'").parent().append(new Option('Publikation som uppdateras', 'bib-level:i'));
      $("#subtype select option[value='mus:i'").parent().append(new Option('Seriell publikation', 'bib-level:s'));
    }
    else if ( $('html').attr('lang') == 'en') {
      $("#advsearch-tab-mtype a").text("Material type");
      $("#advsearch-tab-subloc a").text("Sub location"); 
      $("#advsearch-tab-agelevel a").text("Age levels");
      $("#searchterms select").append(new Option('Other classification', 'other-classification'));
      $("#searchterms select").append(new Option('UDC classification', 'udc-classification'));
      $("#subtype select option[value='mus:i'").parent().append(new Option('Integrating resource', 'bib-level:i'));
      $("#subtype select option[value='mus:i'").parent().append(new Option('Serial', 'bib-level:s'));
    }

    $("#searchterms select option[value='location']").val('loc'); /* Muuttaa location-arvon loc-arvoksi "Hakusanat"-valikossa */
});

/// LOPPU ///

Muut rimpsussa määritettävät toteutuvat Hellen Tarkka haku -toiminnossa.

**Comment by AnneliO** [comment]
Tämä pitäisi toimia niin, että AdvancedSearchTypes -järjestelmäasetukseen lisätään subloc, mutta näköjään arvot eivät tule näkyviin välilehdelle. Liittynee ehkä siihen, että auktorisoitu arvo on kirjoitettu isolla SUBLOC.  En enää muista, oliko hyllytarkennetta tarkoituskaan alunperin lisätä tuolla tavalla omaksi välilehdekseen vai onko testaus aikanaan jäänyt puolitiehen.

Nykysellään se ei tosiaan tule toimimaan, kun auktorisoidun arvon luokka on isolla kirjoitettu ja tuo toimintatapa tukenee vain pieniä kirjaimia. Arvon luokan muuttaminen on todennäköisesti iso muutos ja voi aiheuttaa yllättäviä oireita.

**Comment by Kati-Helle** [comment]
Tiedoksi, että vaihdoin tiketin rimpsuun ruotsinkieliset vastineet 

Päivittyvä julkaisu
Publikation som uppdateras

Kausijulkaisu
Seriell publikation


Saako jonnekin vaihdettua vielä nämä? 

Emokohde
Huvudobjekt

Osakohde
Delobjekt

Hellessä ruotsinkieliset ovat nuo joskus miettineet sen jälkeen, kun rimpsu oli jo käytössä. Jääneet muuttamatta.

**Comment by AnneliO** [comment]
Kiitos käännöksistä! Lisäsin nuo nyt tähän IntranetUserJS-rimpsuun. Lisään tuo vielä myöhemmin IntranetUserJS-wikiin.

```
/// ALKU ///

/* Näillä rimpsuilla tehdään tiedonhakuun Indeksointi-työryhmän päättämät muutokset. Asetetaan otsikot eri kielillä aineistotyyppi-, hyllytarkenne- ja ikärajavälilehdille tiedonhaussa. Lisätään alasvetovalikoihin YKL, UDK, Päivittyvä julkaisu ja Kausijulkaisu */
$(document).ready(function() {

    if ( $('html').attr('lang') == 'fi-FI') {
      $("#advsearch-tab-mtype a").text("Aineistotyyppi"); /* MTYPE auktorisoituarvo tarkassa haussa */
      $("#advsearch-tab-subloc a").text("Hyllytarkenne"); /* SUBLOC auktorisoituarvo tarkassa haussa */
      $("#advsearch-tab-agelevel a").text("Ikärajat"); /* AGELEVEL auktorisoituarvo tarkassa haussa */
      $("#advsearch-tab-bib-level a").text("Emokohde/Osakohde"); /* bib-level auktorisoituarvo tarkassa haussa */
      $("#searchterms select").append(new Option('YKL-luokitus', 'other-classification')); /* Lisää uuden valinnan YKL-luokitus */
      $("#searchterms select").append(new Option('UDK-luokitus', 'udc-classification')); /* Lisää uuden valinnan UDK-luokitus */
      $("#subtype select option[value='mus:i'").parent().append(new Option('Päivittyvä julkaisu', 'bib-level:i')); /*Lisää lisärajoitukset valikkoon uuden arvon */
      $("#subtype select option[value='mus:i'").parent().append(new Option('Kausijulkaisu', 'bib-level:s')); /*Lisää lisärajoitukset valikkoon uuden arvon */
    }
    else if ( $('html').attr('lang') == 'sv-SE') {
      $("#advsearch-tab-mtype a").text("Materialtyp");
      $("#advsearch-tab-subloc a").text("Underplats");
      $("#advsearch-tab-agelevel a").text("Åldersgränser");
      $("#advsearch-tab-bib-level a").text("Huvudobjekt/Delobjekt");
      $("#searchterms select").append(new Option('YKL-klassification', 'other-classification'));
      $("#searchterms select").append(new Option('UDC-klassification', 'udc-classification'));
      $("#subtype select option[value='mus:i'").parent().append(new Option('Publikation som uppdateras', 'bib-level:i'));
      $("#subtype select option[value='mus:i'").parent().append(new Option('Seriell publikation', 'bib-level:s'));
    }
    else if ( $('html').attr('lang') == 'en') {
      $("#advsearch-tab-mtype a").text("Material type");
      $("#advsearch-tab-subloc a").text("Sub location"); 
      $("#advsearch-tab-agelevel a").text("Age levels");
      $("#advsearch-tab-bib-level a").text("Child/monographic record");
      $("#searchterms select").append(new Option('Other classification', 'other-classification'));
      $("#searchterms select").append(new Option('UDC classification', 'udc-classification'));
      $("#subtype select option[value='mus:i'").parent().append(new Option('Integrating resource', 'bib-level:i'));
      $("#subtype select option[value='mus:i'").parent().append(new Option('Serial', 'bib-level:s'));
    }

    $("#searchterms select option[value='location']").val('loc'); /* Muuttaa location-arvon loc-arvoksi "Hakusanat"-valikossa */
});

/// LOPPU ///
```

**Comment by ajrajala** [comment]
> Tämä pitäisi toimia niin, että AdvancedSearchTypes -järjestelmäasetukseen lisätään subloc, mutta näköjään arvot eivät tule näkyviin välilehdelle. Liittynee ehkä siihen, että auktorisoitu arvo on kirjoitettu isolla SUBLOC. En enää muista, oliko hyllytarkennetta tarkoituskaan alunperin lisätä tuolla tavalla omaksi välilehdekseen vai onko testaus aikanaan jäänyt puolitiehen.
> 
> Nykysellään se ei tosiaan tule toimimaan, kun auktorisoidun arvon luokka on isolla kirjoitettu ja tuo toimintatapa tukenee vain pieniä kirjaimia. Arvon luokan muuttaminen on todennäköisesti iso muutos ja voi aiheuttaa yllättäviä oireita.

Vaskissa asetukseen AdvancedSearchTypes subloc on kirjoitettu pienellä, ja meillä hakuvaihtoehto näkyy omalla välilehdellään (+tekee onnistuneesti haun tyyliin _'subloc:("SLTM")'_ )

**Comment by AnneliO** [comment]
Testasin nyt uudelleen Hellen nextillä ja kyllä se tosiaan toimii. En tiedä, miten testasin aiemmin. :D 

Muokkasin myös tuota IntranetUserJS-rimpsua, koska sieltä puuttui emokohde/osakohde-välilehdeltä englanninkielinen käännös.

**Comment by Kati-Helle** [comment]
Kiitos, hyllytarkenne on nyt hakuvaihtoehtona ja kuvassa avattuna hakuvaihtoehtoineen.
![kuva](https://user-images.githubusercontent.com/99952449/225223233-b871e5e9-869c-448e-b278-96efadb2e361.png)

Tällä hetkellä Tarkan haun Lyhytlaina-hyllytarkenteella haun hakutulos on 23.
Nidehaussa Lyhytlaina-hyllytarkenteen hakutulos on 56.
