### ISSUE TITLE
Asiakastiedot, viestiasetusten Varauksen noutomuistutus -vaihtoehdon piilottaminen

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-22x#126]
### Mikä vikana?

Miten piilottaa uudessa versiossa asiakastiedon viestiasetuksista Varauksen noutomuistutus? Viestiasetukset ovat asiakkaan muokkauksessa ja asiakkaan tiedoissa.

Nyt käytössä olevan version rimpsulla tapahtui uudessa versiossa näin (ennen/jälkeen kuvat):

![kuva](https://user-images.githubusercontent.com/99952449/224264042-c875b9a4-b172-4423-85a0-f080691c8145.png)

Testatessa käytetyt rimpsut:
/* Varauksen noutomuistutuksen piilotus asiakaslomakkeelta */
body#pat_memberentrygen #memberentry_messaging_prefs tr:last-child { display:none; }

/* Varauksen noutomuistutuksen piilotus asiakkaan tiedot-sivulta */
body#pat_moremember #patron-messaging-prefs tr:last-child { display:none; }

**Comment by AnneliO** [comment]
Testailin tuota rimpsua aiemmin, mutta se tosiaan rikkoo viestiasetustaulun. En vielä keksinyt toista keinoa. Jatkan tutkimista ja jos en keksi mitään, joku muu saa jatkaa miettimistä. :)

**Comment by ajrajala** [comment]
Vaski-nextillä piilotus ei näyttäisi rikkovan mitään, ihan samat ei näköjään ole nuo meidän nextillä olevat css-rimpsu (boldasin eroavaisuudet):

/* Noutomuistutuksen piilotus asiakaslomakkeelta */ /* Toimii 9.3.2023 MLI */
 body#pat_memberentrygen #memberentry_messaging_prefs **table tbody** tr:last-child { display:none; }

/* Noutomuistutuksen piilotus tiedot-sivulta */ /* Toimii 9.3.2023 MLI */
body#pat_moremember #patron-messaging-prefs **table tbody** tr:last-child { display:none; }

**Comment by Kati-Helle** [comment]
Kiitos Anni!
Vaskin rimpsuilla asiakkaan viestiasetusten Varauksen noutomuistutus- vaihtoehto nätisti piilossa. Helle-esimerkkikuva asiakkaan Tiedot-näytöltä
![kuva](https://user-images.githubusercontent.com/99952449/226316207-71b8f27d-614b-4b9d-aa01-24fcf93a7b59.png)

**Comment by AnneliO** [comment]
Lisäsin Annin laittamat rimpsut [IntranetUserCSS-sivulle vapaaehtoisiin](https://github.com/KohaSuomi/Koha-22x/wiki/IntranetUserCSS#vapaaehtoiset). :)

**Comment by ReettaSiili** [comment]
Toimivat myös Siilissä nätisti.
