### ISSUE TITLE
Teoksen varaukset sivulla ei toimi varauksen poisto toiminnolla "Cancel selected holds"

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha-22x#127]
### Mikä vikana?

Teoksen varaukset sivulla, esim. OUTIssa: https://outi-next.koha-suomi.fi/cgi-bin/koha/reserve/request.pl?
ei toimi toimintopainike "Cancel selected holds". Kun valitsee poistettavan varauksen ja painaa ko. painiketta, varaus ei poistu.
![image](https://user-images.githubusercontent.com/98814860/225590546-0fc2f2de-029c-4b4d-ac73-a550f2265516.png)

### Mitä pitäisi tapahtua

Kun on valinnut poistettavan varauksen ja painaa ko. toimintopainiketta, varauksen pitäisi poistua.

**Comment by AnneliO** [comment]
Liittyneekö tikettiin #56.

**Comment by emta001** [comment]
Korjaus tuotu nexteille.

**Comment by AnneliO** [comment]
Tämän voi testata kunnolla vasta sitten, kun tiketti #129 on saatu ratkaistua.

**Comment by pirliis** [comment]
Joo, ei ainakaan vielä "Cancel selected holds" -painike toimi teoksen varaukset sivulla.

**Comment by emta001** [comment]
#129 on nyt korjattu, toimiiko tämä nyt?

**Comment by Kati-Helle** [comment]
Testasin tietueella, jolla on yksi varaus.
Varauksen poistoon valitsin varauksen ja klikkasin 'Cancel selected holds'. Tuon jälkeen varaustieto 'välähti', eikä varaus poistunut tietueen varauksista. Kävin tietueen perustiedoissa ja palasin varauksiin, jossa varausta ei enää näkynyt.

Poisto toimii, mutta poisto ei näy heti tietueen varaussivulla.

**Comment by AnneliO** [comment]
Testasin Vaaran nextillä ja Cancel selected holds -nappi toimii.

Kati, varauksen poisto menee taustatöihin, mikä ei näy Koha-Suomen sivutus-muutosten vuoksi (tieto taustatyöstä ja linkki siihen puuttuu). Kun työ on valmistunut ja päivittää varaussivun, poistuvat poistetut varaukset näkyvistä. Tämä toimii tuotannossa tällä hetkellä samalla tavalla.
