### ISSUE TITLE
Taustatyöt ei toimi oikein

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha-22x#129]
### Mikä vikana?

Vaski-nextillä huomattiin, että niteiden erämuokkauksessa työjonoon siirtynyt työ ei valmistu eikä sitä ilmesty näkyville [Taustatyöt-sivulle](https://vaski-next.koha-suomi.fi/cgi-bin/koha/admin/background_jobs.pl?). Jos Taustatöissä klikkaa pois rastin "Only include jobs started in the last hour", saa pop-upina seuraavan virheilmoituksen:

_Jotain meni pieleen taulua ladattaessa.
500: Internal Server Error. 
Expected object - got null.
Expected object - got null.
Expected object - got null.
Expected object - got null.
Expected object - got null.
Expected object - got null.
Expected object - got null.
Expected object - got null.
Expected object - got null.
Expected object - got null.
Expected object - got null.
Expected object - got null.
Expected object - got null.
Expected object - got null.
Expected object - got null.
Expected object - got null.
Expected object - got null.
Expected object - got null.
Expected object - got null.
Expected object - got null._

### Jotain muuta?

Anneli testasi Vaara-nextillä ja siellä samaa ongelmaa ei ilmennyt. Muista next-kannoista ei tietoa.

**Comment by emta001** [comment]
Ainakin 500 herjaan löytyi vastaus, backgroundjobs-tauluun on tullut uusi sarake context, joka on kaikilla vanhoilla taulun riveillä NULL. Mutta API haluaa, että siinä lähetettäisiin JSON-objekti. Muutin kaikkien vanhojen rivien context arvoksi {} (tyhjä JSON objekti) ja ainakin taustatyöt ilmeistyivät näkyviin ja herjailu katosi.

**Comment by ajrajala** [comment]
500 herja tosiaan katosi. Mutta koitin tehdä vielä niteille erämuokkauksen uudelleen eikä se edelleenkään ilmesty taustatöihin (eikä niteille päivity niille asetettua uutta arvoa).

**Comment by AnneliO** [comment]
Myöskään Vaarassa niteiden erämuokkaukset eivät mene taustatöihin, eikä niteisiin tapahdu muutoksia.

**Comment by ghost** [comment]
Taustatöissä on uusi työjono long_tasks johon menevät mm. varausten poistot. Tuo pitää ottaa background_jobs_workeria ajaessa käyttöön, muuten taustatyöt eivät valmistu (eivätkä ilmeisesti näy käyttöliittymässä, tallentuvat kyllä tietokantaan).

**Comment by ajrajala** [comment]
Long_tasks on ilmeisesti käytössä, nyt taustatöihin ja käyttöliittymään muutenkin tulee näkyviin esim. varausten poistot ja niteiden erämuokkaukset. Tämän tiketin voinee siis sulkea.

**Comment by AnneliO** [comment]
Vaarassa ei toimi edelleenkään esim. niteiden erämuokkaukset, eikä ne tule jonoon.

**Comment by CodoDerDritte** [comment]
> Long_tasks on ilmeisesti käytössä, nyt taustatöihin ja käyttöliittymään muutenkin tulee näkyviin esim. varausten poistot ja niteiden erämuokkaukset. Tämän tiketin voinee siis sulkea.

Kyllä, se laitettiin päälle eilen (vai olikohan se toissapäivänä).

**Comment by AnneliO** [comment]
Testasin nyt uudelleen ja toimi se sittenkin, mutta ilmeisesti toiminnossa on nyt ainakin tällaiset ongelmat:

Kun työ menee jonoon, saa ilmoituksen, jossa on linkki työhön. Linkistä kuitenkin puuttuu työn id ja käyttäjä päätyy taustatöiden ylläpitosivulle, jonne ei ole kaikilla pääsyä.

![kuva](https://user-images.githubusercontent.com/33121325/233370694-bb2e0125-ecc3-4bdb-9f3d-80074d456d57.png)

Taustatöiden listalla taas jos ottaa täpän pois kohdasta _Only include jobs started in the last hour_, katoaa listalta työt lähitunneilta.

Täppä paikallaan:
![kuva](https://user-images.githubusercontent.com/33121325/233371624-0837c759-ef61-47ef-b56e-5e2582a92fc3.png)


Täppä pois:
![kuva](https://user-images.githubusercontent.com/33121325/233371721-4fb1c89c-537d-431f-b084-7b940d4c5968.png)

**Comment by AnneliO** [comment]
Testasin tätä vielä Vaaran ja OUTIn nexteillä sellaisella tunnuksella, jolla ei ole taustaöiden hallinnoinnin oikeuksia ja niillä pääsi kyllä tuohon töiden listanäkymään eli sen puolesta asia ok.

Testasin PTFS Europen sandboxissa erämuokkausta ja siellä taustatyölinkkissä on myös työn id ja linkistä päättyy kyseisen työn tietoihin.

**Comment by AnneliO** [comment]
Tein Only include jobs started in the last hour -täpästä erillisen tiketin #170.

Taustatyöilmoituksen puuttumista käsitellään tiketissä #37.

Suljen tämän tiketin.

**Comment by emta001** [comment]
> Testasin nyt uudelleen ja toimi se sittenkin, mutta ilmeisesti toiminnossa on nyt ainakin tällaiset ongelmat:
> 
> Kun työ menee jonoon, saa ilmoituksen, jossa on linkki työhön. Linkistä kuitenkin puuttuu työn id ja käyttäjä päätyy taustatöiden ylläpitosivulle, jonne ei ole kaikilla pääsyä.
> 
> ![kuva](https://user-images.githubusercontent.com/33121325/233370694-bb2e0125-ecc3-4bdb-9f3d-80074d456d57.png)

Tää onkin jännä ongelma. Testailtiin sekä Villen että miun koneella, Villellä toimii id:n muodostus ja miulla ei. Testattiin myös eri kimpoissa, missään ei vaikuttaisi toimivan. Ei edes siili-nextillä, jonka kannasta Villellä on kopio. Eli ei voi olla skeema virhe. Ennemmin näyttäisi sille, että taustatyö ei kerkiä tallentumaan kantaan jolloin id:täkään ei muodostu siihen mennessä kun linkki pusketaan näytölle.
