### ISSUE TITLE
Tietuenäytön muutokset - ksdev/ks-0041-KD-4592-intra-xslt-display

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#13]
### Siirrettävä ominaisuus

Tietuenäytön xslt-muutokset.

**Comment by CodoDerDritte** [comment]
KohaSuomi/Koha#1963

**Comment by pknuuti** [comment]
Ihan hyvältä näyttää. Meillä kovasti toivotaan, että nimekkeen luokka näkyisi suoraan hakutulosnäytöllä, ettei tarvis klikata nimekettä auki. En tiedä, onko se tämän tiketin asia, mutta toivomus tässä siis esille :)

**Comment by AnneliO** [comment]
> Ihan hyvältä näyttää. Meillä kovasti toivotaan, että nimekkeen luokka näkyisi suoraan hakutulosnäytöllä, ettei tarvis klikata nimekettä auki. En tiedä, onko se tämän tiketin asia, mutta toivomus tässä siis esille :)

Hakutuloslistan luokkatietoa ei ole vielä toteutettu nykyversioon, vaan se on ollut toteutuslistalla. Se mainitaan tiketissä KohaSuomi/Koha#1963.

**Comment by pirliis** [comment]
OUTIn tuotannossa ja nextillä näyttäisi olevan samat tiedot sekä hakutulosnäytöllä että teoksen perustiedotnäytöllä.

**Comment by Kati-Helle** [comment]
Vertasin Hellen tuotannon ja nextin näkymiä. Nextillä tuotantoa vastaavat tiedot. 

Nextin Perustiedot-näytöllä hyvänä lisänä 'Asiakasliittymänäkymä: Avaa uudessa ikkunassa', jota tuotannossa ei ole.
(Linkki ei vielä toimi.)

**Comment by CodoDerDritte** [comment]
> Vertasin Hellen tuotannon ja nextin näkymiä. Nextillä tuotantoa vastaavat tiedot.
> 
> Nextin Perustiedot-näytöllä hyvänä lisänä 'Asiakasliittymänäkymä: Avaa uudessa ikkunassa', jota tuotannossa ei ole. (Linkki ei vielä toimi.)

Ei se kovin hyvä lisä ole kun se olisi viemässä Kohan OPAC:iin, jota ei ole eikä tule :D Oikea linkki on siellä oikeassa yläkulmassa nimellä "Open in Finna" / "Avaa Finnassa" / "Öppna i Finna". Täytyy pistää piiloon tuo turha "Asiakasliittymänäkymä".

**Comment by CodoDerDritte** [comment]
Tuon linkin näkymistä näköjään säätelee OpacBaseURL - asetus, jonka tulee olla tyhjä, koska OPAC ei ole käytössä. Tyhjensin sen Hellestä.

**Comment by CodoDerDritte** [comment]
![Screenshot from 2023-05-04 16-35-58](https://user-images.githubusercontent.com/13198085/236221979-5ea959f5-a653-493b-b515-7ba21e4dde93.png)

Tuo on siis oikea nappula, josta Finna-näkymään oikeasti pääsee siirtymään.

**Comment by rakkyllo** [comment]
Vaskin tuotannossa ja nextillä näyttäisi olevan samat tiedot. Testattiin myös tuon oikean Finna-painikkeen toiminta, toimii kuten pitää.

**Comment by Tuomas-Kyyti** [comment]
Kyytin Nextillä näkyy emotietueissa (esim. cd-levy ja nuotti) tietuenäytössä kohta _Kausijulkaisut: Näytä kausijulkaisutiedot_. Linkki vie hakutulokseen emoon kuuluvista osakohteista. Tuotannossa siinä kohtaa lukee _Osakohteet: Näytä osakohteet_.

![Image](https://user-images.githubusercontent.com/99244794/236814517-9a5c8d78-1ced-417a-a51d-f23bae425f9f.png)

**Comment by Tuomas-Kyyti** [comment]
Havainto siis tosiaan suomenkieliseltä puolelta. Englanniksi näkyy samoin kuin tuotannossa _Analytics: Show analytics_

**Comment by pknuuti** [comment]
Kappas, niinpä on Vaarassakin. Eli käännösvirhe.

**Comment by AnneliO** [comment]
Oikeita käännöksiä ei vielä ole, joten se taitaa kaivaa sen nyt jostain mistä lie sen käännöksen.

**Comment by AnneliO** [comment]
Analytics-käännös korjattu ja viety koha-translations-repositorioon [22.xx-branchiin](https://github.com/KohaSuomi/Koha-translations/commit/d210f58a818f57011c800ccd321cc13d6c15b80d).

**Comment by velimarj** [comment]
OUTIssa ainakin tuo _Kausijulkaisut: Näytä kausijulkaisutiedot_ oli muuttunut muotoon _Osakohteet: Näytä osakohteet_, kuten pitikin.

**Comment by pknuuti** [comment]
Huomioita Vaaran nextillä: Aineistotyyppi ei ole näkyvissä perustiedot-näkymässä. Pitää saada ehdottomasti näkyviin.
Uusina kenttinä näkyy perustiedot-näytöllä "MARC-kuvailupohjat: Kirja" ja "Elasticsearch tietue: [Näytä]". Tuo kuvailupohjatieto voi olla ihan tarpeellinen, mutta ton Elasticin vois jättää tuosta pois. Ainakaan minä en usko, että se kovinkaan monia käyttäjiä palvelee.

**Comment by LeenaKinnunen** [comment]
Lapissa nextissä samat tiedot kuin tuotannossa lukuunottamatta puuttuvaa Aineistotyyppiä. 
Kenttien 370 ja 388 (paikkamerkintö ja luontiaika) tiedot eivät näy nextillä (cd-aineisto).

Samaa mieltä Päivin kanssa, Elasticsearch tietue-linkki on turha.

**Comment by AnneliO** [comment]
Minun mielestä Elasticsearch tietue -linkki on tarpeellinen esim. kun selvitellään indeksoinnin ongelmia. Rivivirkailijalle se ei välttämättä ole sen tarpeellisempi kuin Finnassa oleva vastaava tieto. :)

Eli en piilottaisi sitä, jos siitä ei muuten ole haittaa. :)

**Comment by Kati-Helle** [comment]
> OUTIssa ainakin tuo _Kausijulkaisut: Näytä kausijulkaisutiedot_ oli muuttunut muotoon _Osakohteet: Näytä osakohteet_, kuten pitikin.

Hellessä samoin :)

**Comment by Kati-Helle** [comment]
DVD-elokuvatietueen erot Helle-nextissä tuotantoon verrattuna
puuttuu 
- Aineistotyyppi
- Kuulovammaisille tarkoitetun tekstityksen kieli
- Tuottajan maa
- Luontiaika
- Ikäraja

![kuva](https://github.com/KohaSuomi/Koha-22x/assets/99952449/843193ce-1296-42c4-8d5f-016f98c7bfec)

**Comment by AnneliO** [comment]
Käsitelty 23-version tiketissä. Suljen tämän.
