### ISSUE TITLE
Varauksen tiedoissa ei näy, että se kohdistuu nideryhmään

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#130]
### Mikä vikana?

Nyt kun tietueen varaukset-sivulle on tuotu Koha-Suomen sivutustoiminto, varauksen tiedoissa ei näy, että se kohdistuu nideryhmään.

### Mitä pitäisi tapahtua

Varauksen kohdalla pitäisi näkyä näin nideryhmä:

![kuva](https://user-images.githubusercontent.com/33121325/226322931-e0428035-f717-4f7d-8a54-6f9c40315bb9.png)

Mutta se näkyy näin:

![kuva](https://user-images.githubusercontent.com/33121325/226323272-5b94b261-1da0-4a0f-a347-3f5840f65380.png)

### Kuinka toistaa ongelma/asia

1. Hae jokin tietue, jossa on nideryhmä, esim. https://vaski-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=4271235
2. Tee varaus kohdistuen nideryhmään.
3. Huomioi, että nideryhmä-tieto ei näy varauksen kohdalla.

### Asiasanat/tagit

varaus nideryhmät nideryhmä varauksen teko varauksen tekeminen

**Comment by AnneliO** [comment]
Liittyy tikettiin #56.

**Comment by AnneliO** [comment]
Asiakkaan tiedoista käsin varausta katsellessa varausryhmä näkyy.

**Comment by emta001** [comment]
Varaukset-sivulta tosiaan puuttui koko koodi näiden tietojen hakemiseen. Tuon tämän testeille jossain vaiheessa, korjailen samalla muitakin sivulta löytyviä virheitä.

**Comment by emta001** [comment]
Korjaus tuotu nexteille.

**Comment by AnneliO** [comment]
Ryhmän nimi näkyy nyt, mutta teksti on vähän eri tavalla kuin aiemmin. 

Nyt:
![kuva](https://user-images.githubusercontent.com/33121325/227230931-042ca8a2-0151-47ea-861a-08819e3fdcd3.png)

Ennen sivutusta:
![kuva](https://user-images.githubusercontent.com/33121325/227231342-69ca53dd-4f6f-4691-ab21-7428cd2bb202.png)

Eli sinänsä kyllä tieto löytyy, mutta onko se riittävän selkeä muiden mielestä? :)

**Comment by ajrajala** [comment]
Äsken kun katsoin niin Varaukset-sivulla näkyi nyt teksti "Seuraava vapaa nideryhmän 2023 : 1 nide" joka on sama kuin mitä näkyy asiakkaan tiedoissakin varauksia katsoessa. Nythän tuo on tosi selkeästi ilmaistu, ainakin minun mielestä. :)

**Comment by velimarj** [comment]
Selkeältä näytti minustakin.

**Comment by AnneliO** [comment]
Kun hyvältä näyttää, niin suljen tiketin. :)
