### ISSUE TITLE
Uuden huollettava aikuinen -asiakastiedon lisääminen: asiakastiedon saa lisättyä/tallennettua ilman takaajatietoa

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-22x#133]
### Mikä vikana?

Miten taakajatiedon saa huollettava aikuinen -asiakkaalle pakolliseksi tiedoksi?

Käytössä on tämä uuden version ominaisuus: Aikuisasiakastyypin voi määrittää huollettavaksi
Aikuisasiakastyypin voi määrittää huollettavaksi asiakastyyppien ylläpidossa. Aiemmin asiakastyyppi piti määrittää lapsi-tyyppiseksi, jotta asiakkaan lisäys/muokkausnäytölle tuli mahdollisuus lisätä asiakkaalle takaaja. Tätä voi käyttää esim. Huollettava muu kuin lapsi -asiakastyypillä
![kuva](https://user-images.githubusercontent.com/99952449/226556103-c68ef7b7-fd6b-4e4f-b0d1-2642d43ca872.png)

Kun ominaisuus on käytössä:
- Huollettava aikuinen -asiakastiedon muokkauksessa on mahdollista lisätä Takaaja-tieto
- Takaaja-tieto ei ole pakollinen tieto, eli asiakastieto tallentuu ilman takaaja-tietoa
![kuva](https://user-images.githubusercontent.com/99952449/226557628-84e57db5-25ac-4d8c-a7d9-5c2d1f96be1b.png)

Helle-tuotannossa Koha ilmoittaa tallentaessa, kun huollettavalta aikuiselta puuttuu takaajatieto:
![kuva](https://user-images.githubusercontent.com/99952449/226556345-39904c4d-6c03-49a3-a250-ba932b77b64b.png)

**Comment by AnneliO** [comment]
Liittyy tikettiin #44.

**Comment by emta001** [comment]
Tämä johtuu siitä, että takaajan pakollisuus tarkistetaan vain lapsiasiakkailta. Helle-nextillä huollettava aikuinen on määritelty aikuiseksi, tuotannossa tämä on vastaavasti lapsi.

**Comment by Kati-Helle** [comment]
Eli tämä uuden version mukana tullut uusi ominaisuus ei ole eikä tule olemaan käyttökelpoinen?
Aikuisasiakastyypin voi määrittää huollettavaksi
Aikuisasiakastyypin voi määrittää huollettavaksi asiakastyyppien ylläpidossa. Aiemmin asiakastyyppi piti määrittää lapsi-tyyppiseksi, jotta asiakkaan lisäys/muokkausnäytölle tuli mahdollisuus lisätä asiakkaalle takaaja. Tätä voi käyttää esim. Huollettava muu kuin lapsi -asiakastyypillä

**Comment by emta001** [comment]
> Eli tämä uuden version mukana tullut uusi ominaisuus ei ole eikä tule olemaan käyttökelpoinen? Aikuisasiakastyypin voi määrittää huollettavaksi Aikuisasiakastyypin voi määrittää huollettavaksi asiakastyyppien ylläpidossa. Aiemmin asiakastyyppi piti määrittää lapsi-tyyppiseksi, jotta asiakkaan lisäys/muokkausnäytölle tuli mahdollisuus lisätä asiakkaalle takaaja. Tätä voi käyttää esim. Huollettava muu kuin lapsi -asiakastyypillä

Kyseessä on ilmeisesti [tämä](https://github.com/KohaSuomi/Koha-22x/wiki/Uutta#aikuisasiakastyypin-voi-m%C3%A4%C3%A4ritt%C3%A4%C3%A4-huollettavaksi) asetus? Jos takaajan pakollisuus totetutetaan samoin kuin se on aiemmassa versiossa toiminut, niin asetus on tosiaan turha. Mutta pitää tutkia voitaisiinko tuo ottaa huomioon? Oletettavasti sen pitäisi onnistua ilman ongelmia.

**Comment by Kati-Helle** [comment]
> Kyseessä on ilmeisesti [tämä](https://github.com/KohaSuomi/Koha-22x/wiki/Uutta#aikuisasiakastyypin-voi-m%C3%A4%C3%A4ritt%C3%A4%C3%A4-huollettavaksi) asetus? Jos takaajan pakollisuus totetutetaan samoin kuin se on aiemmassa versiossa toiminut, niin asetus on tosiaan turha. Mutta pitää tutkia voitaisiinko tuo ottaa huomioon? Oletettavasti sen pitäisi onnistua ilman ongelmia.

Joo, tuosta linkistä aukeavasta uudesta asetuksesta on kysymys.

**Comment by emta001** [comment]
Sain tämän toetutettua niin, että holhottava asiakas voi olla aikuis-tyyppiä ja häneltä vaaditaan takaaja.

**Comment by Kati-Helle** [comment]
Toimii. Kiitos Emmi! 
Hellessä Huollettava aikuinen -asiakkaan tyyppi Aikuiset

![kuva](https://user-images.githubusercontent.com/99952449/228507274-4d17e77c-cf9e-4060-81f9-b40c5e6f2d97.png)


Huollettava aikuinen -asiakastieto tallennetaan ilman Takaaja-tietoa, jolloin Koha kertoo

![kuva](https://user-images.githubusercontent.com/99952449/228507693-2fae0b89-79f0-4c91-9177-14a3dec4cedb.png)

**Comment by pknuuti** [comment]
Vaaran nextillä testattu: holhottava, muu kuin lapsi -asiakastyyppi toimii kuten pitääkin eli vaatii vastuuhenkilön, muuten tallennus ei onnistu.

**Comment by emta001** [comment]
Tämänkin voisi sulkea.
