### ISSUE TITLE
Kausijulkaisun vastaanotossa kentät asettumaan siistimmin

### ISSUE THREAD

**Issue by HeliAuranen** [KohaSuomi/Koha-22x#134]
### Mikä vikana?

Nextissä kausijulkaisun vastaanotossa kentät ovat oletuksena vasemmalle keskitettynä, mutta perinteisesti kenät ovat siististi keskitetty

IntranetUserCSS:ään, Vaskin jo testattua toimintoa
body#ser_serials-edit.ser fieldset.rows ol li {display:block;}
body#ser_serials-edit.ser fieldset.rows ol li label {float: left; font-weight: 700; margin-right: 1rem; text-align: right;}

**Comment by AnneliO** [comment]
Lisäsin nämä rimpsut [IntranetUserCSS](https://github.com/KohaSuomi/Koha-22x/wiki/IntranetUserCSS#vapaaehtoiset)-wikiin vapaaehtoisiin. :)
