### ISSUE TITLE
Hae asiakkaita -hakuvaihtoehtojen muutostarpeita

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-22x#135]
### Mikä vikana?

Miten piilottaa Hae asiakkaita -vaihtoehdoista
- Käyttäjätunnus
- Toinen nimi

Muut hakuehtojen muutostarpeet
- nimimuutos: Puhelinnumero -> Lankapuhelin
- nimimuutos: Muu nimi (varaustunnus) -> Varaustunnus
- Varaustunnus-haku kohdistumaan oikeaan asiakastieto-kenttään

Helle-next vs. Helle-tuotanto
![kuva](https://user-images.githubusercontent.com/99952449/226907065-74ca204e-9dc7-49ad-85fb-141c1a956b56.png)

**Comment by AnneliO** [comment]
Teillä taitaa olla nuo kaksi määritetty valikkoon DefaultPatronSearchFields -järjestelmäasetuksessa. Eli jos otat ne pois tuosta asetuksesta, niin ne pitäisi kadota myös valikosta.

Tuo Muu nimi (Varaustunnus) eli othernames tulee myös  DefaultPatronSearchFields -asetuksesta, sekin kannattaa poistaa. Kentän nimen voisi tosiaan muuttaa, koska sitä ei jatkossa käytetä varaustunnuksena.

Pitää tutkia, saako asiakasmääreen jotenkin tuonne valikkoon vaihtoehdoksi. Manuaalin mukaan se tukee vain borrowers-taulun arvoja ja asiakasmääreet eivät ole borrowers-taulussa. HOLDID-asiakasmääreen haku pitäisi kuitenkin onnistua perushaulla.

**Comment by AnneliO** [comment]
Lankapuhelin-käännös on jo olemassa ennestään ja tulee näkyville seuraavan kerran, kun käännökset ajetaan.

**Comment by Kati-Helle** [comment]
Kiitos Anneli tiedoista.

Käyttäjätunnus-hakuarvo ei poistunut, vaikka arvon asetuksesta poistin.

Erikoistako? Matkapuhelin (mobile) hakuarvon lisääminen sellaisenaan asetukseen ei muodostanut hakuehtoa Matkapuhelin. Asetuksessa mainitaan tämä: 
Jos tyhjä, Koha asettaa oletukseksi "firstname,middle_name,surname,othernames,cardnumber,userid". Muut tähän asetukseen lisätyt kentät lisätään hakuvaihtoehtoina pudotusvalikkoon asiakkaan hakusivulla. 

Kun Helle-asetuksessa arvoina: surname,cardnumber,mobile

Hakuvaihtoehtoina nämä ja Käyttäjätunnus (username) edelleen hakuvaihtoehtona
![kuva](https://user-images.githubusercontent.com/99952449/227117098-6b69a0a5-8f54-45d2-8102-b9f5bf215da3.png)


Kun Helle-asetuksessa arvoina: cardnumber,mobile

Hakuvaihtoehtoina nämä ja Käyttäjätunnus (username) edelleen hakuvaihtoehtona
![kuva](https://user-images.githubusercontent.com/99952449/227118986-7acb2fec-bd3f-49e6-bad5-d1ee9cf1a323.png)


Kun Helle-asetuksessa arvona: mobile

Hakuvaihtoehtoina nämä ja Käyttäjätunnus edelleen hakuvaihtoehtona
![kuva](https://user-images.githubusercontent.com/99952449/227117188-adb28eb8-578e-43ba-b327-fb6eddf7ecb9.png)


En onnistunut saamaan hakutulosta, kun hain varaustunnus-asiakasmääreellä asiakastiedon perushaulla.
![kuva](https://user-images.githubusercontent.com/99952449/227119742-095de025-d32a-4ad1-85b5-3274f8f73bde.png)

**Comment by AnneliO** [comment]
Tuo näyttäisi nyt siltä, että nuo tietyt vaihtoehdot ovat valikossa tarjolla, oli  DefaultPatronSearchFields -asetuksessa mitä vaan.

Lisäsin Vaarassa nämä vaihtoehdot surname,firstname,cardnumber,mobile, niin valikossa oli nämä:
![kuva](https://user-images.githubusercontent.com/33121325/227136210-b73b680b-e494-40b6-9e66-224330decc6c.png)

Ja nyt kun luen asetuksen englanninkielistä kuvausta tarkemmin, niin sehän menee näin: Comma separated list defining the default fields to be used during a patron search **using the "standard" option**. Eli tuolla asetuksella määritetään vain perushaussa huomioon otettavat kentät. Jos asetukseen lisää sellaisia kenttiä, joita ei oletuksena siinä ole, silloin ne lisätään alasvetovalikkoon.

Testasin perushaulla varaustunnus-asiakasmääreellä hakua Vaarassa ja Hellessä ja sain kummassakin kannassa haettua varaustunnuksella.

Näkisin, että tähän ei liity sinänsä nyt näiden mainittujen säätöjen jälkeen versionvaihtoon liittyvistä muutoksista johtuvia kriittisiä/haitallisia ongelmia/ominaisuuksia, eli nykyversion valikko on hyvin samanlainen. Jos toivot edelleen joidenkin tietojen piilottamista, niin teetkö niistä erillisen tiketin Koha-repositorioon. Katsotaan niitä sitten versionvaihdon jälkeen. :)
