### ISSUE TITLE
Asiakkaan muokkauksessa Kirjastokortin numero-kentän arvon kopioitumien Käyttäjätunnus-kenttään

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-22x#136]
### Mikä vikana?

Onkohan uuteen versioon IntranetUserJS-rimpsua, joka kopioi asiakkaan muokkauksessa Kirjastokortin numero -kentän arvon Käyttäjätunnus-kenttään?
Asiakkaan Tiedot-välilehdellä näkyy nyt esim. uuden asiakastiedon lisäyksen jälkeen käyttäjätunnus tyyliin asiakkaan  etunimi.sukunimi

![kuva](https://user-images.githubusercontent.com/99952449/227157292-995a9528-bd54-49cf-af48-8b2ca560c6a3.png)

**Comment by AnneliO** [comment]
JS-rimpsua ei enää käytetä vaan tilalla on tietokantatriggeri joka vie kirjastokortin numeron userid-kenttään tallennuksen yhteydessä. Se triggeri nyt varmaankin puuttuu (vielä) nexteiltä.

**Comment by AnneliO** [comment]
Liittyy tikettiin #137.

**Comment by lmstrand** [comment]
Triggeri lisätty Helle-nextille.

**Comment by Kati-Helle** [comment]
Kiitos Lari :) Toimii.

![Image](https://user-images.githubusercontent.com/99952449/229023767-8b9398cc-93c9-4d77-b6a4-6992c0da5a87.png)
