### ISSUE TITLE
Tietokantatriggerit

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#137]
Meillä on käytössä erilaisia tietokantatriggereitä, joiden toiminta nexteillä pitää varmistaa.

Olemassa on seuraavat triggerit
- [ ] borrowers.cardnumber -> borrowers.userid (Triggereiden tarkoituksena on kirjoittaa userid-kenttään asiakkaan korttinumero, koska järjestelmään kirjautuminen halutaan mahdollistaa ainoastaan kirjastokortin numerolla + pin-koodilla. Samaan järjestelmään ei haluta toista rinnakkaista kirjautumistunnusta.)
- [ ] items.location -> items.permanent_location (Niteelle automaattinen permanent location tallennettaessa/muokatessa, ei voida käyttää CART-toiminnon kanssa yhdessä)
- [ ] ISBN- ja EAN-tunnuksista poistetaan väliviivat
- [ ] smsalertnumber -> mobile (Asiakkaiden matkapuhelinnumerotiedon tallennus/muuttaminen muuttaa automaattisesti tekstiviesti numeroon-kentän tiedon samaksi)
- [ ] wants digest = 1 pakotus (Koosteviesti-täppien pakotus)

### Asiasanat/tagit

triggeri, triggerit, trigger, triggers

**Comment by lmstrand** [comment]
Keräsin triggerien luontirimpsut tähän:

```
delimiter $$
create or replace trigger before_message_preferences_insert
before insert on borrower_message_preferences
for each row
begin
  if new.message_attribute_id=1 or new.message_attribute_id=2 then
    set new.wants_digest=1;
  end if;
end $$
delimiter ;


create or replace trigger before_borrowers_insert
    BEFORE INSERT
    ON borrowers FOR EACH ROW
    SET new.userid=new.cardnumber;

create or replace trigger before_borrowers_update
    BEFORE UPDATE
    ON borrowers FOR EACH ROW
    SET new.userid=new.cardnumber;
    
DELIMITER //
CREATE OR REPLACE TRIGGER insert_biblioitems_kd5270
BEFORE INSERT ON biblioitems
FOR EACH ROW FOLLOWS insert_remove_hyphens
BEGIN
IF NEW.isbn IS NOT NULL AND NEW.isbn like '%|%' THEN SET NEW.isbn = TRIM(SUBSTRING_INDEX(NEW.isbn, '|', 1));
END IF;
IF NEW.ean IS NOT NULL AND NEW.ean like '%|%' THEN SET NEW.ean = TRIM(SUBSTRING_INDEX(NEW.ean, '|', 1));
END IF;
IF NEW.issn IS NOT NULL AND NEW.issn like '%|%' THEN SET NEW.issn = TRIM(SUBSTRING_INDEX(NEW.issn, '|', 1));
END IF;
END //

DELIMITER ;


DELIMITER //
CREATE OR REPLACE TRIGGER update_biblioitems_kd5270
BEFORE UPDATE ON biblioitems
FOR EACH ROW FOLLOWS update_remove_hyphens
BEGIN
IF NEW.isbn IS NOT NULL AND NEW.isbn like '%|%' THEN SET NEW.isbn = TRIM(SUBSTRING_INDEX(NEW.isbn, '|', 1));
END IF;
IF NEW.ean IS NOT NULL AND NEW.ean like '%|%' THEN SET NEW.ean = TRIM(SUBSTRING_INDEX(NEW.ean, '|', 1));
END IF;
IF NEW.issn IS NOT NULL AND NEW.issn like '%|%' THEN SET NEW.issn = TRIM(SUBSTRING_INDEX(NEW.issn, '|', 1));
END IF;
END //

DELIMITER ;




delimiter $$
create or replace trigger insert_remove_hyphens
   before insert on biblioitems
   for each row
begin
   set new.isbn = REPLACE(new.isbn,'-',''), new.ean = REPLACE(new.ean,'-','');
end$$
delimiter ;

delimiter $$
create or replace trigger update_remove_hyphens
   before update on biblioitems
   for each row
begin
   set new.isbn = REPLACE(new.isbn,'-',''), new.ean = REPLACE(new.ean,'-','');
end$$
delimiter ;



delimiter $$
create or replace trigger before_items_insert
   before insert on items
   for each row
begin
   set NEW.permanent_location=NEW.location;
end$$
delimiter ;

delimiter $$
create or replace trigger before_items_update
   before update on items
   for each row
begin
   set NEW.permanent_location=NEW.location;
end$$
delimiter ;


DELIMITER $$

CREATE TRIGGER insert_smsalertnumber
    BEFORE INSERT
    ON borrowers FOR EACH ROW
BEGIN
    set new.smsalertnumber=new.mobile;
END$$    

DELIMITER ;


DELIMITER $$

CREATE TRIGGER update_smsalertnumber
    BEFORE UPDATE
    ON borrowers FOR EACH ROW
BEGIN
    set new.smsalertnumber=new.mobile;
END$$    

DELIMITER ;


PÄIVITETTY mobile<>sms-triggeri updatelle:

DELIMITER $$

CREATE OR REPLACE TRIGGER update_smsalertnumber
BEFORE UPDATE
ON borrowers FOR EACH ROW
BEGIN
if (new.smsalertnumber <=> old.smsalertnumber or (new.smsalertnumber is null and old.smsalertnumber <=> '') or (new.smsalertnumber <=> '' and old.smsalertnumber is null)) and not (new.mobile <=> old.mobile or (new.mobile is null and old.mobile <=> '') or (new.mobile <=> '' and old.mobile is null)) then set new.smsalertnumber=new.mobile; end if;
if (new.mobile <=> old.mobile or (new.mobile is null and old.mobile <=> '') or (new.mobile <=> '' and old.mobile is null)) and not (new.smsalertnumber <=> old.smsalertnumber or (new.smsalertnumber is null and old.smsalertnumber <=> '') or (new.smsalertnumber <=> '' and old.smsalertnumber is null)) then set new.mobile=new.smsalertnumber; end if;
END$$

DELIMITER ;

```

**Comment by lmstrand** [comment]
Vaara-next: Kaikki triggerit lisätty

**Comment by lmstrand** [comment]
Lappi-next: Kaikki paitsi before_items_insert/update lisätty (CART-toiminnon takia)

**Comment by lmstrand** [comment]
Vaski-next: Kaikki paitsi before_borrowers_insert/update (tyhjiä korttinumeroita)

**Comment by lmstrand** [comment]
Lumme-next: Kaikki paitsi before_borrowers_insert/update ja before_items_insert/update (CART)

**Comment by lmstrand** [comment]
Lappi-next: kaikki paitsi before_items_insert/update (CART) ja before_borrowers_insert/update (Virkailijoilla tekstimuotoisia tunnuksia/userid:tä)

**Comment by lmstrand** [comment]
Siili-next: kaikki paitsi before_borrowers_insert/update (before_items_insert/update puuttunut tuotannosta vaikka CART ei käytössä)

**Comment by lmstrand** [comment]
Outinext: kaikki lisätty (insert/update_smsalertnumber puuttui tuotannosta)

**Comment by lmstrand** [comment]
Kyyti-next: Kaikki paitsi  before_borrowers_insert/update ja before_items_insert/update (CART käytössä)

**Comment by lmstrand** [comment]
Kirkes-next: Kaikki paitsi before_borrowers_insert/update ja before_items_insert/update. Pitää kysyä CART-ominaisuuden käytöstä.

**Comment by lmstrand** [comment]
Helle-next: Kaikki paitsi before_borrowers_insert/update ja before_items_insert/update. (CART ei käytössä, lisätäänkö before_items_insert/update-triggerit?)

**Comment by lmstrand** [comment]
https://github.com/KohaSuomi/Koha-22x/issues/136 perusteella Helle-Nextille lisätty before_borrowers_insert/update-triggeri.

**Comment by lmstrand** [comment]
> Kirkes-next: Kaikki paitsi before_borrowers_insert/update ja before_items_insert/update. Pitää kysyä CART-ominaisuuden käytöstä.

CART ei käytössä. Triggerit before_items_insert/update lisätty.

**Comment by Kati-Helle** [comment]
Hellessä testatessani kävi näin:

borrowers.cardnumber -> borrowers.userid
-	toimii uudella asiakastiedolla
-	toimii olemassa olevan asiakkaan kirjastokorttinumeroarvon muuttaessa

items.location -> items.permanent_location
-	toimii uudella niteellä
-	toimii olemassa olevan niteen hyllypaikka-arvon muuttaessa

ISBN- ja EAN-tunnuksista poistetaan väliviivat
- ISBN-tunnus, ei toimi: poimin TäTistä tietueen, jossa on 020-kentän arvossa väliviivat 020a=978-951-1-40886-4. Hellessä tietueen muokkausnäytöllä väliviivoja ei ole/ei näy. Tietueen tallennuksen jälkeen väliviivoja ei ole/ei näy.
*Muutin toimii -> ei toimi, koska Heikkisen Antti ilmoitti "Hei, hoksautuksena tähän, ettei itse Marc-tietueesta/Marc-näytöiltä saisi poistua väliviivat 020, 024 ja 028-kentistä, vain niistä tietokantatauluista kentissä 020 ja 024."
- EAN-tunnus: vielä testaamatta, kun en löytänyt/keksinyt väliviivallisen EAN-arvon omaavaa tietuetta TäTistä

smsalertnumber -> mobile
- arvo lisätty Matkapuhelin-kenttään: tallennuksen jälkeen arvo on myös Tekstiviesti numeroon -kentässä
- Matkapuhelin-kentän arvoa muutettu: tallennuksen jälkeen muutettu arvo on myös Tekstiviesti numeroon -kentässä
- arvo poistettu Matkapuhelin-kentästä: tallennuksen jälkeen arvoa ei ole myöskään Tekstiviesti numeroon -kentässä
- arvo lisätty Tekstiviesti numeroon -kenttään: tallennuksen jälkeen arvoa ei ole Tekstiviesti numeroon -kentässä eikä Matkapuhelin-kentässä

wants digest = 1 pakotus
-	mikä onkaan tämä?

**Comment by lmstrand** [comment]
Wants Digest -triggeri on koosteviestien päällepakotukseen.

**Comment by Kati-Helle** [comment]
> Wants Digest -triggeri on koosteviestien päällepakotukseen.

Toimii :)

![kuva](https://user-images.githubusercontent.com/99952449/232394663-7e5b4bc0-0447-41c0-9f1d-e762496a8393.png)

**Comment by Kati-Helle** [comment]
Tiedoksi vielä Vain koosteilmoitus -valintoihin liittyen.

Vain koosteilmoitus -vaihdoehdot voi myös klikata käyttöön. Tässä vain toinen valittuna ennen asiakastiedon tallennusta.
(Tallennuksen jälkeen valinta molemmissa.)

![kuva](https://user-images.githubusercontent.com/99952449/232395289-aa43c63b-528e-436f-98ee-ca1e28cd709e.png)

Tiedoksi myös, että kun asiakkaan muokkauksessa poistaa asiakkaalle jo tallennetut Vain koosteilmoituksen sisältämät sähköpostiviesti-valinnat, poistuvat Vain koosteilmoitus -valinnat automaattisesti jo asiakkaan muokkausnäytöllä.

**Comment by Kati-Helle** [comment]
Jos EAN-tunnuksella tarkoitetaan tietueen 028a-kentän väliviivan sisältämää arvoa, niin testatessani arvon sisältämä väliviiva ei poistunut 
![kuva](https://user-images.githubusercontent.com/99952449/232406092-dfb2fea1-fbff-4957-9f17-c818d286cf34.png)

Hain TäTistä ko. kentän ne arvot, jotka sisältävät väliviivan. Testasin poimimalla TäTi-tietueen, jolla nämä arvot
024 3  _a602517235847
028 02 _a0-06025-1723584-7

Poiminnan jälkeen Hellen tietueen muokkausnäytöllä väliviiva edelleen arvolla
![kuva](https://user-images.githubusercontent.com/99952449/232408076-25bf3a31-96a3-4220-bc17-d6b4793c82bb.png)

Samoin tietueen tallennuksen jälkeen
![kuva](https://user-images.githubusercontent.com/99952449/232408581-1d07328e-e135-4b37-8e10-29db0d77181a.png)

(Myöskään Helle-tuotannossa 028a-kentän arvon väliviivat eivät kadonneet. Poimin saman tietueen tuotannossa testatessani.)

**Comment by AnttHeik** [comment]
Hei, hoksautuksena tähän, ettei itse Marc-tietueesta/Marc-näytöiltä saisi poistua väliviivat 020, 024 ja 028-kentistä, vain niistä tietokantatauluista kentissä 020 ja 024.

**Comment by Kati-Helle** [comment]
Testasinpa uudestaan 020-kentällistä tietuetta

Tuon tämän TäTi-tietueen Helleen Z39.50-toiminnolla poimien. TäTi-tietueen 020-kenttäarvolla on väliviivat
![kuva](https://user-images.githubusercontent.com/99952449/232682022-0aede0be-2795-42d6-a96e-c16f12c2e0b0.png)

Helle-tietueen muokkausnäytöllä 020-kenttä on väliviivaton heti tietuepoiminnan jälkeen ennen tallennusta
![kuva](https://user-images.githubusercontent.com/99952449/232682206-1f5ac66f-933e-438e-a462-a3d563c62ef3.png)

Helle-tietueen tallennuksen jälkeen Marc-esikatselussa 020-kentässä ei näy väliviivoja
![kuva](https://user-images.githubusercontent.com/99952449/232682710-f06834bd-7f2a-4c31-b133-05ebf7ffc50e.png)

Tietueen biblioitems-taulussa isbn-kenttäarvo on väliviivaton
![kuva](https://user-images.githubusercontent.com/99952449/232682923-385a4f55-15ca-4567-b701-7b026ad3ef8b.png)

Testissä
- Marc-näytöltä 020-kentän väliviivat olivat virheellisesti poistuneet
- biblioitems-taulussa 020-kentän arvo eli isbn on oikein väliviivaton

Toivottavasti tulkitsen oikein :)

**Comment by AnttHeik** [comment]
Juu, ja tuosta Z39.50-haussa tapahtuvasta väliviivojen poistumisesta on oma tikettinsäkin: https://github.com/KohaSuomi/Koha/issues/352

**Comment by Kati-Helle** [comment]
Testissä 024-kenttäarvon omaavan TäTi-tietueen poiminta Helleen

TäTi-tietue Z39.50-toiminnossa. Ensimmäisessä 024a-arvossa on väliviivat
![kuva](https://user-images.githubusercontent.com/99952449/232718569-2ebc6e1f-4bef-4f5c-9f13-c74e72c187d1.png)

Helleen poimittu tietue, jonka ensimmäisessä 024a-arvossa on väliviivat
![kuva](https://user-images.githubusercontent.com/99952449/232718887-61c8e748-0d4a-455f-920e-ed630c719422.png)

Tietueen 024a-arvo biblioitems-taulussa
![kuva](https://user-images.githubusercontent.com/99952449/232719376-5129d009-6044-406c-93a2-45c78f9610bc.png)

Testissä
- Hellen Marc-näytöllä tietueen ensimmäisen 024a-kenttäarvon väliviivat ovat kuten kuuluukin olla
- biblioitems-taulussa 024-kentän arvo (ean) on oikein eli väliviivaton

**Comment by Kati-Helle** [comment]
Testasin vielä sellaisen TäTi-tietueen tuonnin, jolla on vain yksi 024-kenttäarvo
![kuva](https://user-images.githubusercontent.com/99952449/232723660-44d39684-7da1-4687-9ea7-5fdb5b4f75da.png)

Helleen tuotuna tietueen Marc-näytöllä näkyy väliviivat 024a-kentän arvossa kuten tuleekin näkyä
![kuva](https://user-images.githubusercontent.com/99952449/232722618-17768457-dfdc-4106-a443-7bf34d1e9e32.png)

Tietueen biblioitems-taulun ean on väliviivaton kuten kuuluukin olla
![kuva](https://user-images.githubusercontent.com/99952449/232722935-a6d1cdf6-a37d-4c24-8046-3a12a65f5abe.png)

**Comment by ajrajala** [comment]
> Vaski-next: Kaikki paitsi before_borrowers_insert/update (tyhjiä korttinumeroita)

@lmstrand Vaski-nextille voisi nyt pistää tuonkin triggerin käyttöön, sillä ollaan täydennetty korttitiedot nextille ja tuotantoon kaikkiin oleellisiin tunnuksiin joilta ne puuttui.

**Comment by lmstrand** [comment]
Lisätty Vaski-nextille. Tuotantoja koskeva tiketti tehdään erikseen, jolla on tarkoitus yhtenäistää kimppojen toiminta triggerien osalta. Eli en vielä lisää triggeriä tuotantoon.

**Comment by ajrajala** [comment]
> Lisätty Vaski-nextille. Tuotantoja koskeva tiketti tehdään erikseen, jolla on tarkoitus yhtenäistää kimppojen toiminta triggerien osalta. Eli en vielä lisää triggeriä tuotantoon.

Kiitos, näytti toimivan nextillä kuten pitää!

**Comment by lmstrand** [comment]
Nämä taitaa olla nyt kuosissa joten suljen tiketin.
