### ISSUE TITLE
AutoControlNumber-järjestelmäasetuksen ollessa päällä 999d-osakenttään generoituu edellisen tietueen numero

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha-22x#139]
### Mikä vikana?

Kun AutoControlNumber -asetukseen on valittu, että tietuenumero generoidaan 001-kenttään, generoituu 001-kenttään sekä 999c-osakenttään tietuenumero kuten pitääkin, mutta 999d-osakenttään muodostuu jostain syystä yhtä pienempi numero. Esim. tietueeseen [4289658](https://vaski-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=4289658) tallentui 999d-osakenttään numero 4289657.

Tuotantoversiossa sekä c että d -osakenttään tallentuu ko. tietueen tietunumero.

**Comment by AnneliO** [comment]
Hmm.. kokeilin lisätä Vaaran nextille tietueen ja siihen 999-kentät muodostui oikein.

![kuva](https://user-images.githubusercontent.com/33121325/227465885-d80fdb90-c7fd-462f-976f-6aa2f78740e7.png)

Jatkan testailuja.

**Comment by AnneliO** [comment]
Tuo johtuu itseasiassa todennäköisesti siitä, että Vaskin nextillä on biblionumber ja biblioitemnumber nyt jostain syystä epäsynkassa biblioitems-taulussa. Siellä on 22 tietuetta, joissa biblionumber ja biblioitemnumber ei vastaa toisiaan.

Tuo epäsynkka pitäis nyt jotenkin korjata.

**Comment by paxed** [comment]
Ajoin kodon kirjottaman realign-biblionumber-biblioitemnumber.sh -skriptin ja sen tuottaman korjauksen - lieneekö nyt synkassa?

**Comment by ajrajala** [comment]
Kiitos! Näyttää korjaantuneen.
