### ISSUE TITLE
Taustatyö daemonin korjaus - ksdev/ks-0042-fix-background_jobs_worker

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#14]
### Siirrettävä ominaisuus

Taustatyö daemonin korjaus.

**Comment by Kaarius** [comment]
Tämä on korjattu yhteisön tiketissä https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=31351 meidän muutosta ei enään tarvita. Suljen tiketin.
