### ISSUE TITLE
Muokkaa hakua -linkillä siirtyminen ei säilytä kaikkia valintoja tarkan haun lomakkeella

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha-22x#141]
### Mikä vikana?

Tiedonhaun tuloksista on mahdollista siirtyä muokkaamaan hakua "Muokkaa hakua" -linkin kautta. Toimintoa testaillessa tuli esille, että parissa tilanteessa lomake ei vastaa alkuperäistä tilannetta:

- Jos lomakkeella on käyttänyt hakulaatikoiden välillä operaattoreita + muuttanut siksi hakulaatikoiden kohdistumisia (esim. nimeke kahdessa laatikossa), hakulaatikoiden kohdistumisiin palaavat oletusvaihtoehdot. Hakulaatikoiden välille valitut operaattorit sen sijaan säilyvät.
- Jos tarkan haun lomakkeella on valinnut näkymän "Vähemmän vaihtoehtoja", Muokkaa hakua -linkki ei palauta käyttäjää takaisin tuohon näkymään vaan oletusnäkymään.

**Comment by AnneliO** [comment]
> Jos lomakkeella on käyttänyt hakulaatikoiden välillä operaattoreita + muuttanut siksi hakulaatikoiden kohdistumisia (esim. nimeke kahdessa laatikossa), hakulaatikoiden kohdistumisiin palaavat oletusvaihtoehdot. Hakulaatikoiden välille valitut operaattorit sen sijaan säilyvät.

Tämä johtuu siitä, että osalla kimpoista on IntranetUserJS:ssä rimpsu, joka asettaa käyttävät indeksit valikkoon eli tämä:

```
/* Tarkka-haku ja Sanahaku-oletustermit korvataan Nimeke, Tekijä, Asiasana */ /* Toimii 22.03.2022 MLI */
$(document).ready(function() {
  var elems = $("body#catalog_advsearch select[name='idx']");
  elems.eq(0).val('ti');
  elems.eq(1).val('au');
  elems.eq(2).val('su');
});
/// LOPPU ///
```
Tuon kun ottaa pois käytöstä, niin hakua muokatessa alkuperäiset valikkovalinnatkin säilyvät.

**Comment by ajrajala** [comment]
Ahaa, eipä tullut mieleenkään! Kiitos, mietitäänpä täällä siis onko tarpeen luopua js:stä.

**Comment by AnneliO** [comment]
> Jos tarkan haun lomakkeella on valinnut näkymän "Vähemmän vaihtoehtoja", Muokkaa hakua -linkki ei palauta käyttäjää takaisin tuohon näkymään vaan oletusnäkymään.

Vähemmän vaihtoehtoja -valinnan saa säilymään, kun käyttää selaimen takaisin-nappia. Muokkaa hakua -linkki osoittaa aina "oletusnäkymään".

Tämä ei ole kriittinen ongelma, joten pohditaan tarvittaessa lisää versionvaihdon jälkeen.

**Comment by Kati-Helle** [comment]
Muokkaa hakua -toiminnon etuna on se, että toimintoa käyttäessä tarkan haun hakukentät eivät ole lukossa, kuten ovat selaimen takaisin-nappia käyttäessä.
Tuosta syystä kannatan versionvaihdon jälkeen mahdollista kehitystä Annin mainitsemiin tilanteisiin.

**Comment by AnneliO** [comment]
Ainakaan minulla ei ole hakukentät lukossa, jos palaan selaimen takaisin-napilla. Nykyisessä versoiossa niin käy, mutta ei uudessa.

**Comment by Kati-Helle** [comment]
Testasin taas kertaalleen Helle-nextillä ja edelleen lukko Takaisin painikkeella.

Näin toimin:
Tarkka haku -toiminnolla haku Aineistotyyppi-välilehden arvolla Kirja
Hakutuloksesta Takaisin-painikkeella Tarkka haku -toimintoon, jolloin alasvetovalikoiden arvokentissä lukot.

Sama tapahtui, kun hain Tarkan haun Sanahaku-ehdolla koira
![kuva](https://user-images.githubusercontent.com/99952449/229080374-453a58dd-3d87-4d34-ac7e-183dc2eeeb28.png)

Lisätietona: lukkokuvat ilmestyvät heti, kun painan Tarkka haku -toiminnon Haku-painiketta.
Onkohan lukot säädettävissä pois käytöstä?

**Comment by AnneliO** [comment]
Mielenkiintoista, nyt minullakin kentät menevät lukkoon. :D 

Ahaa, ne eivät mene lukkoon, jos käytössä on "Vähemmän vaihtoehtoja" -valinta. Eli sen osalta selaimen takaisin-napin käyttö auttaa kiertämään Annin mainitseman ongelman, että Muokkaa hakua -linkin painaminen vie Enemmän hakuehtoja -vaihtoehtoon.

**Comment by Kati-Helle** [comment]
Tosiaan, ei siis toimi Tarkka haku -toiminnossa aina samoin ... tiedonhakijalle ei kiva

Ei lukkoja
![kuva](https://user-images.githubusercontent.com/99952449/229083699-f2f86d2c-8f36-4978-a0be-d20d42c5516c.png)

**Comment by AnneliO** [comment]
Olen näköjään tuota lukittumista testannut ja todennut, ettei sitä tapahdu versiossa 22.06: https://tiketti.koha-suomi.fi/issues/5372

Mutta tapahtuu silti.

**Comment by AnneliO** [comment]
PTFS Europen sandboxissa versiossa 22.12 kentissä vilahtaa lukon kuva, kun klikkaa hae (tai painaa enteriä), mutta kun palaa takaisin edelliselle sivulle hakutuloksista, eivät kentät ole lukittu.

**Comment by AnneliO** [comment]
Voiko tämän tiketin sulkea?

**Comment by Kati-Helle** [comment]
Vaikuttaa nyt toimivan oikein :)

Testatessani nyt hakutuloksen Muokkaa hakua -linkillä siirtyessä tarkan haun hakukentät eivät menneet lukkoon kummallakaan valinnalla
- Vähemmän vaihtoehtoja
- Enemmän vaihtoehtoja

(Käyttää kumpaa valintaa tahansa, vie Muokkaa hakua -linkki tarkan haun Enemmän vaihtoehtoja -valintaan.)
