### ISSUE TITLE
Hae tietokannasta -toiminto ja uusi toiminto Hae tuloksista: sanahakuehto ei hae ainakaan teoksen nimestä

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-22x#142]
### Mikä vikana?

Kun Hae tietokannasta -hakutulokseen kohdistaa sanahaun uudella ominaisuudella Hae tuloksista, ei haku hae ainakaan teoksen nimestä (tietueen 245a-kenttä). 

Hakutulosta Hae tietokannasta -haulle itemtype:kirja
![kuva](https://user-images.githubusercontent.com/99952449/227877138-ba2b5c8a-e05f-4860-9ecb-b67573c9476f.png)

Hae tuloksista -kenttään lisätty hakuarvoksi koira ja hakutuloksena tämä:
![kuva](https://user-images.githubusercontent.com/99952449/227877279-8e70365c-ec80-407b-97be-f2e299be54dd.png)

Helle-tuotannon testissä esim. tällä sanahakuehdolla saa hakutuloksen: itemtype:'kirja' and pentu
![kuva](https://user-images.githubusercontent.com/99952449/227878939-be44436a-0f5a-4a7b-b138-0d3c3183e885.png)

Sen sijaan Helle-nextillä ei saa hakutulosta sanahakuehdolla: itemtype:'kirja' and koira
![kuva](https://user-images.githubusercontent.com/99952449/227878133-79be92f3-0b61-4450-84f9-5835c7759c74.png)

Lisätietona: mtype-arvoa haussa käyttäessä sama tulos. Miksi itemtype toimiikaan aineistotyyppihaussa...

**Comment by AnneliO** [comment]
itemtype:'kirja' and koira toimii, jos laitat and-sanan isoilla kirjaimilla eli itemtype:'kirja' AND koira. Tuo isojen kirjaimien vaatimus operaattoreissa piti kyllä muistaakseni olla poistunut, mutta näköjään se on tullut takaisin.

Tuosta kw-haun toimimattomuudesta on näköjään yhteisössä Needs sign off -tilassa tiketti: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=33093

**Comment by AnneliO** [comment]
kw-haun toimimattomuuden saa kierrettyä niin, että laittaa IntranetCatalogSearchPulldown -järjestelmäasetukseen "Älä näytä", jolloin katoaa näkyvistä pudotusvalikko, josta valitaan käytettävä indeksi. Mutta sitten se tosiaan katoaa sekä tuosta kohdasta että pikahakupalkista eli täältä:


![Image](https://user-images.githubusercontent.com/33121325/228189010-4a235692-5b87-4fca-a47b-326d8f8b285d.png)

**Comment by Kati-Helle** [comment]
Kiitos Anneli tiedosta. 
Tietääpä tiedottaa tuosta Hae hakutuloksista -toiminnon ominaisuudesta liittyen näihin
- Sanahaku 
- Fraasihaku

**Comment by AnneliO** [comment]
Anneli testaa yhteisön bugia ja jos se toimii eikä ole teknisiä esteitä muutoksen tuomisesta meidän versioon, niin tuodaan sitten meille.

**Comment by emta001** [comment]
Yhteisön sandbox ei suostu indeksoimaan elasticia, tuodaan muutos meille testattavaksi.

**Comment by emta001** [comment]
Yhteisön korjausehdotus tuotu nexteille testattavaksi.

**Comment by Kati-Helle** [comment]
Kiitos Emmi! Toimivalta vaikuttaa :)

Tein Hellessä Hae tietokannasta -toiminnossa haun hakuehdolla mtype:kirja
![kuva](https://user-images.githubusercontent.com/99952449/229043464-c160fa12-b946-4b44-9c00-a0e0ae5efb20.png)

Sanahaku-rajasin hakutuloksen arvolla: koira
![kuva](https://user-images.githubusercontent.com/99952449/229043186-0b04e571-8660-4569-8df2-9bc8d2e1712d.png)

Hakutulos on neljä, ja jokaisessa hakutulosteoksessa arvo koira on teoksen nimessä ja/tai asiasanana.

Lisätietona: toimii nyt myös pudotusvalikosta valitulla Fraasihaku-hakuehdolla.

**Comment by AnneliO** [comment]
Testasin myös tätä ja toimii tosiaan. Emmi teki yhteisöön Sign offin.

**Comment by AnneliO** [comment]
Tuleeko tämä muutos nyt meidän tuotantoon sitten aikanaan mukaan?

**Comment by emta001** [comment]
> Tuleeko tämä muutos nyt meidän tuotantoon sitten aikanaan mukaan?

Juu tulee, kun siitä on feature-branch.

**Comment by emta001** [comment]
Tämänkin voinee jo sulkea?
