### ISSUE TITLE
Hakurajauksiin tallennetun emo-/osakohderajauksen käyttö sotkee ääkköset

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha-22x#144]
### Mikä vikana?

Jos haussa käytetyssä hakulauseessa on ääkkösiä ja hakutuloksen rajaa haun jälkeen emo- tai osakohteisiin [tallennettuja hakufilttereitä](https://github.com/KohaSuomi/Koha-22x/wiki/Uutta#savedsearchfilters-eli-r%C3%A4%C3%A4t%C3%A4l%C3%B6idyt-rajaukset) käyttäen, eivät ääkköset säily. Esim. haku _päivänsäde ja menninkäinen_ on rajauksen jälkeen muuttunut hauksi _pÃ¤ivÃ¤nsÃ¤de ja menninkÃ¤inen 'bib-level:("m")_.

**Comment by Kaarius** [comment]
Tuotu nexteille testattavaksi.

**Comment by AnneliO** [comment]
Testasin vaara-nextillä hakusanalla 'ä', 'ö' ja 'jännitys' ja hakurajaukset toimivat oikein.

**Comment by ajrajala** [comment]
Testasin myös vaski-nextillä, edellä mainittujen lisäksi varuilta myös ruotsalaisen å:n kanssa tehtyä hakua. Hakurajaukset toimi nyt kuten pitää.

**Comment by AnneliO** [comment]
Testailin tätä vielä siili-nextillä erilaisilla variaatioilla (ä, ö, å, á, à, â) ja kaikki toimivat.

**Comment by AnneliO** [comment]
Testattu toimivaksi, suljen tiketin.
