### ISSUE TITLE
Tiedonhaun tuloksessa osakohteesta ei ole emoon toimivaa linkkiä

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha-22x#145]
### Mikä vikana?

Nextillä tiedonhaun tuloksessa tuleviin osakohteisiin ei sisälly linkkiä emotietueeseen, on vain pelkkä tieto, mihin teokseen osakohte sisältyy. Linkki olisi tärkeä.

**Comment by AnneliO** [comment]
Liittyy [Redmine-tikettiin 4628](https://tiketti.koha-suomi.fi/issues/4628).

**Comment by AnneliO** [comment]
Liittyy nyt myös tikettiin KohaSuomi/Koha#1963.

**Comment by AnneliO** [comment]
Tämä toimi nyt ainakin outi-nextillä.

**Comment by Kati-Helle** [comment]
Testasin uuden version Helle-testissä. Toimii :)

**Comment by pknuuti** [comment]
Vaaran nextillä toimii, samoin testikannassa.

**Comment by pknuuti** [comment]
Testattu toimivaksi.
