### ISSUE TITLE
Taattavan asiakkaan muokkaus: Lisää takaaja -toiminnossa ei saa haettua asiakastietoa esim. tyyliin: sukunimi, etunimi

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-22x#147]
### Mikä vikana?

Taattavalle asiakastiedolle takaajan lisäys Lisää takaaja -toiminnossa: takaajatiedon haku ei onnistu esimerkiksi näillä Haku-ehdoilla
- sukunimi, etunimi
- etunimi sukunimi

Esimerkki löytymättömästä
![kuva](https://user-images.githubusercontent.com/99952449/228480057-10df7535-84f5-4b31-a298-4daf0bf5108a.png)

Asiakastieto löytyy hakuehdolla Selaa sukunimen mukaan: E-kirjainvalinnalla
![kuva](https://user-images.githubusercontent.com/99952449/228480500-0c28b682-701b-48e0-95d6-1cdddae8d69c.png)

Muutakin erikoista esim. Aikuinen-hakutyyppiehto löytää ainakin myös asiakastyypit Kirjaston työntekijä JA Automaatti
![kuva](https://user-images.githubusercontent.com/99952449/228481556-74861259-1e67-46f4-ab96-36e507251906.png)

**Comment by AnneliO** [comment]
Etu- ja sukunimellä hakuun näytti vaikuttavan  DefaultPatronSearchFields -järjestelmäasetus. Hellessä oli siellä nyt vain cardnumber ja mobile. Lisäsin surname ja firstname, niin haku toimi paremmin. Mutta ei edelleenkään hae muodossa "sukunimi, etunimi". Se on muutos vanhaan versioon.

En saa toistettua tuota, että Aikuinen asiakas -rajauksella mukaan tulee myös muita asiakastyyppejä.

**Comment by Kati-Helle** [comment]
Kiitos Anneli tiedosta. Tuotannon asetusmäärittelyt eivät siis ole tämän osalta kopioituneet nextille. Tuotannossa näin
![kuva](https://user-images.githubusercontent.com/99952449/228499815-ce8e6c0b-c350-462a-9046-67f0fc997cc9.png)

Anneli: En saa toistettua tuota, että Aikuinen asiakas -rajauksella mukaan tulee myös muita asiakastyyppejä.

En minäkään saanut enää tuota toistettua. Hyvä näin :)

**Comment by Kati-Helle** [comment]
Ovat varmastikin olleet tuotannosta siirrettäessä Nextissä oikein.
Kaikenlaista testailin ko. järjestelmäasetukseen liittyen, tiketti https://github.com/KohaSuomi/Koha-22x/issues/135

**Comment by AnneliO** [comment]
Testasin takaajahakua PTFS Europen sandboxissa ja siellä pystyi hakemaan takaajaa muodossa 'sukunimi, etunimi'.

**Comment by emta001** [comment]
Korjattu yhteisön tiketissä [32491](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=32491).

**Comment by AnneliO** [comment]
Otetaanko yhteisön korjaus mukaan meille?

**Comment by emta001** [comment]
> Otetaanko yhteisön korjaus mukaan meille?

Juuri mietin tässä samaa, pärjätäänkö ilmankin kun kerta ilman pilkkua hakeminen toimii :thinking:

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 24.4.2023: Otetaan mukaan yhteisön korjaus.

**Comment by emta001** [comment]
Yhteisön korjaus tuotu testattavaksi nexteille.

**Comment by AnneliO** [comment]
Vaara-nextillä toimii nyt asiakkaan haku muodossa sukunimi, etunimi.

**Comment by velimarj** [comment]
OUTIssa toimii myös kaikilla eri tavoilla: sukunimi, etunimi; sukunimi etunimi; etunimi, sukunimi sekä etunimi sukunimi.

**Comment by emta001** [comment]
Suljen tiketin.
