### ISSUE TITLE
Asiakkaan muokkaus ja tietojen tallennus: tallentaessa Koha ilmoittaa oikein jo käytössä olevasta varaustunnisteesta. Saisiko virheilmoituksesta linkin esim. Varaustunnus kenttään?

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-22x#148]
### Mikä vikana?

Nämä tiedot poimittu 3.4.2023 keskustelusta 

Kati Sillgren
Olisikohan mahdollista saada virheilmoituksesta linkki Muut määreet ja tunnukset -osioon tai Varaustunnus-kenttään?
![kuva](https://user-images.githubusercontent.com/99952449/229485040-1633311e-df92-4e97-a6a9-5669531a1ed1.png)

Varaustunnus on nyt asiakkaan muokkausnäytön lopussa. Virheilmoituksen jälkeen pelkkä end-näppäimen painaminen ei auta/vie minnekään, vaan ensin pitää huomata klikata muokkausnäytöllä.

Lari Strand
Mitä jos varaustunnuksen siirtäisi ylös heti vaikka syntymäajan jälkeen? Kyllä tuo linkkikin varmasti onnistuisi joka heittäisi sitten varaustunnuskenttään painaessa...

Päivi Knuutinen / Vaara
Kannatan varaustunnuksen siirtämistä ylöspäin näytöllä.

Kati Sillgren
Paikanvaihtokin passaa eli olisi hyvä vaihtoehto.

Anni Rajala (Vaski)
Olisiko ajatuksena siirtää pelkkä varaustunnus vai "Muut määreet ja tunnukset" -laatikon tiedot kokonaisuudessaan?

Tuli nimittäin mieleen, että sitä sotu-avainkenttääkin joskus kaipailtiin ylemmäs lomakkeella (kehitysehdotuksessa https://github.com/KohaSuomi/Koha/issues/372, tosin ensisijaisena toiveena tuossa ehdotuksessa oli saada syntymäajan generointi-yhdistettyä Tallenna-painikkeeseen ja se on jo toteutettu).

**Comment by lmstrand** [comment]
HOLDID-varaustunnus -asiakasmääreen siirto viimeiseksi ensimmäiseen asiakastietolaatikkoon:

```
$(document).ready(function () {
  if (window.location.href.indexOf("members/memberentry.pl") > -1) {
    var holdidlabel = $('label[for="' + "patron_attr_2" + '"]');
    var li = holdidlabel.parent();
    $( "#identity_lgd" ).next().append(li);
  }
});
```
patron_attr_2 -kohan järjestysnumero on korjattava kimppakohtaisesti.

**Comment by Kati-Helle** [comment]
Kiitos Lari rimpsusta :)
Hellessä Varaustunnus hyppää rimpsulla hieman eri kohtaan eli Lisää hetu -kentän jälkeen 
![kuva](https://user-images.githubusercontent.com/99952449/229488719-6ca3e56c-5525-44d5-9335-68645cb90d4b.png)

OK noin.

**Comment by Kati-Helle** [comment]
Varaustunnus-kenttä kivasti samalla näytöllä varaustunnus on jo käytössä -virheilmotuksen kanssa :)
![kuva](https://user-images.githubusercontent.com/99952449/229490966-310033ab-d0e1-4caf-aeb8-6de6bb622443.png)

**Comment by lmstrand** [comment]
Sotuavaimen siirto "lisää hetu":n jälkeen:
```
// Sotuavain-asiakasmääreen siirto lisää hetu-laatikon alle
$(document).ready(function () {
  if (window.location.href.indexOf("members/memberentry.pl") > -1) {
    var sotuavainlabel = $('label[for="' + "patron_attr_6" + '"]');
    var li = sotuavainlabel.parent();
    var ssnfield = $( '#ssnvalue' );
    ssnfield.parent().append(li);
  }
});
```

patron_attr-numero muutettava kimppakohtaisesti.

**Comment by lmstrand** [comment]
Noiden määreiden siirto riippuu siitä, onko sotuavain-rimpsu ennen vai jälkeen noiden siirtorimpsujen.
Jos sotuavaimen haluaa siirtää, pitää sen siirtorimpsu olla "lisää hetu:" lisäysrimpsun jälkeen, jotta se elementti on jo olemassa kun sen alle yritetään sotuavain siirtää.

**Comment by lmstrand** [comment]
Elikkä jos varaustunnuksen haluaa tuonne listan loppuun, on se sijoitettava intranetUserJS:ssä ennen "lisää hetu:" rimpsua varmaankin.

**Comment by lmstrand** [comment]
Vaara-nextillä varaustunnuksen siirto ennen lisää hetu-rimpsua ja sotuavaimen siirtorimpsu lisää hetu-rimpsun jälkeen (viimeisenä):
![image](https://user-images.githubusercontent.com/18394834/229499812-4739d16b-9077-4514-94f4-44abb4b8b90b.png)

**Comment by Kati-Helle** [comment]
Hellessä rimpsujen järjestelyn jälkeen näin
![kuva](https://user-images.githubusercontent.com/99952449/229502138-19982f3d-b48f-438f-8164-c77b70ac8428.png)

Lisätietona: vaihdoin vielä määreen kuvaukseen tämän: sotuteekki -> Sotusiilo
Hetu-avainkenttä ei liene kirjoitussuojattu? 
(Lisätietona itselleni: Hetu-avainkenttä on nyt kirjoitussuojattu.)

**Comment by piiaseme** [comment]
Kiitos rimpsuista, sain OUTIn nextilläkin laatikot sijoiteltua :) 

Heräsi kysymys, että miten Sotu-avain ja Varaustunnus-laatikot saa pysyvästi pienemmiksi? Niihinhän tulee vain yksi rivi tekstiä, niin ei varmaan ole tarvetta isolle, laajennettavalle laatikolle vaan yhden rivin laatikko riittäisi myös?

**Comment by lmstrand** [comment]
Juu kiinnitin tuohon itsekin huomiota. Saisiko sen määritettyä asiakasmääreen tyypistä? Jos ei, niin onnistuisihan sen muuttaminen noiden rimpsujen sisällä.

**Comment by AnneliO** [comment]
Tiketistä #149 Larin uudet rimpsut:

Varaustunnuksen tyhjentäminen korjatulla (korvatulla omalla) tyhjennysnapilla:

```
// Varaustunnus-asiakasmääreen siirto
$(document).ready(function () {
  if (window.location.href.indexOf("members/memberentry.pl") > -1) {
    var holdidlabel = $('label[for="' + "patron_attr_2" + '"]');
    var clearbutton = holdidlabel.next().next().next();
    clearbutton.replaceWith( '<button type="button" class="fa fa-fw fa-trash fa-lg" style="color:green; border:none;">' );
    holdidlabel.next().next().next().on('click', function(e){
        holdidlabel.next().val('');
    });
    var li = holdidlabel.parent();
    $( "#identity_lgd" ).next().append(li);
  }
});
```
Poistin napista tekstin jottei tarvitse ottaa huomioon kielivalintaa ja isonsin nappia. Olisiko tuo ok?

Sama Sotuavaimelle:

```
// Sotuavain-asiakasmääreen siirto
$(document).ready(function () {
  if (window.location.href.indexOf("members/memberentry.pl") > -1) {
    var sotuavainlabel = $('label[for="' + "patron_attr_6" + '"]');
    var clearbutton = sotuavainlabel.next().next().next();
    clearbutton.replaceWith( '<button type="button" class="fa fa-fw fa-trash fa-lg" style="color:green; border:none;">' );
    sotuavainlabel.next().next().next().on('click', function(e){
        sotuavainlabel.next().val('');
    });
    var li = sotuavainlabel.parent();
    var ssnfield = $( '#ssnvalue' );
    ssnfield.parent().append(li);
  }
});
```

Taas patron_attr_ -numerot säädettävä kimppakohtaisesti kohdistumaan oikeaan määreeseen.

**Comment by pknuuti** [comment]
"Heräsi kysymys, että miten Sotu-avain ja Varaustunnus-laatikot saa pysyvästi pienemmiksi? Niihinhän tulee vain yksi rivi tekstiä, niin ei varmaan ole tarvetta isolle, laajennettavalle laatikolle vaan yhden rivin laatikko riittäisi myös?"

Onko tuolle laatikoiden pienentämiselle olemassa jo joku korjaus? Turhan suuria ovat yhdelle riville.

**Comment by AnneliO** [comment]
> "Heräsi kysymys, että miten Sotu-avain ja Varaustunnus-laatikot saa pysyvästi pienemmiksi? Niihinhän tulee vain yksi rivi tekstiä, niin ei varmaan ole tarvetta isolle, laajennettavalle laatikolle vaan yhden rivin laatikko riittäisi myös?"
> 
> Onko tuolle laatikoiden pienentämiselle olemassa jo joku korjaus? Turhan suuria ovat yhdelle riville.

Jäänyt kirjaamatta, mutta päätimme Koha-Suomen palaverissa, että ongelma ei ole kriittinen, joten siihen ei käytetä nyt aikaa. Jos haluatte, teettekö siitä erillisen tiketin Koha-repositorioon? :)

**Comment by lmstrand** [comment]
Suljen tiketin. Rimpsut testattu toimiviksi. Tehkää uusi tiketti tuosta kentän ulkoasusta jos tarpeen.

**Comment by AnneliO** [comment]
Lisäsin siirtorimpsut nyt myös [vapaaehtoisiin IntranetUserJS-wikiin](https://github.com/KohaSuomi/Koha-22x/wiki/IntranetUserJS#vapaaehtoiset-ja-vain-osalle-kimpoista-tarpeelliset).

**Comment by MikkoLiimatainen** [comment]
Koska en viitsinyt miettiä, mihin väliin tuo varaustunnuksen siirtorimpsu pitää tunkea, jotta se tulisi oikeaan kohtaan, niin päätin korvata rivin `$( "#identity_lgd" ).next().append(li);` rivillä `$('label[for="surname"]').parent().parent().append(li);`, jotta varaustunnus olisi aina tuossa sukunimen sisältävässä osiossa viimeisenä.
