### ISSUE TITLE
SIP muutos - ksdev/ks-0043-KD-2608

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#15]
### Siirrettävä ominaisuus

SIP-muutos

**Comment by lmstrand** [comment]
Feature branchiin ksdev/ks-0043-K22-15-SIP2 yhdistetty SIP2:een liittyvät KS-muutokset/commitit brancheista:

[KD-2608 Handle notforloan status changes on checkin with SIP](https://github.com/KohaSuomi/Koha/commit/faca0cbb80fda4d09dc8300838275e641907b34b)

[KD-913 Add SIP2 response message preference for alert](https://github.com/KohaSuomi/Koha/commit/1646f5dd8faf002aa530fc7665041f2599f4b46b)

[KD-4572 Add ss block support for sip2 63-64 reply](https://github.com/KohaSuomi/Koha/commit/900419c4300870e6d62cd0aebc35ea68675dac55)

**Comment by AnneliO** [comment]
Oisko tähän jotain testaussuunnitelmaa? :)

**Comment by lmstrand** [comment]
Vaski ja Outi testanneet kaikkien valmistajien automaatteja ja mainitsivat pääkäyttäjäpalaverissa että kaikki on ollut ok tähänastisissa testauksissa. Omatoimikirjastojen blokkauksia ei ole testattu.

**Comment by ajrajala** [comment]
Vaskissa testattu tosiaan aika kattavasti automaattien toiminta nextiä vasten:
- kirjastokortilla tunnistautuminen ja erilaiset käytön estävät rajoitteet toimivat kuten pitää
- lainaus onnistuu/on estetty erilaisissa tilanteissa (erikoistilat, hyllyvarattu aineisto, ikärajallinen aineisto, varaukset, kuljetettava aineisto)
- erikoistilat säilyvät/poistuvat lainauksessa/palautuksessa siten, kuten asetuksissa on määritetty
- Uusi järjestelmäasetus UseLocationAsAQInSIP toimii
- Kuitit on ok
