### ISSUE TITLE
Ruotsinkieliselle maksukuitille tulostuu osa maksujen kuvauksista englanniksi

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#150]
### Mikä vikana?

Kun tulostaa ACCOUNTS_SUMMARY-kuitin ruotsinkieliselle asiakkaalle, tulee osa maksujen selitteistä englanniksi. Luulen, että kuvausten käännökset haetaan käännöstiedostoista ja meidän ruotsinkieliset po-tiedostot ovat yli vuoden vanhoja.

Olen odotellut, että joku tekisi yhteisön Pootleen ruotsinkielisiin tiedostoihin korjaukset kriittisiin ongelmiin ennen kuin lataan tiedostot meille: https://translate.koha-community.org/sv/22.11/

Näyttää kuitenkin vähän siltä, että käännöksiä ei kuulu, joten teen paikallisesti huonot käännökset tai siirrän käännökseen englanninkielisen version, jolloin käännös ei ainakaan riko mitään. Kunhan olen tuon tehnyt, vien po-tiedostot translation-repoon ja asennetaan ne Kohaan. Testataan sitten, miten kävi kuvauksille.

### Asiasanat/tagit

maksukuitti ruotsinkielinen ruotsin kieli maksun kuvaus maksu kuitti

**Comment by AnneliO** [comment]
Vein nyt koha-translation-repoon 22.xx-branchiin ruotsinkieliset po-tiedostot, joista korjasin kriittiset virheet. Niihin jäi toki paljon asiasasisällöltään virheellisiä käännöksiä, mutta ne eivät kaada järjestelmää.

Käännökset voisi ajaa, kun joku ehtii.

**Comment by AnneliO** [comment]
Uudet ruotsinkieliset käännökset on nyt asennettu ja minun testien mukaan kuvauksissa näkyy nyt tekstit ruotsiksi niissä tapauksissa, että kyseessä on Kohan oma maksutyyppi, esim. OVERDUE eli myöhästymismaksu. Koha-Suomen omat maksutyypit kuten ODUE ei käänny.

**Comment by AnneliO** [comment]
Testaa näin:
1. Mene sellaisen asiakkaan tietoihin, jolla on maksuja ja vaihda ilmoitusten kieleksi ruotsi.
2. Tulosta asiakkaan maksukuitti Tulosta-valikosta -> Tulosta asiakkaan maksut
3. Tarkista, että Kohan sisäiset maksut kuten OVERDUE (myöhästymismaksu) tai RESERVE_EXPIRED (noutamattoman varauksen maksu) näkyvät kuitilla ruotsiksi.

**Comment by ajrajala** [comment]
Testasin, OVERDUE ja RESERVE_EXPIRED -maksujen selite näkyy kuitilla ruotsiksi:

![kuva](https://user-images.githubusercontent.com/44638512/232422795-2e4b4453-b640-4aa3-ac81-5d5e8d3bc0f6.png)

**Comment by AnneliO** [comment]
Testasin vielä outi-nextillä ja sielläkin toimii. Suljen tiketin.
