### ISSUE TITLE
Kuiteissa oletuskieli tarkoittaa englantia, kun teksti tulee esim. maksun kuvauksesta Kohasta

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#151]
### Mikä vikana?

Meillä ei ole aiemmin ollut käytössä sellaisia kuitti/viestipohjia, joissa haettaisiin esim. maksun kuvauksia suoraan Kohasta. Kaikki teksti on tullut joko tietokannan tauluista tai kuitti/viestipohjasta. Nyt ACCOUNTS_SUMMARY eli maksukuitissa haetaan maksun kuvaus maksutyypin tiedoista ja jos asiakkaalla on valittuna kieleksi Oletus, tulee kuvaukset englanninkielisenä. Jos asiakkaalla on valittuna suomi, tulee kuvaukset suomenkielisenä.

Testasin tätä myös nykyisessä versiossa ja siinäkin toiminta on samanlainen, mutta sitä ei vain ole huomattu. Sinänsä tämä ei ole versionvaihtoon liittyvä ongelma muuten kuin, että tässä versiossa tuli uusi kuittipohja, jossa asia realisoitui.

### Mitä pitäisi tapahtua

Oletuskieli pitäisi olla suomi.

### Jotain muuta?

Tähän on ainakin pari mahdollista ratkaisua:

- muutetaan asiakkaiden kielivalinnaksi suomi heillä, joilla se on oletus
- koitetaan selvittää, miten saisi määritettyä, että oletus tarkoittaa suomea

### Asiasanat/tagit

oletuskieli kuitit viestit kuvaukset maksun kuvaus oletus suomen kieli englanti suomi suomeksi englanniksi

**Comment by ReettaSiili** [comment]
Tämä on ainakin Siilinjärven ongelma, koska meillä ei ole kielivalinnat käytössä. Voidaanhan ne jollain aikavälillä ottaa käyttöön. Toisaalta maksut-kuitti on harvoin käytetty, joten ei ole sinänsä merkittävä ongelma.

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 6.4.2023: Oletuskieli on kovakoodattuna englanniksi. Muutetaan asiakkaille oletuskielen tilalle suomi. Siilinjärvellä kannattaa ottaa kielivalinnat käyttöön ja kopioida kuitti/viestipohjat myös suomi-versioon.

Tehdään muutos osaksi tietokannan päivitysajoa - updatedatabase21x_22x.pl.

Keskustellaan vielä pääkäyttäjien kanssa viikon 15 palaverissa, että tämä sopii kaikille.

**Comment by ReettaSiili** [comment]
Annelin kanssa sovittu menettelystä Siilinjärvellä, otetaan kielivalinnat käyttöön.

**Comment by Kaarius** [comment]
Päivitys lisätty updatedatabase-skriptiin.
