### ISSUE TITLE
Holhottava aikuinen -asiakkaan saa lisättyä takaajaksi

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-22x#152]
### Mikä vikana?

Holhottava aikuinen -asiakastyypin saa lisättyä lapsi -asiakkaan takaajaksi
![kuva](https://user-images.githubusercontent.com/99952449/230044111-3e7077f0-d55c-4bd1-a2b6-159a21258052.png)

Tuotannossa ei onnistu, vaan Koha ilmoittaa
![kuva](https://user-images.githubusercontent.com/99952449/230045189-dd572caf-e163-406a-bbf8-de24cc9a59c2.png)

**Comment by Kaarius** [comment]
tuotu testattavaksi nexteille

**Comment by Kati-Helle** [comment]
Kiitos Emmi! Nyt ainakaan Hellen Lapsi-asiakastyypille ei saa lisättyä takaajaksi Holhottava aikuinen -asiakastyyppistä asiakastietoa. Tallennus ei onnistu ja virheilmoituksen saan: 
Seuraavat tiedot ovat väärin. Korjaa tiedot.
    A guarantor cannot be a guarantee.

![kuva](https://user-images.githubusercontent.com/99952449/231157810-837a8409-336e-4b60-a396-6cff8d259c78.png)

**Comment by ajrajala** [comment]
Vaski-nextillä myös testattu, että toimii kuten pitää.

**Comment by emta001** [comment]
Tämän voinee sulkea @Kati-Helle ?

**Comment by emta001** [comment]
Suljen tiketin.
