### ISSUE TITLE
Takaajan vaihtaminen ei onnistu

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha-22x#153]
### Mikä vikana?

Jos huollettavan tietojen muokkauksessa yrittää poistaa vanhan takaajan, ei Poista-valinnan rastittaminen ja tietojen tallentaminen sen jälkeen poista takaajaa vaan tulee virheilmoitus _"Seuraavat tiedot ovat väärin. Korjaa tiedot. Cannot delete guarantor(s). A child patron needs a guarantor."_

### Mitä pitäisi tapahtua

Tuotannossa Poista-valinnan rastittamisen ja tietojen tallentamisen jälkeen vanhan takaajan tiedot ovat poistuneet muokkauslomakkeelta, mutta lomake vaatii kuitenkin uusien takaajatietojen lisäämisen virheilmoituksella _"Seuraavat tiedot ovat väärin. Korjaa tiedot. Lapsella pitää olla takaaja."_

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 6.4.2023: Huollettavalla on pakko olla vähintään yksi takaaja, joten ainoaa takaajaa ei voi poistaa ilman että lisää toisen ennen tietojen tallentamista. Eli käsittääksemme tämä toimii ihan oikein kummassakin versiossa. Hieman eri tavalla uudemmassa, mutta lopputulos on sama.

**Comment by ajrajala** [comment]
Enpäs hoksannut tuota, meillä on näköjään piilotettu Lisää-nappi näkyvistä silloin kun takaajatieto on jo lisättynä. Taitaa olla meidän oma piilotus kun en samaa js:ää Redminen/Githubin dokumentaatiosta löytänyt, joten napin piilotus ei koskettane ketään muuta kuin Vaskia.
