### ISSUE TITLE
Ilmoitusten kieli -valinnaksi oletuksena Suomi

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#154]
### Mikä vikana?

Tikettiin #151 liittyen pohdittiin 11.4.2023 pääkäyttäjäpalaverissa, onko mahdollista tehdä jonkinlainen js-rimpsu, joka valitsee automaattisesti suomen kielen ilmoitusten kieleksi oletus-vaihtoehdon sijaan? Next-kannoissa, toisin kuin 21.11-kannoissa, uutta asiakasta luodessa Koha ehdottaa oletusta kielivalinnaksi. 22.11-kannassa Koha ehdottaa kirjautuneen käyttäjän kielivalinnan mukaista kieltä.

### Mitä pitäisi tapahtua

Uutta asiakasta luodessa Ilmoitusten kieli -valikkoon pitäisi tulla automaattisesti valituksi suomi:
![kuva](https://user-images.githubusercontent.com/33121325/231081905-78b896e7-9c24-4f39-bff5-2d9ea627213b.png)

### Asiasanat/tagit

ilmoitusten kieli kielivalinta kielen valinta oletuskieli

**Comment by lmstrand** [comment]
Meillä tuon voisi tehdä tietokantatriggerilläkin. Komentoin yhteisöön tikettiä, jossa oltiin sysprefin perään, joka määräisi oletuskielen asiakasta lisättäessä.
https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=29598

**Comment by lmstrand** [comment]
Päätettiin käyttää IntranetUserJS-rimpsua valinnan muuttamiseen oletuksena suomeksi:

```
//Asiakkaalle lähtevien ilmoitusten oletuskielivalinta suomeksi
$(document).ready(function () {
  if (window.location.href.indexOf("members/memberentry.pl") > -1) {
    console.log("switch");
    var $notices_lang_select = document.querySelector('#lang');
  	$notices_lang_select.value = 'fi-FI';
  }
});
```

**Comment by Kati-Helle** [comment]
Lisäsin rimpsun Helleen. 
Uutta asiakastietoa lisätessä Ilmoitusten kieli -kentän arvona on nyt Suomi (fi-FI).

**Comment by lmstrand** [comment]
Jos oikein tulkitsin yhteisötiketin kommentointia, niin aikaisemmin, kun virkailijaliittymän kieli siirtyi oletuksena asiakkaan viestien oletuskieleksi, se nyt tulkitaan bugiksi. Nykyinen toiminta jossa se on aina uutta asiakasta lisätessä valitsematta/default/oletus, on oikea. Joten tästä ei virkailijaliittymään ole ainakaan näköjään tulossa muutosta yhteisössä. Js-rimpsulla siis mennään hamaan tulevaisuuteen.

**Comment by AnneliO** [comment]
Rimpsu toimii kyllä, mutta se asettaa kieleksi suomi myös asiakasta muokatessa. Jos asiakkaalla on valittuna jo jokin muu kieli, se voi tulla ylikirjoitetuksi.

**Comment by lmstrand** [comment]
Ok. Korjataan. Onko ok, jos muokattaessa asiakasta hänellä jostain syystä olisi default-valinta, niin sillon saisi vaihtaa suomenkielen tilalle? Muuten siihen ei koskettaisi.

**Comment by AnneliO** [comment]
> Ok. Korjataan. Onko ok, jos muokattaessa asiakasta hänellä jostain syystä olisi default-valinta, niin sillon saisi vaihtaa suomenkielen tilalle? Muuten siihen ei koskettaisi.

Minusta on.

**Comment by lmstrand** [comment]
Uusi rimpsu:
```
//Asiakkaalle lähtevien ilmoitusten oletuskielivalinta suomeksi
$(document).ready(function () {
  if (window.location.href.indexOf("members/memberentry.pl") > -1) {
    var $notices_lang_select = document.querySelector('#lang');
    var selected = $notices_lang_select.value;
    if (selected == 'default') {
      $notices_lang_select.value = 'fi-FI';  
    }
  }
});
```

**Comment by AnneliO** [comment]
Minusta uusi rimpsu toimii nyt oikein. Olemassa oleva valinta ei ylikirjoitu, uudelle tulee valituksi suomi ja jos asiakkaalla on ennestään default, tulee valinnaksi suomi.

**Comment by Kati-Helle** [comment]
Hellessä uusi rimpsu vaikuttaa toimivalta
- olemassa olevan asiakastiedon muokkauksessa asiakkaan ilmoitusten kieliarvot Suomi, English, Svenska eivät ylikirjoudu arvolla Suomi
- uutta asiakastietoa lisätessä ilmoitusten kieli -kentän oletusarvona on Suomi
- uutta asiakastietoa lisätessä tai olemassa olevaa asiakastietoa muokatessa valittu Oletus-kieli ei tallennu, vaan arvoksi tallentuu Suomi

**Comment by velimarj** [comment]
Myös OUTIssa vaikuttaisi toimivan kuten pitääkin.

**Comment by Tuomas-Kyyti** [comment]
Kyytissäkin toimii.

**Comment by lmstrand** [comment]
Suljen tiketin.
