### ISSUE TITLE
Uusi valittava ominaisuus: vahvistetaanko niteen kuljetus automaattisesti, jos kuljetuspoppari "ohitetaan" - nide ei testatessani mennyt kuljetustilaan

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-22x#156]
### Mikä vikana?

Testasin uuden ominaisuuden, jossa niteen kuljetuksen voi vahvistaa ilman kuljetuspoppariin reagoimista. (Kuljetuspopparin ohitus esim. klikkaamalla hiirellä ’jossain’ näytöllä TAI palauttamalla uusi/toinen nide.)

Testatessa uusi asetus näin
AutomaticConfirmTransfer = Kuljeta automaattisesti, kun ikkunasta poistutaan valitsematta 'Kyllä'. 

Lisäksi tämä asetus näin
TransfersBlockCirc = Älä estä virkailijaa jatkamasta lainojen palautusta, kun kuljetustila aktivoituu. 

Palautettu nide ei mennyt kuljetustilaan, vaikka palautuksessa on tieto kuljetustarpeesta:
![kuva](https://user-images.githubusercontent.com/99952449/231396415-af254a8f-3476-4c30-a12c-27610efbe951.png)

Palautettu nide tietueen perustiedoissa
![kuva](https://user-images.githubusercontent.com/99952449/231397608-e9245068-5a0e-4e75-9587-685362faf595.png)

Tämä testattu Hangon nide ei kellu palautuskirjastossaan Porvoon pääkirjasto. Niteen tietueella on yksi varaus, johon on jo aiemmin tärpännyt nide (kuljetettavaksi). 

Joku asetus vielä väärässä asennossako?

Tätä ei ole nyt sovittu ainakaan Helleen käyttöönotettavaksi. Laitan kuitenkin tiedoksi testaukseni.

**Comment by velimarj** [comment]
OUTIssa on tätä testailtu myös, ja saatiin tuo toimimaan ainoastaan silloin kun oli käytössä myös asetus AutomaticItemReturn: "Kuljeta".

**Comment by Kati-Helle** [comment]
Kiitos Veli-Pekka tiedosta :)
Testasin ja ko. asetusmuutos vaikuttaa myös siihen, että enää niteen kuljetustilaa ei saa peruttua palautuksen popupin kummastakaan teoslinkistä (linkit vievät tietueen Perustiedot-näytölle).

Testissäni palautin Pernajana Loviisan niteen (Loviisan kirjastoja molemmat ja kellutus ei ole käytössä)
![kuva](https://user-images.githubusercontent.com/99952449/231656923-bd1e7861-ab52-4b54-b8a0-6780b35ecefd.png)

Palautuksen popupin teoslinkin klikkauksen jälkeen nide on edelleen kuljetustilainen
![kuva](https://user-images.githubusercontent.com/99952449/231657631-05400be9-e6da-40a3-9718-2efa2e11c18d.png)

**Comment by ReettaSiili** [comment]
Mielestäni vähän turha asetus tämä AutomaticConfirmTransfer, jos  AutomaticItemReturn=kuljeta hoitaa saman asian, riippumatta vastaako poppariin kyllä.
