### ISSUE TITLE
Miten piilottaa Nideryhmät-välilehti?

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-22x#157]
### Mikä vikana?

Saisiko tietueen perustiedot -näytöltä piilotettua Nideryhmät-välilehden? Nideryhmät eivät tule Hellessä heti käyttöön.

![kuva](https://user-images.githubusercontent.com/99952449/231431887-ecf2dbf1-05cc-4774-b5d9-741768c42b95.png)

**Comment by lmstrand** [comment]
EnableItemGroups ja  EnableItemGroupHolds -asetuksilla saa nideryhmät käyttöön/pois käytöstä. Minulla on molemmat pois käytöstä eikä Nideryhmät-välilehteä näy.

**Comment by Kati-Helle** [comment]
Helle ei nyt syystä tai toisesta noilla asetusvalinnoilla Nideryhmät-välilehteä piilota
![kuva](https://user-images.githubusercontent.com/99952449/231447452-a3b0dd4f-88da-4116-99c8-af57048e94c5.png)

Asetukset
![kuva](https://user-images.githubusercontent.com/99952449/231447561-2cea2981-9b54-4965-bbb9-4f3c59895659.png)

**Comment by lmstrand** [comment]
Hmm tuo taisi olla niitä meidän omia optimoituja tauluja. Ilman meidän koodia välilehti ei näy. Ksdev/ks-0015-bug-23269-holds-page-REST.

**Comment by lmstrand** [comment]
Ei taidakaan olla tuosta kyse. Pitää tutkailla.

**Comment by ghost** [comment]
Nideryhmäasetukset eivät nollaudu oikein mistä syystä välilehti jää näkyviin vaikka asetuksen poistaisi käytöstä. Korjaus tulossa.

**Comment by AnneliO** [comment]
Vaara-nextillä ei ollut päällä  EnableItemGroups ja EnableItemGroupHolds -järjestelmäasetukset. Laitoin ne päälle ja takaisin pois päältä, niin Nideryhmät-välilehti katosi näkyvistä tietueen perustiedot-näytöllä.

**Comment by ajrajala** [comment]
Tein saman Vaski-nextillä, se tosiaan tepsi. 👍

**Comment by Kati-Helle** [comment]
Kiitos Anneli, piilotustapa toimii Hellessäkin.

Keinot ovat monet :)

**Comment by AnneliO** [comment]
Lasse oli siis tuonut korjauksen, mutta taulussa oli varmaan vielä vanha virheellinen arvo. Uudelleentallennus tallensi oikeanlaiset arvot ja toiminto meni pois päältä. :)

Tiketin voinee sulkea? :)

**Comment by Kati-Helle** [comment]
Kiitokset Lasselle korjauksesta!
