### ISSUE TITLE
Bug 30920: Add caching to GetAuthorizedValueDesc

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/Koha-22x#158]
### Siirrettävä ominaisuus

Siirretään yhteisöstä.

**Comment by emta001** [comment]
Eikös tämä ole testattavana nexteillä?

**Comment by lmstrand** [comment]
On.

**Comment by lmstrand** [comment]
Suljen tiketin ainakin toistaiseksi, koska ominaisuus tuntuu toimivan nexteillä ok.
