### ISSUE TITLE
OUTIn Finna-nextillä muutospyyntölomake-ongelma

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha-22x#159]
### Mikä vikana?

Kun Finnan nextillä yrittää tehdä muutoksen Katuosoite-, Postinumero-, Kaupunki-, Maa- tai Varaustunnistekenttään, niin saa ilmoituksen "Pyyntöä ei voitu käsitellä. Yritä uudestaan."

Finna-tuki on tutkinut asiaa ja kertoi, että muutospyyntölomakkeen asetukset näyttäisi olevan kunnossa Outin Koha-ajurissa Finnassa ja ongelma ei näytä liittyvän testinäkymän paikallisiin muokkauksiin.

Lokilla Finnan puolella näkyy vain, että Koha vastaa muutospyynnön lähettämiseen:
{"errors":[{"message":"Internal Server Error.","path":"\/"}],"status":500}

Saako ongelman korjattua Kohan puolella?

### Mitä pitäisi tapahtua

Tee muutospyyntö-lomakkeen tietojen pitäisi välittyä Kohaan henkilökunnan käsiteltäväksi.

### Kuinka toistaa ongelma/asia

1. Kirjaudu Finnan nextiin
2. Omat tiedot-sivulla klikkaa auki Tee muutospyyntö
3. Muuta tietoja ja klikkaa Lähetä*

*Kannattaa testata eri tavoilla eli muokkaamalla vain yhtä kenttää kerrallaan / kaikkia kenttiä kerralla. 

### Jotain muuta?

Aluksi, kun virhe huomattiin, saatiin Varaustunnuksen muutospyynnöt lähtemään OUTI-Kohaan ongelmitta, samoin onnistui myös osoite- ja varaustunnus-muutosten **yhtäaikainen** muutospyynnön lähetys. Tuossa vaiheessa virheilmoitus tuli enkuksi: "Updating of patron information failed".

Otimme yhteyttä Finna-tukeen ja tuki katsoi lokilta, että ongelmaan liittyvää 500 Internal server Error -virhettä palautuu rajapinnalta:  {"errors":[{"message":"Internal Server Error.","path":"\/"}],"status":500}

Finna-tuki palautti edelliset asetukset ajuriin. 

Asetusten palautuksen jälkeen ei minkään muutospyynnön lähettäminen enää onnistu, mutta itse virheilmoitus tulee suomen kielellä.

**Comment by rakkyllo** [comment]
Vaskilla on tällä hetkellä sama ongelma. Testasin näitä parin viime viikon aikana, ja jossain vaiheessa onnistuin kyllä lähettämään lomakkeella muutospyynnön next-Kohaan. Nyt tulee virheilmoitus "Pyyntöä ei voitu käsitellä. Yritä uudestaan."

Onko OUTInkin tapauksessa niin, että kun painaa "Lähetä", lomakkeelle tehdyt muutokset nollautuvat? Eli jos vaikka yritän muuttaa varaustunnisteen muodosta "HessuHopo" muotoon "Hessu", niin kun painan "Lähetä", tekstikenttään palautuu muoto "HessuHopo".

**Comment by pirliis** [comment]
Kyllä eli Lähetä-painike nollaa tehdyn muutoksen ja tulee tuo virheilmoitus.

**Comment by Kati-Helle** [comment]
Tein uuden version Helle-Finnaan sisäänkirjautuneena Varaustunnus-kentän arvon muutoksen:
- erikoista? Kohassa ei-pakollinen Maa-kenttä on tyhjä JA Finna vaatii tuohon arvon. Eli Lähetä-painike ei ole aktiivinen silloin kun Maa-kenttä on tyhjä (Maa-kentästä luovutaan, kun ko. arvon sisältämät asiakastiedot on korjattu.)
- Varaustunnus-kentän arvon muuttaminen onnistuu
- Lähetä-painikkeella tietojen muutospyyntö lähtee liikkeelle
- Kohan etusivulla on linkki muutospyyntöön
![kuva](https://user-images.githubusercontent.com/99952449/232458985-ce274f6b-b9a2-4366-a540-43865b0cbd9d.png)

Tietoja muutospyynnössä:
![kuva](https://user-images.githubusercontent.com/99952449/232460973-afc68c05-e410-4637-955a-8d9a50cd15c1.png)


Lisätietona, kun Koha-asiakastiedossa ei ole Varaustunnus-asiakasmäärettä Kohassa
![kuva](https://user-images.githubusercontent.com/99952449/232467558-ca2f0b40-7f98-4af9-b1e8-22fb5e84a024.png)

**Comment by pknuuti** [comment]
Testausta Vaaran nextillä ja Finna-nextillä: osoitteen pystyy muuttamaan vain jos muuttaa samalla varaustunnuksen. Ilman varaustunnuksen muuttamista saa virheilmoituksen päivityksen epäonnistumisesta.

**Comment by pirliis** [comment]
Vaskin ja OUTIn tuotanto-finnoissa oli tänään sama ongelma kuin next-finnoissa. Eli muutospyyntöjen päivitykset eivät onnistuneet, tuli ilmoitus: _Pyyntöä ei voitu käsitellä. Yritä uudestaan._

Tuotannossa ongelmien aiheuttajaksi ilmeni, että kirjastoissa oli ylikirjoitettu sivupohja myresearch/change-address-settings.phtml. Kun ylikirjoitus poistettiin, tuotannon muutospyynnöt alkoivat toimia.

Next-finnoista poistettiin myös sivupohjan ylikirjoitus, mutta siellä se ei auttanut ongelmaan.

**Comment by pknuuti** [comment]
"Vaaran ja OUTIn tuotanto-finnoissa oli tänään sama ongelma kuin next-finnoissa. Eli muutospyyntöjen päivitykset eivät onnistuneet, tuli ilmoitus: Pyyntöä ei voitu käsitellä. Yritä uudestaan."

Tuossa pitäisi olla Vaski eikä Vaara.

**Comment by pirliis** [comment]
> "Vaaran ja OUTIn tuotanto-finnoissa oli tänään sama ongelma kuin next-finnoissa. Eli muutospyyntöjen päivitykset eivät onnistuneet, tuli ilmoitus: Pyyntöä ei voitu käsitellä. Yritä uudestaan."
> 
> Tuossa pitäisi olla Vaski eikä Vaara.

Sori, korjasin. :)

**Comment by rakkyllo** [comment]
Olisiko mahdollista tarkistaa, onko next-Kohan rajapinnassa tapahtunut tämän funktion osalta muutoksia? Vertailimme tuotannon ja next-Finnan lomakkeen kenttien nimiä, ja ne ovat identtisiä. Koska lomake toimii tuotanto-Finnassa, jotenkin tässä järkeilisi, että lomakkeen päivittyminen jää kiinni johonkin kohtaan next-Kohan rajapintaa. Toki voin olla väärässä, mutta jos pystytte vertailemaan lomakkeen käsittelyn nextin ja tuotannon välillä niin oltaisiinpa se ainakin tarkistettu :D

Liitteenä olevassa kuvassa näkyy nykyiset kentät.

![kuva](https://user-images.githubusercontent.com/103504452/233370830-c517ee63-f24e-4956-8a2a-88d252e6291e.png)

**Comment by AnneliO** [comment]
Testasinpa miekin Vaaran nextillä ja jos yritti muuttaa pelkkää osoitetta, niin tuli tällainen ilmoitus:


![Image](https://user-images.githubusercontent.com/33121325/234503205-eb907b94-1e86-4ded-91f1-6210be1cfcd1.png)

Sama tuli nyt myös OUTIssa.

Voisko tuossa olla nyt jotain sellaista, että kun varaustunnusta ei muuteta, niin se tulkitsee sen tuplatiedoksi (tietokannassa on jo sama tunnus)?

**Comment by lmstrand** [comment]
Joo rajapinnassa on bugi. Pitää korjata.

**Comment by lmstrand** [comment]
Korjaus viety nexteille testattavaksi.

**Comment by pknuuti** [comment]
Vaaran nextilllä testattu osoitteen muuttamista ja se toimii nyt. Ei tarvi enää varaustunnusta muuttaa yhtä aikaa.

**Comment by piiaseme** [comment]
OUTIn nextillä testattu ja toimii myös. Kiitos :)

**Comment by AnneliO** [comment]
Suljen tiketin.
