### ISSUE TITLE
Miten piilottaa Varaukset odottaneet yli x päivää toiminnossa Noudettavissa olevat varaukset?

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-22x#161]
### Mikä vikana?

Miten saa piiloon Noudettavissa olevat varaukset -toiminnon välilehden Varaukset odottaneet yli x päivää?
![kuva](https://user-images.githubusercontent.com/99952449/232418353-16e78874-81ea-42e1-bc4c-3add58265c72.png)

Tämä IntranetUserCSS-rimpsu on tuotannossa. Ei tepsinyt Hellen uuden version testissä:
/* Piilota Varaukset odottaneet yli x-päivää */
body#circ_waitingreserves.circ a#ui-id-6.ui-tabs-anchor { display: none; }

**Comment by lmstrand** [comment]
Tämä näyttäisi toimivan:
```
/* Piilota Varaukset odottaneet yli x-päivää */
body#circ_waitingreserves.circ [aria-controls="holdsover"] { display: none; }
```

**Comment by Kati-Helle** [comment]
Kiitos Lari, toimii!
