### ISSUE TITLE
Kausijulkaisut-osiosta puuttuu linkki tarkkaan hakuun

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha-22x#162]
### Mikä vikana?

Nextiltä ei näyttäisi löytyvän linkkiä, jolla pääsisi siirtymään kausijulkaisutilausten tarkkaan hakuun vaikka itse tarkan haun sivu on edelleen olemassa: https://vaski-next.koha-suomi.fi/cgi-bin/koha/serials/serials-search.pl.

Tarkka haku on tarpeellinen esim. silloin kun halutaan hakea tietyn kirjaston kausijulkaisutilauksia.

### Mitä pitäisi tapahtua

Nykyisessä versiossa tarkka haku linkki löytyy kausijulkaisujen issn/nimeke-haun yhteydestä:
![kuva](https://user-images.githubusercontent.com/44638512/232996402-8483b010-2b84-47a6-abae-0f0f527b22f3.png)

**Comment by Kati-Helle** [comment]
Olisivatko siirtyneet hieman toiseen paikkaan? (Vai oliko kyse jostain muusta?)
![kuva](https://user-images.githubusercontent.com/99952449/233002312-3f055dfb-d0e4-4f47-9979-7e267b371aa1.png)

**Comment by ajrajala** [comment]
Ongelmana siis se, ettei ainakaan Vaskin nextillä näy missään linkkiä tarkkaan hakuun. Pääsin tarkkaan hakuun ainoastaan kirjoittamalla sivun osoitteen osoiteriville.

Löysitkö siis Kati Hellen nextiltä linkin tarkkaan hakuun?

**Comment by Kati-Helle** [comment]
Anni, en löytänyt. En myöskään englanninkielisessä Kohassa.
Tarkemmat hakuvaihtoehdot näkyvät vasta lehtitilauksen haun jälkeen näytön vasemmalla (sisältää tehdyn haun hakuehdon)
![kuva](https://user-images.githubusercontent.com/99952449/233005415-9056525f-f718-41c8-8528-f1d47fe15340.png)

**Comment by AnneliO** [comment]
PTFS Europen sandboxissa tuo tarkka haku tulee näkyville heti kausijulkaisujen aloitussivulla.

![kuva](https://user-images.githubusercontent.com/33121325/233272712-9bda0865-fa46-45f8-9fa8-b08b19bf5142.png)

En ainakaan vielä löytänyt tähän liittyen tikettiä yhteisöstä.

**Comment by ajrajala** [comment]
PTFS Europen sandboxissa näkyy myös olevan yläpalkin Title-hakukentän vieressä ikoni josta avautuu lisähakukenttiä ja linkki tarkkaan hakuun, meiltä ikoni uupuu:

![kuva](https://user-images.githubusercontent.com/44638512/233282904-c2d34425-f117-45e9-97af-a2d7906e9e8f.png)

**Comment by emta001** [comment]
Korjattu yhteisössä tiketissä [33014](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=33014)

**Comment by emta001** [comment]
Korjaus tuotu nexteille.

**Comment by Kati-Helle** [comment]
Paikallaan on! Annin mainitsemat lisähakukentät myös.
![kuva](https://user-images.githubusercontent.com/99952449/233559416-8826ed26-2076-4775-94fe-c669c36df107.png)

**Comment by ajrajala** [comment]
Kuittaan myös, että nyt näyttäisi olevan kuten pitää.

**Comment by Kati-Helle** [comment]
Toimiiko Anni Vaskin tuotannon tai nextin Kausijulkaisuissa Julkaisija-arvolla haku?
Kokeilin Hellen nextissä hakea sellaisen lehtitietueen julkaisijaa
- jonka Julkaisija-arvo on tietueen kentässä 260b - ei toiminut (tietueen biblionumber=1598456)
- jonka Julkaisija-arvo on tietueen kentässä 264b - ei toiminut (tietueen biblionumber=1598300)

**Comment by AnneliO** [comment]
Julkaisija-haku näyttäisi hakevan 028a-kentän arvoja.

**Comment by AnneliO** [comment]
> Julkaisija-haku näyttäisi hakevan 028a-kentän arvoja.

Samalla tavalla kuin Nidehaussa Julkaisija-sarakkeessa näytetään 028a-kentän arvo.

**Comment by Kati-Helle** [comment]
oho :)

**Comment by AnneliO** [comment]
Korjaus toimii myös outin ja vaaran nexteillä. Tiketin voinee sulkea? :)
