### ISSUE TITLE
Taattavan lisääminen tuottaa virheen 500

### ISSUE THREAD

**Issue by Tuomas-Kyyti** [KohaSuomi/Koha-22x#165]
### Mikä vikana?

Kun Kyytin nextissä yrittää lisätä henkilöasiakkaalle taattavan _Lisää taattava_ -napista ilmoittaa Koha virheestä 500.
Toisin päin lisäys onnistuu eli taattavalle voi lisätä takaajan.

Emmi katsoi, että ainakin asiakkaalle 201548 tuli virheilmoitus:
`Can't call method "category_type" on an undefined value at /home/koha/Koha/members/[memberentry.pl](http://memberentry.pl/) line 291.`

Kyytissä ei ole käytössä IntranetUserJS-rimpsua "Lisää huollettava monivalintanappi..."

Vaaran nextissä on kuulemma sama ongelma.

### Asiasanat/tagit

takaaja taattava lapsi huoltaja

**Comment by AnneliO** [comment]
Testasin Vaarassa sen verran, että mistään JS-rimpsusta ongelma ei johdu.

**Comment by emta001** [comment]
Johtuu siitä, että "Lisää huollettava" nappia painaessa asiakkaan borrowernumber välitetään parametrinä _guarantor_id_. Mutta muuttujan _category_code_ selvittäminen vaatisi muuttujan _patron_ asettamisen ja se tehdään nimenomaan muuttujan _borrowernumber_ avulla. Eli ongelmana on se, että meidän takaaja muutos ja yhteisön tapa lisätä taattava ei nyt kohtaa tässä. 

Pitänee joko jotenkin saada tuo _category_code_ ulos tai sitten estää takaajan tarkistus.

**Comment by emta001** [comment]
Korjaus tuotu nexteille.

**Comment by pknuuti** [comment]
Ei ainakaan Vaaran nextillä toimi yhtään paremmin kuin aikaisemminkaan.

**Comment by emta001** [comment]
> Ei ainakaan Vaaran nextillä toimi yhtään paremmin kuin aikaisemminkaan.

Vaati näemmä palveluiden uudelleenkäynnistyksen. Mites nyt, toimiiko?

**Comment by AnneliO** [comment]
Mulla taas toimii vaara-nextillä nyt Lisää taattava -nappi.

**Comment by pknuuti** [comment]
Joo, nyt se toimii.

**Comment by Tuomas-Kyyti** [comment]
Kyytissä toimii myös. Suljen tiketin.
