### ISSUE TITLE
Asiakastiedon Lähetä tervetulosähköposti -toiminto ei-aktiiviseen/toimimattomaan tilaan

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-22x#166]
### Mikä vikana?

Saisiko asiakastiedon Lähetä tervetulosähköposti -toiminnon ei-aktiiviseksi (tai piilotettua)?
Toiminto on asiakastiedon Muita toimintoja -alasvetovalikossa ja näkyy sekä lisätylle uudelle asiakastiedolle että jo olemassa olevalle asiakastiedolle
![kuva](https://user-images.githubusercontent.com/99952449/233270657-8f40a986-bee8-4367-8cb0-7d374f3de585.png)

Toimintoon liittyvä järjestelmäasetus Hellessä nyt näin: AutoEmailNewUser = Don't send an email to newly created patrons. 
(Lisäksi toimintoon liittyy asetus AutoEmailPrimaryAddress)

**Comment by AnneliO** [comment]
Jos tyhjennät tai poistat WELCOME-viestipohjan, niin lähteekö vaihtoehto pois valikosta?

**Comment by Kati-Helle** [comment]
Ei auttanut kumpikaan tapa.

Viestipohjan tyhjensin ja Tallenna-painikketta klikattuani Koha ilmoittaa
![kuva](https://user-images.githubusercontent.com/99952449/233286212-7bc3df12-6592-4bcb-a394-b5141efe49ca.png)

Viestipohjan poistin
- asiakastiedon Lähetä tervetulosähköposti -toiminto ei poistunut
- kun klikkasin Lähetä tervetulosähköposti -toimintoa, vei Koha asiakastiedon Lähetetyt ilmoitukset -välilehdelle
![kuva](https://user-images.githubusercontent.com/99952449/233287013-d9d460f9-fcd1-4d6f-b6e1-74ce8f5c14b0.png)

Lisätietona: lisäsin WELCOME-viestipohjan takaisin Helleen alkuperäisin tiedoin.

**Comment by Kati-Helle** [comment]
Kun viestipohja on käytössä, vie Lähetä tervetulosähköposti -toiminnon klikkaus myös asiakastiedon Lähetetyt ilmoitukset -välilehdelle ja välilehden Ilmoitus-kentässä näkyy ko. sähköpostiviesti.

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 20.4.2023: Viestipohjan poistaminen estää viestin lähettämisen, joten se mielestämme ratkaisee ongelman riittävässä määrin.

**Comment by Kati-Helle** [comment]
Ok. Poistin WELCOME-viestipohjan Hellestä.
Tervetulosähköpostin käyttö otettaneen Hellessä käyttöön vasta ensi syksynä.

Tämä vielä tiedoksi: kun asiakkaalle ei ole aiemmin lähetetty viestejä (esim. uusi asiakastieto), ilmoittaa Koha näin Lähetä tervetulosähköposti -toiminnon klikkauksen jälkeen:
![kuva](https://user-images.githubusercontent.com/99952449/233351748-58e179be-0aaa-4a07-8d43-1d30922407fc.png)

**Comment by Kati-Helle** [comment]
> Ok. Poistin WELCOME-viestipohjan Hellestä. Tervetulosähköpostin käyttö otettaneen Hellessä käyttöön vasta ensi syksynä.
> 
> Tämä vielä tiedoksi: kun asiakkaalle ei ole aiemmin lähetetty viestejä (esim. uusi asiakastieto), ilmoittaa Koha näin Lähetä tervetulosähköposti -toiminnon klikkauksen jälkeen: ![kuva](https://user-images.githubusercontent.com/99952449/233351748-58e179be-0aaa-4a07-8d43-1d30922407fc.png)

Kenties teksti voisi olla hieman toisin? Esimerkiksi:
Asiakkaalla ei ole ilmoituksia.
Asiakkaalle ei ole lähetetty viestejä.
Asiakkaalla ei ole viestejä.

**Comment by AnneliO** [comment]
> > Ok. Poistin WELCOME-viestipohjan Hellestä. Tervetulosähköpostin käyttö otettaneen Hellessä käyttöön vasta ensi syksynä.
> > Tämä vielä tiedoksi: kun asiakkaalle ei ole aiemmin lähetetty viestejä (esim. uusi asiakastieto), ilmoittaa Koha näin Lähetä tervetulosähköposti -toiminnon klikkauksen jälkeen: ![kuva](https://user-images.githubusercontent.com/99952449/233351748-58e179be-0aaa-4a07-8d43-1d30922407fc.png)
> 
> Kenties teksti voisi olla hieman toisin? Esimerkiksi: Asiakkaalla ei ole ilmoituksia. Asiakkaalle ei ole lähetetty viestejä. Asiakkaalla ei ole viestejä.

Teetkö tekstimuutoksesta erillisen kehitysehdotuksen Koha-repositorioon? Se ei liity enää alkuperäiseen tikettiin, koska tuo teksti tulee aina, kun asiakkaalle ei ole lähetetty viestejä. :)

Teksti on englanniksi _There is no record of any messages that have been sent to this patron._
