### ISSUE TITLE
Niteen tila näkyy perustiedot näytöllä Ei lainattavissa (Tilattu) Saatavana

### ISSUE THREAD

**Issue by MikkoLiimatainen** [KohaSuomi/Koha-22x#167]
### Mikä vikana?

Niteen notforloan-tilan käsittelyssä on perustiedot näytöllä virhe, joka aiheuttaa sen, että nide näyttää olevan yhtä aikaa ei lainattavissa ja saatavana. Kyseessä on nähdäkseni tämä ongelma, johon on korjaus olemassa: [Bugzilla 32445](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=32445)

### Jotain muuta?

![Nide ei lainattavissa ja saatavana](https://user-images.githubusercontent.com/98884651/233284973-41759dfb-5b42-4bfe-a0bc-0f1496349211.png)

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 20.4.2023: Tuodaan korjaus yhteisöstä.

**Comment by emta001** [comment]
Korjaus tuotu nexteille.

**Comment by MikkoLiimatainen** [comment]
Korjaus näyttää tepsineen. Suljen tiketin.
