### ISSUE TITLE
Asiakkaan muokkauksessa kalenterin alasvetovalikosta puuttuu tammikuu

### ISSUE THREAD

**Issue by velimarj** [KohaSuomi/Koha-22x#168]
### Mikä vikana?

Muokatessa asiakastietoja, kun määrittää kortille alkamis- tai vanhenemispäivää, puuttuu alasvetovalikosta tammikuu. Siihen pääsee kyllä käsiksi siirtymällä nuolella, mutta alasvetovalikosta tammikuuta ei siis saa valittua.

Tutkin myös muutamaa muuta kalenteria (lainausnäytön eräpäivän määrittely, varauksen alkamis- tai vanhenenemispäivä, eräpäiväkalenteri) ja ainakin niissä tammikuu oli paikoillaan.

### Mitä pitäisi tapahtua

Alasvetovalikosta pitäisi pystyä valitsemaan tammikuu.

### Kuinka toistaa ongelma/asia

1. Mene asiakkaan muokkaukseen.
2. Määritä alkamis- tai vanhenemispäivä.
3. Avaa pudotusvalikko.

### Jotain muuta?

![kalenteri_tammi](https://user-images.githubusercontent.com/118160273/234214018-521927ae-7547-4d9f-acca-c97a469892fe.png)

### Asiasanat/tagit

kalenteri
alasvetovalikko
pudotusvalikko

**Comment by AnneliO** [comment]
Tämä IntranetUserCSS-säätö:

/* Piilota ennakkoilmoituksen valinnasta 0 päivän keston. Käy lisäksi valitsemassa asiakastyyppien ylläpidossa asiakastyyppien viestiasetuksiin jotain muuta kuin 0 oletukseksi. Valinta tehtävä kaikille asiakastyypeille erikseen. */
body#pat_memberentrygen.pat option[value='0'] { display:none; }

Näköjään piilottaa tammikuun. Sillä täytynee olla arvo 0, koska se piilottuu.

Lisäsin rimpsuun vähän tarkennusta ja tällä rimpsulla pitäisi mennä viestiasetuksista ennakkoilmoitusvalikosta 0 piiloon, mutta tammikuu säilyä kalenterissa näkyvillä.

```
/* Piilota ennakkoilmoituksen valinnasta 0 päivän keston. Käy lisäksi valitsemassa asiakastyyppien ylläpidossa asiakastyyppien viestiasetuksiin jotain muuta kuin 0 oletukseksi. Valinta tehtävä kaikille asiakastyypeille erikseen. */
body#pat_memberentrygen.pat fieldset#memberentry_messaging_prefs.rows option[value='0'] { display:none; }
```

Rimpsu on OUTIssa paikallaan.

**Comment by velimarj** [comment]
No se oli nopeaa korjattu! Toimii siis OUTIssa.

**Comment by AnneliO** [comment]
Hyvä juttu, lisäsin korjatun rimpsun myös [IntranetUserCSS-wikiin](https://github.com/KohaSuomi/Koha-22x/wiki/IntranetUserCSS).

**Comment by AnneliO** [comment]
Suljen tiketin. :)
