### ISSUE TITLE
Verkkokirjastossa tehdyt uusinnat kirjautuu Finna-api-käyttäjän kotikirjaston mukaan - ksdev/ks-0047-KD-5452

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#17]
### Siirrettävä ominaisuus

Verkkokirjastossa tehdyt uusinnat kirjautuu Finna-api-käyttäjän kotikirjaston mukaan.

Lari teki verkkokirjastouusintoihin korjauksen, että se seuraa OpacRenewalBranch-järjestelmäasetusta statistics-taulun osalta. Korjaus viedään tuotantoon maanantaina. Kaikkien kannattaa käydä tarkistamassa, että tuossa asetuksessa on nyt se valinta, jonka mukaan haluatte verkkokirjastouusintojen tilastoituvan.

Sen sijaan verkkokirjasto seuraa eräpäiväkalenteria valitessaan circcontrol- ja HomeorHoldingbranch-järjestelmäasetuksia. Ne kannattaa säätää siten, kuin haluatte uusintojen seuraavan. Esim. OUTIssa halutaan uusinnan seuraavan lainanneen kirjaston eräpäiväkalenteria, jolloin valitsemme asetuksiin seuraavat:

circcontrol: the library where the item is from
homeorholdingbranch: holdingbranch

HomeOrHoldingbranch-asetuksessa määritetään, käytetäänkö niteen koti- vai sijaintikirjastoa. Kun nide lainataan eri kirjastossa kuin sen kotikirjastossa, on sen sijaintikirjasto lainaava kirjasto, jolloin asetukseen valitaan sijaintikirjasto, mikäli halutaan uusinnan seuraavan lainannutta kirjastoa.

**Comment by lmstrand** [comment]
feature-branchissa ksdev/ks-0047-K22-17-api-OpacRenewalBranch

**Comment by Kati-Helle** [comment]
Helle-nextissä OpacRenewalBranch-asetuksen arvona on: the item the library was checked out from

Uusin lainan Hellen Finna-nextissä: statistics-taulussa uusitun lainatun niteen branch-arvo on sama kuin lainaustapahtuman branch-arvo. Uusinta tilastoituu siis oikein eli lainanneelle kirjastolle..
![kuva](https://user-images.githubusercontent.com/99952449/226346307-1973a3a9-7436-4b2f-b0c8-ec48ac746b22.png)

Asiakkaan (ID 54450) kotikirjasto on Pernajan lähikirjasto, niteen (itemnumber 1141828) kotikirjasto on Hangon kaupunginkirjasto, niteen lainauskirjasto on Porvoon pääkirjasto (PRVPK).

**Comment by ajrajala** [comment]
Vaski-nextissä asetus samoin kuin Hellessä ja testasin Katin tavoin uusia Finnassa niteitä, joiden kotikirjasto + lainanneen asiakkaan kotikirjasto olivat eri kuin lainauskirjasto. Lainat tilastoituvat oikein lainanneelle kirjastolle.

**Comment by pirliis** [comment]
OUTIssa toimii myös oikein eli uusinnat tilastoituvat sen kirjaston eräpäiväkalenterin mukaan, josta lainat oli alunperin lainattu.

**Comment by AnneliO** [comment]
Tähän on tullut kolme hyväksyvää testausta, joten suljen tiketin. :)
