### ISSUE TITLE
Taustatöiden työlistalla "Only include jobs started in the last hour" -valinta toimii väärin

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#170]
### Ongelma

Taustatöiden listalla taas jos ottaa täpän pois kohdasta Only include jobs started in the last hour, katoaa listalta työt lähitunneilta/lähiajalta kokonaan.

Täppä paikallaan:
![kuva](https://user-images.githubusercontent.com/33121325/234245808-2a060e04-7971-4cc5-bc64-9d3dd4e9e4b2.png)

Täppä pois:
![kuva](https://user-images.githubusercontent.com/33121325/234245766-9624771f-116d-45fa-9506-cd2182253fc9.png)

Esimerkeissä ylemmässä kuvassa rivejä on kokonaisuudessaan 178, alemmassa filtteröinti tehdään kokonaisluvusta 158 (joka on filtteröity 178:sta). 

Minun järjen mukaan kun täppä otetaan pois, pitäisi näkyä kaikki rivit (tässä tapauksessa siis 178).

### Asiasanat

taustatyöt filtteröinti filtterit

**Comment by Kaarius** [comment]
Tuotu nexteille testattavaksi.

**Comment by AnneliO** [comment]
Minun vaara-nextillä tehtyjen testien mukaan toimisi nyt järkevästi.

**Comment by ajrajala** [comment]
Only include jobs started in the last hour -valinta toimii minustakin nyt järkevästi silloin kun on täppä pelkästään siinä (tai molemmat täpät otettuna pois).

Jos on valittuna myös valinta "Vain nykyiset taustatyöt", ei Only include jobs started in the last hour -valinta näyttäisi minusta tekevän mitään vaan näkyy aina sama tulosjoukko (joista mikään ei ole aloitettu viimeisen tunnin aikana vaan ovat vanhempia):

![kuva](https://user-images.githubusercontent.com/44638512/235171667-6d865d41-4c0f-492b-ae10-eb955c56ab43.png)
![kuva](https://user-images.githubusercontent.com/44638512/235171722-ea8af66b-96ce-4960-9ada-a44419c48b43.png)

**Comment by AnneliO** [comment]
Vaskissa näyttäisi olevan 36 työtä "aloitettu"-tilassa, jotka näkyvät, kun on täppä _Vain nykyiset taustatyöt_ -kohdassa. Mie ymmärtäisin niin, että kun tuo täppä on valittuna, näytetään keskeneräiset/työn alla olevat työt, joita nuo aloitetut ovat.

**Comment by ajrajala** [comment]
Joo, samalla tavalla tulkitsen myös tuon mitä _Vain nykyiset taustatyöt_ tarkoittaa. Mutta jos sen lisäksi on rastitettuna myös _Only include jobs started in the last hour_ niin pitäiskö silloin kuitenkin suodattua näkyville pelkästään tunnin sisällä aloitetut, edelleen keskeneräiset taustatyöt?

**Comment by AnneliO** [comment]
> Joo, samalla tavalla tulkitsen myös tuon mitä _Vain nykyiset taustatyöt_ tarkoittaa. Mutta jos sen lisäksi on rastitettuna myös _Only include jobs started in the last hour_ niin pitäiskö silloin kuitenkin suodattua näkyville pelkästään tunnin sisällä aloitetut, edelleen keskeneräiset taustatyöt?

Hmm.. pitäisi tosiaan.

**Comment by Kaarius** [comment]
Selvisi miksi se toimii noin, sen voi korjata joko tekemällä niin että ne molemmat voi olla päällä tai kun toisen painaa päälle niin toinen menee pois päältä. Kummin on parempi?

**Comment by ajrajala** [comment]
Itse ajattelisin, että parempi jos molemmat voi olla päällä.

**Comment by Kaarius** [comment]
Testattavana nextillä testillä.

**Comment by ajrajala** [comment]
Minusta rastit tekivät nyt sen mitä pitää.

**Comment by AnneliO** [comment]
Tätä viimeisintä muutosta ei taida saada muualla kuin vaski-nextillä testattua. Se mitä miekin tuota  siellä testailin, niin minusta se toimii nyt loogisesti. Ja toimii edelleen vaara-nextillä loogisesti.
