### ISSUE TITLE
Z39.50-haku tiputtaa 001-kentästä BTJ:n kontrollinumeron pois

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha-22x#171]
### Mikä vikana?

Z39.50-haku tiputtaa 001-kentästä BTJ:n kontrollinumeron pois, kun tietue tuodaan TäTistä tai Melindasta. TäTin nextillä 001 näyttää säilyvän.

### Mitä pitäisi tapahtua

BTJ:n kontrollinumeron pitäisi säilyä tuodussa tietueessa.

**Comment by emta001** [comment]
Näyttäisi toimivan myös Outi-testillä.

**Comment by AnneliO** [comment]
> Näyttäisi toimivan myös Outi-testillä.

Mikä toimii? Mulla tyhjenee edelleen 001-kenttä:
![kuva](https://user-images.githubusercontent.com/33121325/234824086-5d6a631e-51de-410e-a044-938566efa28a.png)

**Comment by emta001** [comment]
> > Näyttäisi toimivan myös Outi-testillä.
> 
> Mikä toimii? Mulla tyhjenee edelleen 001-kenttä: ![kuva](https://user-images.githubusercontent.com/33121325/234824086-5d6a631e-51de-410e-a044-938566efa28a.png)

Testillä siis, ei nextillä :D ja jännästi tosiaan näyttäisi toimivan myös miun testeillä.

**Comment by AnneliO** [comment]
Nii juu, joo. Testillä toimii. :D

**Comment by emta001** [comment]
Hmm, näyttöis sille että hankinnan puolella on oma z39.50-hakunsa. Kehtaatteko testata toimiiko tuo 001 siellä?

**Comment by AnneliO** [comment]
Näyttäis toimivan silloin, kun tietue tuodaan tilausta tehdessä:
![kuva](https://user-images.githubusercontent.com/33121325/235110404-c96d6b40-3ff3-4057-ae2a-4edb82df5305.png)

Tällöin tietuetta ei tarkastella ollenkaan muokkaustilassa, kuten kuvailupuolella tehdään ennen tallentamista.

**Comment by emta001** [comment]
Tämä johtuu siis asetuksesta  autoControlNumber. Jos sen arvona on "generated as biblionumber", olemassa oleva 001-kenttä poistetaan z39.50 kautta tehdyn importin aikana ja kenttä jää tyhjäksi. Ongelmana on nyt kuitenkin se, että asetusta ei voi ottaa pois päältä, sillä silloin 001-kenttään ei generoida arvoa kun tietue luodaan tyhjästä.

Sovittiin Annelin kanssa, että asia otetaan esille 2.5. pääkäyttäjäpalaverissa.

**Comment by AnneliO** [comment]
Pyysin kommentteja tähän myös kuvailuryhmän pj:ltä Heikkisen Antilta.

**Comment by AnttHeik** [comment]
Onpahan kinkkinen tilanne. Eikö tuota asetusta pysty korjaamaan tai muuttamaan siten, että jos 001-kentässä on jokin arvo, niin sitä ei mennä poistamaan tietuetta tuotaessa? Miksi ylipäänsä on keksitty, että Z39.50-haulla tehdyn importin aikana 001-kenttä tyhjennetään? Tavoitehan olisi, että 001-kentän arvo luodaan vain silloin, jos 001-kenttä on tyhjä tietuetta tallennettaessa.

001- ja 003-kenttien tietojen pitäisi vastata toisiaan eli 001-kentän arvo on 003-kentän organisaation antama. Jos tietueilla alkaa olla paljon samoja arvoja 001-kentässä, niin jossain vaiheessa ne väistämättä törmäävät toisiinsa. OUTIssa ainakin kävi jossain vaiheessa sitä, että oli tehty osakohteita BTJ:n emoon, ja näille tuli 001-kenttään OUTIn biblionumber. Sitten kävikin niin, että kun OUTIin poimittiin BTJ:n tietueita, joilla oli sama BTJ:n antama arvo 001-kentässä kuin noilla itse tehdyillä, niin nämä menivät sitten ristiin.

Osakohteiden yhdistymisessä emoon emon 001-kentän arvo on tärkeä olla sama kuin osakohteiden 773w-kentässä ja molemmissa 003-kentän tunnuksen on oltava sama.

Z39.50-haun käyttö on ehkä harvinaisempaa paikalliskannoissa nykyään kun valutus toimii, mutta kyllä sitäkin aina välillä käytetään. En luottaisi siihen, että ihmiset muistavat vaihtaa tietueeseen takaisin siinä olleen oikean 001-kentän arvon. Jos taas arvo tulee Kohasta, niin 001 ja 003 eivät enää vastaa toisiaan. Välttämättä se ei ole niin suuri ongelma niillä tietueilla, joilla ei ole osakohteita, mutta sitten toisaalta aina voi käydä niinkin, että tietueelle ilmestyy osakohteita, jos Kohan luoma uusi 001-kentän arvo onkin jo joidenkin tietokannassa olleiden osakohteiden 773w-kentässä.

Mieluummin melkein ottaisin koko asetuksen pois päältä kuin jättäisin sen päälle, jos se toimii noin niin kuin nyt, vaikka tokihan siitäkin varmaan joitakin ongelmia muodostuu. TäTin nextissä kuitenkin uuden tietueen tallennus luo edelleen tietueelle kontrollinumeron, niin kuin ennenkin. Miksi tätä toimintoa ei voi laittaa toimimaan siten kuin se nyt toimii nykyisessä versiossa tai miksiköhän se on muutettu noin tähän versioon? :)

**Comment by AnttHeik** [comment]
Tuossa Annelin hankinnan puolen Z39.50-haun esimerkkikuvassa on muuten kaksi 000-kenttää, mistäköhän ne ilmestyi tietueelle?

**Comment by AnneliO** [comment]
> Tuossa Annelin hankinnan puolen Z39.50-haun esimerkkikuvassa on muuten kaksi 000-kenttää, mistäköhän ne ilmestyi tietueelle?

Olisko se hankinta sitten lisännyt sen, koska Tätissä ei ole kahta 001:stä ja jos tietuetta menee muokkaamaan, niin silloinkaan ei näy kahta. (Muutin jopa 001:n kuvailupohjassa hetkeksi toistettavaksi). Tallensin tietueen uudelleen ja toistuma poistui.

**Comment by AnttHeik** [comment]
> > Tuossa Annelin hankinnan puolen Z39.50-haun esimerkkikuvassa on muuten kaksi 000-kenttää, mistäköhän ne ilmestyi tietueelle?
> 
> Olisko se hankinta sitten lisännyt sen, koska Tätissä ei ole kahta 001:stä ja jos tietuetta menee muokkaamaan, niin silloinkaan ei näy kahta. (Muutin jopa 001:n kuvailupohjassa hetkeksi toistettavaksi). Tallensin tietueen uudelleen ja toistuma poistui.

Ok, se voi olla. Meillä oli nimittäin OUTIn tuotannossa tällä viikolla yksi elokuvatietue, jolla oli myös kaksi 000-kenttää. Elokuva oli ilmeisesti just saapunut. Pitäisi melkein tarkistaa, onko tämä bugi siis nykyäänkin hankinnassa.

**Comment by AnneliO** [comment]
Pääkäyttäjäpalaveri 2.5.2023: Luovutaan järjestelmäasetuksen käytöstä ja tuodaan 001-liitännäinen uuteen versioon.

**Comment by ajrajala** [comment]
Vaskissa testattu 001-liitännäisen tuonnin jälkeen ja todettu toimivan nyt kuten pitää.

**Comment by Kati-Helle** [comment]
Hellessäkin 001-liitännäinen toimii oikein. Melindasta poimitulla tietueella on Kohassa sama 001-kenttäarvo kuin Melinda-tietueella.

**Comment by AnneliO** [comment]
Tämä toimii nyt, kuten pitää, joten suljen tiketin. :)

**Comment by AnttHeik** [comment]
Voisiko tuon liitännäisen asentaa OUTI-testillekin? Sieltä se puuttuu nyt päivityksen jälkeen.

**Comment by CodoDerDritte** [comment]
Liitännäiset on asennettu nyt kaikkiin testiympäristöihin.

**Comment by Kati-Helle** [comment]
Toimii Helle-testissä.
Testasin poimimalla tietueen Melindasta. Poiminnan ja Helle-testiin tallennuksen jälkeen Helle-tietueella on sama 001-arvo kuin Melinda-tietueella.
