### ISSUE TITLE
Osakohteiden siirto TäTistä tuodulle emolle ei onnistu Vie/Tuo-napilla

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha-22x#172]
### Mikä vikana?

Osakohteiden siirto TäTistä tuodulle emolle ei onnistu Vie/Tuo-napilla (001-kenttä?). Osakohteiden siirto yksitellen onnistuu, mutta osakohteen 773 w-kenttään vaihdettava testikannan emon 001-kentän kontrollinumero että emon ja osakohteen sitominen onnistuu.

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 27.4.2023: Tuo/Vie-nappi ei toimi vielä, joten sen puolesta toiminto ei ole vielä voinut toimia. Lisäksi, toiminto on tällä hetkellä kiinni täti-nextillä, jossa on hyvin rajallinen määrä tietueita. Tutkitaan, saadaanko kannat kiinni täti-testille, jossa on enemmän tietueita.

**Comment by emta001** [comment]
> Koha-Suomen palaveri 27.4.2023: Tuo/Vie-nappi ei toimi vielä, joten sen puolesta toiminto ei ole vielä voinut toimia. Lisäksi, toiminto on tällä hetkellä kiinni täti-nextillä, jossa on hyvin rajallinen määrä tietueita. Tutkitaan, saadaanko kannat kiinni täti-testille, jossa on enemmän tietueita.

Broadcast biblios-plugari on nyt yhdistetty Täti-testille ja Vie/Tuo toiminto näyttäisi toimivan esim. tällä tietueella: https://outi-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2279911.

**Comment by emta001** [comment]
@pirliis onnistuuko myös osakohteiden siirto, kun käytössä on täti-test?

**Comment by emta001** [comment]
Yhteyden nextien ja Täti-nextin välillä pitäisi nyt toimia. Oletettavasti osakohteidenkin tuominen onnistuu (vieminenhän ei ole käytössä).

**Comment by AnttHeik** [comment]
OUTIssa ainakin tulee vain ilmoitus: Epäonnistui (Internal Server Error) sekä osakohteellisilla että osakohteettomilla tietueilla.

**Comment by AnneliO** [comment]
Onkohan OUTIssa kaikki säädöt oikein, koska esim. tietueella https://outi-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2279911 Tätin tietueen tiedot ei vastaa tati-nextin tietoja: https://tati-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2343351

**Comment by AnneliO** [comment]
Vie/tuo-napin takaa
![kuva](https://user-images.githubusercontent.com/33121325/237063113-cef9619b-fa39-426b-a0fa-3119d12802fe.png)

tati-nextillä:
![kuva](https://user-images.githubusercontent.com/33121325/237063305-a804e7c8-9f2a-4d30-96d9-ebff555caf20.png)

**Comment by emta001** [comment]
Onhan siellä varmasti broadcast bibliossa oikea osoite?

**Comment by emta001** [comment]
Eipä olleet, nyt on :D

**Comment by AnttHeik** [comment]
Jeps, nyt löytää tuon Hevostallin asukkaan TäTi-nextiltä. Vaati kuitenkin sen, että poistin ensin OUTIn tietueesta 035-kentän, jonka jälkeen suoritti etsinnän 020-kentän mukaan.

**Comment by emta001** [comment]
> OUTIssa ainakin tulee vain ilmoitus: Epäonnistui (Internal Server Error) sekä osakohteellisilla että osakohteettomilla tietueilla.

Kehtaako laittaa jotain esimerkkejä, niin voin vilkaista tätä. Toki jos alkoi toimimaan, niin hyvä sitten.

**Comment by AnttHeik** [comment]
> > OUTIssa ainakin tulee vain ilmoitus: Epäonnistui (Internal Server Error) sekä osakohteellisilla että osakohteettomilla tietueilla.
> 
> Kehtaako laittaa jotain esimerkkejä, niin voin vilkaista tätä. Toki jos alkoi toimimaan, niin hyvä sitten.

Tätä testasin nyt, mutta jäi odotustilaan: https://outi-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2297499 

Nuo edelliset epäonnistuneet eivät löydy TäTi-nextiltä.

**Comment by emta001** [comment]
> > > OUTIssa ainakin tulee vain ilmoitus: Epäonnistui (Internal Server Error) sekä osakohteellisilla että osakohteettomilla tietueilla.
> > 
> > 
> > Kehtaako laittaa jotain esimerkkejä, niin voin vilkaista tätä. Toki jos alkoi toimimaan, niin hyvä sitten.
> 
> Tätä testasin nyt, mutta jäi odotustilaan: https://outi-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2297499

Näyttäs sille, että yksi palvelu meni Täti-nextin päässä nurin eikä suostu nousemaan pystyyn. Selvittelen mikä siellä on vialla.

**Comment by emta001** [comment]
Kirjailen tästä tuonne tikettiin #174

**Comment by emta001** [comment]
Laitanpa tännekin, testeillä homman pitäisi pelittää kuten pitääkin. Siellä on vain OUTI-Täti-yhteys pystyssä, joten testaus onnistuu OUTI-testin kautta.

**Comment by AnttHeik** [comment]
Eli onko OUTI-test nyt päivitetty uuteen versioon ja siellä voi testata? ei enää nextillä? :)

**Comment by emta001** [comment]
> Eli onko OUTI-test nyt päivitetty uuteen versioon ja siellä voi testata? ei enää nextillä? :)

Joo ne päivitettiin eilen. Testaile mieluummin tosiaan testillä, koska se nyt vaikuttaisi toimivan oikein :D
