### ISSUE TITLE
Tietueiden muokkaus eräajona -toiminnossa Näytä Marcin esikatselu jää jumittamaan

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha-22x#173]
### Mikä vikana?

Tietueiden muokkaus eräajona -toiminnossa Näytä Marcin esikatselu jää vain lataamaan eikä näytä tietueen tietoja.

![image](https://user-images.githubusercontent.com/98814860/234542558-f8303a3b-1fa7-4983-be89-4a24a9f685d0.png)

### Kuinka toistaa ongelma/asia

1. Kohan toiminto: Tietueiden muokkaus eräajona
2. Anna tietuenumero ja valitse mallipohja.
3. Valitse Jatka.
4. Avaa Marcin esikatselu.
5. Näyttö jää vain latautumaan.

**Comment by Kaarius** [comment]
Korjattu tuomalla yhteisön tiketti https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=32631.

**Comment by AnneliO** [comment]
Testasin vaara-nextillä ja esikatselu avautuu oikein.

**Comment by Kati-Helle** [comment]
Hellessä esikatselu aukeaa kuten pitää (näyttäen myös tulevan tietuemuutoksen).

**Comment by velimarj** [comment]
Avautuu oikein nyt myös OUTIssa.

**Comment by emta001** [comment]
Näyttäisi siis toimivan kuten pitää, suljen tiketin.
