### ISSUE TITLE
Valutuksen testaus

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-22x#174]
### Siirrettävä ominaisuus

Tämä on testauksen koontitiketti valutuksen ja Tätin kanssa käytettäville plugineille. Yritän parhaani mukaan kirjoittaa tähän kullekin pluginille oman testaussuunnitelman, käykää ne läpi ja raportoikaa tähän mahdolliset ongelmat (ja onnistumiset tietysti). Ja jos miulta on jäänyt jotain huomioimatta, niin raportoikaa nekin.

Valutuksessa käytetään 4 eri pluginia, joista seuraavat on asennettu kimppojen nexteille; Broadcast biblios ja Siirtoraportti. Käykää ensin laittamassa näiden asetukset kuntoon. Ne voi käydä kopioimassa testeiltä tai tuotannosta, huomaatka kuitenkin vaihtaa mahdolliset osoitteet nexteille (esim. tati.koha-suomi.fi -> tati-next.koha-suomi.fi) .

**_HUOM! Nämä on vielä hieman työn alla ja kovin vajaat_**

**Broadcast biblios (koha-plugin-broadcast-biblios)** 

Tietueen aktivointi:
1. Luo uusi tietue tai etsi jokin vanha tietue, jota ei ole vielä aktivoitu
2. Aktivoi tietue painamalla kuvaketta "Aktivoi tietue" -> Kuvakkeen pitäisi muuttua kahle-ikoniksi
3. Avaa siirtoraportti-työkalu ja mene välilehdelle "Tarkista aktivointi"
4. Syötä tietueen biblionumber -> Listaan pitäisi aueta tietueen tiedot 

Vie/Tuo tietue:
1. Paina kuvaketta "Vie/Tuo tietue" -> tämän pitäisi avata pop-up, jossa on tietueen MARC-kentät
2. Jos tietue löytyy myös Täti-nextiltä, Tätissä olevan tietueen MARC-kentät näkyvät myös pop-upissa ja tietue on mahdollista tuoda Tätistä
3. Jos tietue on Täti-nextillä ja sitä on muokattu, muokkauksien tulisi näkyä listalla ja tietueen voi tuoda Tätistä

**Siirtoraportti (koha-plugin-exporter-report)**

1. Säädä plugarin asetukset kuntoon (kopioi testiltä tai tuotannosta).
    -> REST-osoitteena voi käyttää joko Tätin-tuotannon tai nextin osoitetta, ensimmäsellä pitäisi saada samat tulokset kuin   tuotannossa olevalla plugarilla
    -> Jos osoitteena on Täti-nextin osoite, tulisi sivun aueta ilman herjoja, mutta listat ovat tyhjinä.
4. Kun olet onnistuneesti aktivoinut ja/tai saanut siirrettyä tietueita, niiden pitäisi näkyä listattuna raportilla
5. Varmista että kaikki ominaisuudet toimivat:
    -> kaikki välilehdet aukeavat ilman herjoja
    -> tietueisiin pääse tietuenumerolinkkejä painamalla
    -> muutokset näkyvät "Avaa" painiketta painamalla
    -> aktivoidun tietueen voi hakea "Tarkista aktivointi" välilehdellä
    -> keskeytyneistä töistä pääsee tietuenumerolinkin kautta Tätiin

**KohaSuomiServices**

Asetukset kopioitu Täti-testiltä ja muokattu nextille sopivaksi.

1. Mene osoitteeseen https://tati-next.koha-suomi.fi/service -> kirjautumislomakkeen tulisi aueta onnistuneesti
2. Kirjaudu sisään -> tämän tulisi onnistua Täti-tunnuksilla
3. Raportilla tulisi näkyä, mitä siirtoja Tätistä/Tätiin on tehty ()

**Import remote biblios (koha-plugin-import-remote-biblios)** 

Käytössä vain Tätissä.

1. Paina "Vie/Tuo"-nappia ja valitse valikosta "Melinda".
2. Paina "Vie" nappia pop-upin alalaidassa.
3. Pop-up siirtyy "Tapahtumat"-välilehdelle, tapahtuma jää "Odottaa"-tilaan.
4. Tietueen importin tulisi näkyä KohaSuomiService-raportilla.
7.  Sieltä sen tulisi aikanaan siirtyä joko onnistuneisiin tai feilanneisiin (tämä on vielä selvittelyn alla)

**Comment by ajrajala** [comment]
Tietueen aktivoinnin on testattu toimivan, mutta Vie/Tuo -testaus tyssäsi siihen, että näkyviin tulee pelkästään oman tietueen tiedot vaikka täti-nextiltä on tarkistettu että tietue sieltä löytyy:
![kuva](https://user-images.githubusercontent.com/44638512/235142513-51d0be5e-d279-42f4-9674-25ec5077cea1.png)

Broadcast biblios -pluginin asetuksiin on muutettu osoitteeksi tati-next, mutta onko vielä joku asetus mitä en tajunnut muuttaa? Vertasin tuotannon asetuksiin ja ovat samat tuota host-osoitetta lukuunottamatta:

![kuva](https://user-images.githubusercontent.com/44638512/235143665-cf7fdb31-2b31-466c-a177-d7f94d96e241.png)

**Comment by emta001** [comment]
@ajrajala Tuossa käy luultavasti niin, että vastaavaa tietuetta ei löydy Täti-nextiltä ja siksi näkyy vain paikalliset tiedot. Outilla auttoi se, että asetukseen vaihtoi molempiin osoitteisiin Täti-testin osoitteen. 

Pitää yrittää vielä kalastaa jostain tietue, joka on sekä täti-nextillä että jonkin kimpan nextillä ja kokeilla sillä näkyykö nappi sitten.

**Comment by ajrajala** [comment]
Joo, nyt kun muutin molempiin osoitteisiin tati-test.koha-suomi.fi niin näkyy sekä paikalliset että TäTin tiedot.

**Comment by ajrajala** [comment]
Laitan tähän vielä tiedoksi tietueen, jolle ei tullut näkyville TäTin tietoja silloin kun Broadcast biblios -plugarin asetuksissa osoitteena oli tati-next.koha-suomi.fi:

https://vaski-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=4281093

Sama tietue löytyy täti-nextiltä ja täti-testiltä:
https://tati-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2343591
https://tati-test.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2322753

**Comment by emta001** [comment]
> Laitan tähän vielä tiedoksi tietueen, jolle ei tullut näkyville TäTin tietoja silloin kun Broadcast biblios -plugarin asetuksissa osoitteena oli tati-next.koha-suomi.fi:
> 
> https://vaski-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=4281093
> 
> Sama tietue löytyy täti-nextiltä ja täti-testiltä: https://tati-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2343591 https://tati-test.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2322753

Hmm, jossain vaiheessa epäiltiin että nuo yhdistyis esim. 020$a-kentän avulla. Mutta tuossa täti-testillä olevassa tietueessakin ISBN on väliviivallinen kuten nextillä. Eli joko siellä on toinen kenttä, joka yhdistää ne tai sitten nextillä on jotain höps.

**Comment by emta001** [comment]
@ajrajala testailen tätä vaski-nextillä, niin siellä saattaa broadcast-urlit vaihtua lennosta ja näkyä muutakin hassua

**Comment by emta001** [comment]
@ajrajala nyt pitäisi pelittää, kehtaatko testailla jossain vaiheessa?

**Comment by emta001** [comment]
Näyttäisi sille, että yhteys nextien ja Täti-nextin välillä toimii, mutta tietueen tuominen luo tatinext_biblioservicen exporter-tauluun virheellisen rivin, joka taasen kaataa palvelut. Otin palvelut nyt kokonaan pois päältä, tutkaillaan mikä tuossa voisi mättää ja laitetaan palvelut päälle kunhan testailu taas onnistuu.

**Comment by ajrajala** [comment]
Juuri tänään ehdin pyytää meidän kuvailijaa testaamaan, laitan vielä tähän tiedoksi sen mitä oli onnistuttu testaamaan:

- Vie/tuo -nappulaa klikkaamalla molempien tietueiden tiedot tulivat näkyviin ja onnistui valita ”tuo”, mutta tosiaan tietojen siirto ei edennyt loppuun asti (näkyivät jonkin aikaa raportin ”Odottavat” -välilehdellä, sitten keskeytyneissä).
- Siirtoraportin toiminta oli ok, lukuun ottamatta sitä ettei ”Onnistuneet” -välilehden toimintoja ole vielä pystynyt testaamaan. Tätin tietuenumero johtaa väärään tietueeseen Tätissä, mutta näyttää johtuvan siitä että numero on testi-Tätin tietueen ja linkki johtaa Täti-tuotantoon.

**Comment by emta001** [comment]
Vaikuttaisi sille, että testeillä tietueen tuonti Tätistä toimii kuten pitää. Valitettavasti testillä valutus on käynnissä vain OUTIssa, joten testaaminen onnistuu vain sitä kautta.

**Comment by AnttHeik** [comment]
Pystyykö Melindaan vientiäkin jo testaamaan TäTissä?

**Comment by emta001** [comment]
> Pystyykö Melindaan vientiäkin jo testaamaan TäTissä?

Hmm, ainakin vienti-nappi näkyy olevan paikallaan. Periaatteessahan, jos viennin testaus on onnistunut testillä aiemmin, niin kyllä sen pitäisi olla testattavana nytkin.

**Comment by AnttHeik** [comment]
Joo, näyttää onnistuvan Melindaan vienti.

**Comment by AnttHeik** [comment]
Sellainen ongelma on kuitenkin, että sekä TäTi että Outi näyttää osakohteet aakkosjärjestyksessä eikä tietuenumerojärjestyksessä. Saisiko sen korjattua, koska sekoittaa? :)

**Comment by AnttHeik** [comment]
Paitsi että OUTIssa järjestys muuttui valutuksen (Melinda-Täti-OUTI) seurauksena oikeaksi :D Pitää testata vielä lisää.

**Comment by AnttHeik** [comment]
No niin eli Testi-TäTissä on nyt sellainen ongelma, että siellä osakohteet näytetään aakkosjärjestyksessä eikä tietuenumerojärjestyksessä. Tästä seuraa sitten se ongelma, että kun tietueen tuo OUTIin, niin osakohteet tallentuvat jostain syystä tuossa aakkosjärjestyksessä OUTIin eikä niiden tietuenumerojärjestyksessä, joka olisi se oikea järjestys. TäTi: 2322766 ja OUTI: 2261811. 

Lisäksi OUTIssa näyttää olevan epäsynkka 999c ja d-kentissä uusilla tietueilla, kuten tuo 2261811 tai sitten tämä: 2261810
![kuva](https://github.com/KohaSuomi/Koha-22x/assets/116169663/8d0a16ba-736a-4156-8e77-6b22ee674e8a)

Muuten tietueiden valutus toimii sekä Vie/Tuo-napilla että automaattisesti.

**Comment by emta001** [comment]
> No niin eli Testi-TäTissä on nyt sellainen ongelma, että siellä osakohteet näytetään aakkosjärjestyksessä eikä tietuenumerojärjestyksessä. Tästä seuraa sitten se ongelma, että kun tietueen tuo OUTIin, niin osakohteet tallentuvat jostain syystä tuossa aakkosjärjestyksessä OUTIin eikä niiden tietuenumerojärjestyksessä, joka olisi se oikea järjestys. TäTi: 2322766 ja OUTI: 2261811.
> 
> Lisäksi OUTIssa näyttää olevan epäsynkka 999c ja d-kentissä uusilla tietueilla, kuten tuo 2261811 tai sitten tämä: 2261810 ![kuva](https://user-images.githubusercontent.com/116169663/237621514-8d0a16ba-736a-4156-8e77-6b22ee674e8a.png)
> 
> Muuten tietueiden valutus toimii sekä Vie/Tuo-napilla että automaattisesti.

Onko tuo siis aiemmin toiminut OK outi-testillä?

**Comment by AnneliO** [comment]
Kävin nyt muuttamassa täti-testillä  ShowComponentRecords -järjestelmäasetukseen, että tietueet järjestetään tietuenumeron mukaan. Onkohan sillä vaikutusta?

**Comment by emta001** [comment]
Siellä oli epäsynkkaa biblioitemnumbereiden ja biblionumbereiden välillä, kävin korjaamassa ne, niin auttoiko se tuohon 999c ja d ongelmaan?

ShowComponentRecords-asetuksen säätäminen täti-testillä laittoi ainakin siellä osakohteet oikeaan järjestykseen. Voisi kokeilla auttoiko se sitten tuohon asoakohteiden tuontiin.

**Comment by AnttHeik** [comment]
> Siellä oli epäsynkkaa biblioitemnumbereiden ja biblionumbereiden välillä, kävin korjaamassa ne, niin auttoiko se tuohon 999c ja d ongelmaan?
> 
> ShowComponentRecords-asetuksen säätäminen täti-testillä laittoi ainakin siellä osakohteet oikeaan järjestykseen. Voisi kokeilla auttoiko se sitten tuohon asoakohteiden tuontiin.

Jeps, nyt toimii niin kuin pitääkin. Molemmat viat korjaantui :)

**Comment by AnttHeik** [comment]
Miksiköhän tuo Vie-nappi näyttää valkealta minulla?

![kuva](https://github.com/KohaSuomi/Koha-22x/assets/116169663/47fd0d0b-f4fe-432e-b4f9-8cdc999e47ed)

**Comment by AnneliO** [comment]
> Miksiköhän tuo Vie-nappi näyttää valkealta minulla?
> 
> ![kuva](https://user-images.githubusercontent.com/116169663/237642873-47fd0d0b-f4fe-432e-b4f9-8cdc999e47ed.png)

Siellä on nyt jokin värimääritys hupsis. Se muuttuu vihreäksi, kun sitä klikkaa esim. hiiren oikealla näppäimellä ja takaisin valkoiseksi, kun klikkaa napin ulkopuolella.

**Comment by emta001** [comment]
Pitää vielä hieman hienosäätää noita nappeja. Lisätään samalla aktivointi-napin viereen se "Aktivoitu"-tesksti.
