### ISSUE TITLE
Finnassa tekstiviestinumeron ja sähköpostiosoitteen päivitys epäonnistuu.

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#175]
### Mikä vikana?

Jos yrittää Finnassa päivittää Numero tekstiviesteille (smsalertnumber) tai sähköpostiosoitteen (email), tulee ilmoitus _Updating of patron information failed_.

![kuva](https://user-images.githubusercontent.com/33121325/234866096-11ad0812-efee-481f-a36d-84820396b6c1.png)

Nämähän pitäisi päivittyä ilman, että niistä lähtee päivityspyyntöä Kohaan. Testattu Vaaran Finna-nextillä.

### Mitä pitäisi tapahtua

Tekstiviestinumeron ja sähköpostin pitäisi pystyä muuttamaan Tallenna-painiketta painamalla.

### Kuinka toistaa ongelma/asia

1. Kirjaudu Finnaan ja mene omiin tietoihin.
2. Muutta Numero tekstiviesteille tai Sähköpostiosoite -kenttien tietoja ja paina Tallenna vähän alempaa.
3. Saa yläreunaan ilmoitus _Updating of patron information failed_.

### Jotain muuta?

Tämä muistaakseni toimi aiemmin.

### Asiasanat/tagit

finna
numero tekstiviesteille
sähköpostiosoite
tietojen päivitys

**Comment by lmstrand** [comment]
Minun asiakkaalta puuttui email, lisäys onnistui. Myös olemassaolevan matkapuhelinnumeron muuttaminen onnistui vaara-nextille Finnasta. En äkkiseltään keksi syytä. Onko muutettavalla asiakkaalla jo varaustunnus asiakasmääreessä?

Nämä tiedot saa mennä suoraan tietokantaan:
        'privacy' => 1,
        'sms_number' => 1,
        'email' => 1,
        'phone' => 1,

**Comment by AnneliO** [comment]
Asiakkaalla on ennestään sms-numero ja email. Myös varaustunnus on asiakasmääreessä.

https://vaara-next.koha-suomi.fi/cgi-bin/koha/members/moremember.pl?borrowernumber=11010256

**Comment by AnneliO** [comment]
Testailin lisää ja vertasin testiasiakkaani tietoja toiseen, jonka tietojen päivitys onnistui. Minun testitunnuksella oli superlibrarian-käyttäjäoikeus, jonka poistamalla päivitys rupesi toimimaan testiasiakkaallakin.
