### ISSUE TITLE
Hae ja varaa -toiminnossa hakutuloslistalla linkkivirhe

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#176]
### Mikä vikana?

Jos tekee varauksen niin, että valitsee asiakkaan tiedoissa Hae ja varaa, tekee haun ja vie sitten hakutuloslistalla hiiren _Varaa asiakkaalle xxxx_ -kohtaan, on linkki jakautunut kahtia. 

* Eka osio _Varaa asiakkaalle_ vie oikeaan paikkaan varaussivulle ja mukana on myös asiakastieto.
* Toka osio _asiakkaan nimi_ vie taas asiakastietoon

Tuossa kohdassa pitäisi kuitenkin olla vain yksi linkki, joka vie ekan osion mukaiseen paikkaan. Tässä näyttäisi olevan vähän samaa vikaa kuin perustiedot-näytön Varaa asiakkaalle -valikossa oli tiketissä #122 .

### Mitä pitäisi tapahtua

_Varaa asiakkaalle xxxx_ -kohdassa pitäisi olla vain yksi linkki, joka on muotoa https://vaara-next.koha-suomi.fi/cgi-bin/koha/reserve/request.pl?biblionumber=11687718&findborrower=kirjastokortinnumero

### Kuinka toistaa ongelma/asia

1. Mene jonkun asiakkaan tietoihin ja valitse _Hae ja varaa_.
2. Tee haku.
3. Mene jonkin teoksen kohdalle hakutuloslistassa ja vie hiiri _Varaa asiakkaalle xxxx_ -kohtaan.
4. Huomaa linkin jakaantuneen kahtia ja toisen vievän varauksen tekoon ja toisen asiakkaan tietoihin.

### Jotain muuta?

![kuva](https://user-images.githubusercontent.com/33121325/235679515-894e3737-b844-4791-8da6-954dd5965f5d.png)

### Asiasanat/tagit

hae ja varaa
varaaminen
varauksen tekeminen
linkki

**Comment by Kati-Helle** [comment]
Hellessä toimii hieman toisin:

- eka osiona oleva _Varaa_ vie oikein tietueen varauksiin mutta ilman asiakastietoa
- toka osiona oleva _asiakkaan nimi_ vie oikein tietueen varauksiin asiakastiedon kera

![kuva](https://user-images.githubusercontent.com/99952449/236435863-03bdfc1e-fbb2-43c0-88ed-06adcc5ae004.png)

**Comment by Kati-Helle** [comment]
Hellessä hakutuloslistalla avautuu tämä Varaa-painikkeesta
![kuva](https://user-images.githubusercontent.com/99952449/236436869-6ce3db72-c85f-4395-a1ad-b047f00a5d86.png)

Valitsen hakutuloslistaukselta teoksen (rasti ruutuun)
- Varaa-klikkaus vie varauksen tekoon ilman asiakastietoa
- Varaa asiakkaalle -klikkaus vie varauksen tekoon asiakastiedon kera
- asiakkaan nimen klikkaus vies asiakastietoon
- Unohda-klikkaus 'unohtaa'/poistaa asiakastiedon Varaa-painikkeesta

Tarkoititkohan Anneli tätä?

**Comment by AnneliO** [comment]
@Kati-Helle en tarkoittanut tuota vaan kuvauksessa olevan kuvan mukaista paikkaa ruudulla.

Mutta näköjään samanlainen vika on myös tuossa sinun huomaamassa paikassa.

**Comment by Kati-Helle** [comment]
Hellessä toimii samalla tavalla.
Tulipa testailtua ensin väärin hyvästä ohjeestasi huolimatta, Anneli :)

**Comment by Kati-Helle** [comment]
> @Kati-Helle en tarkoittanut tuota vaan kuvauksessa olevan kuvan mukaista paikkaa ruudulla.
> 
> Mutta näköjään samanlainen vika on myös tuossa sinun huomaamassa paikassa.

Poistin testauskommenttini... Lisään sen nyt kuitenkin vielä uudestaan
Hellessä hakutuloslistalla avautuu tämä Varaa-painikkeesta
![kuva](https://user-images.githubusercontent.com/99952449/236439268-6f06ec8b-5cf1-4c93-8b08-ba369e1e6008.png)
 
Valitsen hakutuloslistaukselta teoksen (rasti ruutuun)
•	Varaa-klikkaus vie varauksen tekoon ilman asiakastietoa
•	Varaa asiakkaalle -klikkaus vie varauksen tekoon asiakastiedon kera
•	asiakkaan nimen klikkaus vie asiakastietoon
•	Unohda-klikkaus 'unohtaa'/poistaa asiakastiedon Varaa-painikkeesta

**Comment by emta001** [comment]
Tuota noin, eihän tuo kyseinen "Varaa asiakkaalle ...."-linkki edes toimi :D Tulee vain pop-up, jossa lukee "Nothing is selected". Ja samoin käy yhteisössä. Tuolla on näemmä tyhjä a href molemmissa versioissa, pitänee tehdä yhteisöön tiketti, korjata sinne ja tuoda meille.

**Comment by emta001** [comment]
Tai oikeastaan, korjaan tuon jakautuneen linkin erikseen, tehdään sitten uusi tiketti tuosta toisesta ongelmasta :D

**Comment by emta001** [comment]
> Tuota noin, eihän tuo kyseinen "Varaa asiakkaalle ...."-linkki edes toimi :D Tulee vain pop-up, jossa lukee "Nothing is selected". Ja samoin käy yhteisössä. Tuolla on näemmä tyhjä a href molemmissa versioissa, pitänee tehdä yhteisöön tiketti, korjata sinne ja tuoda meille.

Ei tässä ollutkaan mitään virhettä, mie en vaan ymmärtänyt kuinka tuo ominaisuus toimii :D

**Comment by emta001** [comment]
Korjaus tuotu nexteille.

**Comment by AnneliO** [comment]
Testasin vaara-nextillä ja kummassakin rikkinäisessä kohdassa on nyt toimivat, yhtenäiset linkit. :)

**Comment by Kati-Helle** [comment]
Testasin Hellessä. Annelin ilmoittama linkkivirhe on nyt korjaantunut (eikä enää kahtena kappaleena).
Varauksen teko toimii kuten pitää. Varaa asiakkaalle -linkkin vie tietueen varaukseen asiakastiedon kera.

![kuva](https://github.com/KohaSuomi/Koha-22x/assets/99952449/67ef7eec-fc6e-489a-803c-e59132729498)

Ilmoittamani Hakutuloksen Varaa-kohta toimii myös oikein. Hakutuloksesta valittuna yksi tietue ja
- Varaa-painike vie valitun tietueen varaukseen ilman asiakastietoa
- Varaa asiakkaalle... -painike vie tietueen varaukseen asiakastiedon kera
- Unohda-painikkeella asiakastieto poistuu Varaa-painikkeesta

![kuva](https://github.com/KohaSuomi/Koha-22x/assets/99952449/2c1b8315-afa8-4f7b-a7f5-2eb9f5f4d825)

**Comment by AnneliO** [comment]
Testattu toimivaksi, joten suljen tiketin. :)
