### ISSUE TITLE
Jo olemassa olevan asiakastiedon muokkauksessa virheilmoitus hävitti asiakastietoon tallennettuja tietoja

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-22x#177]
### Mikä vikana?

Jo rekisteriin tallennetun Lapsi-asiakkaan muokkausnäytön avatessa Koha ilmoitti 'Seuraavat tiedot ovat väärin. Korjaa tiedot. A guarantor cannot be a guarantee.' Erikoisuutena se, että Asiakkaan muokkausnäytöllä ei ollut/näkynyt asiakastietoon tallennettuja tietoja: Sukunimi, Etunimi, Syntymäaika, Varaustunnus, Korttinumero
![kuva](https://user-images.githubusercontent.com/99952449/235867979-9e9ca193-24ba-45a9-a45e-43164b4cf811.png)

Asiakkaan Tiedot-välilehden tietoja
![kuva](https://user-images.githubusercontent.com/99952449/235868807-b1ee35da-1661-4abe-9cd1-0946bd3220de.png)

Kyseessä on asiakastieto, jolle lisäsin aikoinaan takaajaksi Huollettava aikuinen -asiakastyyppisen asiakastiedon. (Tämä ei ole enää mahdollista.)

Voisiko vastaavaa tapahtua johonkin muuhun asiakastiedon muokkauksen virheilmoitukseen liittyen?

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 4.5.2023: Emme äkkiseltään keksi, milloin voisi näin tapahtua. Voitko Kati testata erilaisia tilanteita?

**Comment by Kati-Helle** [comment]
EN saanut vastaavaa aikaan ainakaan näissä 'virhe-testaustavoissani' asiakkaan muokkauksessa Tallenna-painikkeen klikkauksen jälkeen
- lisään uudelle tai olemassa olevalle asiakastiedolle jo olemassa olevan varaustunnuksen
- lisään asiakastiedon ilman pakollisen kentän arvoa
- lisään Lapsi-tyypin asiakastiedon syntymäaika-arvolla, joka ei kuulu lapsi-asiakastyypin ikähaarukkaan
- lisään asiakkaalle Lapsi-asiakastyyppisen takaajan
- Lapsi-asiakastieto ilman takaajatietoa

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 11.5.2023: Ongelma ei näytä kovin todennäköiseltä, joten suljetaan tiketti. Avataan uudelleen, jos tulee tarvetta.
