### ISSUE TITLE
Niteen muokkaus: niteen viivakoodin lisäys ei onnistu Viivakoodi-kentän pisteitä klikkaamalla

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-22x#178]
### Mikä vikana?

Niteen muokkauksessa niteen Viivakoodi-kenttään ei muodostu arvoa, kun klikkaa kentän vieressä olevia kolmea pistettä.

Kenttä ennen kolmen pisteen klikkausta
![kuva](https://user-images.githubusercontent.com/99952449/236130806-19299d8c-6610-44fc-88a3-ef1a3e7413e3.png)

Kenttä kolmen pisteen klikkauksen jälkeen (muodostunut uusi kolme pistettä -rivi kentän viereen)
![kuva](https://user-images.githubusercontent.com/99952449/236130933-ffb1da5e-e6bb-46e8-9b6c-0beb1d564634.png)

**Comment by AnneliO** [comment]
Viivakoodin generoinnin pitäisi toimia nyt.

**Comment by Kati-Helle** [comment]
Hyvin toimii :)
