### ISSUE TITLE
Asiakastiedon saa tallennettua ilman Syntymäaika-kentän arvoa

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-22x#179]
### Mikä vikana?

Asiakastiedoissa Syntymäaika-kenttä on pakollinen kenttä. Pakollisuudesta huolimatta asiakastiedon tallennus onnistuu ilman Syntymäaika-kentän arvoa.

Aikuinen-tyypin asiakastiedon muokkausnäkymää Tallenna-klikkauksen jälkeen, kun asiakastiedosta puuttuu pakolliset kentät Sukunimi Ja Syntymäaika
![kuva](https://user-images.githubusercontent.com/99952449/236181355-32674b83-f6b8-406a-bc51-527d5151c52c.png)

Asiakastieto tallentuu, kun lisää Sukunimi-kenttään arvon. Asiakkaan Tiedot-välilehtinäkymää
![kuva](https://user-images.githubusercontent.com/99952449/236182745-c8289301-9414-443f-abaa-46b36f56df5b.png)

Nykyversio toimii Tallenna-painikkeen klikkauksen jälkeen näin, kun Syntymäaika-kenttä on arvoton. Tallennus ei onnistu ilman Syntymäaika-kenttäarvoa.
![kuva](https://user-images.githubusercontent.com/99952449/236180616-50665f61-1089-4378-a3b6-625b3333e39a.png)

**Comment by AnneliO** [comment]
Kentän pakollisuuden toimimattomuus ei johdu ainakaan IntranetUserJS-säädöistä. Testasin ottamalla kaikki pois.

**Comment by AnneliO** [comment]
Syy ei ole myöskään IntranetUserCSS-säädöissä.

Testasin tätä myös Biblibren sandboxissa asettamalla BorrowerMandatoryField-asetukseen dateofbirthin pakolliseksi. Sielläkään ei toiminut pakollisuuden tarkistus eli asiakastiedon sai pakollisuudesta huolimatta tallennettua ilman syntymäaikaa.

**Comment by emta001** [comment]
Tämä toistuu myös yhteisössä. Tein sinne tiketin [33684](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=33684).

**Comment by AnneliO** [comment]
Odotetaan, josko yhteisöstä saataisiin korjaus tähän.

**Comment by emta001** [comment]
Yhteisöön on tehty korjaus, tuon sen meillekin samantien.

**Comment by emta001** [comment]
Korjaus tuotu nexteille.

**Comment by AnneliO** [comment]
Vaara-nextillä toimi, kun tein asiakkaan lisäsysnäytöllä ensin ctrl+f5:lla päivityksen. Asiakkaan tallentaminen syntymäajan kanssa toimi. Testasin aikuis- ja lapsiasiakkailla. Toimi sekä asiakasta lisätessä että muokatessa.

**Comment by Kati-Helle** [comment]
Hellessä testatessani toimi myös. Kun tallentaa asiakastiedon ilman syntymäaika-kentän arvoa, ei asiakastieto tallennu vaan tulee tämä näkymä
![kuva](https://user-images.githubusercontent.com/99952449/237062809-c8692e0e-183f-4891-9bd7-86336625f893.png)

**Comment by velimarj** [comment]
Myös OUTIssa toimi kuten pitääkin.

**Comment by AnneliO** [comment]
Tähän tuli kolme testausta, joten suljen tiketin. :)
