### ISSUE TITLE
Kimpan logot näkyviin - ksdev/ks-0050-KD-5477

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#18]
### Siirrettävä ominaisuus

Kimpan logot näkyviin.

**Comment by lmstrand** [comment]
Viety branchiin ksdev/ks-0050-K22-18.

**Comment by Kati-Helle** [comment]
Hellessä näkyvillä, esim. etusivulla näin
![kuva](https://user-images.githubusercontent.com/99952449/224309220-7aaaacbe-a251-4b83-9013-71cf42fef4b0.png)

Vasemmassa yläkulmassa Koha-logo (logo-klikkaus vie Kohan etusivulle)
![kuva](https://user-images.githubusercontent.com/99952449/224309416-5d9c2e65-8cf7-483e-8295-6f6ce63900db.png)

Helle-Kohassa logot näin 
![kuva](https://user-images.githubusercontent.com/99952449/224310063-140da5cf-2542-49d4-a3da-aa75d7bcb606.png)

**Comment by lmstrand** [comment]
Jos kimpoilla löytyy kimppojen logot, joissa pääväri on valkoinen niin ne voisi lisätä uutta Kohaa varten noihin logovaihtoehtoihin. Vielä parempi olisi, jos olisi saatavilla .svg-tiedosto tällaisesta negatiivi-kuvasta (valkoista mustan sijaan).
Mustalla olevat logot eivät erotu palkin taustasta sillä kohdin, mihin logo olisi tarkoitus lisätä.

![image](https://user-images.githubusercontent.com/18394834/224324343-815690e2-d97c-4b0e-9248-65735ea8ad93.png)


Vaaran osalta kyselin jo, ja heillä kuulemma sellainen versio logosta löytyy.
Kerätään kaikilta kimpoilta talteen, joilta valkoinen versio logosta löytyy (ja haluavat sen näkyviin vihreän Koha-logon sijaan) ja lisätään palvelimelle yhdellä kertaa.

**Comment by ReettaSiili** [comment]
Siilissä kirjastolla ei ole omaa logoa, mutta käytetään kunnan. Löytyy ihan virallisena valkoisena, tässä vaan yksi kuvakaappaus.

![Image](https://user-images.githubusercontent.com/98806001/225613652-095bb9f0-a493-45d4-9c30-f4babd61e8fb.png)

**Comment by Kati-Helle** [comment]
Helle: logo-kuva on lähetetty Larille tänään 16.3.2023.

**Comment by pknuuti** [comment]
Toimisiko tämä Vaaran logo?
![logo-valk-transparent](https://user-images.githubusercontent.com/73887264/228173436-a07e1fdd-afad-439a-8bb9-9c6120f583be.png)

Näyttää siis pelkältä tyhjältä valkoisella pohjalla, kun logo on transparent valkoinen

**Comment by HeliAuranen** [comment]
![LummeKirjastot-logo_nelivari_web](https://user-images.githubusercontent.com/99177039/228187163-a837cf54-a48f-4db4-a52f-e3d4b1cbc32f.jpg)

**Comment by Kati-Helle** [comment]
Kiitos! Hellessä logo näkyy vasemmassa yläkulmassa
![kuva](https://user-images.githubusercontent.com/99952449/228506076-d77013ec-fd4f-4ca8-a7d9-fffd95f4ea35.png)

**Comment by pirliis** [comment]
Saisiko tätä logoa näkymään OUTIn nextille?


![Image](https://user-images.githubusercontent.com/98814860/228767444-01257f80-928f-4988-96ce-d3102a245181.svg)

**Comment by rakkyllo** [comment]
Tässä Vaskin valkoinen naakka. PNG-muotoinen tällä erää, voin kyllä vielä kysellä svg:n perään jos on tarvis. Kiitos!

![Vaski logo v ri vaaka su-ru-eng valkoinen naakka](https://user-images.githubusercontent.com/103504452/230079733-dac82b70-9339-405a-a0c6-484e879460e5.png)

**Comment by LeenaKinnunen** [comment]
![LAPINKIRJASTO_LOGO-saamet_PNG_lapinakyva](https://user-images.githubusercontent.com/99165331/231070541-494ced41-be4d-47f6-9755-23079ed2c2fa.png)

**Comment by lmstrand** [comment]
Uudet logot lisätty nexteille saataville. Tiedostonimet löytyvät tästä commitista:
https://github.com/KohaSuomi/Koha-22x/commit/c55dbc5f6b4a721361bc42529e6aa7865d31cee6

**Comment by LeenaKinnunen** [comment]
Laitetaanko nämä itse näkyville jotenkin?

**Comment by lmstrand** [comment]
Tässä on Vaskin nextistä kopioidut rimpsut intranetuserCSS-järjestelmäasetukseen:

```
/* Yläkulman logon pienennys sopimaan yläpalkin tilaan. Toimii 6.3.2023 MLI */
#logo.navbar-brand:after {
  background-image: url(/koha-suomi-images/vaski-images/vaski-logo-transparent-white.png);
  background-size: 103px 30px;  
  display: block;
  width: 103px; 
  height: 30px;
  content:"";
}

/* Yläkulman Koha-logon piilotus */
.navbar-brand > img {
    display:none;
}
```
Nuo molemmat tarvitaan. Tuo url-polku pitää korvata oman logon sijainnilla/tiedostonimellä (Lapilla /koha-suomi-images/lappi-images/lapinkirjasto.png). Tuon logon sijaintia/kokoa saattaa joutua säätämään Vaskin arvoista. Vaaran nextillä ainakin oli sellainen tilanne, eikä logo asettunut ilman muutoksia paikalleen nätisti. Voidaan säätää yhdessä tarvittaessa.

**Comment by LeenaKinnunen** [comment]
Lapissa ei asetu paikalleen, kokeilin muuttaa kokoa, mutta yläpalkin korkeus ei näytä riittävän.

**Comment by AnneliO** [comment]
Tällä rimpsulla saa säädettyä yläpalkin korkeutta:

```
/* Musta yläpalkki leveämmäksi */
.navbar {
  height: 45px;
}
```

**Comment by AnneliO** [comment]
Lisäsin rimpsut [IntranetUserCSS-sivulle vapaaehtoisiin](https://github.com/KohaSuomi/Koha-22x/wiki/IntranetUserCSS#vapaaehtoiset).

**Comment by lmstrand** [comment]
Minä voin käydä kokeilemassa, josko saisin logon jotenkin asettumaan. Outi-nextillä oli näköjään kasvatettu palkin kokoa. Sekin voisi olla vaihtoehto. Ei muutenkaan niin ahtaan näköinen tuo yläpalkki.
![image](https://user-images.githubusercontent.com/18394834/231765346-883b623c-ab8a-4f84-b2f8-570a41ea1cd3.png)

**Comment by lmstrand** [comment]
Säädin hieman tuota Lapin logoa. Oliko yläpalkki tarkoitus jättää korkeammaksi? Asetin sen nyt sen korkeamman palkin mukaisesti. Vaalensin myös hieman palkin sävyä, jotta musta teksti erottuu paremmin. Mittasuhteet pitäisi olla ok.

**Comment by LeenaKinnunen** [comment]
Lapissa yläpalkki voi olla matalampikin, mutta minun tuo meidän logo ei toimi mustalla pohjalla. Minä katson, onko meillä jotain muuta versiota.

**Comment by LeenaKinnunen** [comment]
![Lapinkirjasto_logo_valkea](https://user-images.githubusercontent.com/99165331/234796254-f2adc27b-87c2-4a04-9dbf-c8052a1e4986.jpg)
 Saadaanko tämä logo meille, pitäisi olla nyt valkealla pohjalla?

**Comment by lmstrand** [comment]
Lisätty uusi Lapin valkotaustainen logo. Muutin nextille linkin tiedostoon ja säädin kuvan mittasuhteet oikeiksi. Tuota voisi harkita levitettäväksi koko mustan palkin korkuiseksi, ainakin voisi lisätä kuvan ympärille valkoisen reunuksen niin olisi siistimmän näköinen...

**Comment by LeenaKinnunen** [comment]
> Lisätty uusi Lapin valkotaustainen logo. Muutin nextille linkin tiedostoon ja säädin kuvan mittasuhteet oikeiksi. Tuota voisi harkita levitettäväksi koko mustan palkin korkuiseksi, ainakin voisi lisätä kuvan ympärille valkoisen reunuksen niin olisi siistimmän näköinen...

Joo, voisi olla koko palkin korkuinen. Onko tuo kuva väärän kokoinen, ainakin minun näytöllä menee vähän suttuiseksi?

**Comment by lmstrand** [comment]
Säädin hieman lisää ja lisäsin valkoista reunusta. Nyt näyttää minun koneella siistiltä:
![image](https://user-images.githubusercontent.com/18394834/234861550-f3804559-d0fa-476a-baf6-6eb5463b76f8.png)

**Comment by LeenaKinnunen** [comment]
![logon_asettuminen_lappi](https://user-images.githubusercontent.com/99165331/234862322-b9b9141a-9d06-4263-8a39-b5f738b80e82.jpg)
Jos vielä vähän viitsit viilata, minulla sinne vasempaan jää 100% näytöllä parin millin musta palkki?

**Comment by lmstrand** [comment]
Ok katsellaan.

**Comment by LeenaKinnunen** [comment]
Teitkö jotain? Nyt näyttää hyvältä.

**Comment by lmstrand** [comment]
Joo lisäsin valkoista reunusta ympärille. Hyvä homma mennään tuolla.

**Comment by piiaseme** [comment]
Hei, OUTIn logo pitäisi vaihtaa. Tässä uusi logo:
![kuva](https://github.com/KohaSuomi/Koha-22x/assets/98805552/e024ab33-c4d2-4425-8421-6d9b2d017a90)

**Comment by pknuuti** [comment]
Vaaran logo suoraan mustalla pohjalla.

**Comment by pknuuti** [comment]
![Image](https://github.com/KohaSuomi/Koha-22x/assets/73887264/fae02105-1c39-412f-9b2c-189d1fff3513)

**Comment by pirliis** [comment]
> Hei, OUTIn logo pitäisi vaihtaa. Tässä uusi logo: ![kuva](https://user-images.githubusercontent.com/98805552/237655742-e024ab33-c4d2-4425-8421-6d9b2d017a90.png)

Tämä OUTIn uusi logo on varmaan unohtunut vaihtaa. :)

**Comment by lmstrand** [comment]
Se löytyy palvelimelta nimellä koha-tmpl/koha-suomi-images/outi-images/outikirjastot_wb.png (https://github.com/KohaSuomi/Koha-22x/commit/47cee9813b124f3c27032ac8b5592c175bc22522) mutta on tosiaan ainakin tuotannosta jäänyt päivittämättä. Sama koskee Vaaran saman commitin .png -tiedostoa. Tiedostot menevät palvelimelle seuraavan tuotantopäivityksen yhteydessä.

**Comment by velimarj** [comment]
Jos oikein kyylään, niin tuo .png vissiin on nyt meillä OUTI-testillä? Siellä kuitenkin näkyy pelkkää mustaa.

**Comment by lmstrand** [comment]
> Jos oikein kyylään, niin tuo .png vissiin on nyt meillä OUTI-testillä? Siellä kuitenkin näkyy pelkkää mustaa.

Nyt pitäisi olla testillä kyydissä.

**Comment by velimarj** [comment]
> > Jos oikein kyylään, niin tuo .png vissiin on nyt meillä OUTI-testillä? Siellä kuitenkin näkyy pelkkää mustaa.
> 
> Nyt pitäisi olla testillä kyydissä.

Sinnehän se putkahti, kiitokset!

**Comment by pirliis** [comment]
OUTIssa uusi logo tuotannossa.

**Comment by AnneliO** [comment]
Suljen tiketin näiltä osin. :)
