### ISSUE TITLE
Jos noudettavissa olevan varauksen palauttaa varausjonoon, viimeistä voimassaolopäivää ei saa muutettua

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#181]
### Mikä vikana?

Jos noudettavissa olevan varauksen palauttaa takaisin varausjonoon joko varaukset-sivulla peruuttamalla odottava-tilan tai lainaamalla niteen toiselle ja valitsemalla _Peruuta odottava-tila_, tyhjenee viimeinen voimassaolopäivä, eikä siihen saa sen jälkeen tallennettua uutta päivämäärää.

Jos päivämääräkenttää klikkaa, saa kyllä esille kalenterin, josta päivämäärän saa valittua, mutta kun päivämäärän on valinnut, vilahtaa se vain nopeasti kentässä ja kenttä tyhjenee.

### Mitä pitäisi tapahtua

Viimeisen voimassaolopäivämäärän pitäisi saada vaihdettua.

### Kuinka toistaa ongelma/asia

1. Tee varaus ja palauta nide, joka jää siihen kiinni.
2. Mene tietueen varaukset-sivulle ja peruuta odottava-tila.
3. Huomaa, että viimeinen voimassaolopäivä on tyhjä ja yritä valita siihen jokin päivämäärä kalenterista ja kirjoittamalla se käsin.
4. Päivämääräkenttä tyhjenee.

### Asiasanat/tagit

viimeinen voimassolopäivämäärä
voimassaolopäivä
päivämäärä
kalenteri
varaus
varauksen voimassaolo
noudettavissa oleva varaus

**Comment by AnneliO** [comment]
Sama ongelma toistuu myös, jos varaukselta poistaa kuljetettavana-tilan teoksen varaukset-sivulla.

**Comment by Kati-Helle** [comment]
Annelin mainitsema tapahtui myös Hellessä, kun peruutin tärpänneen varauksen varattu-tilan tietueen varauksissa.
Viimeinen voimassaolopäivä -kentän arvon lisääminen ei onnistunut. Kenttä 'välähti' päiväyksen valintayrityksellä.

Tuon jälkeen päivitin Tietueen varaukset -sivun, josta Virhe 500 -ilmoitus
![kuva](https://user-images.githubusercontent.com/99952449/236759180-56f59cdb-f698-45bf-a50e-849c95c7d0d8.png)

Palasin takaisin tietueen varauksiin ja näkymänä: varaus tärpännyt ja noudettava-tilainen ('lähtötilanne')
Tietueen varaukset -sivun päivitys: varaus voimassa-tilainen

**Comment by emta001** [comment]
Onnistuin myös saamaan aikaan tuon 500 virheen. Lokiin tuli 

`Can't call method "biblionumber" on an undefined value at /home/emmi/Koha-22x/C4/Reserves.pm line 2165.`

mikä äkkiseltään ajateltuna voisi johtua siitä, että sivua päivittäessä biblionumber parametri häviää.

Mutta tuota kalenterin "välähdystä" en saa toistettua. Kalenteri jää kyllä näkyviin, voin valita päivämäärän ja hetken kuluttua sivu päivittää itsensä. Mutta valittu päivämäärä ei tallennu. Tämä ei onnistu myöskään "Update holds"-painiketta painamalla. Eikä tämä koske myöskään vaan näitä varauksia, joissa kuljetustila on peruttu, vaan kaikkia varauksia.

**Comment by emta001** [comment]
Testeillä toimii, eli jokin nexteillä on muuttunut niin, että sivu menee rikki.

**Comment by emta001** [comment]
Johtui siis siitä, että 0014-branchin tuomisessa oli käynyt pienoinen fiba. Sinne oli päätynyt patchi, jossa voimassaolopäivän tallennuksen yhteydessä käytettiin ModReserves metodia, kun oikeasti tallennus on tehtävä $hold->set->storella. Nyt tämä on korjattu ja tuotu nexteille. Säädin samalla varauksien API kutsua niin, että holddate ja expirationdate lähetetään JSON-muodossa.

**Comment by AnneliO** [comment]
Jee! Tämä tuntuisi toimivan nyt oikein ainakin vaara-nextillä.

**Comment by ajrajala** [comment]
Testasin myös vaski-nextillä sekä varausjonon että lainauksen kautta perumalla. Nyt kenttä tyhjenee ja siihen pystyy sen jälkeen asettamaan uuden vanhenemispäivän.

**Comment by Kati-Helle** [comment]
Hienosti toimii Hellessäkin :)

**Comment by emta001** [comment]
Toiminee siis, suljen tiketin.
