### ISSUE TITLE
Tietueen Varaukset -toimintoon käännösmuutos liittyen hakukentän haettaviin hakuarvoihin

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-22x#185]
### Mikä vikana?

Tietueen varaukset -toimintoon olisi tarpeellista saada tarkempi tieto arvoista, joilla asiakastiedon voi hakea.

![kuva](https://github.com/KohaSuomi/Koha-22x/assets/99952449/ffa1d0d2-f303-4706-a467-402baaef75cf)

Koha-Suomen pääkäyttäjäpalaverin 18.4.2023 muistiossa
https://github.com/KohaSuomi/kohasuomi.github.io/blob/master/_pages/paakayttajat2023.md#viikko-16-muistio

Käännösmuutos varauksenteko-sivulle?

    Varauksenteko-sivulta on piilotettu asiakashaun hakutulostaulukko, mistä johtuen asiakkaan hakeminen onnistuu käytännössä vain kirjastokortilla tai koko nimellä niin, että tuloksena on yksi ainoa vastaus. Hakukentän yläpuolella on kuitenkin ohje "Syötä kirjastokortin numero tai osa nimestä:" eli englanniksi "Enter patron card number or partial name:". On ehdotettu, että käännöstä muutettaisiin.
    Jos muutos tehdään, on se sellainen, mikä pitää ylläpitää Koha-Suomessa jokaisessa versionvaihdossa. Muita vastaavia muutoksia on esim. phone-kentän nimeäminen Lankapuhelimeksi ja mobile-kentä Matkapuhelimeksi (yhteissö primary phoe ja other phone). Koska muutostarve johtuu meidän omasta piilotuksesta (pyritään vähentämään asiakastietojen katseluja), ei ole perusteltua muuttaa yhteisön käännöstiedostoihin käännöstä.

Päätös: Kannatettiin ajatusta, että ohjeteksti olisi sen mukainen, kuin haku tulee tehdä eli ohjeistetaan, että asiakashaku tulee tehdä kirjastokortilla tai asiakkaan koko niemllä. Kehittäjät ehdottivat, että käännöstiedostojen ajojen jälkeen ajettaisiin aina automaattisesti skripti, joka muuttaisi kaikki Koha-Suomen omat ylläpidettävät käännösmuutokset halutuiksi. Kysytään vielä Annelin mielipidettä.

**Comment by AnneliO** [comment]
Muutos viety Koha-translations-repositorioon [22.xx-branchiin](https://github.com/KohaSuomi/Koha-translations/commit/8d6092ede648b814b7cf9d15deb7908c49e51a9a).

Käännös tulee näkyville, kun käännökset ajetaan seuraavan kerran.

**Comment by Kati-Helle** [comment]
Kiitos Anneli! Nyt näkyy

![kuva](https://github.com/KohaSuomi/Koha-22x/assets/99952449/41d3bda4-b52e-435f-a350-8b365f458f77)

**Comment by AnneliO** [comment]
Hyvä juttu! Suljetko tiketin, jos asia on valmis? :)
