### ISSUE TITLE
Asiakashaun syntymäaikahakuun ei enää kelpaa pvm muodossa pp.kk.vvvv

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha-22x#186]
### Mikä vikana?

Uudessa versiossa asiakashaku syntymäaika-kentällä näyttää vaativan päivämäärän muodossa vvvv-kk-pp. Aiemmin syntymähaku hyväksyi päivämäärän muodossa pp.kk.vvvv ja käyttöliittymässä ohjeistettiin käyttäjää päivämäärän kirjoittamisessa (kuva).

### Jotain muuta?

![kuva](https://github.com/KohaSuomi/Koha-22x/assets/44638512/0ea3bae1-c9e6-44bf-8a6b-9cd27c57dfa3)

**Comment by emta001** [comment]
Näyttäisi sille, ettei tämä toimi myöskään yhteisössä.

**Comment by emta001** [comment]
Toimiikin yhteisössä, mutta tuo vihje ei enää näy.

**Comment by emta001** [comment]
Tuotu testeille testattavaksi.

**Comment by Kati-Helle** [comment]
Toimii Helle-testissä :)

Jännästi haun ollessa vielä käynnissä tulee näkyville tämä teksti Vastaavia tietueita ei löytynyt
![kuva](https://github.com/KohaSuomi/Koha-22x/assets/99952449/720f7d63-c2eb-4d36-8712-1512eff2c075)

**Comment by emta001** [comment]
> Toimii Helle-testissä :)
> 
> Jännästi haun ollessa vielä käynnissä tulee näkyville tämä teksti Vastaavia tietueita ei löytynyt ![kuva](https://user-images.githubusercontent.com/99952449/238611868-720f7d63-c2eb-4d36-8712-1512eff2c075.png)

Olisiko käännöskukkanen?

**Comment by Kati-Helle** [comment]
Tämä näkyy
![kuva](https://github.com/KohaSuomi/Koha-22x/assets/99952449/40356038-d321-40be-9464-2b410054ebdd)

kun haen näin
![kuva](https://github.com/KohaSuomi/Koha-22x/assets/99952449/0718b6a1-bf29-4291-873e-6338bd458d90)

**Comment by AnneliO** [comment]
Tuo _Vastaavia tietueita ei löytynyt_ -teksti tulee datatables.js-tiedostosta, jota käytetään kaikissa taulukoissa, kun tuloksia ei ole. Se on englanniksi _No matching records found_.

_Taulukossa ei ole tietoja_ eli _No data available in table_ tulee samasta datatables.js:stä. 

Näköjään se ei aina tuo loogisempaa vaihtoehtoa näkyville.

**Comment by AnneliO** [comment]
Jos tuo on ongelma, teethän Kati siitä erillisen tiketin. :)

**Comment by ReettaSiili** [comment]
Syntymäaikahaku toimii myös Siilin testissä.

**Comment by sksandel** [comment]
Vaskin testissä toimii myös. 

On aika hidas, etenkin jos avaa suoraan asiakastietueen (vain yksi osuma). Tällöin näyttää ensin "käsitellään"-viestiä ja sen jälkeen hetken pelkkää "vastaavia tietueita ei löytynyt"-tyhjää hakutulosnäkymää. Tämän jälkeen aukeaa löytynyt asiakastietue. Harvinainen tilanne, mutta anonymisoidulla testillä tulee vastaan meillä esim 10.10.1950-syntymäajalla.

**Comment by emta001** [comment]
> Vaskin testissä toimii myös.
> 
> On aika hidas, etenkin jos avaa suoraan asiakastietueen (vain yksi osuma). Tällöin näyttää ensin "käsitellään"-viestiä ja sen jälkeen hetken pelkkää "vastaavia tietueita ei löytynyt"-tyhjää hakutulosnäkymää. Tämän jälkeen aukeaa löytynyt asiakastietue. Harvinainen tilanne, mutta anonymisoidulla testillä tulee vastaan meillä esim 10.10.1950-syntymäajalla.

Tuo on kyllä kieltämättä todella hidas. Käsittääkseni siihen on tehty jotain uudistuksia yhteisössä, tiedä sitten onko tällä asian kanssa tekemistä (en kyllä tarkemmin tutkinut mitä uudistuksia on tehty ja oliko ne mukana jo edellisessä versiossa).

**Comment by emta001** [comment]
Vaikuttaisi toimivan kuten pitää. Laitan tän odottelemaan tuotantoon seuraavaa buildia.

**Comment by AnneliO** [comment]
Tämä on nyt tuotannossa ja testieni mukaan toimiikin.

**Comment by sksandel** [comment]
Toimii myös Vaskissa.

**Comment by emta001** [comment]
Loistavaa, suljen tiketin tältä osin.
