### ISSUE TITLE
MEMBERSHIP_EXPIRY-viesti muodostuu myös sähköpostittomille asiakkaille - ksdev/ks-0051-KD-3357-membership_expiry_email

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#19]
### Siirrettävä ominaisuus

MEMBERSHIP_EXPIRY-viesti muodostuu myös sähköpostittomille asiakkaille. Muutettu niin, että viestit muodostuvat niille asiakkaille, joilla on sähköpostiosoite.

**Comment by Kaarius** [comment]
On viety nexteille testattavaksi.

**Comment by AnneliO** [comment]
Onhan tähän toimintoon liittyvä cron job käynnissä?

Asetin vaara-nextillä neljälle käyttäjätunnukselle viimeisen voimassaolopäivän 26.-29.5.2023 välille. Kolmella on sähköpostiosoite, eli heille pitäisi muodostua viesti. [Adoniikalta](https://vaara-next.koha-suomi.fi/cgi-bin/koha/circ/circulation.pl?borrowernumber=11010257) poistin osoitteen eli hälle ei pitäisi muodostua viestiä.

**Comment by ajrajala** [comment]
Asetin kahdelle testiasiakkaalle vanhenemispäivän 22.5. [Sähköpostilliselle asiakkaalle](https://vaski-next.koha-suomi.fi/cgi-bin/koha/members/notices.pl?borrowernumber=307898) muodostui vanhenemisilmoitus 22.4., ja [sähköpostittomalle](https://vaski-next.koha-suomi.fi/cgi-bin/koha/members/notices.pl?borrowernumber=328971) ilmoitusta ei muodostunut. Vaski-nextillä näyttäisi tämä siis olevan ok.

**Comment by emta001** [comment]
> Onhan tähän toimintoon liittyvä cron job käynnissä?
> 
> Asetin vaara-nextillä neljälle käyttäjätunnukselle viimeisen voimassaolopäivän 26.-29.5.2023 välille. Kolmella on sähköpostiosoite, eli heille pitäisi muodostua viesti. [Adoniikalta](https://vaara-next.koha-suomi.fi/cgi-bin/koha/circ/circulation.pl?borrowernumber=11010257) poistin osoitteen eli hälle ei pitäisi muodostua viestiä.

Ei ollut vaara-nextillä käynnissä, laitoin sen ajoon klo 9.15.

**Comment by AnneliO** [comment]
> > Onhan tähän toimintoon liittyvä cron job käynnissä?
> > Asetin vaara-nextillä neljälle käyttäjätunnukselle viimeisen voimassaolopäivän 26.-29.5.2023 välille. Kolmella on sähköpostiosoite, eli heille pitäisi muodostua viesti. [Adoniikalta](https://vaara-next.koha-suomi.fi/cgi-bin/koha/circ/circulation.pl?borrowernumber=11010257) poistin osoitteen eli hälle ei pitäisi muodostua viestiä.
> 
> Ei ollut vaara-nextillä käynnissä, laitoin sen ajoon klo 9.15.

Ok, laitan uudet testit.

**Comment by emta001** [comment]
> > > Onhan tähän toimintoon liittyvä cron job käynnissä?
> > > Asetin vaara-nextillä neljälle käyttäjätunnukselle viimeisen voimassaolopäivän 26.-29.5.2023 välille. Kolmella on sähköpostiosoite, eli heille pitäisi muodostua viesti. [Adoniikalta](https://vaara-next.koha-suomi.fi/cgi-bin/koha/circ/circulation.pl?borrowernumber=11010257) poistin osoitteen eli hälle ei pitäisi muodostua viestiä.
> > 
> > 
> > Ei ollut vaara-nextillä käynnissä, laitoin sen ajoon klo 9.15.
> 
> Ok, laitan uudet testit.

Mites tässä kävi?

**Comment by AnneliO** [comment]
> Mites tässä kävi?

Huonosti, en osaa laskea oikeaa päivää. :D

**Comment by AnneliO** [comment]
Muutin nyt  MembershipExpiryDaysNotice -järjestelmäasetukseen päiviksi 1 ja testiasiakkaille vanhentumispäiväksi 29.4.2023. Eli jos nyt osaan laskea oikein, niin huomenna pitäisi muodostua tai olla muodostumatta.

**Comment by AnneliO** [comment]
No niin, nyt testit onnistui. Viestiä ei lähtenyt asiakkaalle, jolla ei ollut sähköpostiosoitetta ja lähti sellaiselle, jolla on.

Suljen tiketin.
