### ISSUE TITLE
Hyllyvaraukset-raportti - ksdev/ks-0022-KD-4630

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#2]
### Siirrettävä ominaisuus

Hyllyvaraukset-raportista on tehty oma versio, koska yhteisön raportti on liian hidas ja raskas suomalaiseen varausmäärään nähden.

**Comment by lmstrand** [comment]
Branchissa ksdev/ks-0070-K22-2-pendingreserves.

Viety nexteille testattavaksi.

**Comment by pknuuti** [comment]
Pikaisella testauksella hyllyvarausraportti näyttää toimivalta ja hyvältä.

**Comment by Kati-Helle** [comment]
Vertasin Helle-tuotannon ja Nextin Hyllyvaraus-näkymää: piiloon määritellyt sarakkeet eivät piiloudu millään käyttöliittymäkielellä
![kuva](https://user-images.githubusercontent.com/99952449/229063190-5a214ae0-573b-496c-a9f0-ad018a09989e.png)

**Comment by Kati-Helle** [comment]
> Pikaisella testauksella hyllyvarausraportti näyttää toimivalta ja hyvältä.

Olen samaa mieltä, Päivi. Kirjastotunnusvärityskin paikallaan :)
![kuva](https://user-images.githubusercontent.com/99952449/229066127-2370ec53-6719-411c-a98a-a18f48d6610a.png)

**Comment by ajrajala** [comment]
Vertailin tuotannon hyllyvarausraporttiin ja testailin suodatuksia, järjestelemistä ym, en huomannut mitään virheitä/puutteita.

Lehtivarausten esittämistä hyllyvarausraportilla täytynee miettiä sitten, kun nideryhmien käyttöönotossa päästään eteenpäin. Nyt hyllyvarausraportti listaa mukaan tietueen kaikki numerot, jos tietueeseen on tehty nideryhmään kohdistuva varaus:

![kuva](https://user-images.githubusercontent.com/44638512/229067048-be38ca92-65c8-45db-9b98-47d5b3fa50aa.png)

**Comment by pirliis** [comment]
Sarakkeet-valintaa ei ole. Vai onko sitä tarkoituskaan olla enää tällä raportilla?


![Image](https://user-images.githubusercontent.com/98814860/229088445-e06cb901-a49a-413e-9451-8ecbe395ae10.png)

**Comment by Kati-Helle** [comment]
Hellessä Hyllyvaraukset-toiminnossa näkyvillä näytön oikealla: Määrittely (engl. Configure)
![kuva](https://user-images.githubusercontent.com/99952449/229090122-000fe378-508d-40e6-914f-ad9bf9b416e8.png)

**Comment by AnneliO** [comment]
Määrittely vie ylläpitoon, jossa voi asettaa oletusmääritykset, mutta Pirkko-Liisan kuvassa oleva valikko näkyy kaikille käyttäjille ja sillä voi käyttäjäkohtaisesti määrittää sarakkeiden näkyvyyttä.

**Comment by AnneliO** [comment]
Tuohon Määrittely-nappiin liittyen, se ei vie oikean taulun kohdalle https://vaara-next.koha-suomi.fi/cgi-bin/koha/admin/columns_settings.pl -sivulla. Eli sen pitäisi avata tuo kyseinen sivu Table id: kohasuomi-holds-to-pull -osion kohdalle.

**Comment by lmstrand** [comment]
Korjaus taulun määrittelyyn viety testattavaksi nexteille (englanninkielellä pitäisi toimia).

**Comment by Kati-Helle** [comment]
Helle-nextillä Holds to pull -toiminnon Configure-linkki vie oikeaan kohtaan eli tähän 
![kuva](https://user-images.githubusercontent.com/99952449/229982266-b30fb740-2bbc-48a2-894d-91e68c89ee98.png)

Sarakkeiden piilotusmäärittelyt toimivat
![kuva](https://user-images.githubusercontent.com/99952449/229985060-2104693e-e2e7-42db-8f74-f7d0b128a6ad.png)

**Comment by AnneliO** [comment]
Testasin myös sarakkeiden piilotusta ja määrittelyyn menemistä ja ne toimi nyt oikein.

**Comment by CodoDerDritte** [comment]
Lari on hoitanut tätä, joten siirrän tiketin hänelle.

**Comment by AnneliO** [comment]
Vieläkö tähän tulee testauksia vai voiko tiketin jo sulkea?

**Comment by ReettaSiili** [comment]
Siilissä toimii englanninkielisenä nähdäkseni myös ihan oikein.

**Comment by lmstrand** [comment]
Suljen tiketin. Next patron -ominaisuus luultavasti karsitaan versionvaihdon jälkeen. Siitä tehdään oma tiketti.
