### ISSUE TITLE
GetSuomiFiMessages - ksdev/ks-0054-KD-4624

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#20]
### Siirrettävä ominaisuus

KSMessaging, jolla hallinnoidaan viestien lähetystä mm. suomi.fi viesteihin ja ekirjepalveluihin.

**Comment by CodoDerDritte** [comment]
Feature branch sisältää yhteisön Letters.pm:stä puuttuvan GetSuomiFiMessagesin.
