### ISSUE TITLE
Finto-plugit - ksdev/ks-0070-KD-4590-Finto-value-builders

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#22]
### Siirrettävä ominaisuus

Finto-pluginit:

finto_finaf.pl
finto_seko.pl
finto_seko_nouri.noind.pl
finto_slm_local.pl
finto_yso-aika.pl
finto_yso-aika_ind2_7.pl
finto_yso-aika_noind.pl
finto-yso-kauno.pl
finto_yso-kauno_ind.pl
finto_yso-kauno_noind.pl
finto_yso-paikat.pl
finto_ysopaikat_noind.pl

**Comment by lmstrand** [comment]
Finto-pluginit toimivat ensimmäisessä kenttätoistumassa mutta toistetun kentän kohdalla plugin ei alustu "dynaamisen" Select2-elementin luonnin jälkeen MouseOver-funktiolla.

**Comment by lmstrand** [comment]
https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=30975

**Comment by lmstrand** [comment]
Yheisön patchit mahdollistavat pluginien alustamisen toistettujen kenttien kanssa, mutta entinen tapa alustaa pluginit (select2-elementit, joilla haku fintosta tehdään) viemällä hiiri tekstikentän (johon plugin on määritetty) päälle ei enää toimi. Patchien lisäämisen jälkeen pluginin voi alustaa viemällä hiiri tekstikentän oikeassa laidassa olevan "tag editor"-napin kohdalle ja painamalla sitä, jolloin hakulaatikkoon aktivoituu teksti "Etsi Fintosta" ja haun voi suorittaa.

Branchissa ksdev/ks-0097-K22-bug-30975-framework-plugins-cloned-subfield-fix on mukana myös mukana testausta varten plugin finto_yso-kauno.pl korvatulla click-funktiolla.

Tämä on nyt ainakin väliaikainen ratkaisu, jotta plugineja voi käyttää kun kenttä tarvitaan toistaa.

**Comment by lmstrand** [comment]
Yhteisön korjaus ja testiplugin testattavissa nexteillä.

**Comment by lmstrand** [comment]
Kuvailijoilta tullut tieto, että yhteisön patchi ei ole yhteensopiva joillakin selainversioilla? Versio 78.12.0esr (32-bittinen) kentän toistaminen on rikki patchien tuonnin jälkeen nextien (ainakin täti ja outi) kanssa.

**Comment by AnttHeik** [comment]
Lisään tuohon selainongelmaan vielä, että myöskin kiinteiden kenttien (000, 006, 007 ja 008) Kohan omat editorit lakkasivat toimimasta. Ja aiemmin kun esim. 005-kenttään sai arvon klikkaamalla sitä, niin sitäkään ei enää tapahtunut.

**Comment by AnttHeik** [comment]
Edgellä testattuna itse Finto-plugin toimii nyt myös kenttiä toistettassa.

**Comment by lmstrand** [comment]
Raportoin tuon selainongelman yhteisön tikettiin ja kysyin neuvoa miten pluginit saisi toimimaan kuten nykyisessä tuotannossa mouseover-funktion kanssa (jos se on enää järkevää toteuttaa uuden patchin kera vanhaan malliin koska 'mouseover' and 'mousemove' are not used and would trigger too much events).

**Comment by ajrajala** [comment]
Vaskin kuvailija testaili Finto-pluginia Täti-nextillä ja sai toimimaan kuten tiketissä oli kuvattuna. Firefoxin kanssa ei ilmennyt ongelmia, Turussa mennään tällä hetkellä versiolla 102.8.0esr (64-bittinen).

**Comment by lmstrand** [comment]
Plugineja varten nexteille tuodut patchit rikkovat viivakoodin generoinnin nidetietojen käsittelyssä. Patchit on poistettu nexteillä tällä hetkellä, joten toistuvien kenttien kanssa finto-plugin ei enää toimi. Mietitään jatkotoimenpiteitä.

**Comment by lmstrand** [comment]
Barcode.pl -viivakoodingenerointipluginiin lisätty korjaus, jotta se toimii toistuvat kentät korjaavien patchien kanssa tähän branchiin. Kysyin yhteisöstä neuvoa, miten saisin pluginit toimimaan kuten tuotannossa. Lisään muut finto-pluginit kunhan ratkeaa onnistuuko pluginien käyttö vanhaan tapaan ja onko se järkevää selaimen suorituskyvyn heikkenemisen takia.
Jos tästä patch-muutoksesta seuraa ongelmia muiden value builder-pluginien kanssa, niistä voi tehdä erillisen tiketin.

**Comment by lmstrand** [comment]
Ja tämä branchi viety takaisin nextille barcode-pluginin korjauksen kera.

**Comment by lmstrand** [comment]
Kaikki pluginit tuotu nexteille muokattuina versioina, joissa plugin alustetaan kolmesta pisteestä. Mukana myös finaf-plugin, jonka ei pitäisi toimia ainakaan toistuvien kenttien kohdalla. Finaf-pluginille tehty oma tiketti https://github.com/KohaSuomi/Koha-22x/issues/182.

**Comment by AnttHeik** [comment]
Muuten näyttäisi pluginit toimivan, mutta finaf-plugin antaa virhe 500 -ilmoituksen siinä vaiheessa, kun toiseen ikkunaan pitäisi avautua Asterin auktoriteettitietue tarkasteltavaksi. Ilmoitus tulee siis tuohon avautuvaan ikkunaan.

**Comment by lmstrand** [comment]
> Muuten näyttäisi pluginit toimivan, mutta finaf-plugin antaa virhe 500 -ilmoituksen siinä vaiheessa, kun toiseen ikkunaan pitäisi avautua Asterin auktoriteettitietue tarkasteltavaksi. Ilmoitus tulee siis tuohon avautuvaan ikkunaan.

Tuolta pluginilta puuttui template, kävin lisäämässä sen täti-nextille ja liittymä alkoi toimia mutta plugin ei vieläkään palauta dataa, selvittelen asiaa.

**Comment by AnttHeik** [comment]
Nyt kun testasin, niin auktoriteettitietue tulee näkyviin normaalisti toiseen ikkunaan ja sen voi poimia tietueeseen. Mutta kenttien toiston yhteydessä finaf ei tosiaan sitten enää toimi.

**Comment by lmstrand** [comment]
Niinpä toimiikin, en vaan tainnut osata käyttää pluginia testissäni oikein. Suljen tiketin. Kunhan saadaan testattua mousehoveria plugin-kenttien alustamiseen, avaan tiketin uudestaan.
