### ISSUE TITLE
Aineistotyyppi näkyviin asiakkaan lainoihin ja palautustoimintoon - ksdev/ks-0074-KD-G238

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#23]
### Siirrettävä ominaisuus

Aineistotyyppi näkyviin asiakkaan lainoihin ja palautustoimintoon.

**Comment by Kati-Helle** [comment]
Hellessä aineistotyyppi näkyy oikein asiakkaan lainoissa
![kuva](https://user-images.githubusercontent.com/99952449/224315251-a953650c-272b-49c4-b525-64893223c248.png)

Sen sijaan palautus-näytöllä aineistotyyppi ei näy vaan sarake on tyhjä
![kuva](https://user-images.githubusercontent.com/99952449/224315457-f3c208de-8b27-4af5-9447-681f1ae41c2f.png)

**Comment by pirliis** [comment]
Samoin OUTIssa.

**Comment by ghost** [comment]
Englanninkielisessä Kohassa näkyy aineistotyyppi myös palautuksissa. Todennäköisesti korjautuu kunhan käännökset ajetaan uusiksi.

**Comment by Kati-Helle** [comment]
Kiitos Lasse tiedosta. 
Kirja-aineistotyyppi näkyvillä englanninkielisen Helle-Kohan palautuksessa
![kuva](https://user-images.githubusercontent.com/99952449/226294263-3cf8acaa-5bb7-4086-a098-892f787b02b1.png)

**Comment by pknuuti** [comment]
Testasin Vaaran nextillä ja aineistotyyppi näkyy sekä lainoissa että palautusnäytöllä.

**Comment by ReettaSiili** [comment]
Samoin Siilissä, aineistotyyppi näkyy sekä lainoissa että palautuksessa, sekä suomeksi että enkuksi.

**Comment by pirliis** [comment]
OUTIssa samoin, aineistotyyppi näkyy sekä asiakkaan lainoissa että palautuksissa, sekä suomen- että englanninkieliseillä näytöillä.

**Comment by Kati-Helle** [comment]
Hellessä aineistotyyppi näkyy nyt oikein myös suomenkielisellä palautusnäytöllä
![kuva](https://user-images.githubusercontent.com/99952449/227920322-959de50f-6803-4411-9913-35b63914eb9a.png)

**Comment by emta001** [comment]
Käännöksetkin siis näemmä toimivat oikein. Suljen tiketin, avataan uudestaan jos tarvetta ilmenee.
