### ISSUE TITLE
Suomi.fi-palvelua ei voi lisätä asiakkaan viestiasetuksiin - ksdev/ks-0076-KD-G207

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#24]
### Siirrettävä ominaisuus

Suomi.fi-palvelua ei voi lisätä asiakkaan viestiasetuksiin.

**Comment by pknuuti** [comment]
Tälle ei ole tehty mitään? Suomi.fi-palvelu ei ole valittavissa viestiasetuksissa.

**Comment by lmstrand** [comment]
Ominaisuus on viety nexteille feature-branchiin ksdev/ks-0076-K22-24-suomifi-msg-prefs. Odottaa uutta nextin rakennusta vielä.

**Comment by pknuuti** [comment]
Suomi.fi-viestin valinta onnistuu englanninkielisenä, suomenkielisellä puolella valinta ei ole mahdollinen eikä tehdyt valinnat näy suomenkielisenä.

**Comment by AnneliO** [comment]
Suomi.fi ei ole käytössä muualla kuin Vaarassa, joten lisää testituloksia ei ole tulossa. Suljen tämän tiketin. Muutokset tulevan suomenkieliseen näkyviin, kun käännökset ajetaan seuraavan kerran. :)
