### ISSUE TITLE
Tarkista varaustunnus ja ilmoita tupla-arvosta - ksdev/ks-0072-KD-5605

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#25]
### Siirrettävä ominaisuus

Muutos voidaan tiputtaa, kun siirrytään tallentamaan varaustunnus asiakasmääreenä.

**Comment by lmstrand** [comment]
Toteutettu Finna-pluginiin hakemaan oletusarvoisesti asiakasmääre HOLDID ja jos määrettä ei ole, käytetään othernamesia (uniikkiustarkistuksen kera, raportoidaan Finnaan virheenä jos tunnus on jo olemassa tietojen muutospyynnön lähetyksen yhteydessä). Varaustunnus-asiakasmääre HOLDID määritetty nexteille uniikiksi.
