### ISSUE TITLE
K-S:n skeema muutokset - ksdev/ks-0003-schema-update 

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#26]
### Siirrettävä ominaisuus

K-S:n skeema muutokset.

**Comment by emta001** [comment]
Skeema rakennetaan buildin rakennuksen yhteydessä, joten erilliselle branchille ei ole tarvetta. Voitaisiin vielä kuitenkin katella tuleeko tuon buildin kanssa ongelmia.

**Comment by emta001** [comment]
Kokeillaan nopeuttaa skeeman rakennusta rakentamalla tiedostot /dev/shm:n alle ja siirretään sieltä oikeaan paikkaan.

**Comment by emta001** [comment]
Koko buildin tekeminen siirrettiin /dev/shm:n alle, josta valmis branch koppastaan Kohan alle. Vaikuttaisi toimivan ilman ongelmia. Suljen tiketin.
