### ISSUE TITLE
K-S:n käännökset - ksdev/ks-0004-translations

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#27]
### Siirrettävä ominaisuus

K-S:n käännökset.

**Comment by lmstrand** [comment]
Suomen- ja ruotsinkieliset käännöstiedostot on lisätty symlinkeillä Koha/misc/translator/po-hakemiston alle Koha-translations-reposta (22.xx-branch) Vaski-nextille.

**Comment by emta001** [comment]
Translations repon käyttöönotto meni pipariksi. Siirretään 0004-branchi seuraavaan versioon. Katsotaan samalla joutuuko ks22 branchista purkamaan gitignore-muutoksen ja puretaan muutos sekä tehdään tarvittavat korjaustoimenpiteet, jos muutos rikkoo käännökset.

**Comment by emta001** [comment]
> Translations repon käyttöönotto meni pipariksi. Siirretään 0004-branchi seuraavaan versioon. Katsotaan samalla joutuuko ks22 branchista purkamaan gitignore-muutoksen ja puretaan muutos sekä tehdään tarvittavat korjaustoimenpiteet, jos muutos rikkoo käännökset.

Päädyttiin sittenkin säilyttämään translations-repo. 

(╯°□°)╯︵ ┻━┻ 

Suljen tiketin.
