### ISSUE TITLE
Finna-rajapinta

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#28]
### Siirrettävä ominaisuus

Finna-rajapinta

**Comment by lmstrand** [comment]
Kansalliskirjastolla on koha-plugin-rest-di-pluginiin tehtyjä committeja, joilla plugin on yhteensopiva 22.11-version kanssa:
https://github.com/NatLibFi/koha-plugin-rest-di/commits/main
Tuodaan Koha-Suomen käyttämään versioon tarvittavat commitit uuteen 22-branchiin ja testataan, kunhan uudet testi-Finnat on saatavilla.

**Comment by lmstrand** [comment]
Branchiin 22.xx tuotu korjaus 22-versiolle autentikoinnissa. Lisätty https://github.com/NatLibFi/koha-plugin-rest-di/commit/5482b9b3fbe2d30b7812a6fb7c87998faa2c6a28 lisäksi https://github.com/NatLibFi/koha-plugin-rest-di/commit/e2ca8fa1848dc167f08b7af929e3391e92bac73e.

**Comment by lmstrand** [comment]
suljen tämän: https://github.com/KohaSuomi/Koha-22x/issues/83

**Comment by lmstrand** [comment]
Finna-plugin toimii odotetusti. Asiakkaan tietoja koskeva koodi käyttää asiakasmäärettä HOLDID oletuksena varaustunnukselle, jos kimpasta senniminen asiakasmääre löytyy. Muutoin käytetään othernames-tietoa. Pluginin rajapintaan on lisätty tuki parametrin hold_id lähettämiselle, mutta jos Finnaan tehdään muutos othernames-paremetrin nimen vaihtamiseksi, tarvitaan myös pluginiin pieni koodimuutos.
