### ISSUE TITLE
GDPR logging improvements - ksdev/ks-0032-KD-2473

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#29]
### Siirrettävä ominaisuus

GDPR logging improvements

**Comment by AnneliO** [comment]
Asiakastietojen katselut

**Comment by AnneliO** [comment]
Patrons page -> SVC members search

**Comment by ghost** [comment]
SVC members search (ja myös C4::Utils::DataTables::Members) on uudesta versiosta poistettu. Pitää selvittää onko hakuun tehty muitakin lokitukseen vaikuttavia muutoksia.

**Comment by ghost** [comment]
Pitäisi siis lokittua seuraavat:

Jos BorrowersLog-järjestelmäasetus on päällä:

- asiakastietojen muokkaus ja muokkausyritys (Patron/Modification.pm)

Jos BorrowersViewLog-järjestelmäasetus on päällä:

- käsittelyä odottavien asiakastietojen muutosten katselu (Patron/Modifications.pm)
- asiakashaku ja asiakasvalinta (REST/V1/Patrons.pm)
- lainausten katselu (circ/circulation.pl)
- asiakkaan tietojen katselu (members/moremember.pl)
- ilmoitusten katselu (members/notices.pl)
- maksujen katselu (members/pay.pl)
- hankintaehdotusten katselu (members/purchase-suggestions.pl)
- kiertolistojen katselu (members/routing-lists.pl)
- tilastojen katselu (members/statistics.pl)
- lokitietojen katselu tai vienti csv:ksi (tools/viewlog.pl)

**Comment by ajrajala** [comment]
Testasin lokittumista Vaski-nextillä:

- asiakastietojen muokkaus ja muokkausyritys (Patron/Modification.pm)
-> Muokkaus lokittui, itseäni hämäsi ensin lokitietoihin tulevat muokkaustiedot, mutta näköjään siellä on monta kenttää joissa tyhjä tieto muuttuu tallennuksessa NULL-arvoksi.

> Next:
> { "contactfirstname" : { "after" : "", "before" : null }, "contactname" : { "after" : "", "before" : null }, "dateofbirth" : { "after" : "2016-03-29", "before" : null }, "password_expiration_date" : { "after" : "", "before" : null }, "primary_contact_method" : { "after" : "", "before" : null } } 

> Tuotanto:
> { "dateofbirth" : { "after" : "2011-01-13", "before" : "2010-01-13" }, "sms_provider_id" : { "after" : "", "before" : null } } 

- käsittelyä odottavien asiakastietojen muutosten katselu (Patron/Modifications.pm)
-> OK (Pending patron modifications page)
- asiakashaku ja asiakasvalinta (REST/V1/Patrons.pm)
-> OK, lokittui sekä pelkkä asiakashaku että tietoihin/lainaukseen siirtyminen asiakashausta
- lainausten katselu (circ/circulation.pl)
-> OK (Check out page)
- asiakkaan tietojen katselu (members/moremember.pl)
-> OK (Patron details)
- ilmoitusten katselu (members/notices.pl)
-> OK (Notices page)
- maksujen katselu (members/pay.pl)
-> OK (Fines page)
- hankintaehdotusten katselu (members/purchase-suggestions.pl)
-> OK (Purchase suggestions page)
- kiertolistojen katselu (members/routing-lists.pl)
-> OK (Routing lists page)
- tilastojen katselu (members/statistics.pl)
-> OK (Statistics page)
- lokitietojen katselu tai vienti csv:ksi (tools/viewlog.pl)
-> lokitietojen katselu lokittui (Log page), mutta csv-tiedoston viennistä ei minusta tullut mitään uutta lokimerkintää. Tuotannossa lokittuminen tosin käyttäytyi minusta samalla tavalla.

Sellaisen huomasin, että salasanan vaihto lokittuu tuotannossa, mutta ei lokittunut nextillä. Mutta liitttyykö tämän lokittuminen ylipäätään BorrowersLog / BorrowersViewLog -lokiin vai johonkin muuhun?

**Comment by ghost** [comment]
Lokitietojen vienti csv:ksi näkyy vasta seuraavan kerran kun lokia katselee, ei siis tule vielä csv-tiedostoon mukaan.

Salasanan vaihdon pitäisi kyllä nexteilläkin lokittua. Toiminto/Action-sarakkeessa näkyy "Vaihda salasana"/"Change password", Tiedot/Info-sarake jää tyhjäksi. Liittyy BorrowersLogiin mutta ei näihin GDPR-muutoksiin, tulee suoraan yhteisöversiosta.

**Comment by ajrajala** [comment]
Totta joo, kyllähän se salasanan vaihto nextilläkin lokittuu. :) Olin tainnut epähuomiossa katsella vain sitä Tiedot/Info-saraketta.

Tarkoitin siis tuosta csv:ksi viennistä, että siitä ei enää kirjautunut varsinaiseen muutoslokiin erillistä lokiriviä vaan ainoastaan lokitietojen katselusta kirjautui lokirivi. Eli jos avasin asiakkaan muutoslokin ja parin minuutin päästä vein tiedot csv:nä ulos, niin ainoastaan tuo muutoslokin avaaminen näkyi myöhemmin lokitiedoissa. Mutta tuotanto toimii ihan vastaavalla tavalla, joten minä ehkä tulkitsin tämän alkujaan vain väärin?

**Comment by ghost** [comment]
Tosiaan, tiedostoon vienti ylempää Tulostus-kohdasta lokittuu erikseen ja kuvaukseksi tulee "Exporting logs to csv" mutta Vie-painikkeen käyttö ei lokitu (eikä ole tuotannossakaan lokittunut). Varmaan ihan tarkoituksella näin, samat tiedothan siinä viedään tiedostoon jotka jo näkyvät näytöllä.

**Comment by velimarj** [comment]
Myös OUTIssa lokittui nuo kaikki.

**Comment by AnneliO** [comment]
Testasin lokittumista Vaara-nextillä ja mainitut teot/katselut lokittuivat.

**Comment by AnneliO** [comment]
Tämän voinee sulkea?

**Comment by ghost** [comment]
Eiköhän ole tarpeeksi testattu, voi sulkea.
