### ISSUE TITLE
UserJS checksumming - ksdev/ks-0024-KD-4343

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#3]
### Siirrettävä ominaisuus

UserJS checksumming on ominaisuus, joka laskee mm. IntranetUserJS-järjestelmäasetuksen sisällölle tarkistussumman.

**Comment by AnneliO** [comment]
Missä tätä voisi testata?

**Comment by AnneliO** [comment]
Kodo testaa itse.

**Comment by CodoDerDritte** [comment]
Testattu kirkes-nextillä ja toimii.
