### ISSUE TITLE
Tekstiviestirajapinnat, message_id arvon lisääminen viestienlähetysfunktioon - ksdev/ks-0034-KD-4618-SMS 

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#30]
### Siirrettävä ominaisuus

Tekstiviestirajapinnat, message_id arvon lisääminen viestienlähetysfunktioon

**Comment by Kaarius** [comment]
On viety nexteille testattavaksi.

**Comment by AnneliO** [comment]
Miten tätä voisi testata?

**Comment by lmstrand** [comment]
En muista mikä SMS-palveluntarjoaja tätä ominaisuutta vaati, mutta viimeistään kun kaikki SMS-pluginit on testattu niin on tämäkin.

**Comment by lmstrand** [comment]
Kaikki teksitviestipalveluntarjoajat käsittelivät teksitviestit ok nexteillä, joten tämäkin toimii kuten pitää.
