### ISSUE TITLE
Do not allow script tags in Koha news - ksdev/ks-0037-KD-4348

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#31]
### Siirrettävä ominaisuus

Do not allow script tags in Koha news

**Comment by Kaarius** [comment]
On viety nexteille testattavaksi.

**Comment by AnneliO** [comment]
Miten tätä voisi testata?

**Comment by AnneliO** [comment]
Testasin tätä nyt niin, että tein uuden uutisen ja lisäsin siihen alla olevan tekstin:

```
<script>dfdfdf</script>

Testausta testausta
```

Se näkyy uutisessa näin:
![Image](https://user-images.githubusercontent.com/33121325/233960502-10af2ccd-51d8-4fef-b5b7-c6808ce09a79.png)

Toiminee?

**Comment by CodoDerDritte** [comment]
Tuo tapahtuu jos wysiwyg-editorissa kirjoittelee tekstikenttään script-tagit. Se ei ollut se varsinainen ongelma tässä. Ongelma on jos siirtyy pois wyswyg-editorista (työkalupalikin <> nappula) ja kirjoittaa suoraan uutisen lähdekoodiin script-tageja. Tällä tavalla lisätyt script-tagit eivät säily tallennuksessa, joten näyttäisi toimivan oikein.

**Comment by CodoDerDritte** [comment]
Tosin uutena ongelma näyttäisi olevan, ettei uutiseen tehty muokkaus tule näkyviin etusivulla muutenkaan, vaikka tallentuisikin...

**Comment by CodoDerDritte** [comment]
Hieman satunnaista kummittelua näkyy liittyvän uutisten muokkausten näkymiseen Kohan etusivulla, mutta tämän tiketin asia on kunnossa, joten suljen tiketin.
