### ISSUE TITLE
Lainakuitin tulostus printteripainikkeesta tulostaa asiakkaan kaikki lainat

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#32]
### Mikä vikana?

[Redmine-tiketti 5334](https://tiketti.koha-suomi.fi/issues/5334)

Pirkko-Liisa Lauhikari 7.4.2022

Jos tulostaa lainausnäytöllä lainakuitin lainauskentän oikeassa yläkulmassa olevasta printterin kuvakkeesta, tulostuu kuitille asiakkaan kaikki lainassa olevat lainat. Eli onkohan kuvakkeeseen määritelty, että tulostuu kuitti ISSUESLIP? Tarkoituksenmukaisempaa olisi tässä kohtaa tulostua kuitti ISSUEQSLIP eli tänään lainatut lainat.

https://outi-test.koha-suomi.fi/cgi-bin/koha/circ/circulation.pl?borrowernumber=286892

![kuva](https://user-images.githubusercontent.com/33121325/209820151-4378ef40-f427-4617-bafe-0a70f77df59c.png)

--

Korjaus olemassa yhteisössä, testataan versionvaihdon yhteydessä.

**Comment by AnneliO** [comment]
[DisplayClearScreenButton-järjestelmäasetuksella](https://github.com/KohaSuomi/Koha-22x/wiki/Uutta#displayclearscreenbutton-j%C3%A4rjestelm%C3%A4asetuksessa-uusia-vaihtoehtoja) voi määrittää, tulostetaanko kaikki lainat vai tämän päivän lainat.

**Comment by piiaseme** [comment]
Tallensin nextillä DisplayClearScreenButton-asetukseen "Näytä tänään lainatut ja tyhjennä näyttö-painikkeet". 
Testauksessa tulostui "Tänään lainatut- kuitti ja ruksista tyhjeni näyttö.

**Comment by AnneliO** [comment]
Hyvä juttu. Suljen tämän tiketin, kun ongelma korjaantuu versionvaihdossa. :)
