### ISSUE TITLE
Tiedonhaku: teosta ei saa haettua kaikilla hakutavoilla, kun teoksen nimessä merkki /

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-22x#33]
### Mikä vikana?

Teoksen nimessä on kauttaviiva / ja teosta ei löydy kaikilla hakutavoilla.

Kyseessä Hesarin esikoispalkinnon voittanut teos nimeltään Ruumis/huoneet 
Helle-tietueen (biblionumber=1591236) 245a-kenttä:
![kuva](https://user-images.githubusercontent.com/99952449/203967510-e4024351-5223-497f-8f8b-233630d047a5.png)

Eri hakutapoja hakuehdolla Ruumis/huoneet testatessani olen löytänyt teoksen hakutavalla:
![kuva](https://user-images.githubusercontent.com/99952449/203966337-79c32058-1bb7-430e-9d13-da4ad80d01af.png)

**Comment by Kati-Helle** [comment]
Hae tietokannasta haulla toimii (ainakin) tämä tapa:
![kuva](https://user-images.githubusercontent.com/99952449/204242071-6706b0c2-3520-44f4-aa0c-cc211bed00ce.png)

**Comment by AnneliO** [comment]
Löysin tähän liittyen Redminestä tiketin https://tiketti.koha-suomi.fi/issues/5135

Tarkassa haussa voi rajata niteen Ei lainata -tilan mukaan, mutta rajaus ei toimi niillä nidetiloilla, joiden tunniste on miinusmerkkinen. Esim. Tilattu, jonka tunniste on -1 ja Saapunut, jonka tunniste on -2. Jos haun tekee perushaussa notforloan:"-1" eli suojaa miinusmerkin, niin haku toimii.

Tässä on todennäköisesti sama ongelma kuin että erikoismerkeillä ei voi hakea. Jos hakee esim ti:fahrenheit 11/9, niin haku ei toimi. Pitää hakea ti:fahrenheit "11/9", jotta haku toimisi.

**Comment by AnneliO** [comment]
Olen kyllä [Elasticsearchin koulutusmateriaaliin](https://tiketti.koha-suomi.fi/attachments/download/5282/Tiedonhaku_Elasticsearchilla.pdf) kirjannut seuraavaa:

 Jos hakusana sisältää erikoismerkkejä, kannattaa ne suojata hipsuilla. Muuten haku ei toimi. **Korjattu uudemmassa versiossa.**
• ti:fahrenheit ”11/9”

Eli jossain vaiheessa olen näköjään testannut, että pitäisi toimia. Mutta nyt en muista, missä olen testannut. Ehkäpä sandboxissa.

**Comment by AnneliO** [comment]
Versioon 22.11 tulee tällainen korjaus: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=31213

Eli jos hakutulos on "tyhjä", niin Koha tekee automaattisesti saman haun hipsujen kanssa. Tällä on pyritty korjaamaan juurikin tuo ongelma, että erikoismerkeillä haku ei toimi ilman hipsuja.

**Comment by CodoDerDritte** [comment]
Siirretään tämä uuden version repoon kunhan sellainen saadaan aikaiseksi. Merkkaan tämän nyt Katille niin testaatko Kati uudestaan tämän sitten kun saadaan uusi versio testeihin.

**Comment by lmstrand** [comment]
Googlailuni perusteella elasticsearch-hakuihin pitää erikoismerkkien eteen laittaa \ -kenoviiva (alt + ?), jolloin ainakin tämä haku toimii tuosta päänäkymän "hae tietokannasta" hakukentästä. Hain siis "Ruumis\\/huoneet". Sama koskee ilmeisesti myös ( , ) jne. merkkejä.

**Comment by AnneliO** [comment]
[Redmine-tiketti 2791](https://tiketti.koha-suomi.fi/issues/2791) korjaantunee myös tällä korjauksella.

**Comment by Kati-Helle** [comment]
Lisäsin kauttaviivan olemassa olevalle tietueelle (biblionumber 55) kenttään 245a=PASSING ON. 
Muutoksen jälkeen 245a=PASSING/ON.

Hae tietokannasta sanahaku TAI Hae tietokannasta nimekehaku
![kuva](https://user-images.githubusercontent.com/99952449/224311777-b2d79662-ffff-42e1-91f1-37fcff484750.png)

Hae tietokannasta fraasihaku
![kuva](https://user-images.githubusercontent.com/99952449/224312039-b506fb3a-6ad5-4430-b355-2be62d31f0cf.png)

Tarkka haku -toiminnossa käyttäytyy samoin kuin Hae tietokannasta -haussa, eli fraasihaku antaa hakutuloksen.

**Comment by ghost** [comment]
Yhteisön tiketin 31213 muutos on meidän 22-versiossa mukana ja tuntuisi toimivan oikein eli haku toistetaan lainausmerkeissä jos ensimmäisellä hakukerralla ei tule yhtään tulosta. Kuitenkin jos QueryRegexEscapeOptions-järjestelmäasetuksessa on valittuna vaihtoehto "Älä käytä escape-komentoa"/"Don't escape", yksittäinen vinoviiva / tulkitaan regexin aluksi ja haku kaatuu virheeseen kun sille ei löydy paria. Vinoviivan eteen tulisi laittaa kenoviiva \ jotta haku toimii oikein (tai sitten lainausmerkit koko haun ympärille). "Ohita escape-komento"/"Unescape escaped" toimii käänteisesti eli "tavallisissa" hauissa kenoviivaa ei tarvita mutta regexeissä tarvitaan. Hiukan nurinkurista mutta voisi vähentää virheellisiä hakuja jos regexejä käytetään vain harvoin? Asetuksella "Käytä escape-komentoa"/"Escape" regexejä ei voi käyttää lainkaan.

Haku siis toimii tällä hetkellä niin kuin sen kuuluukin toimia. Voisi kuitenkin miettiä olisiko QueryRegexEscapeOptions-asetukseksi järkevää vaihtaa "Unescape escaped".

**Comment by AnneliO** [comment]
Testailin vaara-nextillä neon/noir-teoksella (jonka olen siis itse muuttanut tuohon muotoon) ja vaski-nextillä muilla tiketin esimerkeillä, niin että QueryRegexEscapeOptions-asetuksessa on "Unescape escaped".  En ainakaan hoksaa nyt mitään ongelmaa kyseisessä asetuksessa. Tuohon notforloan:-1 -hakuun tämä ei auta, mutta siinä ei olekaan kyse regexistä.

Voisko @ajrajala tai @MikkoLiimatainen (tai joku muu vaskilainen) testailla myös tätä? :)

**Comment by ajrajala** [comment]
En myöskään havainnut tämän aiheuttavan ongelmia hakuja testaillessa. QueryRegexEscapeOptions-asetukseen liittyen tiedoksi, että meillä on tuotannossa ollut asetukseen valittuna "Escape", koska oli sellainen [pieni epäilys että asetuksella olisi voinut olla jotain merkitystä tilaussanomien käsittelyjen epäonnistumisiin](https://github.com/KohaSuomi/Koha/issues/353#issuecomment-1378384652). Mutta eipä asetusmuutoksella ollut vaikutusta, eli senkään puolesta ei olisi ongelma laittaa päälle tuota vaihtoehtoa "Unescape escaped".

**Comment by Kati-Helle** [comment]
Kiitos. Asetuksen QueryRegexEscapeOptions arvon muutos auttaa. Nyt kauttaviivan sisältävä teosnimi löytyy fraasihaun lisäksi myös ainakin nimekehaulla ja sanahaulla.

**Comment by AnneliO** [comment]
Lisäsin QueryRegexEscapeOptions-asetuksen [Mitä pitää tehdä next-kannassa](https://github.com/KohaSuomi/Koha-22x/wiki/Mit%C3%A4-pit%C3%A4%C3%A4-tehd%C3%A4-next-kannassa#p%C3%A4ivitett%C3%A4v%C3%A4t-vanhat-j%C3%A4rjestelm%C3%A4asetukset) -wikiin Päivitettävät vanhat järjestelmäasetukset -osioon.
