### ISSUE TITLE
Niteettömän tietueen varaaminen

### ISSUE THREAD

**Issue by MikkoLiimatainen** [KohaSuomi/Koha-22x#34]
### Mikä vikana?

Hakutulossivulta voi valita useamman tietueen kerralla varattavaksi, jolloin Koha ei estä varauksen tekemistä niteettömään tietueeseen. Valitut tietueet voivat kaikki olla niteettömiä.
![Varauksen teko](https://user-images.githubusercontent.com/98884651/203939960-ee09658a-89ab-4ff3-b451-8622881d98ee.png)

Näin tehdyt niteettömät varaukset tallentuvat ilman noutopaikkaa, mikä rikkoo asiakkaan tiedoissa varaukset välilehden toiminnan.
![Tehdyt varaukset](https://user-images.githubusercontent.com/98884651/203940480-fda9780c-b655-40a8-8d15-4da7b00f0f92.png)
![Asiakkaan varaukset](https://user-images.githubusercontent.com/98884651/203940500-4a5bd5c6-c216-4a5d-ac98-da6cdd13ad72.png)

### Mitä pitäisi tapahtua

Useita tietueita varattaessa pitäisi niteettömien tietueiden varaaminen estää.

**Comment by pirliis** [comment]
Testasin OUTIn testillä eli tein varaukset tietueeseen jossa oli niteitä, mutta toisessa tietueessa ei ollut niteitä. Koha teki varauksen vain tietueeseen, jossa oli varaus. Erikoista, jos OUTIssa toimii kuin pitäisi, mutta Vaskissa ei.

**Comment by emta001** [comment]
Ekana tulee mieleen, että Vaskissa voisi olla päällä asetus, joka mahdollistaa varauksen niteettömään tietueeseen. Pitää tutkia.

**Comment by MikkoLiimatainen** [comment]
Mä en ainakaan tuollaista asetusta löytänyt, mutta voihan siellä jokin sellainen olla. Tosin yksittäiseen niteettömään tietueeseen varauksen tekeminen ei onnistu, ainoastaan silloin onnistuu, kun tietueita varataan kerralla useampi.

**Comment by pirliis** [comment]
Minulla oli parissa testissä molemmissa vain kaksi tietuetta.

**Comment by emta001** [comment]
Sain toistettua omilla testeillä. HIeman alkaa vaikuttaa sille, että koodissa on jonkinlainen porsaanreikä tässä.

**Comment by Kati-Helle** [comment]
Testasin varauksen teon yhdellä niteellisellä ja kahdella niteettömällä tietueella: asiakkaan Varaukset-välilehti ok.
Testasin varauksen teon monella niteellisellä ja niteettömällä tietueella: asiakkaan Varaukset-välilehti sekaisin.

**Comment by emta001** [comment]
Yhteisön tiketti [30742](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=30742) vaikuttaisi oikealle korjaukselle tähän.

**Comment by emta001** [comment]
Pahasti näyttää sille, ettei tämä korjaannukaan pelkän 30742 tuomisella.  Niteetön tietue pääsee edelleen jostain syystä läpi.

**Comment by emta001** [comment]
Joo ei taida onnistua, tuo muutos vaatisi toimiakseen ainakin yhden toisen muutoksen tuomisen (ja se taas luultavasti vaatisi toisen muutoksen jne.). Pitää katsoa vielä onko tähän meidän päässä tehtävissä mitään yksinkertaista muutosta.

**Comment by emta001** [comment]
Tämä korjaantuu seuraavassa versionvaihdossa. Siihen asti tiedotetaan ongelmasta kirjastoille: Laitan tiketin Odottaa -tilaan.

**Comment by AnneliO** [comment]
Siirretään tiketti versionvaihto-repositorioon, kun se on perustettu. Testaatko Mikko tätä sitten, kun ollaan saatu uudemman version testikannat käyttöön?

**Comment by MikkoLiimatainen** [comment]
Juu, mä testailen.

**Comment by MikkoLiimatainen** [comment]
En ole saanut toistettua tätä nextillä, joten niteettömän tietueen varaaminen ei vaikuttaisi olevan mahdollista.
