### ISSUE TITLE
Varaustunnus asiakkaan lisämääreeksi

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#36]
### Kehitysehdotukseni

Kopioitu Redminestä tiketistä https://tiketti.koha-suomi.fi/issues/4807

Varaustunnuksena käytetään nyt other names -kenttää. Se ei kuitenkaan ole kestävä ratkaisu, koska sitä kenttää ei voi säätää yksilölliseksi ja siihen voi syöttää muutakin tietoa.

Parempi ratkaisu on laittaa varaustunnus asiakkaan atribuutteihin.

Kentän toiminta tulee varmistaa:
- Varaustunnuksen näkyminen asiakkaalle lähtevässä noutoilmoituksessa
- Varaustunnuksen näkyminen varauksesta tulostettavassa kirjan väliin menevässä kuitissa
- Varaustunnuksen vaihtaminen Finnassa
- Varaustunnuksen näkyminen Finnassa

--
Inkeri Hakulinen 12.3.2021

Lisäksi saisi olla vielä toiminto:
-Varaustunnuksen ehdottaminen automaattisesti asiakkaan nimen perusteella, kuten nyt on eli "sukunimi, etunimi"

Lisäksi mahdollisuus säätää varaustunnus pakolliseksi pitää olla mukana (toki se nyt on jo esim. HETUssa)

--

Koha-Suomen asiantuntijaryhmän päätös 14.11.2022: Siirytään versionvaihdon yhteydessä käyttämään asiakasmäärettä othernames-kentän sijaan. Tutkitaan Finna-toimiston kanssa yhdessä, miten asiakasmääre saadaan Finnaan näkyviin ja muutettavaksi samalla tavalla kuin nyt.

Sukunimi, Etunimi -vaihtoehtoa ei toteuteta. Huomioitava myös, että kirjastokortin numeroa ei käytetä varaustunnuksena.

Aikataulu: Versiovaihdon yhteydessä

**Comment by AnneliO** [comment]
Lari on säätänyt Finna-liitännäistä niin, että se välittää asiakasmääreessä olevan varaustunnuksen Finnaan ja sen saa muokattua siellä.

Kirjailin muista pääkäyttäjiltä tarvittavista toimista [Mitä pitää tehdä next-kannassa](https://github.com/KohaSuomi/Koha-22x/wiki/Mit%C3%A4-pit%C3%A4%C3%A4-tehd%C3%A4-next-kannassa#varaustunnus-asiakasm%C3%A4%C3%A4reeksi) -wikiin.

Lisäksi kehittäjien pitää tehdä ainakin seuraavat toimet:
- varaustunnusten siirto othernames-kentästä HOLDID-asiakasmääreeseen

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 24.4.2023: Lasse kirjoittaa othernames-kentästä siirron osaksi tietokannan päivitysskriptiä.

**Comment by AnneliO** [comment]
Pääkäyttäjäpalaveri 25.4.2023: Varaustunnus-asiakasmääre kopioidaan nextiltä tuotantoon, joten siirto/kopiointi pitää tehdä ennen kuin varaustunnukset siirretään othernames-kentästä HOLDID-asiakasmääreeseen.

**Comment by ghost** [comment]
Lisätty osaksi tietokannan päivitystä. Asiakasmääreen kopioinnin ei pitäisi olla välttämätöntä, se tulee luoduksi samassa skriptissä jos se puuttuu.

**Comment by ghost** [comment]
Tarkennukseksi vielä: Jos asiakkaalla on jo HOLDID-asiakasmääre, sitä ei ylikirjoiteta vaan olemassa oleva arvo jää voimaan. Jos määre puuttuu, sen arvoksi tulee othernames-kentän arvo. Lopuksi othernames-kentät tyhjennetään.
