### ISSUE TITLE
[Bugi] Varauksen peruminen Varauksia-näytön kautta vähän takeltelee

### ISSUE THREAD

**Issue by IrinaHalminen** [KohaSuomi/Koha-22x#37]
### Mikä vikana?

Olen perumassa varausta Varauksia-näytöltä (esim. https://vaara-test.koha-suomi.fi/cgi-bin/koha/reserve/request.pl?biblionumber=11662035). Klikkaan valintaruksin niteen tietojen edestä ja valitsen niteen tietojen perästä roskakorikuvakkeen/Peruuta. Tulee pop-up-ilmoitus Haluatko varmasti perua varauksen? ja klikkaan siitä valintaa Vahvista poisto. Ei tapahdu mitään eli varausta ei voi poistaa tuolla toiminnolla. Popparin peruuta-nappi toimii.

Jos klikkaan toista vaihtoehtoa eli ylempänä olevaa Peruuta valitut varaukset -nappia, tulee hetkiseksi ilmoitus Käsitellään, mutta varaus ei poistu näytöltä. Kokeilen uudelleen, varaus ei poistu. Kolmannella yrityksellä se häviää näytöltä. Todellisuudessa varauksen poistaminen on onnistunut jo ensimmäisellä yrittämällä, mutta sivu ei päivity. 

### Jotain muuta?

![varaus](https://user-images.githubusercontent.com/99409279/196975959-0aac5a3f-72ac-4fef-b278-2abcf0fa2312.png)

### Kohan osio

Varaukset

**Comment by AnneliO** [comment]
Ensimmäisessä tapauksessa ongelmana on se, että laitat rastin varauksen kohdalle ja vasta sitten klikkaat Peruuta. Se jotenkin sekoittaa toiminnon niin, että popparissa ei toimi vahvista-nappi. Jos et laita rastia ja klikkaat vain Peruuta, niin varauksen poisto toimii.

Toisessa tapauksessa taas varauksen poisto viedään taustatöihin (eli kuten esim. niteiden eräpoistot). Tämä tieto ei tule näkyville varausnäytölle, koska sitä on muutettu silloin, kun tehtiin varausten sivutus Koha-Suomen versioon. Silloin kun toiminto menee taustatöihin, sivu ei lataudu automaattisesti uudelleen ja se pitää itse päivittää manuaalisesti. 

Pitää selvitellä, saisiko sen taustatyö-ilmoituksen näkyville taas.

**Comment by AnneliO** [comment]
"Pitää selvitellä, saisiko sen taustatyö-ilmoituksen näkyville taas."

Korjataan versionvaihdon yhteydessä, jos se on mahdollista.

**Comment by AnneliO** [comment]
Yhdistetään branchiin ksdev/ks-0015.

**Comment by ghost** [comment]
Nexteillä taustatöihin menevät varausten poistot jäävät tällä hetkellä kokonaan käsittelemättä. Taustatöihin on lisätty uusi työjono long_tasks joka pitää ottaa background_jobs_workeria ajaessa käyttöön.

**Comment by ghost** [comment]
Taustatyöjono long_tasks on nyt nexteillä käytössä, varausten perumista voisi testailla uudelleen siellä. ~~Ilmoitusta taustatöihin siirtämisestä ei ilmeisesti vieläkään tule mutta varaukset tuntuvat häviävän näytöltä heti vaikkei koko sivu lataudukaan uudelleen. (Varausten lukumäärä ei päivity automaattisesti mutta tuosta ei hirveästi lienee haittaa?)~~

Poistonapissa on uudessa versiossa sama vika kuin tuotannossakin, ei tee mitään jos varauksia on ruksittuna.

Nyt käykin täysin päinvastoin kuin kirjoitin edellä eli ilmoitus tulee näkyviin ja varausten lukumäärä päivittyy mutta varaukset eivät häviä luettelosta ellei sivua päivitä.

**Comment by AnneliO** [comment]
Testasin varausten poistoa Cancel selected holds -nappiaa painamalla ja sitä ennen useamman varauksen valitsemalla ja varaukset poistuu kunhan taustatyö on ehtinyt ne poistaa. Varaukset katoavat sivulta, kun sivun päivittää. Tämä toimii tuotannossa samalla tavalla.

Eli edelleeen puuttuu vain se ilmoitus taustatyöstä.

**Comment by ghost** [comment]
Jotain outoa nyt on joko varaussivussa tai taustatöissä, ei tule enää minunkaan testiympäristössäni taustatyöilmoitusta vaikka koodissa mikään ei ole muuttunut. En ole löytynyt sivun logiikasta mitään ilmeistä virhettäkään, jostain syystä vaan viime viikolla toimi oikein ja nyt taas ei. Voisiko riippua siitä kuinka nopeasti työt menevät jonoon tai tulevat käsitellyiksi?

**Comment by AnneliO** [comment]
PTFS Europen sandboxissa tulee tällainen ilmoitus, kun varauksen poisto menee taustatöihin:
![kuva](https://user-images.githubusercontent.com/33121325/233994300-4d4e8c8f-4ad7-47b9-8dfd-8cfa27b7d1eb.png)

**Comment by ghost** [comment]
Sellaisen huomasin että varaussivulla on aluksi suomenkielinen "Peruuta valitut"-painike, mutta varausten latautuessa välähtää "Käsitellään" ja tilalle vaihtuu englanninkielinen "Cancel selected". Painikkeen toiminnallisuus vaikuttaa samalta mutta liittyisikö kuitenkin näihin ongelmiin jotenkin?

**Comment by AnneliO** [comment]
> Sellaisen huomasin että varaussivulla on aluksi suomenkielinen "Peruuta valitut"-painike, mutta varausten latautuessa välähtää "Käsitellään" ja tilalle vaihtuu englanninkielinen "Cancel selected". Painikkeen toiminnallisuus vaikuttaa samalta mutta liittyisikö kuitenkin näihin ongelmiin jotenkin?

Minusta nuo englanninkieliset tekstit tulivat näkyville sen jälkeen, kun varausten sivutus otettin käyttöön. Ilman niitä nappien käännökset näkyivät oikein. Se sivutustoiminto ilmeisesti korvaa monia asioita sivulla?

**Comment by AnneliO** [comment]
Suljetaan tämä tiketti ja huomioidaan ongelmat versiossa 23.xx.
