### ISSUE TITLE
Kielen vaihtaminen vie aina etusivulle

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#39]
### Mikä vikana?

Kun vaihtaa kielen esim. asiakkaan tiedoissa ollessaan, siirtyy Koha aina kielen vaihdon jälkeen etusivulle, eikä pysy samalla sivulla.

### Mitä pitäisi tapahtua

Kohan pitäisi pysyä samalla sivulla kuin mitä oltiin ennen kielen vaihtamista.

### Kuinka toistaa ongelma/asia

1. Mene esim. omiin tietoihin
2. Vaihda kielivalinta toiseksi kuin se tällä hetkellä on
3. Päädyt etusivulle

**Comment by emta001** [comment]
Hmm, näkyy tapahtuvan myös esim. hakutuloksissa ja asetuksissa. Luonnollisesti omilla testeillä toimii oikein.

Oon muuten muistaakseni huomannut tätä samaa oireilua ihan tuotannoissakin.

**Comment by emta001** [comment]
Johtui siitä, että _staffClientBaseURL_ asetuksessa oli väärä polku Vaskin tuotantoon. Vaihdoin siihen vaski-nextin osoitteen, nyt pitäisi toimia kuten pitää.

**Comment by AnneliO** [comment]
Jes, toimii! Kiitos!
