### ISSUE TITLE
Palautus ei toimi vaski-nextillä

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#41]
### Mikä vikana?

Jos palauttaa vaski-nextillä niteen, tulee error 500. Yritin palauttaa niteen [LVask119955527](https://vaski-next.koha-suomi.fi/cgi-bin/koha/catalogue/moredetail.pl?itemnumber=2119804&biblionumber=3682290&bi=3682290#item2119804) 27.1.2023 n. klo 15.38 paikkeilla.

### Mitä pitäisi tapahtua

Nide pitäisi palautua ja mahdollisten varausten jäädä kiinni.

### Kuinka toistaa ongelma/asia

1. Mene palautukseen
2. Yritä palauttaa esim. nide [LVask119955527](https://vaski-next.koha-suomi.fi/cgi-bin/koha/catalogue/moredetail.pl?itemnumber=2119804&biblionumber=3682290&bi=3682290#item2119804)
3. Saat virheen 500

### Jotain muuta?

Kokeiltu englanninkielisessä liittymässä, joten ei liene ainakaan kielitempalte-ongelma.

**Comment by emta001** [comment]
Tämä johtui siis siitä, että kannassa oli kellutukseen liittyviä sääntöjä. Sieltä on nyt poistettu circulation_rules-taulusta rivit joissa rule_value = "returnbylibrarygroup". Lisäksi taulusta library_groups on poistettu sarake  "ft_local_float_group".

**Comment by AnneliO** [comment]
Lainaus ja palautus toimii nyt, kiitos!
