### ISSUE TITLE
Jos DefaultHoldExpirationdate on asetettu, varauksen aloituspäivä menee asetuksen mukaiseksi

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#42]
### Mikä vikana?

Jos DefaultHoldExpirationdate-järjestelmäasetus on asetettu, tulee varauksen aloituspäiväksi asetuksessa määritetty päivä. Eli jos asetuksessa on 2 vuotta, tulee 30.1.2023 varauksen aloituspäiväksi 30.1.2025. Asetuksen pitäisi vaikuttaa vain viimeiseen voimassaolopäivään.

### Jotain muuta?

Yhteisössä on tästä avoinna [bugi 32563](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=32563). Seurataan sen etenemistä.

**Comment by AnneliO** [comment]
Asiasanat: vanhentumispäivä expirationdate aloituspäivä varaus varauksen vanhentumispäivä varauspäivämäärä päivämäärä alkamispäivä alkamispäivämäärä alkamispvm aloituspvm aloituspäivämäärä

**Comment by emta001** [comment]
Koha-Suomi palaveri 17.4.2023: Korjataan yhteisössä oleva patchi ja tuodaan korjaus sitten nexteille.

**Comment by emta001** [comment]
Tämä on nyt tuotu nexteille testattavaksi.

**Comment by Kati-Helle** [comment]
Hellessä testatessani ei toiminut oikein.
Tietueen varauksissa varauksen Pvm-kenttään tuli arvoksi 19.4.2026 eli sama kuin Vanhenee-kenttään
![kuva](https://user-images.githubusercontent.com/99952449/233058449-00639009-d483-4a3a-b490-8e62f1d1ed34.png)

**Comment by ajrajala** [comment]
Vaski-nextillä näytti sen sijaan toimivan:

![kuva](https://user-images.githubusercontent.com/44638512/233296128-46c10640-6d48-4182-ad0b-dbb6583b6f83.png)

**Comment by Tuomas-Kyyti** [comment]
Kyytin nextillä päivämäärät vaikuttivat nyt menevän oikein.

**Comment by emta001** [comment]
> Hellessä testatessani ei toiminut oikein. Tietueen varauksissa varauksen Pvm-kenttään tuli arvoksi 19.4.2026 eli sama kuin Vanhenee-kenttään ![kuva](https://user-images.githubusercontent.com/99952449/233058449-00639009-d483-4a3a-b490-8e62f1d1ed34.png)

Hellessä ei ollut asetus päällä. Laitoin sen päälle ja nyt näyttäisi toimivan kuten pitää.

**Comment by Kati-Helle** [comment]
Otin eilen testaukseni jälkeen varauksen pois päältä Aseta -> Älä aseta :)

Nyt testatessani toimi oikein 
![kuva](https://user-images.githubusercontent.com/99952449/233303525-dd045372-5e17-4edb-bcf4-b5a4bd9ebd57.png)

Hienoa, että toimii!

**Comment by Kati-Helle** [comment]
Anni, onko Vaskissa estetty jotenkin tallennetu varauksen varauspäiväyksen muutos? Vaski-kuvassa kun ei näy kalenteria Pvm-kentässä

![kuva](https://user-images.githubusercontent.com/99952449/233312884-712cfa22-8cff-4e33-8dea-a03c32abecef.png)

**Comment by emta001** [comment]
Vaikuttaisi sille, että tämä siis toimii kuten pitää. Suljen tiketin tältä erää.

**Comment by ajrajala** [comment]
> Anni, onko Vaskissa estetty jotenkin tallennetu varauksen varauspäiväyksen muutos? Vaski-kuvassa kun ei näy kalenteria Pvm-kentässä
> 
> ![kuva](https://user-images.githubusercontent.com/99952449/233312884-712cfa22-8cff-4e33-8dea-a03c32abecef.png)

@Kati-Helle Tuo tulee näköjään järjestelmäasetuksesta AllowHoldDateInFuture, siinä on meillä 'Älä salli'.

**Comment by Kati-Helle** [comment]
Kiitos Anni tiedosta!
Asetus AllowHoldDateInFuture = 'Älä salli' estää näköjään nimensä mukaisesti myös varausta tehdessä varauksen aloituspäiväyksen valittavuuden.
