### ISSUE TITLE
TypeError-virheilmoitus selaimen konsolissa vaski-nextillä

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-22x#43]
### Mikä vikana?

Selaimen konsolissa näkyy seuraava virheilmoitus (kaikilla) sivuilla:

_Uncaught TypeError: $(...).datepicker is not a function_

Virhe vaikuttaisi viittavaan a) puuttuvaan jQuery datepicker-pluginiin b) virheelliseen polkuun kyseiseen pluginiin c) siihen, että jQuery ja plugin(it) importataan väärässä järjestyksessä (esim. datepickeriä ei voida importata ennen jQueryä, sillä datepicker ei tällöin löydä jQueryä).

**Comment by emta001** [comment]
Johtuukin vaski-nextillä olevasta jQuery-rimpsusta:

```
/* aseta syntymäpäivä-datepickerin dropdownin vuodet */ /* Toimii. Uudessa versiossa kaksi datepickeriä. Uusi peittää tämän datepickerin. 22.03.2022 MLI */
$(document).ready(function() {
  $("body#pat_memberentrygen.pat #dateofbirth").datepicker({yearRange: "c-50:c+1"});
});
//LOPPU 
```

**Comment by AnneliO** [comment]
Kommentoin rimpsun vaski-nextillä pois käytöstä ja virheilmoitus katosi.
