### ISSUE TITLE
Takaajatieto pakolliseksi lapsiasiakkaalle - ksdev/ks-0019-bug-12133

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#44]
### Mikä vikana?

Takaajatieto pitäisi saada määritettyä pakolliseksi lapsiasiakastyypeille. Versiossa 21.11 on järjestelmäasetus ChildNeedsGuarantor, jolla määritetään pakollisuus.

### Jotain muuta?

Yhteisössä bugi: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=25854

**Comment by emta001** [comment]
Viety testeille. _Kaikki_ takaaja-tiedot tippuvat tällä hetkellä kun sattuu virhe, mikä näyttäisi olevan ongelma myös yhteisössä. Tutkailen sitä vielä tarkemmin.

**Comment by AnneliO** [comment]
Käännös puuttuu vielä, joten suomenkielistä versiota käytettäessä ei näy, mikä virheen aiheuttaa. 

![kuva](https://user-images.githubusercontent.com/33121325/219645231-1a73d2d3-e97e-47f2-abdd-043d51fe68c4.png)

Englanninkielisessä tulee ilmoitus:

![kuva](https://user-images.githubusercontent.com/33121325/219644709-6078a8c4-6085-48fe-bf6d-0774c18f7727.png)

**Comment by emta001** [comment]
Tämä ilmeisesti rikkoo lainauksen lapsiasiakkailta, korjaillaan.

**Comment by emta001** [comment]
Lainaus toimii nyt lapsiasikkaiden osalta. Sen verran tässä on vielä ratkottavaa, että kys. asiakkailta on mahdollista poistaa takaaja seuraavasti: muokkaa asiakasta -> poista takaaja -> yritä tallentaa -> virhe -> peru muokkaus -> takaaja on poistunut.

**Comment by emta001** [comment]
> Lainaus toimii nyt lapsiasikkaiden osalta. Sen verran tässä on vielä ratkottavaa, että kys. asiakkailta on mahdollista poistaa takaaja seuraavasti: muokkaa asiakasta -> poista takaaja -> yritä tallentaa -> virhe -> peru muokkaus -> takaaja on poistunut.

Tämäkin on nyt korjattu ja tuotu nexteille.

**Comment by pknuuti** [comment]
Lapsilainaajalla onnistuu lainaaminen Vaaran nextillä (jos aineisto on sallittu iän puolesta, sekin tuli testattua että ikäraja toimii). Lapselta ei pysty poistamaan takaajaa.

**Comment by ReettaSiili** [comment]
ChildNeedsGuarantor-asetus päällä, en saa poistettua lapselta takaajaa enkä tallennettua lapsiasiakasta ilman takaajaa.
Lainaus onnistuu ja ikäraja pitää. Eli toimii Siilissä.

**Comment by Kati-Helle** [comment]
Onnistuin vaihtamaan lapsi-asiakkaan takaajatiedon vain siten, että lisäsin ensin uuden (toisen) takaajan ja poistin lisäyksen jälkeen poistettavaksi tarkoitetun takaajatiedon.

Tämä tapa muuttunut aiemmasta. Tuotannossa takaajatieto poistuu takaajatiedon Poista-valinnalla, jonka jälkeen Koha ilmoittaa lapsen tietojen muokkauksessa: 
Seuraavat tiedot ovat väärin. Korjaa tiedot. Lapsella pitää olla takaaja.

**Comment by Kati-Helle** [comment]
> Lapsilainaajalla onnistuu lainaaminen Vaaran nextillä (jos aineisto on sallittu iän puolesta, sekin tuli testattua että ikäraja toimii). Lapselta ei pysty poistamaan takaajaa.

Kiitos Päivi ikäraja-testauksesta :)

**Comment by emta001** [comment]
Tämä vaikuttaisi olevan kunnossa, suljen tiketin.
