### ISSUE TITLE
Erämuokkaus- ja poistotyökaluissa tulee virhe 500

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#45]
### Mikä vikana?

Kuvailun etusivulla https://vaski-next.koha-suomi.fi/cgi-bin/koha/cataloguing/cataloging-home.pl jos klikkaa niteen erämuokkausta/poistoa tai tietueen erämuokkausta/poistoa, tulee virhe 500.

### Mitä pitäisi tapahtua

Muokkaus/poistotyökalun pitäisi avautua.

**Comment by AnneliO** [comment]
Samalla sivulla näköjään myös nämä aiheuttavat virheen 500:

https://vaski-next.koha-suomi.fi/cgi-bin/koha/tools/stage-marc-import.pl
https://vaski-next.koha-suomi.fi/cgi-bin/koha/tools/manage-marc-import.pl
https://vaski-next.koha-suomi.fi/cgi-bin/koha/tools/upload-cover-image.pl

**Comment by emta001** [comment]
Kyseessä oli vanhentunut asetus koha-httdp.confissa. Nyt korjattu ja sivujen pitäisi aueta.

**Comment by AnneliO** [comment]
Sivut aukeaa nyt, kiitos! Suljen tiketin. :)
