### ISSUE TITLE
Viivakoodin generointi niteelle - ksdev/ks-0005-bug-30328

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-22x#48]
### Siirrettävä ominaisuus

Kohassa on niteen viivakoodigenerointi, johon lisätty myös Koha-Suomessa vaihtoehtoja, ainakin "Vaara-kirjastot.." ja "generoidaan muodossa <prefixcode>..".

Liittyvät järjestelmäasetukset:

autoBarcode
Tänne lisätty vaihtoehdot "Vaara-kirjastot.." ja "generoidaan muodossa <prefixcode>.."

BarcodePrefix
asetuksella voi määrittää, että tietyn kirjaston viivakoodeihin tulee tietynlainen prefiksi, esim. kuntakoodi.

**Comment by emta001** [comment]
Tuotu testattavaksi.

**Comment by AnneliO** [comment]
Kun  PrefillItem-järjestelmäasetus oli päällä, tuli lisättävälle niteelle automaattisesti edellisen lisätyn niteen viivakoodi. Jos tästä nyt lisäsi useamman niteen kerralla, tuli ilmoitus:

![Image](https://user-images.githubusercontent.com/33121325/219651142-19fa8a45-212e-4235-82ca-131741ec1fd7.png)

Niteet kyllä muodostuivat siitä huolimatta:

![Image](https://user-images.githubusercontent.com/33121325/219651428-6c104a93-983b-4ce2-a399-ec804265a4f6.png)

Kun  PrefillItem-asetuksen laittoi pois päältä, viivakoodi muodostui vasta kolmea pistettä painamalla, eikä useita niteitä kerralla lisätessä tullut yllä olevaa herjaa.

Eli, jos tuota  PrefillItem-asetusta haluaa käyttää, pitää SubfieldsToUseWhenPrefill-asetukseen määrittää ne kentät, jotka kopioidaan edelliseltä niteeltä ja mukana ei saa olla barcode-kenttää. Vaskissa näyttää olevan tuo asetus myös tuotannossa päällä, joten en nyt tiedä, miten hyvin tämä toiminto on toiminut tähän mennessä siellä.

**Comment by ajrajala** [comment]
Tuotannossa meillä ei ole tullut virheilmoitusta ja mitä tuota testailin niin nykyversiossa tuon SubfieldsToUseWhenPrefill-asetuksen tyhjäksi jättäminen on tehnyt sen, ettei niteelle kopioida mitään osakenttiä edelliseltä niteeltä. SubfieldsToUseWhenPrefill-asetuksen toiminta on siis muuttunut, hyvä kun Anneli huomasit tämän.

Tosiaan kun PrefillItem-asetus oli pois päältä, toimi viivakoodin muodostus hyvin sekä yksittäisiä että useampaa nidettä lisättäessä. Testasin viivakoodin generointia myös kausijulkaisujen vastaanotossa sekä olemassa olevan niteen muokkauksessa.

**Comment by Kati-Helle** [comment]
Helle-nextillä viivakoodin generointi toimii uutta nidettä lisätessä ja myös silloin, kun olemassa olevalle niteelle vaihtaa viivakoodin.

**Comment by pknuuti** [comment]
Vaaran nextillä myös testattu toimivaksi kuten Hellessä.

**Comment by emta001** [comment]
Tämä vaikuttaisi siis toimivan kuten pitääkin. Suljen tiketin tältä erää.
