### ISSUE TITLE
Järjestelmäasetus: DebarmentsToLiftAfterPayment - ksdev/ks-0006-bug-16223

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-22x#49]
### Siirrettävä ominaisuus

Koha-Suomen versiossa on aiemmin ollut käytössä järjestelmäasetus DebarmentsToLiftAfterPayment. Yhteisöön on kuitenkin tullut uusi ominaisuus "Patron restrictions/Asiakas rajoitukset(?)", jolla voidaan määritellä käytettäväksi erityyppisiä rajoituksia. Maksurajoja on ehdotettu yhteisöön osaksi ominaisuutta ja järjestelmäasetuksesta voidaan luopua.

**Comment by emta001** [comment]
Tämä on viety vaski-nextille testattavaksi.

**Comment by AnneliO** [comment]
Onko Lift after payment ja Fee limit jostain erityisestä syystä pakollisia?

**Comment by AnneliO** [comment]
Testaa näin:

1. Mene Ylläpito -> Asiakkaan rajoitukset / Administration -> Patron restrictions
2. Tee uusi rajoitetyyppi tai muokkaa olemassaolevaa, esim. Manual.
3. Valitse Lift after payment -kohtaan Yes
4. Kirjoita Fee limit -kohtaan haluamasi maksuraja, esim. 5.00. Huom! Desimaalierottimena käytetään pistettä.
5. Tallenna
6. Mene jonkin testiasiakkaan tietoihin ja lisää hänelle sen tyyppinen rajoite, jota juuri käsittelit
7. Lisää asiakkaalle maksuja yli rajoitteen maksurajan, jos maksuja ei ole ennestään.
8. Huomioi, että rajoite on edelleen olemassa.
9. Merkitse kaikki asiakkaan maksut maksetuksi ja tarkista, että rajoite on poistunut.
10. Toista kohtia 7-9 erilaisilla maksumäärillä ja varmista, että rajoite ei poistu, jos maksuja jää jäljelle yli asetetun rajan ja että rajoite poistuu, kun maksujen määrä alittaa/saavuttaa määritetyn rajan. Huomioi, että kun maksuja on tismalleen rajoitteeseen määritetty määrä, rajoite poistuu. Kokeile myös maksujen poistoa.

**Comment by emta001** [comment]
> Onko Lift after payment ja Fee limit jostain erityisestä syystä pakollisia?

Oot ensimmäinen joka tuosta huomauttaa. Eihän niiden tarttis olla, mikä lie ajatus mulla siinäkin ollut taustalla :D
Voi ne vaihtaakin, ainakin sen Fee limitin vois ottaa veke. Sehän on turha silloin kun toinen on No :thinking:

**Comment by ajrajala** [comment]
Testasin sekä maksujen maksamista että poistoa ja rajoite käyttäytyi kuten piti.

Vaskissa ei näköjään ole koskaan ollut käytössä järjestelmäasetusta DebarmentsToLiftAfterPayment. 😄 Siksi nyt siis vähän tyhmä kysymys, mutta onko tämä toiminut siis niin, että rajoite maksuista on muodostunut asiakkaille automaattisesti kun määritelty maksuraja on tullut täyteen?

**Comment by AnneliO** [comment]
emta001
> > Onko Lift after payment ja Fee limit jostain erityisestä syystä pakollisia?
> 
> Oot ensimmäinen joka tuosta huomauttaa. Eihän niiden tarttis olla, mikä lie ajatus mulla siinäkin ollut taustalla :D Voi ne vaihtaakin, ainakin sen Fee limitin vois ottaa veke. Sehän on turha silloin kun toinen on No 🤔

Epäpakollisuus ois pop, varsinkin jos kimpassa ei haluta käyttää tätä toiminnallisuutta. Pakollisuus pakottaa kirjoittamaan kenttään kuitenkin jotain. :)

ajrajala
> Testasin sekä maksujen maksamista että poistoa ja rajoite käyttäytyi kuten piti.
> 
> Vaskissa ei näköjään ole koskaan ollut käytössä järjestelmäasetusta DebarmentsToLiftAfterPayment. 😄 Siksi nyt siis vähän tyhmä kysymys, mutta onko tämä toiminut siis niin, että rajoite maksuista on muodostunut asiakkaille automaattisesti kun määritelty maksuraja on tullut täyteen?

OUTIssakaan tätä ei ole ollut käytössä, mutta luulisin, että rajoite on lisätty erikseen, eikä se ole muodostunut automaattisesti.

**Comment by emta001** [comment]
> emta001
> 
> > > Onko Lift after payment ja Fee limit jostain erityisestä syystä pakollisia?
> > 
> > 
> > Oot ensimmäinen joka tuosta huomauttaa. Eihän niiden tarttis olla, mikä lie ajatus mulla siinäkin ollut taustalla :D Voi ne vaihtaakin, ainakin sen Fee limitin vois ottaa veke. Sehän on turha silloin kun toinen on No thinking
> 
> Epäpakollisuus ois pop, varsinkin jos kimpassa ei haluta käyttää tätä toiminnallisuutta. Pakollisuus pakottaa kirjoittamaan kenttään kuitenkin jotain. :)

Tätä pitää hetki tuumata, jos sen laittaa ei-pakolliseksi, jääkö se sitten herkästi täyttämättä? Pitäisi varmaan yrittää saada säädettyä tuota jotenkin niin, että jos Lift after payment on Yes, niin Fee limit on silloin pakollinen täyttää. Tai sitten siinä on oletuksena 0.

**Comment by emta001** [comment]
Laitoin yhteisöön patchin, jossa kumpikaan kentistä ei ole pakollinen, mutta jos "Lift after paymentin" laittaa päälle, "Fee limitistä" tulee pakollinen. En vielä tuonut nexteille, koska skeman rakennuksessa on vielä pieniä ongelmia.

**Comment by Kati-Helle** [comment]
Hellessä ei ole käytössä asetus DebarmentsToLiftAfterPayment.

**Comment by emta001** [comment]
> Laitoin yhteisöön patchin, jossa kumpikaan kentistä ei ole pakollinen, mutta jos "Lift after paymentin" laittaa päälle, "Fee limitistä" tulee pakollinen. En vielä tuonut nexteille, koska skeman rakennuksessa on vielä pieniä ongelmia.

Tämä on nyt nexteillä testattavana.

**Comment by ajrajala** [comment]
Testasin asetusta ja jos Lift after paymentin laittoi päälle, Fee limit -kentän viereen tuli tieto pakollisuudesta eikä tallentaminen onnistunut jos kenttä oli tyhjä. Testasin myös uudestaan rajoituksen automaattista poistumista silloin, kun maksut maksetaan maksurajan alle, toimi edelleen kuten piti.

(Suomenkielisellä puolella molemmat kentät näkyi vielä pakollisena eli testasin enkuksi.)

**Comment by AnneliO** [comment]
Lisätyt rajoitteet eivät jostain syystä näy, kun asiakkaalle lisää rajoitusta:
![kuva](https://user-images.githubusercontent.com/33121325/228436216-98e2e278-d23d-4520-ae32-5d1d24bd4ebb.png)

**Comment by emta001** [comment]
> Lisätyt rajoitteet eivät jostain syystä näy, kun asiakkaalle lisää rajoitusta: ![kuva](https://user-images.githubusercontent.com/33121325/228436216-98e2e278-d23d-4520-ae32-5d1d24bd4ebb.png)

Works on my machine. Tutkaillaan.

**Comment by emta001** [comment]
OUTIssa ei ollut asetus PatronRestrictionTypes päällä. Nyt on ja pitäisi rajotusten näkyä OK.

**Comment by AnneliO** [comment]
Haa, niinpä tietenkin. Eipä tuollainen muistunut mieleen. :D Kiitos!

**Comment by pknuuti** [comment]
Vaarassa on ollut käytössä DebarmentsToLiftAfterPayment-asetus. Meillä oli muutaman vuoden käytössä vuodenvaihteessa tuleva lainauskielto, jos asiakkaalla oli maksuja maksamatta. Kun asiakas sitten maksoi maksut vaikka verkkokirjaston kautta, tämä toiminto poisti asiakkaalle asetetun rajoituksen heti pois. Nyt tuota lainauskieltoa ei enää tule ja entisetkin rajoitukset on poistettu. Tuskin tuolle asetukselle on enää käyttöä?

**Comment by emta001** [comment]
> Vaarassa on ollut käytössä DebarmentsToLiftAfterPayment-asetus. Meillä oli muutaman vuoden käytössä vuodenvaihteessa tuleva lainauskielto, jos asiakkaalla oli maksuja maksamatta. Kun asiakas sitten maksoi maksut vaikka verkkokirjaston kautta, tämä toiminto poisti asiakkaalle asetetun rajoituksen heti pois. Nyt tuota lainauskieltoa ei enää tule ja entisetkin rajoitukset on poistettu. Tuskin tuolle asetukselle on enää käyttöä?

Tuskin ellette halua lisätä asiakkaille rajoituksia manuaalisesti, jotka sitten poistuu kun maksuja ei enää ole tai ne on alle tietyn summan.

**Comment by Tuomas-Kyyti** [comment]
Vaikuttaa toimivan Kyytin nextissä ok, vaikka emme tällä tietoa ole ottamassa sitä käyttöön. Rajoite poistuu sekä maksamalla että maksun poistamalla.

Meillä on ollut käytössä DebarmentsToLiftAfterPayment-asetus, johon on määritetty että vuosittaisista lainauskieltoajoista tullut rajoite poistuu, kun maksut on maksettu. Lainauskieltoajossa siis kaikille, joilla oli maksuja, tuli tietty sama rajoiteteksti, joka sitten määritettiin tuossa DebarmentsToLiftAfterPayment-asetuksessa. Ihan hyödyllinen toiminnallisuus, johon varmaan voi jatkossa hyvin käyttää tätä uutta toimintoa. 

Nyt meillä ei ole enää moneen vuoteen ollut lainauskieltoajoja, joten DebarmentsToLiftAfterPayment-asetuksen poistumisesta ei aiheutune ongelmaa. Eikä jäljellä olevia rajoitetekstejä lainauskieltoajoista tarvitse konvertoida tähän uuteen toimintoon.

**Comment by emta001** [comment]
Tämä toiminee kuten pitää. Suljen tiketin tältä erää.
