### ISSUE TITLE
Noutoaika asiakastyypin, aineistolajin ja kirjaston mukaan - ksdev/ks-0008-bug-8367 

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-22x#50]
### Siirrettävä ominaisuus

Yhteisön (ei vielä masterissa) ominaisuus , jolla varaukselle voidaan määritellä noutoaika laina- ja maksusäännöissä.

**Comment by emta001** [comment]
Tuotu testeille.

Testaa näin:
1) Aseta jokin arvo asetukseen ReservesMaxPickUpDelay, jos sitä ei vielä ole
2) Muokkaa laina- ja maksusäännöissä saraketta "Holds pickup period (day)", aseta siihen eri arvo kuin ReservesMaxPickUpDelay-asetukseen
3) Tee varaus tietueelle ja palauta jokin sen niteistä, hyväksy varaus
4) Tarkista, että varauksen vanhenemispäivä noudattaa laina- ja maksusäännöissä asetettua arvoa, ei ReservesMaxPickUpDelay asetusta

Toista vaiheet niin, että olet luonut kirjaston kalenteriin kiinniolopäivän, joka menee päällekäin "Holds pickup period (day)" arvon kanssa. Tällöin kiinniolopäivä otetaan huomioon niin, että "Holds pickup period (day)" arvoon lasketaan kiinniolopäivien määrä.

Kokeile myös asettaa eri "Holds pickup period (day)" eri kirjastoille ja varmista, että vanhenemispäivä noudattaa niitä.

**Comment by ajrajala** [comment]
Vaikuttaisi toimivan kuten pitää, testattu parilla eri kirjastolla joilla eri arvot laina- ja maksusäännöissä.

**Comment by pirliis** [comment]
OUTIssa näyttäisi toimivan kuin pitääkin. Kiinniolopäiviin ei lasketa "Holds pickup period (day)" arvon päiviä, joka on ainakin OUTIssa ok.

**Comment by ReettaSiili** [comment]
Testattu myös Siilissä toimivaksi. Noutoaika haetaan nimenomaan Holds pickup period (day) -sarakkeesta. Eri kirjastojen asetukset ja kiinniolopäivät kalenterissa otettiin huomioon oikein.

**Comment by emta001** [comment]
Testien perusteella tämä siis vaikuttaisi toimivan kuten pitää. Suljen tiketin tältä osin, avataan uudestaan jos on tarvetta.
