### ISSUE TITLE
Kellutusryhmät - ksdev/ks-0010-bug-9525

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-22x#51]
### Siirrettävä ominaisuus

Yhteisöön ehdotettu ominaisuus, jolla kirjastoille voidaan määritellä kellutusryhmät.

**Comment by emta001** [comment]
Tuotu testeille.

Testaa näin:
1) Mene Kirjastoryhmät näytölle ja luo uusi tai useampi kellutusryhmä ("Is local float group"), lisää siihen/niihin joitakin kirjastoja.
2) Aseta kirjastoille laina- ja maksusäännöistä palautus säännöksi "Item floats by library group".
3) Lainaa nide asiakkaalle.
4) Vaihda kirjastoksesi kirjasto, joka kuuluu luomaasi kellutusryhmään.
5) Palauta nide.
-> Kuljetusilmoituksen ei tulisi ilmestyä palautuksen yhteydessä.
6) Lainaa nide uudelleen ja vaihda tällä kertaa kirjatoksesi kirjasto, joka ei kuuluu kellutusryhmään.
7) Palauta nide.
-> Kuljetusilmoituksen tulisi nyt ilmestyä palautuksen yhteydessä.

**Comment by ajrajala** [comment]
Testattu Vaski-nextillä, toimii nähdäkseni kuten pitääkin.

**Comment by Kati-Helle** [comment]
Helle-nextillä toimii oikein.

**Comment by pirliis** [comment]
OUTI-nextillä näytti toimivan oikein.

**Comment by emta001** [comment]
Vaikuttaa toimivan, suljen tiketin.
