### ISSUE TITLE
Maksut-kuitti - ksdev/ks-0011-bug-12285

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-22x#52]
### Siirrettävä ominaisuus

Koha-Suomessa on lisätty Maksut-kuitti eli FINESLIP, johon tulostuu asiakkaan voimassa olevat maksut.

HUOM! Yhteisössä on tehty tästä oma versio (bug [31713](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=31713)). Pitää testata onko tuossa jo kaikki meille tarpeelliset ominaisuudet vai tarvitaanko jotakin tiketistä 12285.

**Comment by AnneliO** [comment]
Versiossa 22.11 on kuittipohja ACCOUNTS_SUMMARY, jolla saa tulostettua asiakkaan maksut kuitille.

Oletuksena siellä on tällainen määritys:

```
[% USE Branches %]
[% USE Koha %]
[% USE KohaDates %]
[% USE Price %]
[% PROCESS 'accounts.inc' %]
<table>
  [% IF ( Koha.Preference('LibraryName') ) %]
    <tr>
      <th colspan='4' class='centerednames'>
        <h1>[% Koha.Preference('LibraryName') | html %]</h1>
      </th>
    </tr>
  [% END %]

  <tr>
    <th colspan='4' class='centerednames'>
      <h2>[% Branches.GetName( borrower.branchcode ) | html %]</h2>
    </th>
  </tr>

  <tr>
    <th colspan='4' class='centerednames'>
      <h3>Outstanding accounts</h3>
    </th>
  </tr>

  <tr>
    <th colspan='4' class='centerednames'>
      <h4>Debts</h4>
    </th>
  </tr>
  [% IF borrower.account.outstanding_debits.total_outstanding %]
  <tr>
    <th>Date</th>
    <th>Charge</th>
    <th>Amount</th>
    <th>Outstanding</th>
  </tr>
  [% FOREACH debit IN borrower.account.outstanding_debits %]
  <tr>
    <td>[% debit.date | $KohaDates %]</td>
    <td>
      [% PROCESS account_type_description account=debit %]
      [%- IF debit.description %], [% debit.description | html %][% END %]
    </td>
    <td class='debit'>[% debit.amount | $Price %]</td>
    <td class='debit'>[% debit.amountoutstanding | $Price %]</td>
  </tr>
  [% END %]
  [% ELSE %]
  <tr>
    <td colspan='4'>There are no outstanding debts on your account</td>
  </tr>
  [% END %]

  <tr>
    <th colspan='4' class='centerednames'>
      <h4>Credits</h4>
    </th>
  </tr>
  [% IF borrower.account.outstanding_credits.total_outstanding %]
  <tr>
    <th>Date</th>
    <th>Credit</th>
    <th>Amount</th>
    <th>Outstanding</th>
  </tr>
  [% FOREACH credit IN borrower.account.outstanding_credits %]
  <tr>
    <td>[% credit.date | $KohaDates %]</td>
    <td>
      [% PROCESS account_type_description account=credit %]
      [%- IF credit.description %], [% credit.description | html %][% END %]
    </td>
    <td class='credit'>[% credit.amount *-1 | $Price %]</td>
    <td class='credit'>[% credit.amountoutstanding *-1 | $Price %]</td>
  </tr>
  [% END %]
  [% ELSE %]
  <tr>
    <td colspan='4'>There are no outstanding credits on your account</td>
  </tr>
  [% END %]

  <tfoot>
    <tr>
      <td colspan='3'>
        [% IF borrower.account.balance < 0 %]
          Total credit as of [% today | $KohaDates %]:
        [% ELSE %]
          Total outstanding dues as of [% today | $KohaDates %]:
        [% END %]
      </td>
      [% IF ( borrower.account.balance <= 0 ) %]<td class='credit'>[% borrower.account.balance * -1 | $Price %]</td>
      [% ELSE %]<td class='debit'>[% borrower.account.balance | $Price %]</td>[% END %]
    </tr>
  </tfoot>
</table>
```

Muokkasin tuosta suomenkielisen version, jossa on poistettu enimmäkseen maininnat credit-maksuista ja siitä tuli tällainen:

```
[% USE Branches %]
[% USE Koha %]
[% USE KohaDates %]
[% USE Price %]
[% PROCESS 'accounts.inc' %]
<table>
  [% IF ( Koha.Preference('LibraryName') ) %]
    <tr>
      <th colspan='4' class='centerednames'>
        <h1>[% Koha.Preference('LibraryName') | html %]</h1>
      </th>
    </tr>
  [% END %]

  <tr>
    <th colspan='4' class='centerednames'>
      <h2>[% Branches.GetName( borrower.branchcode ) | html %]</h2>
    </th>
  </tr>

  <tr>
    <th colspan='4' class='centerednames'>
      <h3>Voimassa olevat maksut</h3>
    </th>
  </tr>

  [% IF borrower.account.outstanding_debits.total_outstanding %]
  <tr>
    <th>Päivämäärä</th>
    <th>Maksu</th>
    <th>Määrä</th>
    <th>Maksamatta</th>
  </tr>
  [% FOREACH debit IN borrower.account.outstanding_debits %]
  <tr>
    <td>[% debit.date | $KohaDates %]</td>
    <td>
      [% PROCESS account_type_description account=debit %]
      [%- IF debit.description %], [% debit.description | html %][% END %]
    </td>
    <td class='debit'>[% debit.amount | $Price %]</td>
    <td class='debit'>[% debit.amountoutstanding | $Price %]</td>
  </tr>
  [% END %]
  [% ELSE %]
  <tr>
    <td colspan='4'>Sinulla ei ole maksamattomia maksuja.</td>
  </tr>
  [% END %]

    <tfoot>
    <tr>
      <td colspan='3'>
        [% IF borrower.account.balance < 0 %]
         Creditiä yhteensä [% today | $KohaDates %]:
        [% ELSE %]
          Maksamattomia maksuja yhteensä [% today | $KohaDates %]:
        [% END %]
      </td>
      [% IF ( borrower.account.balance <= 0 ) %]<td class='credit'>[% borrower.account.balance * -1 | $Price %]</td>
      [% ELSE %]<td class='debit'>[% borrower.account.balance | $Price %]</td>[% END %]
    </tr>
  </tfoot>
</table>

```


Kuitin saa tulostettua asiakkaan tiedoista seuraavasti: Tulosta -> Tulosta asiakkaan maksut (Print -> Print account balance)

Minun silmään kuitti näyttää suht hyvältä, mutta minulla ei ole kuittitulostinta, jolla testata sen asettumista kuitille.

Tässä kuitti pdf-tiedostona A4-koossa:

[accountbalance.pdf](https://github.com/KohaSuomi/Koha-22x/files/10767199/accountbalance.pdf)

Periaatteessa sieltä voisi vielä riisua pois Määrä (amount) -sarakkeen ja laittaa näkyville vain Maksamatta (amountoutstanding) -sarakkeen. Mutta tuota sisältöä voidaan miettiä vaikka pääkäyttäjien kanssa yhdessä tarvittaessa.

Summa summarum: Minusta ei tarvita Koha-Suomen omaa FINESLIP-kuittipohjaa enää mihinkään.

**Comment by ReettaSiili** [comment]
Siilissä kuittiteksti asettuu ihan nätisti vaikkakin pienellä präntillä, kuvassa näyttää suuremmalta kuin onkaan.

![accounts_summary_siili](https://user-images.githubusercontent.com/98806001/224284904-d9f1f4a0-4ca3-4c60-9a21-60fe3596a069.JPG)

**Comment by Kati-Helle** [comment]
Saisiko kuittiin pelkän maksutyypin kuvauksen? Nyt kuitilla on sekä maksutyypin tunnus että maksutyypin kuvaus.
Näyttökuva Helle-kuitista:

![kuva](https://user-images.githubusercontent.com/99952449/224317700-ee35dd2f-2d54-4ab0-806a-0e0d79284fc9.png)

**Comment by AnneliO** [comment]
Hmm.. jos maksun tunnus poistetaan, voipi olla, että esim. Noutamattoman varauksen maksuissa ja myöhästymismaksuissa jää tarvittavia tietoja pois kuitilta. Pystyisitkö @Kati-Helle testaamaan muillakin maksuilla kuin manuaalisesti lisätyillä? :)

**Comment by ajrajala** [comment]
Testasin tätä Vaski-nextillä sellaisella asiakkaalla, jolla oli automaattisesti muodostuneita maksuja. Kuten Anneli epäili niin tosiaan niissä molempien kenttien kuvaus on kuitilla tarpeen:
![kuva](https://user-images.githubusercontent.com/44638512/225238185-78a8e118-b1d3-483c-a48a-41b0d72b1f7b.png)

**Comment by AnneliO** [comment]
Nyt kun katson noita kuitteja, niin onko teistä Määrä-sarake tarpeellinen? Siinähän käytännössä voi olla eri luku vain, jos sallitaan maksujen osittainen maksu. Varmaan ainakin osassa kimpoissa on ehto, että kaikki maksut pitää maksaa kerralla.

**Comment by pirliis** [comment]
Ilmeisesti kuitin ACCOUNTS_SUMMARY oletuskieli on englanti, koska kun kopioin suomenkielisen pohjan oletuspohjaan, maksun kuvaukset tulevat kuitenkin englanniksi.

**Comment by pirliis** [comment]
Määrä-sarakkeen voisi varmaan jättää kuitista pois, koska Maksamatta-sarakkeeseen tulee aina todellinen maksettava summa.

**Comment by AnneliO** [comment]
Tässä ois versio, jossa ei ole Määrä-saraketta:
```
[% USE Branches %]
[% USE Koha %]
[% USE KohaDates %]
[% USE Price %]
[% PROCESS 'accounts.inc' %]
<table>
  [% IF ( Koha.Preference('LibraryName') ) %]
    <tr>
      <th colspan='3' class='centerednames'>
        <h1>[% Koha.Preference('LibraryName') | html %]</h1>
      </th>
    </tr>
  [% END %]

  <tr>
    <th colspan='3' class='centerednames'>
      <h2>[% Branches.GetName( borrower.branchcode ) | html %]</h2>
    </th>
  </tr>

  <tr>
    <th colspan='3' class='centerednames'>
      <h3>Voimassa olevat maksut</h3>
    </th>
  </tr>

  [% IF borrower.account.outstanding_debits.total_outstanding %]
  <tr>
    <th>Pvm</th>
    <th>Maksu</th>
    <th>Summa</th>
  </tr>
  [% FOREACH debit IN borrower.account.outstanding_debits %]
  <tr>
    <td>[% debit.date | $KohaDates %]</td>
    <td>
      [% PROCESS account_type_description account=debit %]
      [%- IF debit.description %], [% debit.description | html %][% END %]
    </td>
    <td class='debit'>[% debit.amountoutstanding | $Price %]</td>
  </tr>
  [% END %]
  [% ELSE %]
  <tr>
    <td colspan='3'>Sinulla ei ole maksamattomia maksuja.</td>
  </tr>
  [% END %]

    <tfoot>
    <tr>
      <td colspan='2'>
       Maksamattomia maksuja yhteensä [% today | $KohaDates %]:
      </td>
     <td class='debit'>[% borrower.account.balance | $Price %]</td>
    </tr>
  </tfoot>
</table>
```

**Comment by AnneliO** [comment]
Myös ruotsinkielisiin kuitteihin tulostuu englanniksi maksun kuvaus, joten ilmeisesti ruotsinkielisissä po-tiedostoissa on nyt jotain puutetta. Mitä katselin, niin meidän po-tiedostot ovat aika vanhoja. Selvitelläänpä tuota.

**Comment by AnneliO** [comment]
Muutin uuteen pohjaehdotukseen vielä sarakkeiden otsikoiksi Pvm, Maksu (taino tämä säilyi samana) ja Summa, koska aiemmat sanat tekivät kentistä turhaan leveitä. Näin Maksu-sarakkeelle jää enemmän tilaa levitä selitteen pituuden mukaan.

**Comment by ajrajala** [comment]
Varmaan selkeämpi tosiaan ilman tuota Määrä-saraketta, vaikka meillä onkin mahdollista lyhentää maksuja.

**Comment by ReettaSiili** [comment]
Siilissä kuitti nyt selkeä ilman Määrä-saraketta ja tekstin koko riittävä. Meillä ei ole kieliversiot käytössä, mutta Myöhästymismaksu (Kertyvä maksu) näkyy kuitilla enkuksi Fine (Accruing).

**Comment by AnneliO** [comment]
Testailin tätä vielä nykyversion testillä ja siellä on vähän vastaava kuitti (ACCOUNT_DEBIT) maksuissa Tapahtumat-välilehdellä aina yksittäisen maksurivin kohdalla. Eli siellä kun klikkaa Tulosta, tulee tämän tyyppinen tuloste:
![kuva](https://user-images.githubusercontent.com/33121325/225912855-fca2a0ea-8d2e-4d26-97e8-c16b7becf6c3.png)

Eli maksun tilityyppi on samalla tavalla englanniksi, kun asiakkaan kielivalintana on Oletus.

En löytänyt järjestelmäasetuksista mitään valintaa sille, mikä on oletuskieli.

**Comment by Kati-Helle** [comment]
Hellen ruotsinkieliselle maksukuitille tulevat käyttöön nämä:
Nuvarande avgifter
Datum
Förklaring
Obetald avgift
Obetalda avgifter sammanlagt
Du har inga obetalda avgifter 

Maksukuitilla näkyvät näin:
![kuva](https://user-images.githubusercontent.com/99952449/226304464-bd4573b5-1115-4f0d-a7e1-2bb356669dd6.png)

(Asiakkaan Tiedoissa Tulosta/Tulosta asiakkaan maksut -vaihtoehtoa ei ole, kun asiakkaalla ei ole maksamattomia maksuja. Missä maksukuitin 'Du har inga obetalda avgifter' näkyisikään...)

**Comment by AnneliO** [comment]
Kiitos Kati! Eli tässä ois ruotsinkielinen maksukuitti:

```
[% USE Branches %]
[% USE Koha %]
[% USE KohaDates %]
[% USE Price %]
[% PROCESS 'accounts.inc' %]
<table>
  [% IF ( Koha.Preference('LibraryName') ) %]
    <tr>
      <th colspan='3' class='centerednames'>
        <h1>[% Koha.Preference('LibraryName') | html %]</h1>
      </th>
    </tr>
  [% END %]

  <tr>
    <th colspan='3' class='centerednames'>
      <h2>[% Branches.GetName( borrower.branchcode ) | html %]</h2>
    </th>
  </tr>

  <tr>
    <th colspan='3' class='centerednames'>
      <h3>Nuvarande avgifter</h3>
    </th>
  </tr>

  [% IF borrower.account.outstanding_debits.total_outstanding %]
  <tr>
    <th>Datum</th>
    <th>Förklaring</th>
    <th>Obetald avgift</th>
  </tr>
  [% FOREACH debit IN borrower.account.outstanding_debits %]
  <tr>
    <td>[% debit.date | $KohaDates %]</td>
    <td>
      [% PROCESS account_type_description account=debit %]
      [%- IF debit.description %], [% debit.description | html %][% END %]
    </td>
    <td class='debit'>[% debit.amountoutstanding | $Price %]</td>
  </tr>
  [% END %]
  [% ELSE %]
  <tr>
    <td colspan='3'>Du har inga obetalda avgifter.</td>
  </tr>
  [% END %]

    <tfoot>
    <tr>
      <td colspan='2'>
       Obetalda avgifter sammanlagt [% today | $KohaDates %]:
      </td>
     <td class='debit'>[% borrower.account.balance | $Price %]</td>
    </tr>
  </tfoot>
</table>
```

Tuossa kuitissa oli alunperin mukana myös credit-maksut, joten voipi olla, että jos olisi credit-maksuja, mutta ei debit-maksuja, niin tuo  'Du har inga obetalda avgifter' näkyis silloin. Eli saattaapi olla tässä turha, mutta ei siitä nyt sinänsä haittaakaan ole. :D

**Comment by AnneliO** [comment]
Ruotsinkielinen kuittipohja lisätty myös [Kuitit ja tulosteet](https://github.com/KohaSuomi/Koha-22x/wiki/Kuitit-ja-tulosteet#ruotsiksi) -wikiin.

**Comment by emta001** [comment]
Mikä tämän tilanne on? Voiko tiketin jo sulkea?

**Comment by AnneliO** [comment]
Tein eilen vielä pieniä säätöjä pohjiin ja minun puolesta ne olisi ok. Ongelmana sinänsä on vielä tuo, että ruotsinkielisiin kuitteihin tulostuu englanninkieliset maksujen kuvaukset ja oletuskielisiin myöskin englanniksi. Mutta pitäisikö niistä avata erilliset tiketit?

**Comment by emta001** [comment]
> Tein eilen vielä pieniä säätöjä pohjiin ja minun puolesta ne olisi ok. Ongelmana sinänsä on vielä tuo, että ruotsinkielisiin kuitteihin tulostuu englanninkieliset maksujen kuvaukset ja oletuskielisiin myöskin englanniksi. Mutta pitäisikö niistä avata erilliset tiketit?

Voisihan tuon, kyseessä vaikuttaa olevan ihan oma ongelmansa :D

**Comment by AnneliO** [comment]
Tein tiketit #150 ja #151, joten suljen tämän tiketin. :)
