### ISSUE TITLE
Järjestelmäasetus: UpdateNotForLoanStatusOnCheckout - ksdev/ks-0012-on-0007-bug-30403

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-22x#53]
### Siirrettävä ominaisuus

Järjestelmäasetus, jolla niteen notforloan-arvo voidaan vaihtaa myös lainatessa.

Mennyt läpi yhteisön masteriin, muttei kerennyt uuteen versioon.

**Comment by emta001** [comment]
Tuotu testeille.

**Comment by Kati-Helle** [comment]
Lainaan niteen, jolla on lainatessa miinusmerkkinen Ei lainata -nidetila Käsiteltävänä
![kuva](https://user-images.githubusercontent.com/99952449/224320951-6ac4d879-326b-4ccd-9bf5-4308f9288b49.png)

Lainatessa Koha kysyy: Nide ei ole yleensä lainattavissa (Käsiteltävänä). Lainaa siitä huolimatta?
![kuva](https://user-images.githubusercontent.com/99952449/224322031-6a8a2d6e-ffa4-41f0-84e0-966f7c1a1139.png)

Kyllä-vastauksella nide menee lainaan ja niteeltä on poistunut miinusmerkkinen Ei lainata -nidetila Käsiteltävänä
![kuva](https://user-images.githubusercontent.com/99952449/224322443-48cc91eb-49e0-4355-9eec-b5c71922f2ef.png)

**Comment by Kati-Helle** [comment]
Lainaan vielä niteeen, jolla on pysyväksi tarkoitettu Ei lainata -nidetila Ei lainata, ei varata 
![kuva](https://user-images.githubusercontent.com/99952449/224324432-13dcad83-8cee-4e15-9456-27e1b8187d90.png)

Lainatessa Koha kysyy: Nide ei ole yleensä lainattavissa (Ei lainata, ei varata). Lainaa siitä huolimatta?
![kuva](https://user-images.githubusercontent.com/99952449/224324577-bdd9643d-6738-4f81-89a9-92b89bc0dc7b.png)


Kyllä-vastauksella nide menee lainaan ja niteellä on edelleen pysyväksi tarkoitettu Ei lainata -nidetila 
![kuva](https://user-images.githubusercontent.com/99952449/224325053-be8132c5-d1d0-4629-81df-8bee2e2e1316.png)

**Comment by AnneliO** [comment]
Testasin vaara-nextillä lainata sellaisen notforloan-tilaisen niteen, joka oli määritetty poistumaan lainatessa sekä sellaisen, jota ei ole määritetty poistumaan lainatessa. Toimi oikein kummassakin tapauksessa.

**Comment by emta001** [comment]
Vaikuttaa toimivalta. Suljen tiketin.
