### ISSUE TITLE
Add cancellation reason to holds delete endpoint - ksdev/ks-0013-bug-30660 

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-22x#54]
### Siirrettävä ominaisuus

Varauslistan sivutukseen tarvittava endpoint.

**Comment by emta001** [comment]
Tuotu testeille. Tätä voinee testata kokeilemalla toimiiko Varaukset-sivu kuten pitää.

**Comment by emta001** [comment]
Tarkennuksena, tätä siis voi testata laittamalla peruutettavalle varaukselle peruutuksen syyn. Sen pitäisi näkyä reserves-taulussa sarakkeessa cancellation_reason.

**Comment by ajrajala** [comment]
Testasin tätä perumalla varauksen yksittäisen varausrivin kohdalta löytyvän Peruuta-napin kautta. Old_reserves -tauluun tuli näkyville peruutuksen syyn auktorisoitu arvo eli toimi kuten piti.

En pystynyt testaamaan peruuttamista Cancel selected -napin kautta, sillä varaukset eivät poistu sitä käyttäessä. Mutta se johtunee siitä, että erämuokkaukset ei nexteillä tällä hetkellä toimi #129 ?

**Comment by Kati-Helle** [comment]
Testattu tietueen Varaukset välilehdellä: poistin varausrivillä olleen varauksen Peruuta-painikkeella peruutuksen syyn valiten. (Testausta varten tein HOLD_CANCELLATION-auktorisoidun arvon valittavaksi.)

old-reserves-taulussa varaus näkyy peruutuksen syyn kera
![kuva](https://user-images.githubusercontent.com/99952449/228178970-8d359682-8d0e-423a-822f-4b2776a6d54b.png)

**Comment by emta001** [comment]
> Testasin tätä perumalla varauksen yksittäisen varausrivin kohdalta löytyvän Peruuta-napin kautta. Old_reserves -tauluun tuli näkyville peruutuksen syyn auktorisoitu arvo eli toimi kuten piti.
> 
> En pystynyt testaamaan peruuttamista Cancel selected -napin kautta, sillä varaukset eivät poistu sitä käyttäessä. Mutta se johtunee siitä, että erämuokkaukset ei nexteillä tällä hetkellä toimi #129 ?

#129 pitäisi olla nyt korjattu, kerkiätkö testaamaan uudelleen?

**Comment by ajrajala** [comment]
Testasin peruuttamista Cancel selected -napin kautta, HOLD_CANCELLATION arvo tallentui tietokantaan. 👍

**Comment by emta001** [comment]
Hmm, eiköhän tämänkin voisi sitten laittaa sulki. Avataan uudelleen, jos tarvetta ilmenee.
