### ISSUE TITLE
Able to update more hold parameters via REST API - ksdev/ks-0014-bug-30661

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-22x#55]
### Siirrettävä ominaisuus

Varauslistan sivutukseen tarvittava endpoint.

**Comment by emta001** [comment]
Tuotu testeille. Tätä voinee testata kokeilemalla toimiiko Varaukset-sivu kuten pitää.

**Comment by ajrajala** [comment]
Varauksen keskeyttäminen määräajaksi ei vaikuttaisi toimivan. Kun päivämäärän valitsee, sivu alkaa päivittämään itseään mutta lopputuloksena varauksen tiedoissa ei ole tapahtunut mitään muutosta.

Nämä varausmuutokset sivulla toimivat kuten pitää:
- uuden varauksen tekeminen
- varauksen siirto jonossa nuolilla ja numerovalikolla
- keskeytetyn varauksen jatkaminen
- kiinni jääneen varauksen tilan peruminen
- varauksen peruminen Peruuta-napista
- varauksen noutopaikan vaihtaminen

**Comment by emta001** [comment]
> Varauksen keskeyttäminen määräajaksi ei vaikuttaisi toimivan. Kun päivämäärän valitsee, sivu alkaa päivittämään itseään mutta lopputuloksena varauksen tiedoissa ei ole tapahtunut mitään muutosta.
> 

Sinne tulee POST virhe:

`POST http://127.0.1.1:8080/api/v1/holds/77174/suspension -> 400 Bad Request`

**Comment by emta001** [comment]
> > Varauksen keskeyttäminen määräajaksi ei vaikuttaisi toimivan. Kun päivämäärän valitsee, sivu alkaa päivittämään itseään mutta lopputuloksena varauksen tiedoissa ei ole tapahtunut mitään muutosta.
> 
> Sinne tulee POST virhe:
> 
> `POST http://127.0.1.1:8080/api/v1/holds/77174/suspension -> 400 Bad Request`

Tämäkin on nyt korjattu ja tuotu nexteille. Tuo endpoint haluaa JSON-dataa, mutta sai jotain ihan muuta :D

**Comment by ajrajala** [comment]
Keskeytystä ja varauksen jatkamista testattu uudestaan (määräajalla ja ilman), nyt toimii kuten pitää!

**Comment by Kati-Helle** [comment]
Testasin Hellessä. Hienostii toimii varauksen keskeyttäminen tietueen varauksissa päiväyksellä tai ilman.

**Comment by emta001** [comment]
Tämäkin lienee kunnossa. Suljen tiketin tältä erää.
