### ISSUE TITLE
Sivutus tietueen Varaukset-sivulle - ksdev/ks-0015-bug-23269

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-22x#56]
### Siirrettävä ominaisuus

Kohan oma Varaukset-sivu on liian hidas ladata. Koha-Suomen versio toimii APIn kautta jotta lista voidaan sivuttaa.

**Comment by emta001** [comment]
Tuotu testeille.

**Comment by ajrajala** [comment]
[Toisen tiketin](https://github.com/KohaSuomi/Koha-22x/issues/69) testauksen yhteydessä huomasin, että suomenkielellä Kohaa käytettäessä varausjono ei lataudu laisinkaan eikä siihen auta vaikka sivun lataisi tai tietueen hakisi uudestaan. "Näytä aina varaukset" -rastin klikkailu ei myöskään auta. Muistelen aiemmin varausten latautuneen suomeksikin käyttäessä, joten voiko olla että sivutus on rikkonut tässä jotain?

**Comment by emta001** [comment]
> [Toisen tiketin](https://github.com/KohaSuomi/Koha-22x/issues/69) testauksen yhteydessä huomasin, että suomenkielellä Kohaa käytettäessä varausjono ei lataudu laisinkaan eikä siihen auta vaikka sivun lataisi tai tietueen hakisi uudestaan. "Näytä aina varaukset" -rastin klikkailu ei myöskään auta. Muistelen aiemmin varausten latautuneen suomeksikin käyttäessä, joten voiko olla että sivutus on rikkonut tässä jotain?

Siellä ei ole vielä meidän käännökset paikallaan, voi johtua siitä. Ajatuksena on ollut siirtää käännökset omaan repoon, mutta toteutus on vielä hieman vaiheessa.

**Comment by ajrajala** [comment]
Sellainen huomio, että Varaukset-sivulla on nyt ainoastaan mahdollista siirtyä seuraavalle/edelliselle sivulle, mutta ei suoraan tietylle sivulle (tuotannossa olevat sivunumerolinkit siis puuttuu).

**Comment by emta001** [comment]
> Sellainen huomio, että Varaukset-sivulla on nyt ainoastaan mahdollista siirtyä seuraavalle/edelliselle sivulle, mutta ei suoraan tietylle sivulle (tuotannossa olevat sivunumerolinkit siis puuttuu).

Tutkin tätä joku aika sitten ja vaikuttaisi sille, että käyttöliittymämuutoksen myötä kaikki Kohan taulukot käyttäytyvät nyt näin. En saanut myöskään numerointia lisättyä erikseen tuonne Varaukset-sivulle. Hieman köpsä muutos, pitää vielä tutkia miksi ihmeessä tämmöinen muutos on tuonne viety.

**Comment by AnneliO** [comment]
Hmm.. Vaaran nextillä näkyvät kyllä sivunumerot ja niitä voi myös käyttää. 

![kuva](https://user-images.githubusercontent.com/33121325/230042069-f1041de8-aaad-42dc-99b9-4d3b496baade.png)

**Comment by emta001** [comment]
> Hmm.. Vaaran nextillä näkyvät kyllä sivunumerot ja niitä voi myös käyttää.
> 
> ![kuva](https://user-images.githubusercontent.com/33121325/230042069-f1041de8-aaad-42dc-99b9-4d3b496baade.png)

Outoa, mikähän niihin sitten vaikuttaa. Mitenhän muilla nexteillä mahtaa olla?

**Comment by AnneliO** [comment]
OUTIssa ei näy:
![kuva](https://user-images.githubusercontent.com/33121325/230047473-7db60575-3e36-4d57-aedc-20dded546cb4.png)

**Comment by emta001** [comment]
> OUTIssa ei näy: ![kuva](https://user-images.githubusercontent.com/33121325/230047473-7db60575-3e36-4d57-aedc-20dded546cb4.png)

Eli Vaarassa on nyt jotain eri tavalla. Sen kun osais taas arvata että mikä :D

**Comment by Kati-Helle** [comment]
Hellessäkään ei näy sivunumerolinkkejä
![kuva](https://user-images.githubusercontent.com/99952449/230057304-15b48cce-14f0-4d2f-bc1f-c4e51ce74157.png)

**Comment by AnneliO** [comment]
Tyhjensin Evästeet ja sivustotiedot sekä Historiatiedot Firefoxin asetuksista, niin sivunumerot tulivat mulla näkyviin OUTIssa, missä ne ei ennen tyhjennystä näkyneet.

Kokeiletteko muutkin? :)

**Comment by Kati-Helle** [comment]
Minulle sivunumerot eivät edelleenkään näy.

**Comment by AnneliO** [comment]
> Minulle sivunumerot eivät edelleenkään näy.

Varmistan, että poistithan kaikki historiatiedot, ei vain osaa? :)

Ja selaimen kiinni tyhjennyksen jälkeen?

**Comment by Kati-Helle** [comment]
Kyllä vain ja kirjauduin noin tehden ulos kaikista toiminnoita, joihin olin kirjautunut :) 
Tein nyt vielä nuo kaikki poistamiset uudestaan ja suljin selaimen.

Mutta ei edelleenkään sivunumeroita näkyvillä 
![kuva](https://user-images.githubusercontent.com/99952449/230068969-b4b9a6ae-753c-4436-868c-72d150b0c927.png)

**Comment by ajrajala** [comment]
Minulla sivunumerot on palanneet takaisin näkyville. Evästeet ja sivustotiedot sekä historiatiedot on tässä välissä tyhjentyneet automaattisesti, joten hyvinkin saattoi olla niistä kiinni.

**Comment by emta001** [comment]
> Minulla sivunumerot on palanneet takaisin näkyville. Evästeet ja sivustotiedot sekä historiatiedot on tässä välissä tyhjentyneet automaattisesti, joten hyvinkin saattoi olla niistä kiinni.

Näkyykö siulla myös "First" ja "Last" namiskat? Nekin näemmä puuttuvat.

**Comment by ajrajala** [comment]
Nekin painikkeet näkyvät (ja toimivat).
![kuva](https://user-images.githubusercontent.com/44638512/231066999-60933e7e-105e-41a4-8537-e00dd09e199d.png)

**Comment by AnneliO** [comment]
> Nekin painikkeet näkyvät (ja toimivat). ![kuva](https://user-images.githubusercontent.com/44638512/231066999-60933e7e-105e-41a4-8537-e00dd09e199d.png)

Minusta tuossa kuvassa ei ole Viimeinen ja Ensimmäinen -kohtia, ellen ihan sokia ole. ;)

**Comment by ajrajala** [comment]
Äh, sori, ajattelin koko ajan noita edellinen ja seuraava -painikkeita. Meillä näkyy tuotannossakin pelkästään ne?

**Comment by emta001** [comment]
Hmm, luulis että nekin ois tullut ton tyhjentelyn jälkeen näkyville jos ovat näkyäkseen. Siellä on varmaan vielä jotain mikä kinnaa.

**Comment by velimarj** [comment]
OUTIssa myös numerot ja edellinen/seuraava -painikkeet näkyvät ja toimivat. Noita ensimmäinen/viimeinen -painikkeita puolestaan ei näy meilläkään nextillä tai tuotannossa.

**Comment by emta001** [comment]
Jaahas :D no sitten ne eivät oo olleet siellä käytössä syystä tai toisesta. Tarvitsisiko olla?

**Comment by AnneliO** [comment]
Sanoisin, että koska olemme pärjänneet ilman tähänkin mennessä, niin tutkitaan ongelmaa versionvaihdon jälkeen. :)

**Comment by emta001** [comment]
Hmmm, laitetaanko tälle tiketille sulku vai odottaa tila?

**Comment by AnneliO** [comment]
Jos tekis noista first/last-namiskoista oman tikettinsä ja jos kukaan ei keksi mitään ongelmia liittyen sivutukseen, niin sitten vois sulkea tän tiketin.

**Comment by emta001** [comment]
> Jos tekis noista first/last-namiskoista oman tikettinsä ja jos kukaan ei keksi mitään ongelmia liittyen sivutukseen, niin sitten vois sulkea tän tiketin.

Tehdään näin.

**Comment by AnneliO** [comment]
Sellainen tuli mieleen, että se taustatyö-ilmoitus ei näy edelleenkään. Oliko meillä tarkoitus saada se näkyville?

**Comment by emta001** [comment]
> Sellainen tuli mieleen, että se taustatyö-ilmoitus ei näy edelleenkään. Oliko meillä tarkoitus saada se näkyville?

Muistelisin, että siitä on tiketti ihan täällä versionvaihdossa.

**Comment by MikkoLiimatainen** [comment]
Sivunumerointi tulee näkyviin tiedostossa https://vaski-next.koha-suomi.fi/intranet-tmpl/prog/css/staff-global_22.1100001.css olevan säännön takia:

```
@media only screen and (min-width:1500px) {
 .dataTables_wrapper .dataTables_paginate span .ellipsis,
 .dataTables_wrapper .dataTables_paginate span .paginate_button {
  display:inline-block
 }
}
```

Samassa tiedostossa näyttää olevan sääntö, joka piilottaa sivunumerot:

```
.dataTables_wrapper .dataTables_paginate span .ellipsis,
.dataTables_wrapper .dataTables_paginate span .paginate_button {
 display:none
}
```
Eli sivun leveyden tulee olla vähintään 1500px, jotta sivunumerointi näkyy. Voisikohan tuota 1500px pudottaa hieman pienemmäksi, jotta sivunumerointi toimisi pienemmissäkin ikkunoissa?

**Comment by emta001** [comment]
> Eli sivun leveyden tulee olla vähintään 1500px, jotta sivunumerointi näkyy. Voisikohan tuota 1500px pudottaa hieman pienemmäksi, jotta sivunumerointi toimisi pienemmissäkin ikkunoissa?

Hmm, pitää tutkia. En oo ihan varma kuinka näihin tehdään muutoksia (ja tätä pitäis myös ehdottaa yhteisöön).

**Comment by ghost** [comment]
> Sellainen tuli mieleen, että se taustatyö-ilmoitus ei näy edelleenkään. Oliko meillä tarkoitus saada se näkyville?

Taustatyöilmoituksen näkymättömyyden syy on edelleen arvoitus: https://github.com/KohaSuomi/Koha-22x/issues/37

**Comment by emta001** [comment]
> Sivunumerointi tulee näkyviin tiedostossa https://vaski-next.koha-suomi.fi/intranet-tmpl/prog/css/staff-global_22.1100001.css olevan säännön takia:
> 
> ```
> @media only screen and (min-width:1500px) {
>  .dataTables_wrapper .dataTables_paginate span .ellipsis,
>  .dataTables_wrapper .dataTables_paginate span .paginate_button {
>   display:inline-block
>  }
> }
> ```
> 
> Samassa tiedostossa näyttää olevan sääntö, joka piilottaa sivunumerot:
> 
> ```
> .dataTables_wrapper .dataTables_paginate span .ellipsis,
> .dataTables_wrapper .dataTables_paginate span .paginate_button {
>  display:none
> }
> ```
> 
> Eli sivun leveyden tulee olla vähintään 1500px, jotta sivunumerointi näkyy. Voisikohan tuota 1500px pudottaa hieman pienemmäksi, jotta sivunumerointi toimisi pienemmissäkin ikkunoissa?

Tämä pitää tosiaan korjata yhteisössä asti, mutta sen aikaa seuraavan rimpsun pitäisi korjata tilanne:

```
@media only screen and (min-width: 1000px) {
    .dataTables_wrapper
        .dataTables_paginate
            span
                .paginate_button,
                .ellipsis {
                    display: inline-block;
                }
}
```
Tuota min-widthiä voi säätää tarpeen mukaan.

**Comment by AnneliO** [comment]
Lisäsin Emmin rimpsun [IntranetUserCSS-wikiin](https://github.com/KohaSuomi/Koha-22x/wiki/IntranetUserCSS#vahvasti-suositeltavat) vahvasti suositeltaviin.

**Comment by MikkoLiimatainen** [comment]
Nähdäkseni tuon rimpsun tulee olla tässä muodossa, jotta tuo ellipsis toimii:
```
@media only screen and (min-width: 1000px) {
    .dataTables_wrapper
        .dataTables_paginate
            span
                .paginate_button,
    .dataTables_wrapper
        .dataTables_paginate
            span
                .ellipsis {
                    display: inline-block;
                }
}
```
Testasin tuota nidehaun tuloksissa, joka myös käyttää näitä paginate-linkkejä. Suurella tulossivujen määrällä nuo kolme pistettä (ellipses) katosivat alkuperäisellä rimpsulla eri tahtiin sivun kokoa muutettaessa. Tämä rimpsu korjaa tuon ongelman.

**Comment by AnneliO** [comment]
Vaihdoin IntranetUserCSS-sivulle Mikon päivitetyn version.

**Comment by MikkoLiimatainen** [comment]
Näyttäisi siltä, että ainakin tietyillä tablettimallella tuo min-width täytyy pudottaa jonnekin 600px tuntumaan, jotta saa pystyasennossa sivunumeroinnin näkymään esim. hyllyvaraukset-raportilla. Mutta tuo on kyllä hyvä, että sen voi omien tarpeiden mukaan säätää. Mihinkään poikkeukselliseen toimintaan en toistaiseksi tuon testailussa ole törmännyt, joten min-width -arvon voinee melko huoletta valita pienimmän laitteen resoluution mukaan.

**Comment by AnneliO** [comment]
Onko tässä vielä jotain vai voiko tiketin sulkea?

**Comment by emta001** [comment]
> Onko tässä vielä jotain vai voiko tiketin sulkea?

Hmm, ainakin tiketissä mainitut ongelmat on suurimmilta osin korjattu. Toki sivulistalta uupuu vielä "First" ja "Last" namiskat, mutta voisiko siitä avata oman tiketin (jos on tarvetta)?

**Comment by AnneliO** [comment]
[Tein first/last-ongelmasta tiketin Koha-repositorioon](https://github.com/KohaSuomi/Koha/issues/523).

Suljen tämän tiketin, avataan tarvittaessa uusia.
