### ISSUE TITLE
Kohan itsepalvelun palautus-toiminto - ksdev/ks-0020-bug-22322

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-22x#57]
### Siirrettävä ominaisuus

Koha-Suomelle lisätty toiminnalisuus, jolla lainat voidaan palauttaa omatoimen kautta ilman kirjautumista.

**Comment by lmstrand** [comment]
Viety nexteille testattavaksi (branch ksdev/ks-0020-K22-57-SCOreturns).

**Comment by AnneliO** [comment]
Pikaisen testin perusteella palautustoiminto toimii.

**Comment by pirliis** [comment]
Testasin OUTIssa ja näytti toimivan.

**Comment by lmstrand** [comment]
Suljen tiketin.
