### ISSUE TITLE
Asiakastiedot: huollettavan muokkausnäytöllä ei näy kirjastokortittomasta huoltajasta/takaajasta mitään tietoja - ksdev/ks-0021-bug-29768

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-22x#58]
### Siirrettävä ominaisuus

Hidepatronname järjestelmäasetus piilottaa takaajan tiedot täysin, jos tällä ei ole kirjastokorttia. Ehdotettu yhteisöön.

**Comment by emta001** [comment]
Tuotu testeille. Tämän testaamisessa kannattaa ottaa huomioon, että muutos ei vaikuta vain takaajan tietoihin muokkaus näytöllä, vaan moneen muuhunkin linkkiin. Jos siis näkyy sellaisia sivuja, joissa esim. breadcrumpseissa näkyy linkki väärällä tavalla, niin ne ovat voineet syntyä tämän muutoksen myötä. 

![Image](https://user-images.githubusercontent.com/37581745/219571797-75a75be7-c072-4518-9a8b-a5c83e72fbf7.png)

Kuvassa esimerkki hyvin käyttäytyvästä breadcrumpsista.

**Comment by Kati-Helle** [comment]
Helle-nextilä HidePatronName=Älä näytä
Kortittoman takaajan nimi näkyy huollettavan asiakkaan muokkausnäytöllä (ja tiedot-näytöllä myös)
![kuva](https://user-images.githubusercontent.com/99952449/226299445-31d2aeae-159a-4314-b3b5-4a50b89d4fc9.png)

Kirjastokortittoman takaaja-asiakastiedon muokkausnäytöllä Emmin mainitsema breadcrump käyttäytyy hyvin
![kuva](https://user-images.githubusercontent.com/99952449/226298598-7ca0b0e4-155e-444a-90e9-73c6043aba61.png)

**Comment by ajrajala** [comment]
Samat havainnot kuin Katilla. Kävin myös kortittoman takaajan eri välilehdet läpi (Lainaus, Tiedot, Maksut jne) ja breadcrumpsit käyttäytyi eri sivuilla hyvin.

**Comment by AnneliO** [comment]
Minun testien mukaan myös toimii hyvin.

**Comment by emta001** [comment]
Tämä siis vaikuttaisi olevan ok. Suljen tiketin.
