### ISSUE TITLE
Palautuskehotusmaksun määrittely - ksdev/ks-0023-KD-4635

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-22x#59]
### Siirrettävä ominaisuus

Myöhästymisilmoitusten määrittely -sivulla voi määrittää asiakastyyppikohtaisesti, mikä summa asiakkaalta veloitetaan palautuskehotuksen lähettämisestä. Maksun voi määrittää erikseen 1.-3. ilmoitukselle.

**Comment by emta001** [comment]
Onko tämä tuotu yhteisöstä bugista [13816](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=13816) vai onko tästä tehty uusi versio? Niin tai näin, yhteisön bugia voisi edistää.

**Comment by AnneliO** [comment]
Tämä on riippuvainen overdue_notices.pl cron jobista.

**Comment by Kati-Helle** [comment]
Helle-nextissä on muodostunut oikein 8 vuorokautta eräpäivästä 1. huomautuksen maksu 2€ (asiakastyypille Aikuinen, asiakas ID 13356)
![kuva](https://user-images.githubusercontent.com/99952449/226611731-473acdb7-b29c-4157-b3e0-238179fff1d6.png)

Mistä osaakaan ottaa huomautuksen maksun määrän, kun myöhästymistoiminnon määrittelyssä maksumäärää ei ole?
![kuva](https://user-images.githubusercontent.com/99952449/226613494-241a39f9-e73f-411d-b056-4e83dcd65891.png)

**Comment by AnneliO** [comment]
> Mistä osaakaan ottaa huomautuksen maksun määrän, kun myöhästymistoiminnon määrittelyssä maksumäärää ei ole? ![kuva](https://user-images.githubusercontent.com/99952449/226613494-241a39f9-e73f-411d-b056-4e83dcd65891.png)

Jos vaihdat englanninkieliseksi liittymän, niin siellä näkyy maksun määrittely. :)

**Comment by Kati-Helle** [comment]
Jep, tuolla Fine arvolla 2 siis näkyvissä
![kuva](https://user-images.githubusercontent.com/99952449/226812512-4bd89293-2b77-4ac6-a55a-9244b616de51.png)

**Comment by ajrajala** [comment]
Katselin Vaski-nextillä muodostuneita ODUE1 ja ODUE2 -ilmoituksia, maksut näyttivät muodostuneen oikein silloin kun pitikin.

**Comment by ReettaSiili** [comment]
En varsinaisesti testannut tämän toimintaa Siilissä, sillä vieläkään ei taida olla ratkaisua meidän ongelmaan: sähköpostimuistutus ei maksa mitään (suurin osa viesteistä), printtimuistutus maksaa 1 € (yksittäisiä muistutuksia), maksun määrittely ei meillä toimi. Lisäämme printtimuistutuksesta siis maksun jatkossakin käsin, no problem.

**Comment by AnneliO** [comment]
Katselin Vaara-nextillä muodostuneita ODUE-maksuja ja ne näyttivät muodosteen oikein.

**Comment by emta001** [comment]
Tämäkin lienee ok. Suljen tiketin.
