### ISSUE TITLE
Signum- ja pääsanapluginit - ksdev/ks-0027-KD-4589

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#6]
### Siirrettävä ominaisuus

Signumeita ja pääsanoja varten on tehty monenlaisia liitännäisiä:

084a_mainheading_branch_loc_signum_builder.pl
084a_mainheading_branchloc_genre_signum_builder.pl
084a_mainheading_branchloc_signum_builder.pl
084a_mainheading_loc_signum_builder.pl
brancloc_084a_mainheading_signum_builder.pl
fi_JSON_084a_signum_builder_subfields.pl
fi_JSON_942khm.pl
fi_paakirjaus.pl
fi_paakirjaus_ohitusind_3merkkia.pl
fi_signumbuilder_942k_branchloc_942hm.pl
fi_signumbuilder_942k_loc_942hm.pl
fi_signumbuilder_942k_loc_ccode_942hm.pl
fi_signumbuilder_942khm_branch_loc.pl
fi_signumbuilder_942khm_branchloc.pl
fi_signumbuilder_942khm_branchloc_genre.pl
fi_signumbuilder_942khm_loc.pl
loc_084a_maingeading_signum_builder.pl
loc_ccode_084a_maingeading_signum_builder.pl
ykl_from_084a.pl

Onko kaikki tarpeellisia edelleen?

**Comment by ghost** [comment]
Olivat niin pienillä muutoksilla yhteensopivia uuden version kanssa että otin varmuuden vuoksi kaikki mukaan.

**Comment by pirliis** [comment]
Pluginit eivät ole valittavissa luettelointipohjien Liitännäinen-valikossa.

**Comment by ghost** [comment]
Jääneet buildista pois, seuraavaan tulevat mukaan.

**Comment by Kati-Helle** [comment]
loc_ccode_084a_maingeading_signum_builder.pl  
Helle-nextillä toimii oikein sekä uutta nidettä lisätessä että jo olemassa olevaa nidettä muokatessa.

**Comment by pknuuti** [comment]
Vaaran nextillä toimii Liitännäinen:branchloc_084a_mainheading_signum_builder.pl, sekä uutta lisättäessä että olemassa olevaa nidettä muokattaessa.

**Comment by ajrajala** [comment]
Vaski-nextillä testattu toimivaksi liitännäinen loc_ccode_084a_mainheading_signum_builder.pl. Testattu samalla, että mukana on [tiketin 288](https://github.com/KohaSuomi/Koha/issues/288) muutos.

**Comment by AnneliO** [comment]
Testattu:

- [x] 084a_mainheading_branch_loc_signum_builder.pl
- [x] 084a_mainheading_branchloc_genre_signum_builder.pl
- [x] 084a_mainheading_branchloc_signum_builder.pl
- [x] 084a_mainheading_loc_signum_builder.pl
- [x] brancloc_084a_mainheading_signum_builder.pl
- [x] fi_JSON_084a_signum_builder_subfields.pl
- [x] fi_JSON_942khm.pl
- [x] fi_paakirjaus.pl
- [x] fi_paakirjaus_ohitusind_3merkkia.pl
- [x] fi_signumbuilder_942k_branchloc_942hm.pl
- [x] fi_signumbuilder_942k_loc_942hm.pl
- [x] fi_signumbuilder_942k_loc_ccode_942hm.pl
- [x] fi_signumbuilder_942khm_branch_loc.pl
- [x] fi_signumbuilder_942khm_branchloc.pl
- [x] fi_signumbuilder_942khm_branchloc_genre.pl
- [x] fi_signumbuilder_942khm_loc.pl
- [x] loc_084a_maingeading_signum_builder.pl
- [x] loc_ccode_084a_maingeading_signum_builder.pl
- [x] ykl_from_084a.pl

**Comment by Tuomas-Kyyti** [comment]
Kyytissä käytettävä 084a_mainheading_branch_loc_signum_builder.pl toimii.

**Comment by AnneliO** [comment]
Testasin 942-kenttiin liittyvät liitännäiset:
* ykl_from_084a.pl - toimii 
* fi_signumbuilder_942khm_loc.pl - toimii 'AIK 65.43 KRA AIK', mutta hassu tuplatietojen vuoksi.
* fi_signumbuilder_942khm_branchloc_genre.pl - toimii 'AIK 65.43 KRA JOEAIK', mutta genreä ei enää ole olemassa eli sitä ei tullut luonnollisesti mukaan. 
* fi_signumbuilder_942khm_branchloc.pl - toimii 'AIK 65.43 KRA JOEAIK', mutta onhan tuo hassu, kun hyllypaikka tulee sekä 942khm:stä että branchlocista.
* fi_signumbuilder_942khm_branch_loc.pl - toimii 'AIK 65.43 KRA JOE AIK', mutta onhan tuo hassu, kun hyllypaikka tulee sekä 942khm:stä että locista.
* fi_signumbuilder_942k_loc_ccode_942hm.pl - toimii 'AIK AIK_NA 65.43 KRA', mutta edelleen hassu tuplatietojen vuoksi.
* fi_signumbuilder_942k_loc_942hm.pl - toimii 'AIK AIK 65.43 KRA', mutta hassu tuplatietojen vuoksi.
* fi_signumbuilder_942k_branchloc_942hm.pl - toimii 'AIK JOEAIK 65.43 KRA', mutta hassu tuplatietojen vuoksi.

**Comment by ghost** [comment]
fi_JSON-alkuisia käytetään noissa muissa, nekin voi merkitä testatuiksi.

**Comment by ReettaSiili** [comment]
Siilissä käytössä sama 084a_mainheading_branch_loc_signum_builder.pl kuin Kyytissä ja toimii.

**Comment by AnneliO** [comment]
fi_paakirjaus_ohitusind_3merkkia.pl sinänsä kyllä toimii, mutta ei ehkä nimensä mukaisesti. En kyllä ole varma, miten sen kuuluisi toimia. Ainakaan se ei ota huomioon ohitusindikaattoreita, kuten nimestä voisi päätellä. Jos pääkirjaus on esim. A street, tulee pääkirjaukseksi "A S".

**Comment by AnneliO** [comment]
fi_paakirjaus.pl toimii, hakee 245a-kentästä tiedon. Sitä en tiedä, kuuluisiko sen toimia noin.

**Comment by AnneliO** [comment]
* 084a_mainheading_branchloc_genre_signum_builder.pl - ei toimi, ei tuota mitään. Kenttään jää näkyville siinä jo ennestään oleva luokka ja kenttä lukittuu. Toisaalta, tämä on aika turha, koska genre-saraketta ei enää ole olemassa.
* 084a_mainheading_branchloc_signum_builder.pl - toimii
* 084a_mainheading_loc_signum_builder.pl -toimii

**Comment by AnneliO** [comment]
Testasin nyt vielä kuitenkin nuo JSON-builderitkin ja

* fi_JSON_084a_signum_builder_subfields.pl - ei toimi, ei tuota mitään. Kolmea pistettä painaessa hypätään sivun alkuun.
* fi_JSON_942khm.pl - ei toimi,  ei tuota mitään. Kolmea pistettä painaessa hypätään sivun alkuun.

**Comment by AnneliO** [comment]
Käyttääkö kukaan noita JSON-versioita? Jos ei, niin niiden korjaamiseen ei kannata käyttää aikaa.

**Comment by ghost** [comment]
JSON-buildereita käytetään muissa buildereissä apuna, toimivat oikein.

**Comment by AnneliO** [comment]
Tämän voinee sulkea?

**Comment by ghost** [comment]
Käytössä olevat pluginit ilmeisesti toimivat oikein, voi sulkea.
