### ISSUE TITLE
Add a script to manage plugins from the command line - ksdev/ks-0049-bug-30999-manage-plugins-script 

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-22x#60]
### Siirrettävä ominaisuus

Skripti jolla voidaan hallita plugineita myös komentoriviltä.

**Comment by paxed** [comment]
Tämä lienee järkevintä siirtää koha-suomi-utilityyn.

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 4.5.2023: Toiminto ei ole tarpeellinen. Ei siirretä.
