### ISSUE TITLE
Jos noudettavan varauksen laittaa kuljetustilaan, rikkoutuu varaus ja hyllyvarausraportti ei toimi sen jälkeen - ksdev/ks-0053-KD-5484

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-22x#61]
### Siirrettävä ominaisuus

Jos varauksen laittaa kuljetukseen joko siirto-toiminnolla tai palauttamalla noudettavissa olevan varauksen muualla kuin noutokirjastossa, katoaa varauksesta nidetieto. Tämän jälkeen hyllyvarausraportti ei toimi, koska kysely kaatuu rikkinäiseen varaukseen.

Jos noudettavissa olevan varauksen palauttaa tuotannossa toisessa kirjastopisteessä, saa virkailija Virhe 500 -ilmoituksen.

**Comment by AnneliO** [comment]
Jos noudettavissa olevan varauksen yrittää laittaa siirto-toiminnolla kuljetukseen toiseen kirjastoon tulee enää seuraavat vaihtoehdto tarjolle:
![kuva](https://user-images.githubusercontent.com/33121325/223415575-5db5d86c-69b0-4f61-9968-868e47aae30f.png)

Eli nidettä ei saa laitettua kuljetustilaan.

Jos taas noudettavissa olevan niteen palauttaa toisessa kirjastossa, tulee ilmoitus varauksesta ja varausmenee kuljetettavaksi noutokirjastoon:
![kuva](https://user-images.githubusercontent.com/33121325/223416077-959ca2e3-3f18-4d85-9a0f-1792a5f33740.png)

Nide sen sijaan ei mene kuljetustilaan kuin vasta toisella palautuskerralla:

1. palautus
![kuva](https://user-images.githubusercontent.com/33121325/223416947-d297c525-3f04-486e-8a6a-fda02e0b705f.png)

2. palautus
![kuva](https://user-images.githubusercontent.com/33121325/223417080-36307bb9-aaf9-4843-a01c-0775f8a55818.png)

Mutta tämä sinänsä ei liittyne tähän ongelmaan. :D

En pystynyt vielä testaamaan hyllyvarausraporttia, koska Koha-Suomen omaa perdingreserves-raporttia ei vielä ole siirretty. #2

**Comment by AnneliO** [comment]
Yritin kaikkeni, mutta en saanut hyllyvarausraporttia kyykättyä varauksilla ja kuljetuksilla. :)
