### ISSUE TITLE
Suojatut kentät näkyvät tyhjinä z39.50-haulla tietueita korvattaessa - ksdev/ks-0059-bug-30966

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-22x#62]
### Siirrettävä ominaisuus

Korjaus, jolla suojeltujen kenttien pitäisi näkyä jo siinä lomakkeessa.

**Comment by AnneliO** [comment]
Emmi tutkii, mikä tässä on tilanne.

**Comment by emta001** [comment]
Ei ole enää test-branch, unohtunut vain päivittää se listaan :D

**Comment by emta001** [comment]
Muutin tuon otsikon vastaamaan sitä mitä branchissa oikeasti tapahtuu. [5500](https://tiketti.koha-suomi.fi/issues/5500) mainitut kaksi muuta tikettiä ovat vielä vaiheessa. Toinen [#332](https://github.com/KohaSuomi/Koha/issues/332) pitäisi testata uudessa versiossa, mutta z39.50-haku ei toimi. Toinen [#333](https://github.com/KohaSuomi/Koha/issues/333) pitäisi jakaa vielä kahteen eri tikettiin.

**Comment by emta001** [comment]
Ja tämän tiketti GitHubissa on siis tosiaan [#331](https://github.com/KohaSuomi/Koha/issues/331).

**Comment by emta001** [comment]
Viety testeille, testisuunnitelma:

1) Luo MARC-yhdistelyn sääntö z39.50:lle.
2) Importtaa tietue z39.50 kautta.
3) Suojeltujen kenttien tietojen pitäisi säily editorissa.

**Comment by Kati-Helle** [comment]
Testini perusteella toimii oikein.

Helle-next-tietueella on yhdistelysääntöihin määritelty kenttä 942c=KIRJA
![kuva](https://user-images.githubusercontent.com/99952449/227506080-a386e6c4-5d8b-4ece-8311-a0fb329529d0.png)

Korvasin Helle-next-tietueen Melinda-tietueella.
![kuva](https://user-images.githubusercontent.com/99952449/227507294-b48699f2-c2b1-4b7e-9ca7-c49c28267ccc.png)

![kuva](https://user-images.githubusercontent.com/99952449/227507354-4652732c-bd7b-496b-9606-059087011382.png)

Helle-nextissä tietueen muokkauksessa näkyy yhdistelysäännöin suojattu kenttä 942c=KIRJA heti tietuekorvauksen jälkeen 
![kuva](https://user-images.githubusercontent.com/99952449/227507730-780c38f6-f4c3-4ffe-af0e-6b1bceebf44d.png)

**Comment by ajrajala** [comment]
Vaski-nextillä testattu, toimii kuten pitää.

**Comment by AnneliO** [comment]
Testasin Vaara-nextillä ja suojatut 856 ja 942-kentät näkyivät editorissa ja säilyivät tallennuksen jälkeen.

**Comment by emta001** [comment]
Suljen tämänkin.
