### ISSUE TITLE
Ilmoituspohjan kopiointi kirjastolta toiselle ei onnistu, kun kopion kohdekirjaston jollain ilmoituspohjalla on sama tunnus kuin kopioitavalla ilmoituspohjalla - ksdev/ks-0062-bug-24616

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-22x#63]
### Siirrettävä ominaisuus

Otsikko lienee tarpeeksi tyhjentävä selitys ongelmasta.

Muutos ehdotettu yhteisöön ja mennyt sinne läpikin, mutta se ei kerennyt tähän uuteen versioon.

**Comment by emta001** [comment]
Tuotu testeille.

Testaus:
1) Yritä kopioida kirjastolle sellainen ilmoituspohja, joka sillä jo on.
2) Pohjaa tallentaessa pitäisi tulla varmistus pop-up, jossa ilmoitetaan että pohja on jo olemassa kyseisessä kirjastossa ja haluatko varmasti tallentaa pohjan.
3) Kun painaa OK, pohjan tulisi tallentua kirjastolle oikein.

**Comment by piiaseme** [comment]
Testasin ohjeen mukaan. En muokannut tallennettavaa ilmoituspohjaa lainkaan.

Sain varmistuspopparin, jossa ilmoitettiin, että pohja on jo olemassa ja että haluanko ylikirjoittaa olemassa olevan pohjan tällä uudella. Klikkasin OK ja pohja tallentui kuten pitää.


![Image](https://user-images.githubusercontent.com/98805552/224039973-51e0aa18-c2e2-4d8e-9caa-f4b1b65d98a4.png)

**Comment by Kati-Helle** [comment]
Testasin Helle-nextillä: oikein toimii.

**Comment by emta001** [comment]
> Testasin ohjeen mukaan. En muokannut tallennettavaa ilmoituspohjaa lainkaan.

Juu se kyselee tuota vaikkei pohjaa muokkaisi. Jos tätä haluis muuttaa niin että kysytään vaan kun tulee muutoksia, pitäs tutkia ja vertailla pohjan uutta sisältöä vanhaan sisältöön. Onnistuisi, mutta tuskin kovin helposti :D 

Mutta tämäkin vaikuttaisi siis toimivan kuten pitää. Suljen tiketin, avataan uudestaan jos tarvetta.
