### ISSUE TITLE
Hankintahaun hitaus ja valikko-ongelma - ksdev/ks-0063-KD-5563

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-22x#64]
### Siirrettävä ominaisuus

Hankitahaku on hidas johtuen GetBudgetHierarchy metodista.

Korjaus om mennyt yhteisön masteriin, muttei kerennyt uuteen versioon.

**Comment by emta001** [comment]
Tuotu testeille. Tätä ei oikein voi testata muuten kuin tekemällä hankintahaun ja katsomalla, ettei haussa kestä ikuisuutta.

**Comment by Kati-Helle** [comment]
Helle-nextillä haku vaikuttaa nopealta. 
Kokeilin hakua yhdellä hakuehdolla sekä useammalla hakuehdolla.

**Comment by ajrajala** [comment]
En huomannut hidastelua myöskään. Jos hakutulos oli oikein iso (esim. hankintahaku pelkällä toimittajan nimellä, tuloksia 8000-9000) niin nextillä hakutulossivu latautui kokonaan jopa hiukan tuotantoa nopeammin.

**Comment by emta001** [comment]
Suljen tiketin.
