### ISSUE TITLE
Koha::Biblio->get_components_query fetches too many component parts - ksdev/ks-0065-bug-31326

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-22x#65]
### Siirrettävä ominaisuus

Metodi "get_components_query" hakee liian monta osakohdetta.

Ehdotus mennyt yhteisön masteriin, muttei ole uudessa versiossa.

**Comment by AnneliO** [comment]
Tuodaan yhteisön masterista meidän versioon.

**Comment by emta001** [comment]
Tuotu testeille odottamaan, tätä ei voi testata ennen kuin #46 on ratkaistu.

Testausohje:
1) Laita QueryAutoTruncate automaattiseksi.
2) Etsi vanha osakohteellinen tietue.
3) Tarkista, että osakohde määrä täsmää.

Esimerkkejä tietueista, joissa ongelma on aiemmin havaittu (kerätty Redminen tiketistä [5544](https://tiketti.koha-suomi.fi/issues/5544))

- Lappi: 2053
- OUTI: 33167
- Vaara: 106909

**Comment by emta001** [comment]
#46 on korjattu, joten tätä voinee jo testata.

**Comment by AnneliO** [comment]
Mitään noista esimerkkitietueista ei ole siirtynyt redusoinnissa nexteille. Koitan etsiä, jos löytyisi jotain vastaavia, mutta se voi olla kyllä mahdotonta noin pienillä tietuemäärillä, mitä nexteillä on.

**Comment by AnneliO** [comment]
Juu, en löytänyt yhtään esimerkkiä Lapista, OUTIsta tai Vaarasta, eli tätä taitaa olla aika mahdotonta testata.

**Comment by emta001** [comment]
No voi hitsi. Voisihan sitä yrittää tuoda jonkun noista tuotannosta, mutta se onkin sitten kysymysmerkki miten se onnistuu :thinking: mutta ainahan voi kokeilla :D

**Comment by AnneliO** [comment]
Melkein pitäisi tuoda se osakohteita kerännyt tietue ja ne, jotka liimautuivat siihen.

**Comment by emta001** [comment]
Joo aika mahdottomaksi taitaa mennä.

**Comment by AnneliO** [comment]
Ehkä tämä pitää vain sitten tuotannossa testata.

**Comment by emta001** [comment]
Jätänkö tämänkin odottaa tilaan?

**Comment by AnneliO** [comment]
Tarkistin nuo mainitut tietueet Lapissa, OUTIssa ja Vaarassa, eikä ne keränneet itselleen osakohteita. Korjaus toiminee siis edelleen.

**Comment by emta001** [comment]
Loistavaa, suljen tiketin.
