### ISSUE TITLE
Raporttien vienti Finnan ymmärtämään JSON-muotoon - ksdev/ks-0066-KD-5573

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-22x#66]
### Siirrettävä ominaisuus

Plugin hook ja finnaprefix-järjestelmäasetus.

**Comment by Kaarius** [comment]
Tuotu testattavaksi nexteille.

**Comment by AnneliO** [comment]
Testaa näin:

1. Käy tarkistamassa Järjestelmäasetuksissa -> Paikalliset tiedot -> finnaprefix-asetuksessa, että siellä on oikea määritys. Todennäköisesti tietokannan nimen perää pitää lisätä _next. Esim. "vaarakirjastot_next.". Klikkaa Muokkaa-painiketta tarkastaaksesi siinä olevan arvon.
2.  Mene Raportit -> Tallennetut raportit -> Aja jokin raportti, jossa ensimmäisessä sarakkeessa on biblionumber. Esim. tämä Varatuimmat nimekkeet (lisää tämä, jos ennestään ei ole sopivaa raporttia):
```
SELECT
  b.biblionumber AS 'biblionumber',
  count(h.reservedate) AS 'Varauksia' 
FROM biblio b 
LEFT JOIN biblio_metadata m USING (biblionumber) 
LEFT JOIN reserves h ON (b.biblionumber=h.biblionumber) 
GROUP BY b.biblionumber 
ORDER BY Varauksia DESC
LIMIT 25
```
3. Valitse raportin tulosten yläpuolelta valikosta Lataa -> Finna JSON
4. Kirjaudu Finnaan ja mene Omat tiedot -välilehdelle.
5. Mene ihan alareunaan ja valitse Tuo suosikit ja haut tiedostosta.
6. Valitse juuri tallentamasi json-muotoinen tiedosto ja klikkaa _Lisää suosikit ja haut_.
7. Jos lisäys onnistui, saat raportin, jossa kerrotaan kuinka monta listaa ja suosikkia lisättiin.
8. Mene vielä Finnassa Suosikit-välilehdelle ja tarkista, että tuonti onnistui.
9. Käy muuttamassa finnaprefix-asetus alkuperäiseen muotoon, koska järjestelmäasetukset kopioidaan tuotantoon versionvaihdon yhteydessä.

**Comment by velimarj** [comment]
OUTIssa toimii kuten pitääkin.

**Comment by ajrajala** [comment]
Testasin tuon "Varatuimmat nimekkeet" -raportin tuontia json-muodossa. Näennäisesti tuonti onnistui, mutta kun menin katsomaan listaa Suosikit-välilehdellä, ei listalla ollut yhtään tietuetta.

finnaprefix-asetuksessa oli meillä entuudestaan 'vaskikoha.' Muutin sen muotoon 'vaskikoha_next.' Onkohan tuo nyt siis kuten pitääkin vai onko tuossa prefixissä jotain pielessä ja listan mukana ei sen takia siirry tietueiden tiedot..?

**Comment by emta001** [comment]
> Testasin tuon "Varatuimmat nimekkeet" -raportin tuontia json-muodossa. Näennäisesti tuonti onnistui, mutta kun menin katsomaan listaa Suosikit-välilehdellä, ei listalla ollut yhtään tietuetta.
> 
> finnaprefix-asetuksessa oli meillä entuudestaan 'vaskikoha.' Muutin sen muotoon 'vaskikoha_next.' Onkohan tuo nyt siis kuten pitääkin vai onko tuossa prefixissä jotain pielessä ja listan mukana ei sen takia siirry tietueiden tiedot..?

Hmm, ainakin OUTIssa siellä on nexteilläkin outi. niin pitäisiköhän Vaskissakin olla vain tuo vaskikoha. :thinking:

**Comment by velimarj** [comment]
Testasin tosiaan siten, että muutin tuon "outi." muotoon "outi_next.". Todettuani toimivaksi kävin jo muuttamassa takaisin tuohon alkuperäiseen muotoon, ettei unohdu.

**Comment by emta001** [comment]
> Testasin tosiaan siten, että muutin tuon "outi." muotoon "outi_next.". Todettuani toimivaksi kävin jo muuttamassa takaisin tuohon alkuperäiseen muotoon, ettei unohdu.

Ahaa, sitten Vaskissa on jotain hassusti.

**Comment by ajrajala** [comment]
Finnaprefixistä näytti olevan kiinni. Jostain syystä meillä on tuotannossa asetuksessa tuo 'vaskikoha' vaikka pitäisi olla Finnan tietue-linkkien perusteella pelkkä 'vaski'. Nyt kun muutin nextille finnaprefixiksi tietuelinkin mukaisesti 'vaski_next', latautui json-tiedosto suosikkilistaksi kuten pitääkin.

Eipä tullut heti mieleen, että asetus tuotannossa olisi väärin, ei vissiin ole sitten ollut noille Finnan json-muotoisille listoille tarvetta. 😃

**Comment by emta001** [comment]
Vaikuttaa toimivan kuten pitää. Suljen tiketin.
