### ISSUE TITLE
Error 500 tilauksen vastaanotossa - ksdev/ks-0079-bug-32472-acqorder-error

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-22x#67]
### Siirrettävä ominaisuus

Tilauksen vastaanotto epäonnistuu virheeseen:

"Template process failed: undef error - The method Koha::Item->count is not covered by tests!"

Tämän ei kuitenkaan pitäisi olla ongelmana uudessa versiossa, mutta tutkitaan vielä onko ongelma korjaantunut.

**Comment by Kati-Helle** [comment]
Testasin 
- vastaanottamalla osan tilauksen niteistä (5 tilattu, 4 vastaanotettu): OK (eli ei virheilmoitusta)
- vastaanottamalla yhden tilatun niteen tilauksen: OK (eli ei virheilmoitusta)

**Comment by AnneliO** [comment]
Tein pari erillistä vastaanottoa Vaski-nextillä ja niissä useampia teoksia, enkä saanut aikaiseksi virhettä 500.

**Comment by emta001** [comment]
Suljen tiketin, avataan uudestaan jos herja palaa.
