### ISSUE TITLE
Tietueen Varaukset-sivulla asiakas-sarakkeen tietoja ei ladata jos käyttäjältä puuttuu edit_borrowers-oikeus - ksdev/ks-0080-bug-32502-api-holds-permission

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-22x#68]
### Siirrettävä ominaisuus

Jos käyttäjällä ei ole edit_borrowers-oikeutta, mitään asiakas-sarakkeessa olevia tietoja ei ladata. APIa muutettu niin, että tiedot ladataan kun käyttäjällä on view_borrower_infos_from_any_libraries-oikeus.

**Comment by emta001** [comment]
Tuotu testeille. Varaukset-sivulla pitäisi näkyä asikas-sarakkeen tietojen pitäisi näkyä, kun käyttäjällä on view_borrower_infos_from_any_libraries-oikeus.

Yhteisön tiketti on tällä hetkellä "In discussion"-tilassa ja siinä on ehdotus view_borrowers oikeuden luomisesta.

**Comment by Kati-Helle** [comment]
Helle-nextillä tietueen Varaukset-sivun Asiakas-sarakkeessa näkyy varaajan kirjastokorttinumero (kirjastokorttinumerosta on linkki asiakastietoon). Koha-käyttäjätunnuksella on oikeus view_borrower_infos_from_any_libraries.
![kuva](https://user-images.githubusercontent.com/99952449/225600195-21250e89-2574-4abf-9adf-af12e6500ae9.png)

Kokeilin käyttäjätunnuksella, jolla ei ole oikeutta view_borrower_infos_from_any_libraries: Asiakas-sarakkeen arvon haku jää 'päälle'
![kuva](https://user-images.githubusercontent.com/99952449/225600953-b561708c-da15-4137-a968-0b5862d42927.png)

**Comment by ajrajala** [comment]
Vaski-nextillä vilkaistu tätä myös ja näyttää tosiaan toimivan toivotulla tavalla.

**Comment by AnneliO** [comment]
Testasin Vaara-nextillä ja toimii kuvatulla tavalla.

**Comment by emta001** [comment]
Suljen tiketin.
