### ISSUE TITLE
Varauksen priority-numeron muuttaminen tietueen varaukset-sivulla ei toimi oikein

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha-22x#69]
### Mikä vikana?

Tietueen varaukset-sivulla voi muuttaa varauksen jononumeroa valitsemalla jononumeron Priority-valikosta. Näyttää kuitenkin siltä, ettei sijoituksen muuttaminen tätä kautta toimi oikein vaan

- priority 1:n valitseminen siirtää varauksen aina priority 2:ksi
- priorityn muuttaminen alemmaksi (esim. 1 -> 3) ei tee yhtään mitään

Jos järjestystä varausjonossa muuttaa käyttämällä nuolipainikkeita, toimivat ne oikein.

### Kuinka toistaa ongelma/asia

1. Mene sivulle https://vaski-next.koha-suomi.fi/cgi-bin/koha/reserve/request.pl?biblionumber=4064791
2. Kokeile siirtää viimeisenä jonossa oleva varaus jonon ensimmäiseksi valitsemalla pudotusvalikosta 1 -> varaus saa jononumeron 2
3. Kokeile siirtää ensimmäisenä jonossa oleva varaus jonon viimeiseksi valitsemalla pudotusvalikosta 3 -> varausten prioriteetit eivät muutu

**Comment by AnneliO** [comment]
Testasin tätä myös PTFS Europen sandboxissa ja siellä tapahtuu samoin. En löytänyt tähän liittyen tikettiä yhteisössä.

Täysi arvaus, mutta voiskohan tämä liittyä jotenkin taustatöihin (background jobseihin).

**Comment by emta001** [comment]
Testailin tätä vaski-nextillä nyt, kun meidän varaus-sivu muutos (#56) on tuotu sinne, enkä havaitse että tämä olisi enää ongelma. Yhteisön masteria en vielä testannut.

**Comment by ajrajala** [comment]
Testasin myös itse uudelleen englanninkielisessä käyttöliittymässä ja toimii tosiaan nyt. Suomenkielellä käytettäessä varausjono ei lataudu näkyville ollenkaan, mutta kommentoin siitä jo tuohon tikettiin #56.

**Comment by emta001** [comment]
Pitää vielä kokeilla yhteisön masterissa, ehkäpä tuo meidän muutos #56 korjasi tämän.

**Comment by emta001** [comment]
Jeps, yhteisössä tuo ei toimi. Pitänee laatia tiketti.

**Comment by emta001** [comment]
Näemmä oon tehnyt tästä yhteisöön tiketin [32993](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=32993) jo ajat sitten. Suljen tämän tiketin.
