### ISSUE TITLE
Hyllytarkenne - ksdev/ks-0030-bug-5312

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#7]
### Siirrettävä ominaisuus

items-tauluun on lisätty sub_location-sarake, johon tallennetaan Hyllytarkenne.

**Comment by emta001** [comment]
Branchi 0040 tuotu testeille.

**Comment by emta001** [comment]
Pitäisikö nämä kuitenkin eriyttää omiksi tiketeikseen? Muuten tulee hankaluuksia nimetä brancheja.

**Comment by AnneliO** [comment]
Pitäis, jokin aivopieru kävi, kun yhdistin nämä ja varmaan jotkin muutkin samaan aiheeseen liittyvät samaan tikettiin.

**Comment by AnneliO** [comment]
Tein ksdev/ks-0040-KD-5312-items_sublocation oman tiketin.

**Comment by emta001** [comment]
Viety testattavaksi. Hyllytarkenteen pitäisi nyt näkyä Kokoelmat-osiossa hyllypaikan perässä sulkeissa.

**Comment by pirliis** [comment]
OUTIssa hyllytarkenne näkyy oikeassa paikassa:


![Image](https://user-images.githubusercontent.com/98814860/224269799-ecf32e3b-17e9-41e3-b1eb-4aa8f1ec7d8f.png)

**Comment by pirliis** [comment]
Hyllytarkenne näkyy oikeassa paikassa, mutta tarkenteessa näkyy auktorisoitu arvo, kun pitäisi näkyä arvon kuvaus. :)

**Comment by emta001** [comment]
> Hyllytarkenne näkyy oikeassa paikassa, mutta tarkenteessa näkyy auktorisoitu arvo, kun pitäisi näkyä arvon kuvaus. :)

Niin tuota, noin se minusta näyttäisi toimivan myös nykyisessä tuotannossa :D Ainakin niteen 494N00521864 (biblionumber 709) kohdalla näkyy näin:
![Screenshot from 2023-03-10 14-01-54](https://user-images.githubusercontent.com/37581745/224311074-3c9e9f95-872b-4657-bb20-bd43985c039d.png)

**Comment by Kati-Helle** [comment]
Helle-tuotannossa hyllytarkenne näkyy oikein. Pikalaina-hyllytarkenne kuvassa:
![kuva](https://user-images.githubusercontent.com/99952449/224313844-75577053-6d6b-4177-90bd-4bfc26fb458f.png)

**Comment by Kati-Helle** [comment]
Tiedä sitten liittyykö tähän, mutta kerron kun vastaan tuli: hyllytarkenne näkyy oikein kuvaus-tiedolla palautus-näytöllä (kuvassa Uutuus-hyllytarkenne, jonka tunnus on UUSI)
![kuva](https://user-images.githubusercontent.com/99952449/224316230-4b26e4ff-870e-46b5-b236-98bfa0be8162.png)

**Comment by emta001** [comment]
> > Hyllytarkenne näkyy oikeassa paikassa, mutta tarkenteessa näkyy auktorisoitu arvo, kun pitäisi näkyä arvon kuvaus. :)
> 
> Niin tuota, noin se minusta näyttäisi toimivan myös nykyisessä tuotannossa :D Ainakin niteen 494N00521864 (biblionumber 709) kohdalla näkyy näin: ![Screenshot from 2023-03-10 14-01-54](https://user-images.githubusercontent.com/37581745/224311074-3c9e9f95-872b-4657-bb20-bd43985c039d.png)

Ja näin siis tosiaan käy OUTIssa :D

**Comment by pirliis** [comment]
Muhoksen lukion kirjaston hyllytarkenteessa oli yksi merkki liikaa ja siitä syystä ei näyttänyt sulkeissa kuvausta. Lyhensin hyllytarkenteen lyhenteen 10 merkkiin eli nyt näyttää hyllytarkenteen kuvauksen oikein OUTIn tuotannossa.
![image](https://user-images.githubusercontent.com/98814860/224324501-e7fb1cc1-34fe-4766-9d2d-34922a2fd5b1.png)

**Comment by ReettaSiili** [comment]
Siilissä hyllytarkenne näkyy nextillä 3-kirjaimisella auktorisoidulla arvolla:

![Image](https://user-images.githubusercontent.com/98806001/225293305-45a03877-a63f-487c-b19e-d1256826cab7.png)

mutta palautuksessa kuvauksella kuten ylempänä Hellessä:

![Image](https://user-images.githubusercontent.com/98806001/225294478-dc9c5f54-c11c-42cb-a897-3c743752c818.png)

tuotannossa näkyy oikein kuvauksella:

![Image](https://user-images.githubusercontent.com/98806001/225293858-44379295-7579-429f-9791-bd7745e4fbbf.png)

**Comment by Kati-Helle** [comment]
Hellessä hyllytarkenne ei näy enää oikein tietueen Perustiedot-näytöllä. Hyllytarkenteena näkyy nyt auktorisoitu arvo PIKA (pitäisi näkyä arvon kuvaus eli Pikalaina)
![kuva](https://user-images.githubusercontent.com/99952449/225856244-15d2c9e4-9728-4665-90df-e91593fae90b.png)

**Comment by emta001** [comment]
Hmm, tämä tosiaan näyttäisi toimivan Palautus-näytöllä, mutta Perustiedot-näyttö ei jostain syystä toimi. Ainakin näin minun testeillä.

**Comment by emta001** [comment]
Korjasin tuon Perustiedot-näytön erheen ja toin nexteille. Näyttääkö nyt oikealle?

**Comment by Kati-Helle** [comment]
Juu, nyt näkyy oikein myös Perustiedot-näytöllä
![kuva](https://user-images.githubusercontent.com/99952449/226259264-62496de8-1b1d-464a-b883-73ccf611950c.png)

ja näkyy edelleen oikein Palautus-näytöllä 
![kuva](https://user-images.githubusercontent.com/99952449/226259691-917db036-aa75-4845-b06b-7d157eea1088.png)

**Comment by pirliis** [comment]
OUTIssa näkyy nyt oikein tietueen Perustiedot-sivulla:

![Image](https://user-images.githubusercontent.com/98814860/227903092-1879de3b-708f-4b7d-ae84-3911f844ee5d.png)

ja Palautus-sivulla:

![Image](https://user-images.githubusercontent.com/98814860/227903414-a5700516-169e-4726-a243-54a56d678bd1.png)

**Comment by emta001** [comment]
Tämä lienee kunnossa. Suljen tiketin, avataan uudestaan jos on tarvis.
