### ISSUE TITLE
Kiireetön varaus ja keskeytetty varaus yhdessä estävät lainan uusimisen

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha-22x#70]
### Mikä vikana?

Kiireetön varaus ei yksistään estä uusimista eikä keskeytetty varaus yksistään estä uusimista, mutta kun varausjonossa on keskeytetty varaus sekä kiireetön varaus, niin lainassa olevaa nidettä ei voi uusia. Sillä ei ollut vaikutusta, että onko kiireetön varaus nide- vai normivaraus. Sillä ei myöskään ollut vaikutusta, että onko keskeytetty varaus nide- vai normivaraus.

### Mitä pitäisi tapahtua

Kiireettömän ja keskeytetyn varauksen ei pitäisi estää lainan uusimista vaikka niitä olisi samassa varausjonossa.

### Jotain muuta?

Redminesta siirretty tiketti: https://tiketti.koha-suomi.fi/issues/5489

**Comment by AnneliO** [comment]
Minun pikaisten testien mukaan tämä olisi korjattu seuraavaan versioon. Testaatko Piia tätä, kunhan saamme next-kannan OUTIlle käyttöön? :)

**Comment by piiaseme** [comment]
Testasin tätä nextillä. Nyt keskeytetty ja kiireetön varaus eivät estä uusimista :-)

**Comment by AnneliO** [comment]
Hienoa! Miepä suljen tämän tiketin, koska tilanne korjaantuu versionvaihdossa. :)
