### ISSUE TITLE
Muut kokoelmat-välilehden Sarake-rajaus puuttuu eikä sarakkeiden pakotettu piilotus toimi

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha-22x#71]
### Kehitysehdotukseni

Redminen tiketit: #5471 ja #5492
https://tiketti.koha-suomi.fi/issues/5471
https://tiketti.koha-suomi.fi/issues/5492

Tietueessa oman kirjaston kokoelmat- välilehdellä ja Hankintatiedot-välilehdellä "Sarakkeet"-rajaus on käytettävissä.
![sarakkeet](https://user-images.githubusercontent.com/98805552/217762357-0aaaaea5-d1a2-4fe5-be45-e02c851ed29d.png)

Sen sijaan Muut kokoelmat- välilehdellä ei ole "Sarakkeet"-rajausta. 
![sarakkeetpuuttuu](https://user-images.githubusercontent.com/98805552/217762186-a44b11d9-7a86-4e1f-bbf6-c0819920e590.png)

Kokeilin muokata otherholdings_table -taulua Kohan ylläpidossa, mutta en saanut piilotusta toimimaan. 

Ruksitin "otherholdings_dateaccessioned" sarakkeesta "Is hidden by default" eli "Piilotettu (oletus)". Päivitin Ctrl+F5 ja tein sekä testillä että tuotannossa, mutta tuota tietoa ei saa piilotettua. Kokeilin piilottaa myös "otherholdings_itypen" ja "otherholdings_itemcallnumberin" testikannassa (tuotannossa en testannut) eivätkä nekään menneet piiloon. Holdings_table -taulun kaikki piilotukset toimivat sekä testillä että tuotannossa.
![Sarakkeidenpiilotus](https://user-images.githubusercontent.com/98805552/217781097-7974ca2b-47cc-4c7e-8000-1fc455fd356a.png)

Liittyneekö oletuspiilotusongelma siihen, että Muut kokoelmat -välilehdellä ei ole toimintoa "Sarakkeet", sillä oman kirjaston kokoelmat -välilehdellä "Sarakkeet"-toiminto on ja sen oletuspiilotus toimii?

### Jotain muuta?

Korjaus yhteisössä versiossa 22.05. https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=30747

**Comment by AnneliO** [comment]
Versiossa 22.11 näyttäisi olevan Muut kokoelmat -välilehdellä oma Sarakkeet-nappula ja pikaisella testauksella sarakeasetusten oletusten muuttaminenkin toimii.
![kuva](https://user-images.githubusercontent.com/33121325/218040281-cf76f00d-0ea5-49f4-b24c-224034853400.png)

Testaatko Piia tätä vielä itsekin, kun OUTIn next-kanta saadaan käyttöön? :)

**Comment by piiaseme** [comment]
Testaan 👍

**Comment by piiaseme** [comment]
Testasin nextillä ja näyttäisi nyt sarake-rajaus toimivan sekä saatavuudessa että ylläpidon puolella :-)

**Comment by AnneliO** [comment]
Hyvä juttu! Suljen tämänkin tiketin, koska ongelma korjaantuu versionvaihdossa. :)

**Comment by ReettaSiili** [comment]
Tämä tosiaan korjautunut, hyvä!
