### ISSUE TITLE
Z39.50-haku Tätistä ei onnistu

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#72]
### Mikä vikana?

Jos yrittää tehdä Z39.50-haun Tätiin vaski-nextiltä, tulee ilmoitus _Yhteys palvelimeen localhost epäonnistui_.

### Mitä pitäisi tapahtua

Haun pitäisi hakea Tätistä.

### Kuinka toistaa ongelma/asia

1. Mene Kuvailu-osioon
2. Valitse _Uusi Z39.50/SRU-haku_
3. Kirjoita Nimeke-kenttään emännöitsijä
4. Saa ilmoitus Yhteys palvelimeen localhost epäonnistui

**Comment by AnneliO** [comment]
Ongelma johtuu todennäköisesti siitä, että Tätin kanssa keskusteleva REST-palvelu on alhaalla. Testataan uudelleen, kun palvelu on pystyssä.

**Comment by emta001** [comment]
Tämä vaatii toimiakseen myös apachen konffien säätämistä. Outissa tämä on kunnossa ja siellä haku toimii. Tarvitseeko muillekin nexteille käydä säätämässä?

**Comment by AnneliO** [comment]
Olisihan tuo hyvä ainakin pariin kimppaan säätää, jotta kuvailun toimintoja voi kattavasti testata useammassa kimpassa.

**Comment by emta001** [comment]
Miepä laitan sen suosiolla kaikille kuntoon, ei tarvii sitten muistella keillä se on ja keillä ei :D

**Comment by emta001** [comment]
Nyt pitäisi tämän haun toimia kaikissa kimpoissa.

**Comment by AnneliO** [comment]
Toimii Vaara-nextillä.

**Comment by AnneliO** [comment]
Toimii outi-nextillä, siili-nextillä ja lappi-nextillä.

Suljen tiketin.
