### ISSUE TITLE
Keskeytä kaikki varaukset, Jatka kaikki keskeytetyt varaukset -toiminnot eivät toimi muilla kuin superlibrarianeilla

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha-22x#73]
### Mikä vikana?

Redminessa tiketti #5438 
https://tiketti.koha-suomi.fi/issues/5438

Varausten massamuokkaus (Keskeytä kaikki varaukset, Jatka kaikki keskeytetyt varaukset) ei onnistu uudessa versiossa vaikka henkilökunnan käyttäjätunnuksilla olevien varausten käsittely-oikeuksien pitäisi siihen hyvinkin taipua. Yrittäessä muokata Koha heittää ulos sanoen, että oikeudet eivät riitä: ”Virhe: sinulla ei ole oikeuksia tähän sivuun”.

Superlibrarian-oikeuksilla massamuokkaus onnistuu. 

Varausten yksittäinen muokkaus onnistuu henkilökunnan tunnuksilla, joille on asetettu oikeus tehdä varauksia asiakkaille (place_holds), mutta ei siis massamuokkaus.

Ongelma ei liity Kohasession aikakatkaisuun.

### Mitä pitäisi tapahtua

Useamman varauksen keskeyttäminen yhdellä kertaa ilman, että lisätään työtunnuksille liian laajoja oikeuksia tai että Koha heittää pihalle.

**Comment by AnneliO** [comment]
Piia, testaatko tämän uudemmassa versiossa, kunhan next-kannat ovat käytössä?

**Comment by piiaseme** [comment]
Voin testata.

**Comment by piiaseme** [comment]
Testasin outi-next-kannassa varausten keskeyttämistä. Yksitellen keskeyttäminen ja jatkaminen onnistuivat, mutta "Keskeytä kaikki varaukset"-toiminnalla Koha nakkasi ulos kuten nykyisessäkin versiossa ja ilmoitti, että oikeudet eivät riitä.

Virkailijatunnuksellani oli place_holds-oikeus.

**Comment by Kati-Helle** [comment]
Missä kohtaa outi-nextissä näkyykään "Keskeytä kaikki varaukset"?
Helle-next-näkymä ennen varauksien valintaa
![kuva](https://user-images.githubusercontent.com/99952449/225581109-7f7f4d3f-ec9c-48a9-9e98-7298f3bbf01f.png)

Näkymä varauksien valinnan jälkeen
![kuva](https://user-images.githubusercontent.com/99952449/225581835-0fa495ee-7462-462e-a408-50d6203308ac.png)

Sisäänkirjauminen käyttäjätunnuksella, jolla on oikeus place_holds

**Comment by pirliis** [comment]
Keskeytä kaikki varaukset -toiminto löytyy asiakkaan Varaukset-välilehdeltä.

**Comment by Kati-Helle** [comment]
Kiitos tiedosta :) Hups, olin eksyksissä.

Helle-nextillä asiakastiedoissa varauksen keskeyttäminen yksitellen toimii, samoin varauksen keskeytyksen poistaminen yksitellen.

Keskeytä kaikki varaukset -toiminto: Koha heittää Kohan kirjautumissivulle huomautustiedolla: 
Virhe: Sinulla ei ole oikeuksia tähän sivuun. 
![kuva](https://user-images.githubusercontent.com/99952449/225591653-387a89f5-7e75-45b3-ac1f-94a421ca4739.png)

Vastaava tapahtuu, kun yrittää jatkaa kaikki keskeytetyt varaukset toiminnolla Jatka kaikki keskeytetyt varaukset.

Kohaan kirjautuneella käyttäjätunnuksella on oikeus place_holds.

**Comment by AnneliO** [comment]
[Tiketti 30732 yhteisössä](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=30732)

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 24.4.2023: Tuodaan korjaus yhteisöstä ja testataan riittääkö se meidän tarpeisiin. Yhteisössä vielä kesken.

**Comment by emta001** [comment]
Tuotu testattavaksi nexteille.

**Comment by velimarj** [comment]
OUTIssa tunnuksella, jolla place_holds, sain sekä keskeytettyä että jatkettua kaikki varaukset. Myös päivämäärän valinta onnistui.

**Comment by Tuomas-Kyyti** [comment]
En saanut Kyytissä toimimaan. Yksittäin varausten keskeytys ja jatkaminen onnistui, mutta ei kaikkia kerralla, heitti kirjautumisruutuun. Kohaan kirjautuneella käyttäjätunnuksella on oikeus place_holds. Onkohan korjaus varmasti tuotu myös Kyytiin?

**Comment by AnneliO** [comment]
Viimeisen puolen tunnin aikana on voinut nexteillä olla toimimattomuutta. Kokeiletko kohtapuoliin uudelleen?

**Comment by Tuomas-Kyyti** [comment]
Jaha, no nyt tämä toimii ok.

**Comment by emta001** [comment]
Vaikuttaisi toimivan, suljen tiketin.
