### ISSUE TITLE
Tietueen varaukset -näyttö: Sija jonossa (Priority) -sarake näkyviin. Sarakkeessa näkyy tieto, monentena asiakkaan varaus on

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-22x#74]
### Mikä vikana?

Tiedot Redmine-tiketistä https://tiketti.koha-suomi.fi/issues/5583
Start date: 29/08/2022

Kati Sillgren
Saisiko Tietueen Varauksia -näytölle näkyviin sarakkeen Sija jonossa (Priority)?
Asiakkaan varauksen sija varausjonossa näkyy nyt vain silloin, kun Koha-käyttäjätunnuksella on oikeus modify_holds_priority. Kyseinen varausjärjestysmuutos-oikeus on ainakin Hellessä vain pääkäyttäjillä.

Nyt asiakaspalvelussa asiakkaalle tehdyn varauksen sija varausjonossa pitää laskea itse. Tai tarkistaa asiakkaan varaustiedoista, etenkin kun varauksia on paljon.

![kuva](https://user-images.githubusercontent.com/99952449/218740867-66fb77a9-0526-44d4-8317-b7ab9cd75ea9.png)

---

Lari Strand
Ongelma on ratkaistu Kohan versiossa 22.11. Siinä varausprioriteettilistan sijat näkyvät numeroina (eikä näkyvissä pudotusvalikkona jolloin sijojen muutos olisi mahdollista) sellaisile tunnuksille, joilta jonon muokkausoikeus puuttuu (modify_holds_priority). Korjausta ei saa tuotua meidän 21.11-version päälle (varausnäkymä on muuttunut paljon uudemmassa 22.11-versiossa), joten ominaisuutta pitää nyt odotella seuraavaan versionvaihtoon.
https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=30213

---

Kati Sillgren
Kiitos Lari tutkimisesta ja tiedosta!

---

Anneli Österman
Testattava uuden version testillä.

---

Kati Sillgren
Laitoin testaustarpeen itselleni muistiin.

**Comment by piiaseme** [comment]
Kävin katsomassa varausjonoa sellaisella tunnuksella, jolla ei ole varausten järjestyksen muuttamis-oikeutta ja varausten sijat näkyvät numeroina.

**Comment by Kati-Helle** [comment]
Helle-nextilläkin varausten sija ilmoitettu numeroin
![kuva](https://user-images.githubusercontent.com/99952449/225598673-c381e1ff-829a-4e17-8b80-bc2fff158db3.png)

Kohaan kirjautuneella käyttäjätunnuksella on oikeus place_hold. Oikeutta varausjärjestyksen muuttamiseen ei ole.

**Comment by ReettaSiili** [comment]
Siilinjärvellä virkailijoilla on oikeus muokata varausjonon järjestystä, joten tämä ei koske suoranaisesti meitä. Sija jonossa näkyy kuitenkin myös virkailijalle, jolla on pelkkä varauksenteko-oikeus.

**Comment by AnneliO** [comment]
Testasin tätä myös vaara-nextillä ja sijanumero näkyy sellaisella käyttäjätunnuksella, jolla on vain place_holds-oikeus.


![Image](https://user-images.githubusercontent.com/33121325/232033922-c956cf5d-f1d4-4a73-bf96-39b63b875a7c.png)

(Omituiset sijanumerot johtuu tietokannan redusoinnista, kun mukaan on otettu vain osa varauksista, jotka ovat olleet satunnaisella sijalla jonossa.)

**Comment by AnneliO** [comment]
Tämän voinee sulkea?
