### ISSUE TITLE
koha-suomi-utility (KSU)

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/Koha-22x#75]
### Siirrettävä ominaisuus

Koha-Suomi utility tools

**Comment by AnneliO** [comment]
Miten tätä testataan?

**Comment by ghost** [comment]
Lähinnä cronjobit piti testata ja ne olen kaikki testannut (paitsi overdue_noticesia en aivan kaikilla mahdollisilla optioilla kun erilaisia yhdistelmiä on niin mahdottoman paljon, sitäkin kyllä testattiin tiketin https://github.com/KohaSuomi/Koha-22x/issues/59 yhteydessä ja toimii niillä asetuksilla mitkä nyt on käytössä). Muista ylläpito- ym. skripteistäkin olisi varmaan jo huomattu jos ne eivät toimisi oikein. Ehkäpä tämän tiketin voi toistaiseksi sulkea ja avataan uudestaan jos ongelmia ilmenee.
