### ISSUE TITLE
Koha-translations (KTRAN)

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/Koha-22x#76]
### Siirrettävä ominaisuus

Koha-Suomi translation files are kept here under lock and key.

**Comment by AnneliO** [comment]
Loin Koha-translations-repositorioon 22.xx-branch ja vein sinne uusimmat suomenkieliset po-tiedostot.

**Comment by AnneliO** [comment]
Koha-translations-repositorioon on viety po-tiedostot, joissa on mukana Koha-Suomen käännökset. Ruotsinkielisissä on vain tarkistettu, että ei ole käyttöä estäviä virheitä. Varsinaisia käännöksiä en osannut tehdä.

Käännökset pitää vielä asentaa nexteille.

**Comment by AnneliO** [comment]
Testeillä ei näy käännöksiä esim. 

* koha-suomi-pendingreserves-sivulla. Käännöksiä ei myöskään ole po-tiedostossa.
* varauksentekosivulla Cancel selected -nappulassa tai Sija varausjonossa -sarakkeessa In transit/Waiting

**Comment by AnneliO** [comment]
Tein edellisen kommentin virheistä erilliset tiketit ja suljen tämän.
