### ISSUE TITLE
koha-plugin-OKM-stats (KPOKM)

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/Koha-22x#77]
### Siirrettävä ominaisuus

Tilastoliitännäinen

**Comment by emta001** [comment]
Plugin on korjattu uutta versiota varten, nextillä käytetään kehitykseen branchia devel-22.xx.

**Comment by emta001** [comment]
Kokeillaan jossain vaiheessa ajella biblio_data_elements-taulun päivitys.

Käyttöliittymän päässä testaamisen kannalta on oleellista, että raporttilistaus ja itse raportti näkyvät. Samoin piilotusten sekä filtteröinnin tulisi toimia oikein.

**Comment by emta001** [comment]
BDE-ajo näyttää onnistuvan OK, yksi virhe tulee joka ei kuitenkaan estä ajoa:
_Can't locate object method "throw" via package "Koha::Exceptions::Exception"_

 Tilastoajoissa on häikkää, OKM-ryhmien ajossa valittaa:
_The method Koha::Library::Groups->title is not covered by tests!_

ja kirjastoajossa:
_The method Koha::Libraries->branchcode is not covered by tests!_

**Comment by emta001** [comment]
Nyt näyttäisi ajotkin pelittävän ok.

**Comment by piiaseme** [comment]
Saako määritykset kopioida tuotannosta nextille? Tarvitseeko tehdä muuta, jotta voi testata?

Edit: kopioin määritykset nextille

**Comment by emta001** [comment]
> Saako määritykset kopioida tuotannosta nextille? Tarvitseeko tehdä muuta, jotta voi testata?
> 
> Edit: kopioin määritykset nextille

Juu saa kopioida, niiden pitäisi toimia sellaisenaan uudessakin versiossa.

**Comment by Kati-Helle** [comment]
Helle-nextillä ei näytä olevan liitännäisiä
![kuva](https://user-images.githubusercontent.com/99952449/225552618-d88678c6-1d7a-4a6c-871f-e446e1e68be5.png)

**Comment by emta001** [comment]
Juu pitää asennella nämä kaikille. Ilmottelen kuhan on kuosissa.

**Comment by emta001** [comment]
> Helle-nextillä ei näytä olevan liitännäisiä ![kuva](https://user-images.githubusercontent.com/99952449/225552618-d88678c6-1d7a-4a6c-871f-e446e1e68be5.png)

Nyt on liitännäiset asennettu kaikille kimpoille.

**Comment by Kati-Helle** [comment]
Kiitos Emmi :)
Helle-nextillä on nyt 13 liitännäistä.
(Helle-tuotannossa 16.)

Vasemmalla Hellen tuotanto, oikealla next.
![kuva](https://user-images.githubusercontent.com/99952449/225595901-6d04bbbb-bad0-45d1-9d68-d220cb2de350.png)

**Comment by emta001** [comment]
Muutama liitännäinen herjasi, kun niitä yritettiin asentaa sellaisenaan uuteen versioon, joten ne on otettu pois käytöstä. Asennellaan, kunhan saadan nekin kuosiin.

**Comment by ajrajala** [comment]
Testailin Vaski-nextillä, raporttilistaus ja sen suodatus näkyy/toimii oikein. Samoin raportit aukeavat ja raportissa suodattaminen sekä sarakkeiden piilotus toimii. Testasin myös exceliin vientiä ja kopiointia, sekin ok.

**Comment by AnneliO** [comment]
Testailin vaara-nextillä samoja kuin Anni ja kaikki toimi.

**Comment by emta001** [comment]
Suljen tiketin, avataan uudestaan jos tulee jotain.
