### ISSUE TITLE
koha-plugin-overdue-tool (KPODUE)

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/Koha-22x#78]
### Siirrettävä ominaisuus

Laskutusliitännäinen

**Comment by emta001** [comment]
Plugin tuotu nextille testattavaksi, käytetään branchia 22.xx. Ainakin laskujen generointi liittymän kautta vaikuttaisi toimivan oikein, lähettämistä pitää vielä testata.

**Comment by AnneliO** [comment]
Testasin pdf-laskun luontia Vaara-nextillä ja se toimi mielestäni kuten pitikin.

Yritin outi-nextillä testata Finvoicea, mutta saan ilmoituksen _Request failed with status code 400: Finvoice is not valid XML for OUUL_. Viestipohja on tuotannosta, joten sen pitäisi kyllä olla toimiva.

**Comment by Tuomas-Kyyti** [comment]
En saanut Kyytin Nextillä tätä testattua, kun se ilmoittaa "Aikavälillä ei ole laskutettavia lainoja!", vaikka miten päivämäärärajausta muuttaa. Ei myöskään löydy mitään, jos laittaa "Näytä laskutetut". Voikohan johtua ihan siitä, että asiakkaita on niin vähän ettei ketään sellaista sattunut mukaan otantaan.

**Comment by AnneliO** [comment]
> En saanut Kyytin Nextillä tätä testattua, kun se ilmoittaa "Aikavälillä ei ole laskutettavia lainoja!", vaikka miten päivämäärärajausta muuttaa. Ei myöskään löydy mitään, jos laittaa "Näytä laskutetut". Voikohan johtua ihan siitä, että asiakkaita on niin vähän ettei ketään sellaista sattunut mukaan otantaan.

Todennäköisesti johtuu. Koita lainata jollekin (testi)asiakkaalle niin, että laitat eräpäivän menneisyyteen.

**Comment by pirliis** [comment]
Testasin Finvoicen e-laskua OUTIssa. Laskun luonti onnistui, asiakkaalle tuli rajoite laskutetusta aineistosta, laskutetulle niteelle tuli laskutettu-tila, mutta asiakkaan ilmoituksiin ei syntynyt laskua. Laskutettu asiakas borrowernumber=301783.

**Comment by emta001** [comment]
> Testasin Finvoicen e-laskua OUTIssa. Laskun luonti onnistui, asiakkaalle tuli rajoite laskutetusta aineistosta, laskutetulle niteelle tuli laskutettu-tila, mutta asiakkaan ilmoituksiin ei syntynyt laskua. Laskutettu asiakas borrowernumber=301783.

Enpä osaa sanoa vielä mikä tässä on, mutta näemmä plugarissa käytetään edelleen accountlines.accounttype-saraketta, jota ei ole ollut olemassa viime versionvaihdon jälkeen. Korjailen senkin samalla.

**Comment by emta001** [comment]
@pirliis Tämmöisen virheen sain aikaiseks outi-nextillä:

Tapahtui virhe:
    Request failed with status code 400: Finvoice is not valid XML for OUPE

Testasin asiakkaalla 302197. Onkohan tuolla pohjassa jotain vialla?

**Comment by pirliis** [comment]
Testasin myös laskujen luontia kirjautuneena Oulun eri kirjastoihin ja sain myös tuon saman virheilmoituksen. 
Anneli hoksasi, että tuo virheilmoitus tulee varmaan siitä syystä, kun Oulussa on laskun viestipohja vain OUPK:lle, jolla laskujen luonti onnistuu. :)

Eli nyt näyttäisi, että sekä finvoice-laskutus että e-laskujen luonti onnisuu. Molemmilla laskutustavoilla lainaajille syntyi rajoite, laskutetuille niteille meni laskutettu-tila päälle ja laskut syntyivät asiakkaan ilmoituksiin.

Testilaskut näkyvät tuolla sinun asiakastunnuksella.

**Comment by MikkoLiimatainen** [comment]
Nähdäkseni Vaskissa laskutustyökalu toimii juuri niin kuin pitääkin. Laskut, asiakasviestit ja rajoitukset muodostuvat kuten pitääkin ja niteille tulee laskutettu tila. Sekä Finvoice, että PDF-kirje muodostuvat oikein.

**Comment by emta001** [comment]
Eli ainakin käyttöliittymän päässä tämä vaikuttaisi toimivan ok. Pitäisiköhän tätä testata myös lähettämisen kannalta?

**Comment by MikkoLiimatainen** [comment]
Meillä ei koettu tarvetta testata lähetystä ennen tuotantoon siirtymistä. Teemme joka tapauksessa tuotannossa testin, jotta näemme lähetyksen toimivan, ennen kuin annamme luvan laskutukseen. Ne palvelinasetuksethan varmaan säilyvät ennallaan, joten lähetyksen pitäisi toimia nykyiseen tapaan?

**Comment by emta001** [comment]
> Meillä ei koettu tarvetta testata lähetystä ennen tuotantoon siirtymistä. Teemme joka tapauksessa tuotannossa testin, jotta näemme lähetyksen toimivan, ennen kuin annamme luvan laskutukseen. Ne palvelinasetuksethan varmaan säilyvät ennallaan, joten lähetyksen pitäisi toimia nykyiseen tapaan?

Jeps, asetukset pysyvät sellaisenaan.

**Comment by emta001** [comment]
Jospa suljen tiketin kuitenkin tältä erää. Jos on tarve, avataan uudestaan.
