### ISSUE TITLE
koha-plugin-report-services (KPREP)

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/Koha-22x#79]
### Siirrettävä ominaisuus

Raportointipalvelu

**Comment by emta001** [comment]
Tämä hommahan on jäissä, joten siirto voi odottaa rauhassa.

**Comment by emta001** [comment]
Tehdäänpä ihan niin, että suljetaan tää tiketti. Avataan sitten joskus uudestaan kunhan tässä päästään eteenpäin.
