### ISSUE TITLE
Luokitusoppaissa omia järjestelysääntö-plugineja - ksdev/ks-0033-KD-1459-cn_sort-routines

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#8]
### Siirrettävä ominaisuus

Kohan luokitusoppaisiin on lisätty omia järjestelysääntö-plugineja.

Koha-yhteisön tapa muodostaa niteiden signum poikkeaa suomalaisten yleisten kirjastojen tavasta. Niteen itemcallnumber-sarakkeen tieto kopioidaan niteen cn-sort-sarakkeeseen siten, että cn-sort-sarakkeeseen tieto tulee muodossa "luokka - pääsana", eli mahdolliset kirjasto- ja hyllypaikkalyhenteet tiputetaan pois. cn-sort-sarakkeen tietoa käytetään mm. tiedonhaussa luokan mukaan järjestämiseen. Jos sarakkeeseen tallennetussa tiedossa on alussa muuta kuin luokkatieto, tiedot eivät järjesty oikein.

Jotta tiedot saadaan vietyä oikein, luotiin sitä varten Kohan luokitusoppaisiin kaksi uutta järjestelysääntöä "OUTI" ja "LUMME".

**Comment by lmstrand** [comment]
branchissa ks-0033-K22-8-cn_sort-routines.

**Comment by AnneliO** [comment]
Testasin vaski-nextillä, jossa on käytössä outi-versio (pitäisiköhän nämä muuten joskus nimetä uudelleen? ja cn_sort näytti muodostuvan oikein niin, että ensimmäinen osio signumista pudotettiin ja loput vietiin cn_sortiin. Tosin, jos signumissa oli vain yksi osio, vietiin se.

**Comment by Kati-Helle** [comment]
Helle-nextissä cn_sort vaikuttaa muodostuvan oikein. Olisikohan luokitusoppaissamme ylimääräisiä/poistettavia?
![kuva](https://user-images.githubusercontent.com/99952449/225866638-b08613ab-7165-4fde-81f3-007a2378b6f3.png)

**Comment by AnneliO** [comment]
Vaara-nextillä on käytössä outi-versio ja se toimii oikein.

**Comment by AnneliO** [comment]
cn_sorteja voi katsella esim. tällä sql-kyselyllä:

```select cn_sort from items where itemnumber=<<itemnumber>>```

Oikein muodostunut cn_sort pitäisi alkaa numerolla.

**Comment by Tuomas-Kyyti** [comment]
Kyytissä cn_sort näyttää samalta kuin signum. Liekö sitten oikein näin?

![Image](https://user-images.githubusercontent.com/99244794/234830598-b877ac2c-65ae-406e-9894-442f27a27260.png)

**Comment by AnneliO** [comment]
> Kyytissä cn_sort näyttää samalta kuin signum. Liekö sitten oikein näin?
> 
> ![Image](https://user-images.githubusercontent.com/99244794/234830598-b877ac2c-65ae-406e-9894-442f27a27260.png)

Minusta menee oikein.

**Comment by AnneliO** [comment]
Kummankin tyyppinen plugin testattu, joten suljen tiketin.
