### ISSUE TITLE
koha-plugin-ceepos-integration (KPCPU)

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/Koha-22x#81]
### Siirrettävä ominaisuus

Koha-Ceepos-liitännäinen

**Comment by emta001** [comment]
Plugari on asennettu outi-, vaara- ja lappi-nexteille. Plugarin-asetukset vain pitää käydä laittamassa kuntoon. Pitää vielä tutkia mitä asetuksia palvelimelle pitää laittaa, että voidaan testailla.

**Comment by pirliis** [comment]
Lisäsin OUTIn kirjastokohtaiset tuotteet Ceepos-plugariin.
Kun lähetin maksua Ceepos-kassalle, tuli oikein ilmoitus: "Maksu lähetetty, käsittele kassassa!", mutta kun kuittasi ilmoituksen OK:lla, tuli virheilmoitus:
![image](https://user-images.githubusercontent.com/98814860/234832866-4bf5b98d-ad89-44c1-861e-0a41fd305db4.png)
Maksu ei siirtynyt kassalle.

**Comment by emta001** [comment]
> Lisäsin OUTIn kirjastokohtaiset tuotteet Ceepos-plugariin. Kun lähetin maksua Ceepos-kassalle, tuli oikein ilmoitus: "Maksu lähetetty, käsittele kassassa!", mutta kun kuittasi ilmoituksen OK:lla, tuli virheilmoitus: ![image](https://user-images.githubusercontent.com/98814860/234832866-4bf5b98d-ad89-44c1-861e-0a41fd305db4.png) Maksu ei siirtynyt kassalle.

Höm, ne on varmaan ne palvelimen asetukset mistä tuo jää kiinni. _Joku_ unohti käydä laittaa ne sinne :D

**Comment by emta001** [comment]
Noita on kyllä Outissa tuhat ja yks... @pirliis minkä kirjaston kassalla testailet? Voisin laittaa tonne nextille vain sen asetukset.

**Comment by pirliis** [comment]
Kaijonharjun kirjaston (OUUL) kassalla15, auktorisoituarvo KOHA15. Tarvitko muuta tietoa?

**Comment by emta001** [comment]
> Kaijonharjun kirjaston (OUUL) kassalla15, auktorisoituarvo KOHA15. Tarvitko muuta tietoa?

Tuo riittää, kiitti :) Laitoin asetuksen nyt kuntoon.

**Comment by emta001** [comment]
Myös Vaaralla pitäisi olla asetus kunnossa, laitan Lapin kuosiin huomenna.

**Comment by emta001** [comment]
Asetukset säädetty myös Lapille.

**Comment by pirliis** [comment]
Nyt OUTIssa antaa maksun lähetyksen jälkeen ilmoituksen:


![Image](https://user-images.githubusercontent.com/98814860/235073738-fc624e46-4188-4875-b779-55460e3f4869.png)

**Comment by emta001** [comment]
> Nyt OUTIssa antaa maksun lähetyksen jälkeen ilmoituksen:
> 
> ![Image](https://user-images.githubusercontent.com/98814860/235073738-fc624e46-4188-4875-b779-55460e3f4869.png)

Ai himputti, nuo näemmä puuttuu tuolta nexteiltä.

**Comment by emta001** [comment]
> Nyt OUTIssa antaa maksun lähetyksen jälkeen ilmoituksen:
> 
> ![Image](https://user-images.githubusercontent.com/98814860/235073738-fc624e46-4188-4875-b779-55460e3f4869.png)

Nyt noiden tarvittavien filujen pitäs olla kopsattuna paikalleen, toimiiko nyt?

**Comment by pirliis** [comment]
Maksun lähetys Kohasta Ceeposiin toimii, mutta kun maksun maksoi (maksoin kortilla) Ceeposissa tuli virheilmoitus:


![Image](https://user-images.githubusercontent.com/98814860/235132834-9c5b4b33-3ecc-4d6e-89a0-2ed641476885.png)

Rahat meni, mutta maksukuittaus Kohaan ei toiminut ja maksu yhä Kohassa. :D

**Comment by pirliis** [comment]
Olisiko tätä maksurajapintaa aikaa edistää, josko tämä saatas kuntoon?

**Comment by lmstrand** [comment]
Kohan pään maksukuittausongelma paljastui lokituksen vaihtamisella log4perlin moduuliin eli lokituksessa on nyt testeillä ja tuotannoissa ongelma, kun käytetään Kohan omia lokiolioita (tiedosto-oikeudet?).

Ongelma aiheutui muissakin plugareissa havaitusta ->as_list -funktion puuttumisesta, kun kohasta haetaan accountlinet, mitkä on maksettu (https://github.com/KohaSuomi/koha-plugin-ceepos-integration/commit/a5b9b13b37c8015f8513f9609fb93698e92ffab2).

Viedään korjaus tiistaina tuotantoon.

**Comment by emta001** [comment]
Niin tämähän taitaa toimia? Suljen tiketin.
