### ISSUE TITLE
koha-plugin-add-marc-field-001 (KPM001)

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/Koha-22x#85]
### Siirrettävä ominaisuus

Plugin to automatically add MARC field 001 if it is missing.

**Comment by AnneliO** [comment]
Tätä ei enää tarvita Kohan oman toiminnallisuuden vuoksi.

**Comment by emta001** [comment]
Pääkäyttäjäpalaveri 2.5.2023: Tuodaan plugin uuteen versioon, tällä korjataan tiketissä #171 ilmennyt ongelma.

**Comment by ghost** [comment]
Lisäosa on nyt tuotu kaikille nexteille. Jos autoControlNumber-asetus on jossain vielä päällä, se pitää ottaa pois.

**Comment by AnneliO** [comment]
Testasin vaara-nextillä tietueen luontia luomalla uuden kuvailutyökalun avulla sekä luomalla tietueen tilauksen teon yhteydessä tyhjästä. Kummassakin tapauksessa 001-kenttään tuli oikein biblionumber.

Testasin myös Z39.50-haun kautta kuvailutietueen tuontia ja silloin säilyi 001-kentän arvo alkuperäisenä, joka oli Tätissä.

**Comment by LeenaKinnunen** [comment]
Lapissa hankintaosasto testasi, ja toimii oikein.

**Comment by AnneliO** [comment]
Tiketissä #171 myös tähän liittyviä testituloksia, joten eiköhän tämän voi todeta toimivaksi. :)
