### ISSUE TITLE
koha-plugin-editx (KPEDX)

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/Koha-22x#86]
### Siirrettävä ominaisuus

EDItX-sanomia käsittelevä liitännäinen

**Comment by lmstrand** [comment]
Yhteensopivuus 22.11-version kanssa korjattu branchissa ks22. Nexteillä testattavissa.

**Comment by lmstrand** [comment]
Outi-nextillä testattu kahta eri sanomaa ja ne käsiteltiin onnistuneesti (sequences-taulun kopioinnin jälkeen tuotannosta). Kyrilliset merkit näkyvät ok. Productform alternative ok.

Niteiden tila Kohassa:
![image](https://user-images.githubusercontent.com/18394834/231397016-86c71016-9600-4231-850e-979cd1b8ad7f.png)

**Comment by AnneliO** [comment]
Vastaanotto onnistui myös ilman herjoja. Tilaukset näkyivät tileissä.

**Comment by lmstrand** [comment]
Tarvitsisiko tätä testata vielä toisessa kimpassa?

**Comment by lmstrand** [comment]
Testattu myös kyyti-nextillä toimivaksi.
