### ISSUE TITLE
koha-plugin-visual-label-tool (KPVLT)

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/Koha-22x#87]
### Siirrettävä ominaisuus

Tarratyökalu

**Comment by lmstrand** [comment]
Plugin toimii oikein, mutta intranetuserjs-rimpsua käytettäessä ja omalle tulostusjonolle/listalle niteitä lisättäessä ( Lisää valitut niteet tulostusjonoon , cgi-bin/koha/catalogue/detail.pl ) toiseen kertaan samassa näkymässä, päätyvät niteet tuplana omalle listalle. Ongelma korjaantuu, jos sivun päivittää, mutta taas toista kertaa nidettä/niteitä lisätessä ongelma palaa.

**Comment by lmstrand** [comment]
Tässä vielä käyttämäni js-rimpsu:

```
/* Niteiden lisätys tarratulostustyökaluun perustiedot-näytöltä */
$(document).ready(function() {
        $("#holdings .itemselection_action_modify, #otherholdings .itemselection_action_modify").after('<a href="#" class="itemselection_action_print" onclick="addItemsToPrintQueue(event, $(this))"> <i class="fa fa-print"></i> Lisää valitut niteet tulostusjonoon</a>');
});
function addItemsToPrintQueue(e, element) {
    e.preventDefault();
    var requests = [];
    $("input[name='itemnumber'][type='checkbox']:visible:checked", 'table.items_table').each(function() {
        var itemnumber = $(this).val();
        requests.push($.ajax({
            url: "/api/v1/contrib/kohasuomi/labels/print/queue",
            type: "POST",
            datatype: "json",
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify({ itemnumber: itemnumber, printed: 0 }),
            error: function (err) {
                console.error( `Niteen nro. ${itemnumber} lisäys tulostusjonoon epäonnistui.` );
            }
        }));
    });
    window.onbeforeunload = function () {
        if ( requests.length ) {
            return "";
        }
    };
    $('.itemselection_action_print').html(`<a> <i class="fa fa-print"></i> Lisätään ${requests.length} nide${requests.length == 1 ? "" : "ttä"} tulostusjonoon...</a>`);
    $.when.apply($, requests).done(function () {
        alert( `${requests.length} nide${requests.length == 1 ? "" : "ttä"} lisätty tulostusjonoon.` );
    }).fail(function () {
        alert( "Niteiden lisäys tulostusjonoon keskeytyi. Tarkista tulostusjono." );
    }).always(function () {
        $('.itemselection_action_print').html('<a href="#" class="itemselection_action_print" onclick="addItemsToPrintQueue(event, $(this))"> <i class="fa fa-print"></i> Lisää valitut niteet tulostusjonoon</a>');
        requests = [];
    });
}
```

**Comment by lmstrand** [comment]
Taisi tulla myös tuplapopup lisätystä niteestä.

**Comment by AnneliO** [comment]
Larin mainitsemat ongelmat korjattu Koha-repon [tiketissä 472](https://github.com/KohaSuomi/Koha/issues/472). Uusin versio rimpsusta viety [IntranetUserJS](https://github.com/KohaSuomi/Koha-22x/wiki/IntranetUserJS)-wikiin.

**Comment by Kati-Helle** [comment]
Larin tekemä uusi rimpsu lisätty Helle-nextille.

**Comment by AnneliO** [comment]
outi-nextillä puuttuu tarrapohjat ja jos menee liitännäisen konfigurointiin, tulee sivu:

"Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later."

**Comment by pirliis** [comment]
Tarrapohjat puuttuvat vielä, mutta enää ei tule tuota ilmoitusta mikä Annelille on tullut eilen, kun menee tarratulostustyökalun määrittelyihin.

**Comment by AnneliO** [comment]
Emmi kopioi tarrapohjat outin nextille.

Tarrapohjat näkyvät nyt ja tarrat muodostuvat oikein.

Ylläpidossa tarrojen asettelu on kuitenkin pielessä, kaikki määritykset ovat yhdellä rivillä, vaikka ne pitäisi olla määritysten mukaisissa kohdissa. Esim. _12 tarran arkki_:

![Image](https://user-images.githubusercontent.com/33121325/235063106-911f02ec-d80b-464f-9d04-6a576c8dbeb6.png)

Samaa näyttäisi tapahtuvan myös vaara-nextillä.

**Comment by AnneliO** [comment]
Jaha, tää oli vissin jokin välimuistihärö, koska kun tein sivun päivityksen ctrl+F5:lla, niin rivit asettuivat nätisti. xD

![kuva](https://user-images.githubusercontent.com/33121325/235901804-8568b6e9-1a2c-4f59-b129-2f83bc8e6acf.png)

**Comment by MikkoLiimatainen** [comment]
Vaskissa kaikki toimii hienosti.

**Comment by Kati-Helle** [comment]
Hellessä välimuistin tyhjennyksestä huolimatta tarrapohjan muokkausnäkymät tämän kaltaiset
![kuva](https://user-images.githubusercontent.com/99952449/236397379-8b8b921e-6c06-42e2-bf5b-4c29dca981a4.png)

**Comment by Kati-Helle** [comment]
Uusi välimuistityhjennys tepsi :)
![kuva](https://user-images.githubusercontent.com/99952449/236397655-6ef2f7fc-bcde-4725-80e3-38093669eaac.png)

**Comment by lmstrand** [comment]
Ok. Suljen tiketin.
