### ISSUE TITLE
Do not allow script-tags in systempreferences - ksdev/ks-0035-KD-4346

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-22x#9]
### Siirrettävä ominaisuus

Do not allow script-tags in systempreferences.

**Comment by Kaarius** [comment]
On viety nexteille testattavaksi.

**Comment by AnneliO** [comment]
Miten tätä voisi testata?

**Comment by lmstrand** [comment]
Jos oikein ymmärrän toiminnan, niin tunkemalla sysprefien arvoksi esim:
<script>
</script>
Pitäisi aiheuttaa jonkinlaisen virhetilanteen.

**Comment by AnneliO** [comment]
Kirjoitin vaara-nextillä IntranetCirculationHomeHTML -järjestelmäasetukseen

```<script>dfdfdf</script>```

Tiedon sai kyllä tallennettua, mutta kun asetuksen haki uudelleen näkyville oli se muuttunut tämän näköiseksi:

![kuva](https://user-images.githubusercontent.com/33121325/233639280-8a489bc9-0c8f-4420-bf53-4b2f8c768a20.png)

Tuossa siis näkyi ennen tallentamista otsikko _Omia raportteja, linkki _Noutamattomat varaukset_ ja sen alla tuo script-hässäkkä. Nyt asetusta ei voi enää muokata ja Lainaus ja palautus -etusivulla näyttää tältä:
![kuva](https://user-images.githubusercontent.com/33121325/233639818-0e4d26fd-f10f-4806-9e91-219d80e16afc.png)

Eli ilmeisesti toimii, mutta en saa enää testejäni pois.

**Comment by AnneliO** [comment]
Voisiko joku poistaa Vaara-nextiltä IntranetCirculationHomeHTML -järjestelmäasetuksesta tuon "<script>dfdfdf</script>", jotta se ei kopioidu tuotantoon versionvaihdossa? :)

**Comment by lmstrand** [comment]
Poistettu.

**Comment by AnneliO** [comment]
Testattu uudelleen niin, että script-tägi lisätty lähdekoodiin. Jos sellaisen yritti tallentaa, tuli ilmoitus palvelinvirheestä eikä tieto tallentunut.

Tämä siis toimii kuten pitää, joten suljen tiketin.
