### ISSUE TITLE
koha-plugin-exporter-report (KPER)

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/Koha-22x#90]
### Siirrettävä ominaisuus

Get export report from KohaSuomiServices

**Comment by AnneliO** [comment]
Oisko tähän testaussuunnitelmaa?

**Comment by emta001** [comment]
> Oisko tähän testaussuunnitelmaa?

Näistähän piti tehdä se yhteinen testaustiketti :thinking:

**Comment by emta001** [comment]
Loin testauksen koontitiketin #174
