### ISSUE TITLE
koha-plugin-ssn-provider (KPSSN)

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/Koha-22x#92]
### Siirrettävä ominaisuus

Sotu-siilo liitännäinen

**Comment by lmstrand** [comment]
Kopioin Vaara-nextiin tuotannosta SSN-konfiguraation Vaara-nextin koha-conf.xml:ään.
Hetujen haku sotuavaimella onnistui nextillä ja hetun lisäys/tallennus onnistui (tosin ei olisi pitänyt onnistua, käytin omaa sotuani. Ymmärtääkseni olisi pitänyt tulla herja että se on jo olemassa). Hetun tallennuksen jälkeen sotuavain-kenttä oli tyhjä. Tein testin borrowernumberilla 11010263.

Käyttöliittymä ok.

**Comment by emta001** [comment]
Mikä tän tiketin status siis on? Onko tää testattavissa nexteillä?

**Comment by lmstrand** [comment]
Konfiguraatiot pitäisi katsoa kuosiin. Testasin vain Vaara-nextillä. Eli käyttöliittymässä hetun lisäys pitäisi vielä testata, koska sain tallennettua tuotantokonffin kanssa oman hetuni onnistuneesti Vaara-nextillä vaikka se on ollut jo sotu-siilossa. Silloinhan pitäisi tulla herja, että se on jo käytössä tms.

**Comment by lmstrand** [comment]
Voitko @pknuuti testata Vaaran nextillä toimiiko tuo sotun lisääminen/sotuavaimen haku oikein ja osaako liittymä huomauttaa mm. tuplasotusta? Voisi testata vaikka 111111-111A -muotoisella sotulla, jotta se on helppo poimia virheeliseksi, kun noita joskus siivotaan. Sen pitäisi mennä läpi. Vaaran nextillä on konfiguraatio tuotannon kanssa identtinen ja käyttää tuotannon sotusiiloa.

**Comment by pknuuti** [comment]
Testasin eilen hetun lisäystä tiketin https://github.com/KohaSuomi/Koha-22x/issues/149 pyynnön mukaan. Siellä on kuvakaappaus, jossa näkyy millä tunnuksella testasin. Voitko tarkistaa, onko se hetu (generaattorin antama) siilossa, koska mitään sotuavainta se ei antanut näkyviin, vaikka tallennus näytti onnistuvan.
Tuota mainitsemaasi 111-muotoista hetua ei voi tallentaa, koska se ei täytä hetun vaatimuksia (tarkistusmerkki) - testasin.

**Comment by lmstrand** [comment]
Pluginin käyttämään intranetUserJS-rimpsuun liittyvä ongelma korjattu tiketissä #149 . Suljen tiketin.
