### ISSUE TITLE
koha-plugin-print-pdf-notices (KPPDF)

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/Koha-22x#93]
### Siirrettävä ominaisuus

Koha plugin for printing notices

**Comment by Kaarius** [comment]
Tämän pitäisi toimia asennetaan vielä kaikille nexteillä.

**Comment by AnneliO** [comment]
En löytänyt tätä liitännäistä Vaarasta, OUTIsta, Hellestä tai Kyytistä. Siilinjärveltä löytyi. Sinänsähän tämä ei tarvitse näkyä kuin niillä, joilla se on käytössä. Muistaakseni Siili ja Helle? Kyyti ehkä?

Koitin Siilissä aiheuttaa noutoilmoituksen, mutta joko en osannut tai sitten liitännäiseen ei vain tullut mitään tulostettavaa (eli ei toiminut).

**Comment by Tuomas-Kyyti** [comment]
Kyyti käyttää ja voisi testata, jos liitännäinen olisi asennettuna.

**Comment by emta001** [comment]
> Kyyti käyttää ja voisi testata, jos liitännäinen olisi asennettuna.

Nyt on asennettu kyyti-nextille.

**Comment by Tuomas-Kyyti** [comment]
Varauksen saapumisilmoitus toimi ok. Yritän vielä saada huomautuskirjeen muodostumaan tuonne.

Vielä eilen plugin herjasi virheestä, mutta tänään toimi.

**Comment by Tuomas-Kyyti** [comment]
Tänään muodostui muistutuskirje ja tulostus onnistuu, joten mielestäni tämä toimii niin kuin pitääkin.

**Comment by Kaarius** [comment]
> En löytänyt tätä liitännäistä Vaarasta, OUTIsta, Hellestä tai Kyytistä. Siilinjärveltä löytyi. Sinänsähän tämä ei tarvitse näkyä kuin niillä, joilla se on käytössä. Muistaakseni Siili ja Helle? Kyyti ehkä?
> 
> Koitin Siilissä aiheuttaa noutoilmoituksen, mutta joko en osannut tai sitten liitännäiseen ei vain tullut mitään tulostettavaa (eli ei toiminut).

Siellä on siilijärven kirjastoasetuksissa on sähköpostiosoittena noreply@koha-suomi.fi, mutta message_queue taulussa from_address arvoksi tulee kirjasto@siilinjarvi.fi. Siksi REST ei osaa hakea noita viestejä.

**Comment by ReettaSiili** [comment]
Avaan tämän vielä Siilin osalta uudestaan, kun en ollut aiemmin hoksannut testata tätä.
Testasin asiakkaalla ID=6667 Taigaaula.
1. ja 2. myöhästymisilmoitus muodostuivat oikein ja siirtyivät myös työkaluun tulostettaviksi.
Sen sijaan varausten saapumisilmoitukset näkyvät asiakkaan ilmoituksissa odottaa-tilassa, mutta ne eivät ole siirtyneet työkaluun.
Miksiköhän? Liittyykö tämä nyt jotenkin varaustunnusten muutokseen othername -> HOLDID vai mistä johtuu?

**Comment by emta001** [comment]
> Avaan tämän vielä Siilin osalta uudestaan, kun en ollut aiemmin hoksannut testata tätä. Testasin asiakkaalla ID=6667 Taigaaula.
> 
>     1. ja 2. myöhästymisilmoitus muodostuivat oikein ja siirtyivät myös työkaluun tulostettaviksi.
>        Sen sijaan varausten saapumisilmoitukset näkyvät asiakkaan ilmoituksissa odottaa-tilassa, mutta ne eivät ole siirtyneet työkaluun.
>        Miksiköhän? Liittyykö tämä nyt jotenkin varaustunnusten muutokseen othername -> HOLDID vai mistä johtuu?

Eli ongelma on siinä, että yhteisössä on muutettu tapaa jolla varausten saapumisilmoituksiin määritetään message_queue.from_address arvo. Aiemmin arvona on käytetty kirjaston sähköpostia, mutta uudessa versiossa käytetäänkin vastausosoitetta. Siilissä pääkirjaston ja kirjastoauton sähköpostina käytetään noreply@koha-suomi.fi osoitetta, kun taas vastausosoitteena on kirjasto@siilinjarvi.fi. Mutta plugin rajaa viestiet kirjaston sähköpostin perusteella, Siilin pääkirjaston ja kirjastoauton tapauksessa siis noreply-osoitteella. Tämän vuoksi saapumisilmoitukset eivät näy.

Tehdään tämän kanssa niin, että otetaan viestin hausta sähköpostilla rajaaminen kokonaan pois, Pluginissa on suodatus toiminto, jolla viestejä voidaan suodattaa kirjaston/kirjastojen mukaan eli kimpat joilla on useampia kirjastopisteitä voivat sen avulla suodattaa viestejä.

**Comment by emta001** [comment]
Laitoin muutoksen nexteille testattavaksi.

**Comment by AnneliO** [comment]
Jos @Tuomas-Kyyti pystyisi testaamaan tarkemmin vielä, mutta se mitä testasin kyyti-nextillä, niin rajaus ei toimi siellä enää loogisesti. Elimäen ja Haminan varaukselle tuli kirjastopisteeksi KOU_PK ja kirjastorajaukset eivät toimi. Jos valitsen Haminan pääkirjaston, niin ei tule tulostettavia, vaikka sellainen on.

**Comment by ReettaSiili** [comment]
Siilissä kävi nyt nextillä niin, että samaisen asiakkaan Taigaaula kolme uutta varausta (1 pk:ssa, 1 autossa ja 1 Vuorelassa) eivät nousseet työkaluun tulostettaviksi. Kun kävin poistamassa kaikilta kirjastoilta vastausosoitteen kirjasto@siilinjarvi.fi, seuraavaksi tekemäni pääkirjaston varaus Ajatus on hiirihaukka on nyt työkalussa.

Jätänkö nyt laittamatta tuon vastausosoitteen takaisin kirjastoille? Se on sama kaikilla kolmella Siilin kirjastolla.

**Comment by emta001** [comment]
Outoa, äsken olin katsovinani että Siilissä tuo toimii vaikka vastausosoite oli paikallaan. Auttaisiko Ctrl+F5?

**Comment by ReettaSiili** [comment]
Huoh, olin kyllä omasta mielestäni painellut ctrl+f5 mutta painelin lisää, jolloin sekä vastausosoitteellisen kirjaston että osoitteettoman kirjaston varaukset nousivat listalle. Anteeksi sähläys. Palautin vastausosoitteet paikoilleen.

Sen sijaan tuo suodatus ei tosiaan toimi, kaikki varaukset näyttäisivät olevan pk:n nimissä.

**Comment by Tuomas-Kyyti** [comment]
Joo, suodatus ei Kyytissä toimi, koska se suodattaa kirjastopiste-sarakkeen mukaan ja siihen tuleva lyhenne on asiakkaan kotikirjasto eikä varauksen noutokirjasto. Kirjaston sähköposti-sarake kertoo varauksen noutokirjaston. Varaukset sinänsä tulevat tuokaluun näkyviin, mutta aikaleima ei oikein toimi: siihen tulee kellonaika 14:04, vaikka noutoilmoitukset muodostuivat selvästi myöhemmin.

**Comment by emta001** [comment]
Tätä pitääkin tuumata hieman enemmän, mutta se keretään tekemään vasta versionvaihdon jälkeen. Otan tuon tekemäni muutoksen pois ja @ReettaSiili jos kävisit hätäratkaisuna ottamassa kirjastoilta vastausosoitteet pois.

**Comment by Tuomas-Kyyti** [comment]
Sen verran täsmennystä, että niinhän se tuotannossakin toimii, että tuo kirjastopiste-sarake näyttää asiakkaan kotikirjaston (vaikka sillä ei mitään merkitystä olekaan), mutta tuo muutos aiheutti sen, että listalla näkyi kaikkien kirjastojen ilmoitukset ja silloin suodatusta olisi tarvittu. Tuotannossa ja - nyt kun muutos otettiin pois - nexteilläkin näkyy vain kirjautuneen kirjaston ilmoitukset, jolloin suodatusta ei tarvita.

**Comment by emta001** [comment]
Mietittiin tämmöstä ratkaisua:

1. Otetaan pois API-kutsusta from_address-kentällä rajaus.
2. Korjataan olemassa oleva suodatus suodattamaan sähköposti-osoitteetn perusteella (pitää vain ensin tarkistaa mitä spostia käytetään).

Näin siksi, että kun Kyytissäkin otetaan käyttöön noreply-muutos, niin siellä on sitten sama tilanne kuin Siilissä eli viestit ei välttämättä näy oikein. Mutta suunnitellaan vielä tarkemmin kunhan pääsen tutkimaan tarkemmin miten tuo muutos ylipäätään onnistuu.

**Comment by ReettaSiili** [comment]
Hyvä. Kyytissä suodatuksen toiminta voi olla tarpeellisempi kuin Siilissä, me olemme kuitenkin vain yksi kirjasto ja kaikkien kolmen toimipisteen kirjeet tulostetaan itse asiassa pääkirjastossa.

**Comment by emta001** [comment]
Tehdään niin, että tehdään tämän plugarin alle tuosta suodatusongelmasta oma tiketti ja suljetaan tämä.
