### ISSUE TITLE
koha-plugin-delete-biblio-components (KPDELC)

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/Koha-22x#94]
### Siirrettävä ominaisuus

Osakohteiden poistoliitännäinen

**Comment by AnneliO** [comment]
Testaa näin:
1. Poista emotietue ja tarkista, poistuvatko osakohteet emon poiston mukana.

**Comment by LeenaKinnunen** [comment]
Lapissa testattu hankintaosastolla, toimii oikein.

**Comment by Kati-Helle** [comment]
Hellessä toimii. Emotietueen poisto poistaa myös emon osakohteet.

**Comment by AnneliO** [comment]
Hyvä juttu! Pari testausta tullut, joten suljen tiketin. :)
