### ISSUE TITLE
koha-plugin-self-service 	(KPSS)

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/Koha-22x#99]
### Siirrettävä ominaisuus

Self-service permission API for Koha ILS

**Comment by lmstrand** [comment]
Tästä voisi asentaa viimeisimmän version .kpz:nä kimpoillle, jotka tätä tarvitsevat Hypernovan reposta:
https://github.com/Hypernova-Oy/koha-plugin-self-service

**Comment by lmstrand** [comment]
Meidän forkista puuttuu viimeisin korjaus. Onko tarvetta ylläpitää omaa forkkia?

**Comment by lmstrand** [comment]
-

**Comment by lmstrand** [comment]
Pluginin konfigurointi ei onnistu 1.0.11-versiolla. Plugin asentuu, mutta se pitäisi testata ja korjata yhteensopivuus 22.11-version kanssa Hypernovan puolesta. Vaaran pääkäyttäjille tiedotettu ongelmasta.

**Comment by lmstrand** [comment]
Vaara-nextille asennettu Olli-Antin toimittama 22.11-version kanssa yhteensopiva versio pluginista testattavaksi (koha-plugin-self-service-22.11.0). Konfiguraatiot pluginille ovat kopioituneet Vaaran tuotannosta. @pknuuti testaa Hypernovan kanssa.

**Comment by lmstrand** [comment]
Pluginin asennuksen yhteydessä syntyvää SSBAN-asiakasmäärettä ei tarvitse. Sen voi siis poistaa. Plugin hakee tietokantataulusta omatoimiestot, eli Tovereidenkin kanssa voidaan noudattaa nykyistä systeemiä, jossa devaajat lisäävät eston https://github.com/KohaSuomi/koha-suomi-utility/blob/master/misc/create_borrower_ss_blocks.pl -skriptillä Toveri-switchillä (jotka poistetaan automaattisesti https://github.com/KohaSuomi/koha-suomi-utility/blob/master/cronjobs/drop_borrower_ss_blocks.pl-skriptillä). Pluginissa on vielä bugi, jota korjataan. Odotellaan uutta versiota.

**Comment by AnneliO** [comment]
Testattu Hypernovan kanssa uusin plugin-versio Vaarassa. Pitää laittaa vielä Lumpeille tuotannossa.
